### ISSUE TITLE
Linux version problem

### ISSUE THREAD

**Issue by artagres** [bepass-org/oblivion-desktop#10]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Do you have plan for linux version? 
I can help you

### Minimal Reproducible Example (MRE)

.

### Version

latest

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
the builds for Mac & Linux will be added in the next few days

**Comment by Majidzam1101** [comment]
> the builds for Mac & Linux will be added in the next few days

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه دومین مشکل اتصال به سایفون است هیچ سایتی باز نمی کنه
![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/027f07eb-0e06-4154-bb8f-67b8bb494420)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/8ecdb170-fc67-4a29-8643-1df15be30347)
![Screenshot (7)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/7401b9ce-f745-4178-8b13-0bfc12ea60af)

**Comment by artagres** [comment]
I can help implement this feature. Is anybody currently working on it?

**Comment by ircfspace** [comment]
Yes, we are working on it and it will be available in a few days.
After that, we would be happy if you could contribute with us to improve it.
