### ISSUE TITLE
مشکل اتصال در ویندوز ۱۰

### ISSUE THREAD

**Issue by RimaElpaso** [bepass-org/oblivion-desktop#101]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

میزنه متصل است اما هیچ سایت باز نمیکنه و تلگرام رو باز نمیکنه
تمامی گزینه ها رو امتحان کردم در هر ۲ نسخه پورتابل و ویندوز کار نمیکرد. فقط میزنه متصل است

### Minimal Reproducible Example (MRE)

میزنه متصل است اما هیچ سایت باز نمیکنه و تلگرام رو باز نمیکنه
تمامی گزینه ها رو امتحان کردم در هر ۲ نسخه پورتابل و ویندوز کار نمیکرد. فقط میزنه متصل است
![ggdfggdfg](https://github.com/bepass-org/oblivion-desktop/assets/169486572/c29a5718-7e21-4b42-9868-9d657ee24837)

### Version

V0.2.52.0 Beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by RimaElpaso** [comment]
سلام
از پیگیریتون ممنونمهیچگونه  اکستنشن پروکسی روی مرورگرم نصب نیست
اگر براتون اهمیت داره باید بگم از کروم استفاده میکنم
    Am Freitag, 10. Mai 2024 um 23:45:12 GMT+3:30 hat IRCF ***@***.***> Folgendes geschrieben:  
 
 


سلام

اگر اکستنشن پروکسی روی مرورگرتون نصب هست، حذف کنین
همینطور در رابطه با تلگرام روی گزینه use system proxy قرار بگیره

**Comment by hosseinkazemi7400** [comment]
سلام از مرورگر های دیگه استفاده کنید  ، با مرورگر های دیگه کار می کنه

**Comment by ircfspace** [comment]
درصورت امکان اسکرین‌شاتی از لیست اکستنش‌های مرورگر کروم رو برام بفرستین
@RimaElpaso

**Comment by k1slm** [comment]
time=2024-05-13T00:12:16.388+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-13T00:12:16.390+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-13T00:12:16.392+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-13T00:12:17.916+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-13T00:12:17.916+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-13T00:12:17.918+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-13T00:12:19.100+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-13T00:12:24.821+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.211 error="read udp 192.168.1.3:56022->162.159.193.211:942: i/o timeout"

time=2024-05-13T00:12:28.101+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.99.133:943 RTT:190.5099ms CreatedAt:2024-05-13 00:12:27.6242364 +0330 +0330 m=+11.248979501} {AddrPort:162.159.195.151:3581 RTT:1.1137434s CreatedAt:2024-05-13 00:12:26.6504907 +0330 +0330 m=+10.275233801}]"
time=2024-05-13T00:12:28.101+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.99.133:943 162.159.195.151:3581]"
time=2024-05-13T00:12:28.101+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-13T00:12:30.449+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-13T00:12:32.667+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=relay-72da16c0.net.anydesk.com:443

time=2024-05-13T00:12:33.584+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=relay-4757ad50.net.anydesk.com:443

time=2024-05-13T00:12:36.197+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-13T00:12:38.187+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=twitter.com:443

time=2024-05-13T00:12:38.190+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=abs.twimg.com:443

time=2024-05-13T00:12:38.212+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cdn.jsdelivr.net:443

time=2024-05-13T00:12:38.286+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=abs.twimg.com:443

time=2024-05-13T00:12:38.299+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=api.twitter.com:443

time=2024-05-13T00:12:38.300+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=api.x.com:443

time=2024-05-13T00:12:38.301+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=pbs.twimg.com:443

time=2024-05-13T00:12:38.302+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=t.co:443

time=2024-05-13T00:12:38.304+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=video.twimg.com:443

time=2024-05-13T00:12:38.595+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=abs.twimg.com:443

time=2024-05-13T00:12:38.915+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:12:39.910+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:12:40.531+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=optimizationguide-pa.googleapis.com:443

time=2024-05-13T00:12:41.486+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=api.twitter.com:443

time=2024-05-13T00:12:42.235+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.google-analytics.com:443

time=2024-05-13T00:12:42.422+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=content-autofill.googleapis.com:443

time=2024-05-13T00:12:44.428+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=abs-0.twimg.com:443

time=2024-05-13T00:12:45.210+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=video.twimg.com:443

time=2024-05-13T00:12:45.829+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=video.twimg.com:443

time=2024-05-13T00:12:50.056+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:12:57.267+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:01.216+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:06.836+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:12.495+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:18.169+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:23.755+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:30.862+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:36.592+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:43.609+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:49.243+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:13:56.289+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:14:01.795+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=activity.windows.com:443

time=2024-05-13T00:14:03.359+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:14:10.347+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:14:17.370+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

time=2024-05-13T00:14:22.968+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=edgedl.me.gvt1.com:80

**Comment by RimaElpaso** [comment]
همین الان با EDGE امتحان کردم درست شدممنون
    Am Freitag, 10. Mai 2024 um 23:45:12 GMT+3:30 hat IRCF ***@***.***> Folgendes geschrieben:  
 
 


سلام

اگر اکستنشن پروکسی روی مرورگرتون نصب هست، حذف کنین
همینطور در رابطه با تلگرام روی گزینه use system proxy قرار بگیره
