### ISSUE TITLE
خطای هویت سنجی با کلودفلر

### ISSUE THREAD

**Issue by rm-killer** [bepass-org/oblivion-desktop#102]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

خطای هویت سنجی با کلودفلر رو چجوری میشه رفع کرد؟

### Minimal Reproducible Example (MRE)

After click connect

### Version

0.2.52

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
در توضیحات اشاره شده :

**- در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه**
- 
اگر لایسنس اضافه کردین، موقتن حذفش کنین

**Comment by razeghiii** [comment]
برای من لایسنس هم نداره ولی همین خطا رو میده

**Comment by kiomarzsss** [comment]
@razeghiii 
لطفا pre-release بعدی رو تست کنین احتمالا مشکلتون حل شده باشه
