### ISSUE TITLE
آپدیت نرم‌افزار از داخل خود اپ

### ISSUE THREAD

**Issue by alibayat73** [bepass-org/oblivion-desktop#103]
### Feature description

ممنون می‌شم هر زمان براتون مقدور شد، این قابلیت رو هم اضافه کنید که بشه اپ رو از داخل خود نرم‌افزار هم آپدیت کرد که نیاز نباشه برای گرفتن ورژن های جدید به گیتهاب رجوع کنیم و کار نصب رو دوباره انجام بدیم.

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،
این مورد جز تسک‌ها قرار داره و هر زمان برنامه به شرایط استیبل برسه روش کار میکنیم
