### ISSUE TITLE
[FR] Add some these features in the next version

### ISSUE THREAD

**Issue by Daredevil74** [bepass-org/oblivion-desktop#105]
### Feature description

سلام، خسته نباشید.
یه چن تا پیشنهاد براتون دارم که در صورت امکان در ورژن های بعدی به برنامه اضافه کنید، ممنون.

- امکان استفاده از لایسنس های وارپ پلاس از [منبع خودتون](https://github.com/ircfspace/warpkey) در اولین اجرا و جایگزین کردن اونها در صورت به مشکل خوردن لایسنس

- امکان ریست کردن کلید بدون نیاز به ریست کردن کل تنظیمات
- امکان تبدیل به یوزر zero trust (میگن سرعتش بیشتره اون پروژه)
-  امکان انتقال کامل به بخش system tray بعد از اتصال و مدیریت کانکت و دیسکانکت از اون بخش
- تغییر رنگ آیکون برنامه به سبز بعد از اتصال و قرمز هنگام قطع شدن (در sysytem tray)
- پین شدن پنجره برنامه به پایین گوشه سمت راست صفحه (بالای ساعت و تقویم) و قفل شدن سایز پنجره در یک اندازه معمول و استاندارد
- افزودن نوتیفیکشن و اعلانات
- اضافه شدن چکر هوشمند اندپوینت و پورت برای اتصال به سرور خلوت و سالم

**Comment by kiomarzsss** [comment]
@Daredevil74 
سلام تشکر.
ممنون از پیشنهادات جالبتون. برای نسخه های بعد حتما بهشون فکر میکنیم. ولی در حال حاضر تمرکز روی استیبل کردن قابلیت های فعلی برای افراد بیشتر و نسخه مک و لینوکس هستش. بازم ممنون.

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از پیشنهادات شما،

1. متاسفانه به‌دلیل جلوگیری از مشکلات حقوقی احتمالی، امکان اضافه‌کردن این‌مورد وجود نداره
2. بررسی میکنیم
3. برای این‌مورد باید در [warp-plus](https://github.com/bepass-org/warp-plus) ایشو ایجاد کنین
4. انجام شده و در بروزرسانی بعدی در دسترس قرار میگیره
5. انجام شده و در بروزرسانی بعدی در دسترس قرار میگیره
6. انجام شده ور دبروزرسانی بعدی در دسترس قرار میگیره
7. چیزی غیر از بخش لاگ و خطاهای مهمی که با توست نشون میدیم منظورتونه؟
8. برای این‌مورد هم باید در warp-plus ایشو ایجاد کنین

**Comment by ircfspace** [comment]
سلام مجدد،
مورد 2 هم انجام شد و در آپدیت بعدی در دسترس قرار میگیره
