### ISSUE TITLE
ساخت یک یوزر جدید با هر اتصال

### ISSUE THREAD

**Issue by iHMahmoodi** [bepass-org/oblivion-desktop#107]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
الان به نسخه 2.52 آپگرید کردم و متوجه شدم با هر اتصال یک یوزر در بخش اکانت کلود فلر وارپ میسازه
در نتیجه بعد از دوبار اتصال تعداد یوزر ها به 5تا میرسه و دیگه خطای هویت سنجی میده چون وارپ اجازه میده 5تا اکانت به یک حساب وصل باشن
فعلا از طریق موبایل میرم اون رو پاک میکنم هربار که اجازه بده وصل بشه

نکته: یکی از خطاهایی که کاربران دیدم دارن و نمیدونن از کجاست و مشکلش چیه دقیقا همین تعداد یوزرهای داخل اکانته
یک ارور هم برای اون میتونید تعریف کنید که البته نیاز هست بدونید الان چندتا یوزر ریجستر شده.

### Minimal Reproducible Example (MRE)

warp 1.1.1.1 on mobile
accounts

### Version

0.2.52

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از گزارش شما،

مورد اول مربوط میشه به استفاده از برنامه ضمن درج لایسنس شخصی؟
مورد دوم باید از سمت هسته warp-plus هندل بشه

**Comment by iHMahmoodi** [comment]
بله بله
حواسم نبود بنویسم که با وارد کردن لایسنس این اتفاق میافته و چون تعداد یوزرها در هر حساب یک لایسنس نهایتا 5تاس این سریع با دوبار قطع و وصل پر میشه

**Comment by ircfspace** [comment]
یعنی دو مرتبه روی اتصال میزنین بار سوم دیگه لایسنس رو قبول نمیکنه، اما دفعات اول و دوم همه چی با اون لایسنس اوکیه؟

**Comment by iHMahmoodi** [comment]
> یعنی دو مرتبه روی اتصال میزنین بار سوم دیگه لایسنس رو قبول نمیکنه، اما دفعات اول و دوم همه چی با اون لایسنس اوکیه؟

ببین سیستم خود اپ کلودفلر اینه که لایسنس رو که بهش میدی دیگه دستگاه رو تشخیص میده و تمام و برای بارهای بعدی هم میدونه این کدوم دستگاه هست

ولی الان باگی که اپ oblivion داره اینه که با هر بار چک لایسنس انگار داره به کلود فلر میگه این یک دستگاه جدیده و باید ریجسترش کنی

من 3تا دیوایسم قبلا ثبت شده بود با خود اپ اصلی 1.1.1.1

الان با هر بار اتصال یک یوزر اونطرف میسازه و باید بری پاکش کنی

خیلی ها هم که نمیتونن وصل بشن مشکلشون همینه چون نمیدونن چه اتفاقی میافته و اروری هم بهشون نشون نمیده (البته من همون اول که یوسف اپ موبایل رو معرفی کرد از طریق لاگ هاش متوجه شدم مشکلش کجاست)

**Comment by iHMahmoodi** [comment]
در نتیجه اگر بتونید تعداد دیوایس های ثبت شده رو از طریق api یا چیزی retrieve کنید میشه این ارور رو هم نشون داد که دستگاه بیش از اندازه ثبت شده
یا حتی اگر بتونید حالت پیشرفته ترش رو درست کنید که خود اپ oblivion بخش اکانت داشته باشه و بتونه دستگاه های ریجستر شده رو نشون بده

صرفا پیشنهاد بود

پ.ن: همینم اینجا اضافه کنم که اپ oblivion رو اندرویید من کامل قطع شده و دیگه نمیتونه وصل بشه که احتمال به خاطر آپدیت GFW هست ولی روی PC با این نسخه وصل میشم

**Comment by johhny1898** [comment]
با سلام
دقیقا همینطوره که این دوستمون گفتن من با چند تا لایسنس وصل میشم الانم با لایسنس وصلم ولی با یکی دوبار دیسکانکت و دوباره کانکت شدن ارور هویت میده اینو باید یجوری رجیسترش کرد

**Comment by ircfspace** [comment]
یکی‌از مشکلات ممکنه به خاطر حذف فولدر stuff در هربار دیسکانکت‌کردن باشه
توی آپدیت بعدی این‌پروسه رو تغییر میدم؛ فقط درصورت امکان بعدن تست بگیرین و نتیجه رو اعلام کنین

**Comment by ircfspace** [comment]
سلام
متاسفانه مربوط میشه به محدودیتی که روی گیت‌هاب داریم و نمیتونیم نسخه‌های Draft رو بی‌دردسر برای بتاتسترها قرار بدیم، اما هر موقع به نسخه استیبل برسیم، نسخه های Pre-release عمومی خواهند بود.

**Comment by ircfspace** [comment]
لطفن مشکل گزارش شده رو بعد از آپدیت به نسخه جدید بررسی کنین :
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta

**Comment by iHMahmoodi** [comment]
> لطفن مشکل گزارش شده رو بعد از آپدیت به نسخه جدید بررسی کنین : https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta

سلام
درست شده و دیگه چندتا یوزر نمیسازه، ممنون

نسخه موبایل رو هم آپدیت میکنید لطفا، چون سه هفته ای است که دیگه وصل نمیشه

**Comment by iHMahmoodi** [comment]
این مشکل در نسخه جدید که الان منتشر شد نه تنها برگشته بلکه با همون اتصال اول 3تا اکانت میسازه و حتی با ساختن اکانت ها هم وصل نمیشه و ارور میده
انگار دائما میخواد اکانت بسازه ولی دیگه جا نداره
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.0-beta

**Comment by ircfspace** [comment]
این مورد در آپدیت قبلی وجود نداشت؟

**Comment by iHMahmoodi** [comment]
> این مورد در آپدیت قبلی وجود نداشت؟

نه، الان برگشتم به ورژن قبلی و دارم استفاده میکنم

**Comment by ircfspace** [comment]
بررسی میکنیم

**Comment by ircfspace** [comment]
ضمن تشکر از گزارش شما، 
بروزرسانی جدید در دسترس قرار گرفت‌:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.8-beta
