### ISSUE TITLE
Duplicate "گول" option in Warp's settings

### ISSUE THREAD

**Issue by mazdakdev** [bepass-org/oblivion-desktop#108]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![Screenshot 2024-05-11 at 12 13 30 PM](https://github.com/bepass-org/oblivion-desktop/assets/60855141/ff93b206-6e18-4715-a3b0-9966f4671f9b)

There is a extra radio-box for activating the "گول"

### Minimal Reproducible Example (MRE)

1. Clone the repo on mac book M1
2. cd repo && npm install && npm run dev
3. go to warp's settings menu

### Version

0.3.0-beta

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

تشکر از گزارش شما،
مشکل برطرف شد
