### ISSUE TITLE
ویندوز۷

### ISSUE THREAD

**Issue by emisemok** [bepass-org/oblivion-desktop#11]
### Feature description

برا ویندوز ۷ هم گسترشش بدین و اگد امکانش رو دارید نسخه پرتابلشم قرار بدین

**Comment by ircfspace** [comment]
درحال‌حاضر نسخه پرتابل قرار گرفته

درخصوص ویندوزهای قدیمی از سمت ما مشکلی نیست، اما متاسفانه Warp-Plus فعلن ازشون پشتیبانی نمیکنه

**Comment by emisemok** [comment]
نمی خوام از شخصی اسم بیارم ولی خودتون حتما در جریان هستین ک شخصی حالا ب هر شکلی اون رو پیاده سازی کرده ولی خودم حاضر نیستم از هر شخصی هر نوع فیلترشکنی استفاده کنم 
بازم ممنونم از تمامی زحماتی ک تا بحال کشیدین🙏

**Comment by ircfspace** [comment]
ما هم مث خودتون : )
اما همونطور که گفتم Warp-Plus از ویندوز 7 پشتیبانی نمیکنه

البته این‌مورد رو @markpash بهتر میتونه نظر بده.

**Comment by ircfspace** [comment]
ویندوز 7 شما 64 بیتی نیست؟

**Comment by emisemok** [comment]
وین هفت ۶۴ بیتی هستش

**Comment by Amir-th1362** [comment]
این برنامه روی چه ویندوزی اجرا میشه؟ روی ویندوز 7 یک خطای طولانی که آخرش با kernel32.dll تمام میشه گرفت

**Comment by emisemok** [comment]
آری دقیقا همینه

**Comment by ircfspace** [comment]
متاسفانه electron حدود یکساله دیگه از ویندوز 7 پشتیبانی نمیکنه

اگر راهی برای حل مشکل باشه بعد از رسیدن به نسخه استیبل روش وقت میذاریم

**Comment by xylra19** [comment]
آیا نسخه قدیمی که از ویندوز ۷ پشتیبانی می‌کند وجود دارد؟

**Comment by ircfspace** [comment]
> آیا نسخه قدیمی که از ویندوز ۷ پشتیبانی می‌کند وجود دارد؟

متاسفانه خیر
مطالعه کنید:‌ https://github.com/bepass-org/oblivion-desktop/issues/76#issuecomment-2252535770
