### ISSUE TITLE
system proxy misconfiguration

### ISSUE THREAD

**Issue by D3LTA-AK74** [bepass-org/oblivion-desktop#110]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

my system proxy settings have been misconfigured by the app

### Minimal Reproducible Example (MRE)

simply exit the app at "در حال اتصال" state.

### Expected Behavior

the app should undo any changes it made before exiting.

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
روی کدوم نسخه از ویندوز این مشکل پیش میاد؟

**Comment by D3LTA-AK74** [comment]
Windows 11 23H2 (build 22631.3527)

**Comment by ircfspace** [comment]
یکبار با Run as admin برنامه رو اجرا کنین ببینین تغییری در وضعیت ایجاد میکنه؟

**Comment by D3LTA-AK74** [comment]
نتونستم مشکل رو بازسازی کنم، احتمالا برنامه ای از سمت خودم پروکسی رو خراب
کرده بوده، شرمنده بابت گرفتن وقت ارزشمند شما.🙏🏼
