### ISSUE TITLE
عدم اثر عملی رو سیستم عامل ویندوز11

### ISSUE THREAD

**Issue by parsathelightcore** [bepass-org/oblivion-desktop#111]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هم حالت سایفون هم گول متصل میشن و آیپی جدید هم نشون میده اما عملا ویندوز تونل نشده و هیچ جا با هیچ مرورگری هیچ‌چیز از فیلترش برداشته نشده.

پ.ن. با run as administrator هم برنامه باز و تست شده هردو ورژن پرتابل و نصبی.

### Minimal Reproducible Example (MRE)

![Screenshot 2024-05-12 114150](https://github.com/bepass-org/oblivion-desktop/assets/136087745/f2c0b4ad-1b85-4535-8d37-952c88b5401e)

سایتای بدون فیلتر کار میکنن ولی فیلترا فیلترن.

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by aminpple** [comment]
سیستمت رو ریستارت کن 

من هروفت اینجوری میشه ریستارت میکنم و دوباره وصل میشه و درست کار میکنه

**Comment by ircfspace** [comment]
سلام

بعد از اتصال موفق چک کنین که آیا تنظیمات پروکسی روی سیستمتون اعمال شده؟

**Comment by mark522412** [comment]
از این افزونه های پروکسی مرورگر مثل omega proxy استفاده کن. بعد یه پروکسی جدید داخلش تنظیم کن. مثلا اینو میتونی بزنی اگه پورت پیشفرض رو تغییر نداده باشی:
127.0.0.1:8086
همین پروکسی رو هم دستی میتونی وارد کنی تو تنظیمات پروکسی ویندوز اگه میخوای کل سیستم تونل شه. البته پیشنهاد من استفاده از همون افزونه هست

**Comment by parsathelightcore** [comment]
@mark522412 
مرسی از پیشنهادت یکم مبهم فهمیدم واسه مرورگر افزونه تونل‌بیعر واسم عالی عمل میکنه ولی 

1. میخوام کل سیستم تونل شه.
2. میخوام آیپیم قشنگ به آمریکا عوض شه مثل کاری که با ترکیب وارپ و افزنه تونل‌بیعر یا ترکیب وارپ و سایفون تو آبلیوین میشه کرد 

که تونل‌بیعر نسخه ویندوزش عمل نمیکنه و به همه لوکیشنا راگیان دسترسی نمیده
 و آبلیوین که خیلی منتظر نسخه ویندوزش بودم و لطف کردن ارائه دادن طبق توضیحات بالا از شانسم کار نمیکنه منتظرم جواب بدن ایشالا حل شه.

با این روشی که پیشنهاد دادی میشه امن همین کارو کرد که رایگان کل سیستم با آیپی آمریکا تونل شه؟

**Comment by ircfspace** [comment]
ضمن رفع یه سری از ایرادات، بخش لاگ برنامه رو توسعه دادیم که بهتر بشه متوجه مشکلات شد
لطفن منتظر آپدیت بعدی برنامه بمونین

**Comment by parsathelightcore** [comment]
@ircfspace 
عاالی سپاسگزار.

**Comment by kiomarzsss** [comment]
checkout https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta and see if the issue still persist?

**Comment by parsathelightcore** [comment]
@ircfspace @kiomarzsss 
خیییلی ممنونم از اطلاع‌رسانیتون. نصب کردم ورژن جدید رو و باز هم رو سیستم چیزی پیاده نمیشه علی‌زغم اینکه رو حالت سیستم پروکسی قرار داره و با ران عز ادیمنستر باز شده و دسترسی فایروال رو داره 
.هم رانه warp-svc و
من مشکلم با روش دیگه‌ای رفع شد ولی حتما اگر تغییراتی اعمال کردید و دیدم کار کرد همینجا جهت اطلاع‌رسانی پست میکنم. ممنون از زحماتتون.
![Screenshot 2024-05-19 110858](https://github.com/bepass-org/oblivion-desktop/assets/136087745/0040803f-1f9f-43a4-a50f-18a8e6ea8232)
