### ISSUE TITLE
درخواست آپلود نسخه ی مک

### ISSUE THREAD

**Issue by alijason72** [bepass-org/oblivion-desktop#112]
### Feature description

با تشکر از زحمات برنامه نویس این برنامه خواهش می کنم نسخه ی مک رو با ساپورت اپل سیلیکون سریع تر قرار بدید کارت عالیه سرعت vpn ایشالله همیشه اینقد عالی بمونه

**Comment by ircfspace** [comment]
سلام

این نسخه با مشارکت دوستان آماده شده، اما درحال تست هستیم
توی اپدیت بعدی سعی میکنیم در دسترس قرار بدیم
