### ISSUE TITLE
Firewall Prompt

### ISSUE THREAD

**Issue by titancomputer** [bepass-org/oblivion-desktop#113]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello

i wrote this issue before : https://github.com/bepass-org/oblivion-desktop/issues/13#issue-2279078564
after that you changed the warp-plus.exe location to "\AppData\Local\Temp" and it causes other problems.
when i run oblivion-desktop app, it creates a temp settings and copy warp-plus.exe file on Temp folder.
i think this is wrong, because a firewall system like ESET will prompt every single requests of warp-plus demands every time.
for first usage it's ok and i make a rule to access In/Out requests for warp-plus.exe file but the requests will prompt every time i launch oblivion.
after that i have no chance to use firewall and oblivion together and i have to disable it completely to use oblivion.
i think it happens for Temp folder location.
you should change the runtime files location to "\AppData\Roaming\oblivion-desktop" or "My Documents" folder
i think the cloudflare auth problem caused by Temp folder too and you re-write the stuff folder every time and it uses 5 device support of licenses.
i'm using warp-plus.exe 1.1.3 with license and i don't have any problem like cloudflare auth error or too many connected devices.

Best Regards

### Minimal Reproducible Example (MRE)

install the app as usual
use ESET firewall and set it on Interactive Mode
run app every time and see firewall prompts
make a rule for warp-plus.exe file
close and re-run app
you see firewall prompts every time for every requests

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
@titancomputer thank for your accurate recommendation. we change the warp-plus binary path to: 
(userData("\AppData\Roaming\oblivion-desktop" in windows case))
in 0.3.

**Comment by titancomputer** [comment]
> how can we download "0.3.13-beta" for testing? @kiomarzsss @ircfspace

this is my question too.
i think we should wait for next release build or we can build this live version but i don't know how to do it.

**Comment by kiomarzsss** [comment]
@titancomputer @Graveyard9988 checkout: https://github.com/bepass-org/oblivion-desktop/blob/main/DOCS.md for building from the source for your local platform

**Comment by kiomarzsss** [comment]
> @kiomarzsss I'm not programmer and I can't build files

hang tight 😉. we will have a new beta pre-release very soon and you can download latest executable packages for windows and mac

**Comment by titancomputer** [comment]
> @titancomputer thank for your accurate recommendation. we change the warp-plus binary path to: (userData("\AppData\Roaming\oblivion-desktop" in windows case)) in 0.3.11-beta please take a look and see if the issue it fixed after this update or not 🙏

its ok on [0.4.5-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta)
thanks
