### ISSUE TITLE
404 problem Mac version link

### ISSUE THREAD

**Issue by Y4CN** [bepass-org/oblivion-desktop#115]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

لینک های دانلود برای سیستم عامل مک ۴۰۴ برمیگردونه 
ممکنه این رو فیکس کنین ؟

### Minimal Reproducible Example (MRE)

<img width="1259" alt="Screenshot 2024-05-13 at 11 26 50 AM" src="https://github.com/bepass-org/oblivion-desktop/assets/101870735/e1c60fe1-4fe0-4500-8fc3-98760f6a256d">
404 PROBLEM 

### Version

v 1.3.8

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

نسخه مک هنوز عمومی نشده. 
امروز یا فردا (بعد از انجام چندتا تست دیگه) منتشر و متعاقبا اطلاع رسانی میکنیم
