### ISSUE TITLE
اضافه شدن بخش اپدیت برنامه و یا تنظیمات مورد نیاز به اپدیت جهت رفع مشکل کار نکردن 

### ISSUE THREAD

**Issue by Amohasan23** [bepass-org/oblivion-desktop#116]
### Feature description

درود برشما 
لطفا بخشی به نسخه اندروید و ویندوز اضافه کنید تا درصورپ وجود نسخه جدید از ان بخش برسی و دانلود و نصب شود 
باتشکر فراوان از زحمات شما عزیزان

**Comment by mammad145** [comment]
please release oblivion linux version

**Comment by ircfspace** [comment]
سلام

> لطفا بخشی به نسخه اندروید و ویندوز اضافه کنید تا درصورپ وجود نسخه جدید از ان بخش برسی و دانلود و نصب شود


بعد از رسیدن به نسخه استیبل روی این موضوع کار میکنیم
@Amohasan23

> 
please release oblivion linux version


بزودی آماده میشه
@mammad145
