### ISSUE TITLE
پیکربندی شبکه

### ISSUE THREAD

**Issue by MohammadHasan80** [bepass-org/oblivion-desktop#118]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

پیکربندی شبکه رو خاموش میکنم دوباره میرم توی تنظیمات میبینم باز روشنه
تست هم کردم گفتم شاید فقط نشون میده اشتباهی دیدم ن کل سیستم پروکسی میشه

### Minimal Reproducible Example (MRE)

1.تنظیمات
2.پیکربندی شبکه

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از گزارش شما،
این مشکل در آپدیت بعدی برطرف میشه
