### ISSUE TITLE
کار نکردن حالت فقط پروکسی

### ISSUE THREAD

**Issue by mark522412** [bepass-org/oblivion-desktop#119]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام. این تیک حالت پروکسی کل سیستم رو برمیدارم ولی بازم کل سیستم رو تونل میکنه. داخل تنظیمات پروکسی سیستم رو هم سر زدم دیدم هر موقع وصل میشم چه تیک زده باشه چه نباشه پروکسی رو قرار میده. من نسخه پرتابل استفاده کردم نسخه نصبی رو نمیدونم شاید این مشکل رو نداشته باشه. در ضمن ممنون از برنامه عالیتون

### Minimal Reproducible Example (MRE)

تنظیمات/پیکربندی شبکه

### Version

0.2.52-beta

### Platform/OS

Windows 10

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از گزارش شما،
این موضوع درحال حاضر برطرف شده و در آپدیت بعدی در دسترس قرار میگیره
