### ISSUE TITLE
شروع خودکار در بوت سیستم عامل

### ISSUE THREAD

**Issue by fakhamatia** [bepass-org/oblivion-desktop#12]
### Feature description

- تنظیم باز شدن خودکار برنامه در بوت سیستم عامل
- تنظیم برای اتصال خودکار در شروع خودکار
- تنظیم باز شدن خودکار در حالت Minimize (silent start)

**Comment by ircfspace** [comment]
ضمن تشکر از پیشنهادتون،
براش تسک تعریف شده :

https://github.com/orgs/bepass-org/projects/4?pane=issue&itemId=61731727

**Comment by Majidzam1101** [comment]
> ضمن تشکر از پیشنهادتون، براش تسک تعریف شده :
> 
> https://github.com/orgs/bepass-org/projects/4?pane=issue&itemId=61731727
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه

![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/52794cb6-da86-4d44-b5e4-cf92626909ee)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/789f58ba-d0bf-4100-9e43-5c85bdbaab5d)

**Comment by Majidzam1101** [comment]
> ضمن تشکر از پیشنهادتون، براش تسک تعریف شده :
> 
> https://github.com/orgs/bepass-org/projects/4?pane=issue&itemId=61731727

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه
