### ISSUE TITLE
برنامه برای اجرا به نصب نرم‌افزار Powershell نیاز دارد.

### ISSUE THREAD

**Issue by Emtin** [bepass-org/oblivion-desktop#120]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هنگام زدن دکمه اتصال این پیام را داده و همینطور گیر می‌کند (مدت طولانی‌ای به آن وقت دادم باز هم اتفاقی نیفتاد).
چیزهایی که تست کردم:
- نسخه پورتبل
- نسخه نصبی
- پاک کردن تمام فولدرهای کش و تمپ و نصب از اول
- جا‌به‌جایی دایرکتوری
- تغییر PATH variable
- نصب PowerShell با winget
- حذف PowerShell
- Run As Administrator
- Compatibility mode
- روش‌های مختلف کانکشن
- باز کردن برنامه با پراکسی و دی‌ان‌اس
- ریستارت کامپیوتر...
سیستم عامل: Windows 10 Home 64-bit

### Minimal Reproducible Example (MRE)

1. Open software
2. Click Connect
3. "برنامه برای اجرا به نصب نرم‌افزار Powershell نیاز دارد."
4. Stuck forever

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
@Emtin 
ممنون از اطلاع رسانیتون این مشکل در pre-release بعدی حل میشه

**Comment by MOFA2002** [comment]
I'm in the same situation   Win10

**Comment by kiomarzsss** [comment]
checkout https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta and see if the issue still persist?

**Comment by Emtin** [comment]
I can confirm the issue does not persist in the new version. However, although it says connected, it doesn't seem to be working.

**Comment by kiomarzsss** [comment]
> I can confirm the issue does not persist in the new version. However, although it says connected, it doesn't seem to be working.

see if this helps: https://github.com/bepass-org/oblivion-desktop/issues/135#issuecomment-2119277993
