### ISSUE TITLE
مشکل وصل شدن در اندروید 5.1.1

### ISSUE THREAD

**Issue by siaabd** [bepass-org/oblivion-desktop#122]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام.
در اندروید 5.1.1 برنامه در "درحال اتصال" میمونه و بعدش خود به خود قطع میشه و در زمانی هم که در حال اتصال بوده در اصل متصل بوده و به وی پی ان وصل هستش. مشکل از اندروید 5.1.1 است چون با چند نوع اینترنت همین مشکل رو داره و در پلتفرم های دیگه همچین مشکلی ندارم.

### Minimal Reproducible Example (MRE)

1.Android 5.1.1 phone
2.try to connect with one of the three methods
3.it stays at "trying to connect" phase

### Version

App Version: 2

### Platform/OS

Windows, macOS, Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

این پروژه مربوط به نسخه دسکتاپ هست

درخصوص موبایل باید اینجا گزارش مشکل رو ثبت کنین:
https://github.com/bepass-org/oblivion/issues
