### ISSUE TITLE
ارور هویت سنجی کلودفلر در مبین نت 

### ISSUE THREAD

**Issue by alijason72** [bepass-org/oblivion-desktop#123]
### Feature description

 سلام روی ویندوز 11 ارور مجوز هویت سنجی 
به کلودفلر با اینترنت مبین نت بهم می ده البته با نسخه ی اندرویدش مشکلی نداره وصل می شه  با نسخه ی دسکتاپش مشکل داره از همین امروز ظهر  اینطوری شد تا دیشب کار می کرد خواهش می کنم رفع کنین این مشکل رو با تشکر

**Comment by alijason72** [comment]
ممنون از پاسخ گویی شما الان روی ایریانسل تست کردم با همین برنامه ی دسکتاپ موجود خیلی عالی کار می کنه فقط روی مبین نت اون خطای هویت سنجی رو می ده اونم فقط روی نسخه ی دسکتاپ

**Comment by ircfspace** [comment]
ضمن تشکر از @Daredevil74 ،
بخشی از مشکل در آپدیت بعدی برنامه مرتفع میشه

لطفن صبور باشین
