### ISSUE TITLE
New version "v0.2.52-beta" not connecting, only version "v0.2.44-beta" will connect

### ISSUE THREAD

**Issue by Msadr471** [bepass-org/oblivion-desktop#125]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

[نسخه ابتدایی](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.2.44-beta) که نصب کردم به راحتی متصل می‌شود. اما [نسخه جدید](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.2.52-beta) برای من به هیچ وصل متصل نمی‌شود. در حال حاضر از [نسخه قدیمی](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.2.44-beta) استفاده می‌کنم.

### Minimal Reproducible Example (MRE)

1. it doesn't connect at all!
2. I tried all options also "run as administrator"

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
منتظر ارائه نسخه جدید باشین
