### ISSUE TITLE
Startup to Connect auto and Minimal the form?

### ISSUE THREAD

**Issue by pangafu** [bepass-org/oblivion-desktop#127]
### Feature description

or Make an option to connect when startup and minimal the form

**Comment by kiomarzsss** [comment]
thanks for your suggestion. we will consider to add this feature in the future.

**Comment by reddy14389** [comment]
we will consider to add this feature in the future. TANQ

**Comment by ircfspace** [comment]
hi,
The feature of connectivity upon opening the application and the possibility of quick connection will likely be available in the next update.
