### ISSUE TITLE
Privilege Problem

### ISSUE THREAD

**Issue by titancomputer** [bepass-org/oblivion-desktop#13]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello
if users choose to install the setup.exe file as administrator for all accounts of windows, the default install location will be "C:\Program Files\Oblivion Desktop" and because of this install location they need to launch the app with run as administrator.
if they don't, then warp-plus.exe hasn't privilege to start connection and it says access denied.

### Minimal Reproducible Example (MRE)

run oblivion-desktop-win-x64.exe
choose first option "anyone who uses this computer (all users)" and install on default location, then run the app as usual (without administrator privilege)
then start the connection and see the logs

### Expected Behavior

change the default install location to "AppData\Local\Programs\Oblivion Desktop"
or
if user installed the app on "C:\Program Files\Oblivion Desktop" then force the app to run as administrator by default

### Version

0.2.44-beta

### Platform/OS

Windows

### Relevant log output

```shell
time=2024-05-04T18:56:24.008+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-05-04T18:56:24.015+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T18:56:24.015+03:30 level=ERROR msg="unable to enable write config file: open stuff\\primary\\wgcf-profile.ini: Access is denied."
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
Thank you,
We will fix this issue in the next update
