### ISSUE TITLE
نشان دادن سرعت اتصال و میزان حجم مصرفی

### ISSUE THREAD

**Issue by ehsanna11111** [bepass-org/oblivion-desktop#132]
### Feature description

ممنون از ایجاد و تداوم ارتقا نرم افزار خوبتون
لطفا اگه امکان داره در کنار پینگ مقدار نت مصرف شده و سرعت دانلود و آپلود لحظه ایی رو هم نمایش بدید

**Comment by WeebMan1** [comment]
با تشکر درخواست دوستمون رو کامل تر کنم با اجازه عزیزان
ممنون میشم حالت های زیر در صورت امکان اضافه بشن
Tun و در صورت امکان حالت گیمینگ به دلیل تحریم لازم هست
ماکس سرعت دانلود و اپلود / سرعت دانلود و اپلود لحظه ای
حجم مصرف شده در روز و ماه ( + دکمه رست حجم مصرف شده)
