### ISSUE TITLE
Allow Connection from LAN Not Working

### ISSUE THREAD

**Issue by titancomputer** [bepass-org/oblivion-desktop#133]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello
it's about https://github.com/bepass-org/oblivion-desktop/issues/14#issue-2279085979
in [0.4.5-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta) Allow Connection from LAN option doesn't work correctly.
here is some logs
```
[2024-05-18 23:38:19.878] [info]  past logs was deleted for new connection.
[2024-05-18 23:38:19.894] [info]  starting wp process...
[2024-05-18 23:38:19.895] [info]  C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:1080 --scan
[2024-05-18 23:38:19.930] [info]  trying to set system proxy...
time=2024-05-18T23:38:19.977+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
```

i had many tests w/wo license or w/wo proxy or none and in all modes it uses **127.0.0.1** and this is wrong.

Best Regards

### Minimal Reproducible Example (MRE)

install the app
activate allow from LAN in settings
connect
see logs

### Expected Behavior

when we select Allow Connection from LAN it should use " -b 0.0.0.0:8086 " parameter

### Version

0.4.5-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
please continue discussion about this issue here: https://github.com/bepass-org/oblivion-desktop/issues/142
