### ISSUE TITLE
تست ورژن 0.4.5

### ISSUE THREAD

**Issue by johhny1898** [bepass-org/oblivion-desktop#134]
### Feature description

سلام خسته نباشین
لایسنس چک شد خوب کار میکنه با چند بار قطع و وصلی رجیستر مشکلی نداره
 سایفون خوبه

 **ولی مشکل عدم باز کردن یوتوب و توییتر داره,یعنی عملا سایفون عمل عبور از فیلترینگو انجام نمیده و فقط سایتهای آزادو باز میکنه**
وارپ و گول خوب
اگر در استفاده از لایسنس با دامنه پیش فرض وصل نشدین یا ارور احراز داد با آی پی و پورت تمیز کلود امتحان کنین وصل میشه
پیشنهاد به جای اضافه کردن Non proxy
**SPLIT TUNNEL اضافه کنین**
**(پراکسی چین)(**upstream**)و همینطور ترکیب سایفون و وارپ**
با تشکر دوباره

**Comment by alijason72** [comment]
تست کردم خیلی عالی بود این ورژن مشکل با مبین نت رفع شده یه پورت خوب از همین برای مک انجام بشه عالیه دیگه ممنون موفق باشید

**Comment by kiomarzsss** [comment]
ممنون بخاطر تست دقیقی که انجام دادین. اینطور بازخورد ها بهم برای ادامه روحیه میده. و سعی میکنیم نسخه به نسخه مشکلات نرم افزار رو حل کنیم ❤️ 

(لطفا در رابطه به مشکلات مطرح شده هم به بخش ایشو های پین شده برای پیگیری ادامه ماجرا مراجعه کنید)
