### ISSUE TITLE
VBS path issue (System proxy settings not changing [BUG])

### ISSUE THREAD

**Issue by siq0o** [bepass-org/oblivion-desktop#135]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After 615a77d system proxy settings don't change to their respective values.

### Minimal Reproducible Example (MRE)

1. Select any connection method
2. Try connecting

### Version

v0.4.5

### Platform/OS

Windows

### Additional Context

Here are my previous settings that were changed using nekobox:

> [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
> "CertificateRevocation"=dword:00000001
> "DisableCachingOfSSLPages"=dword:00000000
> "IE5_UA_Backup_Flag"="5.0"
> "PrivacyAdvanced"=dword:00000001
> "SecureProtocols"=dword:00002800
> "User Agent"="Mozilla/4.0 (compatible; MSIE 8.0; Win32)"
> "ZonesSecurityUpgrade"=hex:95,17,bf,53,92,a7,da,01
> "WarnonZoneCrossing"=dword:00000000
> "EnableNegotiate"=dword:00000001
> "ProxyEnable"=dword:00000000
> "MigrateProxy"=dword:00000001
> "LockDatabase"=hex(b):cc,20,ad,18,af,0a,da,01
> "ProxyServer"="127.0.0.1:2081"
> "ProxyOverride"="<local>;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*"

### Relevant log output

```shell
[2024-05-19 01:02:36.985] [info] proxy has been set for your system successfully! time=2024-05-19T01:02:40.079+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
@siq0o 
i see 🤔...
could you please do the following and get back to me?:
1. right click on the app icon
2. open the file location 
3. and send me a screen shot of what you have on `resources/assets/bin`

also how you installed the app? (zip/exe(all users, one user))?

**Comment by siq0o** [comment]
@kiomarzsss Here are the files:
![image](https://github.com/bepass-org/oblivion-desktop/assets/101428607/749d931b-e9d5-4e20-9740-a7cd1b633635)

I'm running the portable app compiled from source (zip)

**Comment by kiomarzsss** [comment]
> @kiomarzsss Here are the files: ![image](https://private-user-images.githubusercontent.com/101428607/331872538-749d931b-e9d5-4e20-9740-a7cd1b633635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzMxMDksIm5iZiI6MTcxNjEzMjgwOSwicGF0aCI6Ii8xMDE0Mjg2MDcvMzMxODcyNTM4LTc0OWQ5MzFiLWU5ZDUtNGUyMC05NzQwLWE3Y2QxYjYzMzYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQxNTMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmMyNzAwY2RlNjdhOTJjOTAzNzIxN2FmNWQ5NzEzMDZjZDhjMzI2NzMyMWZkYWY2OGFlMTA0MDMxNzkwMmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.swF9H79XKYPXB0BA1DoGlGvzjl7S4RxcHUYhCjkP1bw)
> 
> I'm running the portable app compiled from source (zip)

i see...
create a folder in this folder called "vbs" and move all the files exept warp-plus.exe to it and your problem should be fixed.
i will fix this bug in the next version.

**Comment by kiomarzsss** [comment]
@siq0o 
i see...
create a folder in this folder called "vbs" and move all the files exept warp-plus.exe to it and your problem should be fixed.
i will fix this bug in the next version.

**Comment by kiomarzsss** [comment]
@siq0o 
i re-checked the problem and there was no problem on the official packages(https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta)
if you want to build from the source again run 'npm install' and build again and your problem should be fixed
