### ISSUE TITLE
اختلال وصل دو دستگاه همزمان

### ISSUE THREAD

**Issue by DANITOXIC** [bepass-org/oblivion-desktop#136]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام خسته نباشید مرسی از برنامه خوبتون 
مشکلی دارم که خواستم بگم
وقتی که از اپ شما روی ویندوز وصل میشم رو یک وایفای, روی دستگاه اندرویدم نمیتونم به vpn وصل بشم 

### Minimal Reproducible Example (MRE)

1:زمانی که وصل میشم روی ویندوز
2:روی موبایلم نمیتونم وصل بشم 
(هر دو دستگاه به یک شبکه وصل هستند)

### Version

0.4.5

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
سلام و درود مرسی از مشارکتتون. مشکل بررسی خواهد شد ولی در حال حاضر جزو اولویت ها نیست

**Comment by ircfspace** [comment]
سلام
از آخرین‌نسخه از برنامه استفاده کنین :
https://github.com/bepass-org/oblivion-desktop/releases/latest
