### ISSUE TITLE
خطا در اجرای لایسنس و سایفون

### ISSUE THREAD

**Issue by mehrdadaria** [bepass-org/oblivion-desktop#138]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

وقتی با سایفون وصل میشم نمیشه از توییتر اینستاگرام و یوتیوب استفاده کرد و کار نمیکنن در واقع با سایفون فقط میتونم از گوگل کروم و تلگرام استفاده کنم
یکی دیگه اینکه وقتی لایسنس و وارد میکنم خطای احراز هویت در کلودفلر میزنه و کلا با لایسنس وصل نمیشه. حتی چنتا کد مختلف وارد کردم که همشون همین خطارو میزدن و وصل نمیشدن

### Minimal Reproducible Example (MRE)

![Screenshot (30)](https://github.com/bepass-org/oblivion-desktop/assets/170221801/1cf4eeb0-9315-4b87-a30f-e8acbbba39a3)

### Version

0.4.5

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Onward4tw** [comment]
سلام وقت بخیر
من هم مشکل خطای احراز هویت در کلودفلر رو دارم. (لایسنس رایگان هست)
* همین مشکل رو با نسخه قبلی هم داشتم.

**Comment by Onward4tw** [comment]
سلام وقت بخیر
من هم مشکل خطای احراز هویت در کلودفلر رو دارم. (لایسنس رایگان هست)

* همین مشکل رو با نسخه قبلی هم داشتم.

[2024-05-19 11:33:04.136] [info]  past logs was deleted for new connection.
[2024-05-19 11:33:04.138] [info]  starting wp process...
[2024-05-19 11:33:04.139] [info]  C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --endpoint engage.cloudflareclient.com:2048
[2024-05-19 11:33:04.142] [info]  trying to set system proxy...
time=2024-05-19T11:33:04.159+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-19T11:33:04.159+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-19T11:33:04.161+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-19T11:33:04.161+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.56:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."

[2024-05-19 11:33:04.162] [info]  wp process exit successfully.
[2024-05-19 11:33:04.163] [info]  trying to disable system proxy...
[2024-05-19 11:33:04.201] [info]  proxy has been set for your system successfully!
[2024-05-19 11:33:04.219] [info]  proxy has been disabled for your system successfully!

**Comment by kiomarzsss** [comment]
about Psiphon(douplicated): https://github.com/bepass-org/oblivion-desktop/issues/139

about license issue quote from @johhny1898 (https://github.com/bepass-org/oblivion-desktop/issues/134) :
"اگر در استفاده از لایسنس با دامنه پیش فرض وصل نشدین یا ارور احراز داد با آی پی و پورت تمیز کلود امتحان کنین وصل میشه"
