### ISSUE TITLE
Psiphon issue

### ISSUE THREAD

**Issue by Ahmad-2213** [bepass-org/oblivion-desktop#139]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Psiphon can't handle http requests through proxy.
Isn't that possible to make it work with HTTP while it's already working on SOCKS5 ?
The problem is when you proxy an application such as discord via SOCKS5 , it is not able to handle the connections and you need to have it on HTTP rather than SOCKS5 in case if it's to be working.

### Minimal Reproducible Example (MRE)

Run warp + Psiphon 
establish a proxy via proxifier HTTP 
you'll see it isn't working but doing the same thing with SOCKS5 will work.( but it'll not answering the http requests)

### Version

latest

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
@Ahmad-2213 
thanks for your detailed explanation. oblivion desktop is GUI for warp-plus and we are not that much of experienced in network stuff. do you think this Psiphon issue would be fixed if we use tun mode?

**Comment by mahfelwp** [comment]
راه حل این مورد به این شکل هست که در مرورگر فایرفاکس به قسمت تنظیمات برید و قسمت network setting رو باز کنید و سپس در پنجره باز شده تیک گزینه Proxy DNS when using SOCKS v5 رو بزنید.

در مرورگر کروم هم بر روی آیکون نرم افزار کلیک راست کنید و گزینه properties رو بزنید در صفحه باز شده در تب Shortcut  در قسمت target دستور زیر رو وارد کنید و دکمه ذخیره رو بزنید. بخش اول که مسیر نرم افزار کروم هست از قبل موجود هست و احتمالا در سیستم شما مسیر دیگری داشته باشد که به اون دست نمیزنید و از --proxy به بعد رو بهش اضافه میکنید.
"C:\Program Files\Google\Chrome\Application\chrome.exe" --proxy-server="socks5://127.0.0.1:8086" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE 127.0.0.1"

**Comment by kiomarzsss** [comment]
@mahfelwp 
امکان برای تسهیل این فرآیند از سمت oblivion desktop پیشنهاد میکنید؟

**Comment by Ahmad-2213** [comment]
> @Ahmad-2213 thanks for your detailed explanation. oblivion desktop is GUI for warp-plus and we are not that much of experienced in network stuff. do you think this Psiphon issue would be fixed if we use tun mode?

I Change few things and break them down in case if you could fix the issues.
let's talk about Warp in Warp, I've noticed that domains are not resolved through the proxy (at least via Proxifer) and I had to do it manually via proxifier to be fixed. ( same on Psiphon ) 

// So the first issue is that domains are not resolved through the proxy automatically and they're by default , using DNS server which is set on PC.

For Psiphon though , It doesn't work on tun mode , and also , it can not be proxied via http protocol.
if it's to be used on chrome or other sort of browsers , Proxy softwares such as switchy omega are needed provided that establishing a SOCKS5  proxy.

This is all by far I know.

**Comment by johhny1898** [comment]
با سلام
مشکل سایفون مشکل ساکسه باید فورسش کنی تو بروزرها 
فایرفاکس خودش گزینه داره ولی کروم وایج ندارن باید تو برنامه دستوری بدی که از دی انس ساکس استفاده کنه 
تو موزیلا
about:config>>proxy
یه نگاهی بندازین

**Comment by ircfspace** [comment]
برای کروم هم یه راه حل پیدا کردم؛
توی آپدیت بعدی در دسترس قرار میگیره

**Comment by kiomarzsss** [comment]
> > @Ahmad-2213 thanks for your detailed explanation. oblivion desktop is GUI for warp-plus and we are not that much of experienced in network stuff. do you think this Psiphon issue would be fixed if we use tun mode?
> 
> I Change few things and break them down in case if you could fix the issues. let's talk about Warp in Warp, I've noticed that domains are not resolved through the proxy (at least via Proxifer) and I had to do it manually via proxifier settings to be fixed. ( same on Psiphon )
> 
> // So the first issue is that domains are not resolved through the proxy automatically and they're by default , using DNS server which is set on PC.
> 
> For Psiphon though , It doesn't work on tun mode , and also , it can not be proxied via http protocol. if it's to be used on chrome or other sort of browsers , Proxy softwares such as switchy omega are needed provided that establishing a SOCKS5 proxy.
> 
> This is by far all I know.

for TUN we will probably will go sing-box. since im getting good results tunneling my system using nekoray and warp-plus. but we have to test it on more scenarios just to make sure. 
one other problem that we have is that (as i mentioned before) im not that much of knowledge in network field and im open to any guides on how to use warp-plus+sing-box to tunnel all system traffic. (as mentioned im now doing it using nekoray)

**Comment by Draganikov** [comment]
Where is a boat
