### ISSUE TITLE
Allow Connection from LAN

### ISSUE THREAD

**Issue by titancomputer** [bepass-org/oblivion-desktop#14]
### Feature description

Hello

in warp-plus.exe v1.1.3 we can use the -b option like "warp-plus.exe -b 127.0.0.1:8086" and then use this proxy on internet options or other apps which you used this option on first beta release.

Also we can use "warp-plus.exe -b 0.0.0.0:8086" instead of previous parameters for allowing other device requests through the 8086 port which is known as "Share Connection in Local Network" or "Allow Connection from LAN".

in the next releases you can make an option in proxy setting for users to Allow Connection from LAN or not by changing the "0.0.0.0" or "127.0.0.1" in your codes.

Best Regards

**Comment by ircfspace** [comment]
Hi
This feature will be available in the next update
https://github.com/bepass-org/oblivion-desktop/pull/50

**Comment by titancomputer** [comment]
Hello
in latest beta release [0.4.5-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta)
Allow for LAN option doesn't work correctly
here is some logs

```
[2024-05-18 23:38:19.878] [info]  past logs was deleted for new connection.
[2024-05-18 23:38:19.894] [info]  starting wp process...
[2024-05-18 23:38:19.895] [info]  C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:1080 --scan
[2024-05-18 23:38:19.930] [info]  trying to set system proxy...
time=2024-05-18T23:38:19.977+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
```

i had many tests w/wo license or w/wo proxy or none and in all modes it uses 127.0.0.1 and this is wrong.

Best Regards
