### ISSUE TITLE
عدم اتصال به یوتیوب در حالت سایفون

### ISSUE THREAD

**Issue by kooshadab** [bepass-org/oblivion-desktop#140]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در نسخه آخر، در حالت روشن بودن گزینه سایفون ارتباط با وبسایت یوتیوب برقرار نمی‌شود، در حالی که سایر سایتها بدون مشکل باز می‌شوند. قبل از آپدیت به نسخه آخر این مشکل وجود نداشت.

### Minimal Reproducible Example (MRE)

۱. روشن کردن گزینه سایفون
۲. روشن کردن فیلترشکن
۳. باز کردن وبسایت یوتیوب

### Version

v0.4.5-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
@kooshadab 
این مشکل امکان داره بسته به تغییرات سیاست های GFW باشد... آیا در یک ساعت مشخص نسخه قبلی در حالت سایفون براتون کار میکنه و نسخه جدید
(0.4.5-beta)
 خیر؟

**Comment by kiomarzsss** [comment]
please continue discussion about this issue here: https://github.com/bepass-org/oblivion-desktop/issues/139
