### ISSUE TITLE
Share (LAN) not working, alway bind to 127.0.0.1

### ISSUE THREAD

**Issue by pangafu** [bepass-org/oblivion-desktop#142]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The newest version v0.4.5-beta
When check Share (LAN) options, alway bind proxy port to 127.0.0.1, other machine can't connect to the proxy.
![image](https://github.com/bepass-org/oblivion-desktop/assets/10149168/4779d303-cd99-4fa5-8994-fad1765429d5)
![image](https://github.com/bepass-org/oblivion-desktop/assets/10149168/949859ae-5105-46ec-89f9-9b07df88f56a)

### Minimal Reproducible Example (MRE)

1. check the option " Share (LAN)"
2. connecting
3. netstat -an | findstr port

### Version

v0.4.5-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by dreamskr** [comment]
i have same problem , hope fix it soon

**Comment by ircfspace** [comment]
Hi,
Thank you for your feedback.

We tried to fix the problem in the new update

https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.7-beta

**Comment by pangafu** [comment]
> Hi, Thank you for your feedback.
> 
> We tried to fix the problem in the new update
> 
> https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.7-beta

I tried 0.4.7-beta, still bind to 127.0.0.1...
![image](https://github.com/bepass-org/oblivion-desktop/assets/10149168/f09ecde6-b4a2-4556-8fdc-1c0e6d79ee21)
![image](https://github.com/bepass-org/oblivion-desktop/assets/10149168/3fe0ea98-e67f-44de-a7ce-fa25d5421f7f)

**Comment by kiomarzsss** [comment]
it should be fixed by now... could check check the latest version and see if the issue still persist? @pangafu @dreamskr

**Comment by pangafu** [comment]
> it should be fixed by now... could check check the latest version and see if the issue still persist? @pangafu @dreamskr

After restore setting, all is ok now, thanks~
