### ISSUE TITLE
برنامه متصل نمیشود خطای تنظیم اندپوینت میدهد.

### ISSUE THREAD

**Issue by shindler55** [bepass-org/oblivion-desktop#145]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

برنامه متصل نمیشود خطای تنظیم اندپوینت میدهد.

### Minimal Reproducible Example (MRE)

![oblivion](https://github.com/bepass-org/oblivion-desktop/assets/129758727/366f2e27-f84f-4e22-a658-bae3fae373f9)

### Version

v0.4.5beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
از تنظیمات برنامه گزینه بازیابی رو بزنید و یکبار دیگه امتحان کنید
