### ISSUE TITLE
نمی دونم چرا قبلیت tun سازنده اضافه نمی کنه 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#147]
### Feature description

![Screenshot (26)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/b7e22aa5-a7e7-480d-9219-a0159b6c3a44)

**Comment by Majidzam1101** [comment]
متاسفانه واتساپ ماکروسافت استور باز نمی کنه نمی دونم چرا قابلیت tun اضافه نمیشه !

**Comment by kiomarzsss** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/78
