### ISSUE TITLE
متاسفانه واتساپ ماکروسافت استور باز نمی کنه نمی دونم چرا قابلیت tun اضافه نمیشه !این نسخه همین مشکل قبلی یعنی تونل کردم کل سیستم ویندوز داره 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#148]
### Feature description

متاسفانه واتساپ ماکروسافت استور باز نمی کنه نمی دونم چرا قابلیت tun اضافه نمیشه !این نسخه همین مشکل قبلی یعنی تونل کردم کل سیستم ویندوز داره 

![Screenshot (26)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/f473af10-df0f-439f-a56b-ba0d9f4cdbfb)

**Comment by kiomarzsss** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/78
