### ISSUE TITLE
خطای اعتبار سنجی کلودفلر

### ISSUE THREAD

**Issue by kham3ro** [bepass-org/oblivion-desktop#149]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

زمان اتصال به خطای هویت سنجی کلودفلر بر می‌خورم (در اسکرین شات قابل دیدن است). در هر سه حالت وارپ، گول و سایفون تست کردم و هرسه هم خطا می‌دهند.

### Minimal Reproducible Example (MRE)

روی ویندوز ۱۱ تست شد و خطای ذکر شده در تصویر قابل رؤیت است.
![image](https://github.com/bepass-org/oblivion-desktop/assets/59319492/4c3cad0e-bc33-4d31-b6cd-a7575d28d3d3)

### Expected Behavior

متصل شود و روی پورت ۸۰۸۶ پروکسی ایجاد کند.

### Version

0.2.52-beta

### Platform/OS

Windows

### Application Config Options

```shell
تنظیمات پیشفرض برنامه تغییر داده نشدند
```

#### وارپ

```shell
time=2024-05-19T19:34:45.654+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-19T19:34:45.655+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-19T19:34:45.656+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-19T19:34:45.657+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-19T19:34:45.657+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.187:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```
#### سایفون
```
time=2024-05-19T19:19:09.136+03:30 level=INFO msg="psiphon mode enabled" country=CA
time=2024-05-19T19:19:09.136+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-19T19:19:09.137+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-19T19:19:09.138+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-19T19:19:09.139+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-19T19:19:09.139+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.70:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```

**Comment by ircfspace** [comment]
اگر لایسنس اضافه کردین اونو حذف کرده و از تنظیمات برنامه بر روی بازگردانی تغییرات بزنین

**Comment by Airuop** [comment]
> اگر لایسنس اضافه کردین اونو حذف کرده و از تنظیمات برنامه بر روی بازگردانی تغییرات بزنین

با تنظیمات پیشفرض و بدون لایسنس هم خطا میدهد.

**Comment by ircfspace** [comment]
لاگ برنامه بعد از بازگردانی تنظیمات رو هم ارسال کنین

**Comment by kham3ro** [comment]
بعد از انجام دستورات همچنان ایراد داره ... 
### Relevant log output

#### وارپ

```
time=2024-05-20T19:54:48.764+03:30 level=INFO msg="psiphon mode enabled" country=RO
time=2024-05-20T19:54:48.765+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T19:54:48.765+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T19:54:48.766+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T19:54:48.767+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-20T19:54:48.767+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.16:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```

#### سایفون
```
time=2024-05-20T19:54:48.764+03:30 level=INFO msg="psiphon mode enabled" country=RO
time=2024-05-20T19:54:48.765+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T19:54:48.765+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T19:54:48.766+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T19:54:48.767+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-20T19:54:48.767+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.16:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```


#### گول

```
time=2024-05-20T19:54:17.712+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T19:54:17.713+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T19:54:17.713+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T19:54:17.715+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-20T19:54:17.715+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.16:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."


```

**Comment by ircfspace** [comment]
با آخرین آپدیت تست بگیرین:

https://github.com/bepass-org/oblivion-desktop/releases

**Comment by illegal1** [comment]
با آخرین اپدیت تست کردم اول مشکلی نداشت بعد :
time=2024-05-24T12:29:37.890+04:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-24 11:29:37.940] [info] system proxy has been set.
time=2024-05-24T12:29:53.624+04:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-24T12:29:53.624+04:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": uTlsConn.Handshake() error: EOF"

[2024-05-24 11:29:53.626] [info] wp process exited.
[2024-05-24 11:29:53.627] [info] trying to disable system proxy...
[2024-05-24 11:29:53.695] [info] system proxy has been disabled on your system.
برنامه رو ریست هم کردم همچنان مشکل هست

**Comment by illegal1** [comment]
با آخرین اپدیت تست کردم اول مشکلی نداشت بعد :

`time=2024-05-24T12:29:37.890+04:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-24 11:29:37.940] [info] system proxy has been set.
time=2024-05-24T12:29:53.624+04:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-24T12:29:53.624+04:30 level=ERROR msg="Post "[https://api.cloudflareclient.com/v0a3596/reg\](https://api.cloudflareclient.com/v0a3596/reg%5C)": uTlsConn.Handshake() error: EOF"

[2024-05-24 11:29:53.626] [info] wp process exited.
[2024-05-24 11:29:53.627] [info] trying to disable system proxy...
[2024-05-24 11:29:53.695] [info] system proxy has been disabled on your system.`
برنامه رو ریست هم کردم همچنان مشکل هست

**Comment by martinjoker** [comment]
[2024-05-24 14:56:21.612] [info]  past logs was deleted for new connection.
[2024-05-24 14:56:21.615] [info]  ------------------------MetaData------------------------
[2024-05-24 14:56:21.616] [info]  running on: win32 10.0.19044 x64
[2024-05-24 14:56:21.616] [info]  at od: 0.7.0-beta
[2024-05-24 14:56:21.617] [info]  at wp: v1.1.3
[2024-05-24 14:56:21.618] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-24 14:56:21.618] [info]  method: gool
[2024-05-24 14:56:21.619] [info]  proxyMode: false
[2024-05-24 14:56:21.619] [info]  endpoint: default
[2024-05-24 14:56:21.620] [info]  license: false
[2024-05-24 14:56:21.620] [info]  exe: C:\Program Files\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-24 14:56:21.621] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-24 14:56:21.622] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-24 14:56:21.622] [info]  ------------------------MetaData------------------------
[2024-05-24 14:56:21.635] [info]  starting wp process...
[2024-05-24 14:56:21.636] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --scan
time=2024-05-24T14:56:21.826+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-24T14:56:21.827+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-24T14:56:21.828+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-24T14:56:36.997+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account

time=2024-05-24T14:56:36.998+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": uTlsConn.Handshake() error: read tcp 172.16.10.150:65501->141.101.113.182:443: wsarecv: An existing connection was forcibly closed by the remote host."

[2024-05-24 14:56:37.001] [info]  wp process exited.

**Comment by kiomarzsss** [comment]
مشکلات وصل نشدن در روز های اخیر بابت آپدیت سیستم فیلترینگ هست و از سمت Oblivion Desktop قابل حل نیست و نیازه که مشکل در سمت دوستانمون در [warp-plus](https://github.com/bepass-org/warp-plus) پیگیری بشه و لطفا مشکلات مربوط به کانکشن رو داخل این پروژه مطرح کنید. ایشو های آتی مربوط به این قضیه تگ داپلیکت خورده و به این ایشو رفرنس داده میشن. با تشکر از وقتی که برای مشارکت گذاشتین.

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.

**Comment by kiomarzsss** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/202
