### ISSUE TITLE
درخواست لیست سیاه

### ISSUE THREAD

**Issue by behtash-fani** [bepass-org/oblivion-desktop#15]
### Feature description

سلام خدمت شما 
واقعا گل کاشتید. دمتون گرم عالی و به شدت پر سرعت
فقط اگر بشه در نسخه های بعدی یکی لیست سیاه برای اپلیکیشن ها و یکی هم برای دامنه های مختلف رو هم قرار بدید خیلی خوب میشه
ممنونم

**Comment by ircfspace** [comment]
سلام

لیست سیاه برنامه‌ها فعلن شدنی نیست، 
اما درحال کار روی بخش قوانین مسیریابی هستیم که بتونین مثل v2rayNG از دستورات GeoIP استفاده کنین

**Comment by behtash-fani** [comment]
آها . در هر صورت ممنونم ازتون . خسته نباشید
