### ISSUE TITLE
پیغام entry point not found

### ISSUE THREAD

**Issue by deyhimd** [bepass-org/oblivion-desktop#150]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و خدا قوت به توسعه دهنده عزیز
بعد از نصب پیغام  ظاهر میشه و برنامه باز نمیشه. نمیدونم مشکلش چیه. ایشالا اینم برطرف میکنین :)
![zedth zethzet E tnzryn](https://github.com/bepass-org/oblivion-desktop/assets/170257455/624e8be6-30ea-4964-bfb1-ace2faa8b29c)

### Minimal Reproducible Example (MRE)

I don't know

### Version

0.5.4

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
درود
ویندوزتون 8 هستش؟

**Comment by kiomarzsss** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/76

**Comment by deyhimd** [comment]
سلام. بله درسته
