### ISSUE TITLE
خطای احراز هویت در کلودفر در اینترنت مخابرات

### ISSUE THREAD

**Issue by Tebjox** [bepass-org/oblivion-desktop#151]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

خطای احراز هویت در کلودفر

### Minimal Reproducible Example (MRE)

1.Click on connect

### Oblivion Version

v0.4.7-beta

### Platform/OS

Windows

### Version / Architecture

11 x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
از تنظیمات برنامه بر روی بازگردانی تغییرات بزنین و مجدد تست کنین
اگر مشکل حل نشد، لاگ برنامه رو ارسال کنین

**Comment by hypo-thesis** [comment]
[2024-05-19 22:40:41.290] [info]  past logs was deleted for new connection.
[2024-05-19 22:40:41.295] [info]  starting wp process...
[2024-05-19 22:40:41.295] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
[2024-05-19 22:40:41.297] [info]  trying to set system proxy...
time=2024-05-19T22:40:41.315-07:00 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-19T22:40:41.316-07:00 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-19T22:40:41.317-07:00 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-19 22:40:41.373] [info]  proxy has been set for your system successfully!
time=2024-05-19T22:40:46.772-07:00 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.97.223 error="read udp 192.168.1.5:52777->188.114.97.223:1010: i/o timeout"

**Comment by MedicoAssassino** [comment]
[2024-05-19 23:15:53.139] [info]  past logs was deleted for new connection.
[2024-05-19 23:15:53.143] [info]  starting wp process...
[2024-05-19 23:15:53.143] [info]  C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
time=2024-05-19T23:15:53.170+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-19T23:15:53.171+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-19T23:15:53.172+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-19T23:16:08.387+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-19T23:16:08.387+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": EOF"

[2024-05-19 23:16:08.389] [info]  wp process exit successfully.

**Comment by shayandavoodii** [comment]
ISP: MTN
```
[2024-05-19 23:56:26.062] [info]  past logs was deleted for new connection.
[2024-05-19 23:56:26.069] [info]  starting wp process...
[2024-05-19 23:56:26.070] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
[2024-05-19 23:56:26.078] [info]  trying to set system proxy...
time=2024-05-19T23:56:26.115+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-19T23:56:26.115+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-19T23:56:26.116+03:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-19 23:56:26.204] [info]  proxy has been set for your system successfully!
time=2024-05-19T23:56:41.393+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-19T23:56:41.393+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": uTlsConn.Handshake() error: EOF"

[2024-05-19 23:56:41.395] [info]  wp process exit successfully.
[2024-05-19 23:56:41.397] [info]  trying to disable system proxy...
[2024-05-19 23:56:41.494] [info]  proxy has been disabled for your system successfully!

```

**Comment by dalpozak** [comment]
[2024-05-20 02:06:52.031] [info]  past logs was deleted for new connection.
[2024-05-20 02:06:52.038] [info]  starting wp process...
[2024-05-20 02:06:52.038] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
[2024-05-20 02:06:52.043] [info]  trying to set system proxy...
time=2024-05-20T03:06:52.144+04:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T03:06:52.147+04:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-20T03:06:52.155+04:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-20 02:06:52.254] [info]  proxy has been set for your system successfully!
time=2024-05-20T03:06:52.385+04:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:c3b0:5af4:2b53:53b5 error="dial udp [2606:4700:d1:0:c3b0:5af4:2b53:53b5]:854: connect: A socket operation was attempted to an unreachable network."

time=2024-05-20T03:06:52.868+04:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:f9bf:b761:1331:a5d1 error="dial udp [2606:4700:d0:0:f9bf:b761:1331:a5d1]:945: connect: A socket operation was attempted to an unreachable network."

time=2024-05-20T03:06:54.189+04:30 level=INFO msg="scan results" endpoints="[{AddrPort:162.159.195.107:880 RTT:153.5111ms CreatedAt:2024-05-20 03:06:53.7424445 +0430 +0330 m=+1.612930701} {AddrPort:188.114.98.137:7152 RTT:183.5108ms CreatedAt:2024-05-20 03:06:52.8665442 +0430 +0330 m=+0.737030401}]"
time=2024-05-20T03:06:54.189+04:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.107:880 188.114.98.137:7152]"
time=2024-05-20T03:06:54.189+04:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-20T03:06:58.285+04:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-20T03:06:58.597+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:06:58.661+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:01.268+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:02.331+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:02.426+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:04.608+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:25.171+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:80

time=2024-05-20T03:07:25.499+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=self.adblockultimate.net:443

time=2024-05-20T03:07:28.609+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:28.671+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:31.277+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:32.342+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:34.616+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:39.617+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:40.660+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=push.services.mozilla.com:443

time=2024-05-20T03:07:58.623+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:07:58.689+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:00.603+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=self.adblockultimate.net:443

time=2024-05-20T03:08:01.283+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:02.353+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:04.619+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:09.620+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:10.818+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=push.services.mozilla.com:443

time=2024-05-20T03:08:15.081+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:80

time=2024-05-20T03:08:17.974+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.com:443

time=2024-05-20T03:08:19.019+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-20T03:08:19.020+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443
time=2024-05-20T03:08:19.020+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-20T03:08:19.088+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-20T03:08:24.792+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:80

time=2024-05-20T03:08:28.637+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:28.700+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:29.281+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.com:443

time=2024-05-20T03:08:31.295+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:32.356+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:33.413+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.com:443

time=2024-05-20T03:08:36.545+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T03:08:39.536+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gateway-us-east1-b.discord.gg:443

time=2024-05-20T03:08:39.633+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

[2024-05-20 02:08:39.863] [info]  wp process exit successfully.
[2024-05-20 02:08:39.865] [info]  trying to disable system proxy...
[2024-05-20 02:08:40.131] [info]  proxy has been disabled for your system successfully!

**Comment by majidmcoin** [comment]
نکته جالب اینکه بعد از صانحه فرود سخت که اینترنت محابرات محدودشده ورژن 0.2.44 وصل میشه ولی ورژنهای بالاتر وصل نمیشن

**Comment by dalpozak** [comment]
> نکته جالب اینکه بعد از صانحه فرود سخت که اینترنت محابرات محدودشده ورژن 0.2.44 وصل میشه ولی ورژنهای بالاتر وصل نمیشن

تست کردید؟

**Comment by dalpozak** [comment]
![Screenshot 2024-05-20 152708](https://github.com/bepass-org/oblivion-desktop/assets/166274609/a112d888-baa6-42d7-9949-3569fd6a9b5d)
برای بنده هرکاری میکنم وصل نمیشه(نسخه 0.2.44)و نسخه های جدید تر وصل که میشه تو قسمت دریاف اطلاعات فریز میشه

**Comment by majidmcoin** [comment]
> > نکته جالب اینکه بعد از صانحه فرود سخت که اینترنت محابرات محدودشده ورژن 0.2.44 وصل میشه ولی ورژنهای بالاتر وصل نمیشن
> 
> تست کردید؟

بله. درحالت گول روی pc و mobile وصل شد

**Comment by dalpozak** [comment]
> > > نکته جالب اینکه بعد از صانحه فرود سخت که اینترنت محابرات محدودشده ورژن 0.2.44 وصل میشه ولی ورژنهای بالاتر وصل نمیشن
> > 
> > 
> > تست کردید؟
> 
> بله. درحالت گول روی pc و mobile وصل شد

خب برای بنده وصل نمیشه
چطوری میتونم باهاتون تو یه جای دیگه صحبت کنم؟
تلگرام یا دیسکورد دارید؟میخواستم یه چندتا سوال بپرسم

**Comment by majidmcoin** [comment]
همینجا میشه

**Comment by dalpozak** [comment]
> همینجا میشه

حالا جدا از این حرفا برای من  نه تو نسخه 0.2.44 وصل میشه نه جدید ترین نسخه نمی‌دونم مشکل از کجاست کمکی میتونید کنید

**Comment by majidmcoin** [comment]
گفتم با ورژن قدیمی امتحان کنید . مثلا ورژن ۱ رو موبایل

**Comment by Aseptronn** [comment]
> از تنظیمات برنامه بر روی بازگردانی تغییرات بزنین و مجدد تست کنین اگر مشکل حل نشد، لاگ برنامه رو ارسال کنین

[2024-05-20 17:18:15.019] [info]  past logs was deleted for new connection.
[2024-05-20 17:18:15.034] [info]  starting wp process...
[2024-05-20 17:18:15.035] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --endpoint engage.cloudflareclient.com:2048
time=2024-05-20T17:18:15.431+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T17:18:15.483+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T17:18:30.666+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account

[2024-05-20 17:18:30.720] [info]  wp process exit successfully.
time=2024-05-20T17:18:30.668+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": EOF"

**Comment by ircfspace** [comment]
از لایسنس دارین استفاده میکنین؟
@Aseptronn

**Comment by dahraf** [comment]
[2024-05-23 01:57:53.432] [info]  past logs was deleted for new connection.
[2024-05-23 01:57:53.434] [info]  ------------------------MetaData------------------------
[2024-05-23 01:57:53.435] [info]  running on: win32 10.0.22631 x64
[2024-05-23 01:57:53.436] [info]  at od: 0.7.0-beta
[2024-05-23 01:57:53.436] [info]  at wp: v1.1.3
[2024-05-23 01:57:53.437] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-23 01:57:53.438] [info]  method: psiphon
[2024-05-23 01:57:53.438] [info]  proxyMode: false
[2024-05-23 01:57:53.439] [info]  endpoint: default
[2024-05-23 01:57:53.440] [info]  license: false
[2024-05-23 01:57:53.440] [info]  exe: C:\Users\<USERNAME>\Downloads\Compressed\oblivion-desktop-win-x64\Oblivion Desktop.exe
[2024-05-23 01:57:53.441] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-23 01:57:53.442] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-23 01:57:53.442] [info]  ------------------------MetaData------------------------
[2024-05-23 01:57:53.454] [info]  starting wp process...
[2024-05-23 01:57:53.455] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --cfon --country GB --scan
time=2024-05-23T01:57:53.509+03:30 level=INFO msg="psiphon mode enabled" country=GB
time=2024-05-23T01:57:53.510+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-23T01:57:53.511+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-23T01:57:53.512+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-23T01:57:59.146+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.147 error="read udp 192.168.1.36:54603->162.159.193.147:880: i/o timeout"

time=2024-05-23T01:58:04.628+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.195.233 error="read udp 192.168.1.36:54604->162.159.195.233:7103: i/o timeout"

time=2024-05-23T01:58:06.526+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.97.179:878 RTT:144.9931ms CreatedAt:2024-05-23 01:58:05.0664582 +0330 +0330 m=+11.561952101} {AddrPort:188.114.96.81:946 RTT:151.6517ms CreatedAt:2024-05-23 01:58:06.1936295 +0330 +0330 m=+12.689123401}]"
time=2024-05-23T01:58:06.526+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.97.179:878 188.114.96.81:946]"
time=2024-05-23T01:58:06.526+03:30 level=INFO msg="running in Psiphon (cfon) mode"

time=2024-05-23T01:58:08.755+03:30 level=INFO msg="Handshaking, Please Wait..." subsystem=psiphon

err: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2024-05-22T22:28:09.764Z"}

time=2024-05-23T01:58:09.819+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=104.18.164.46:443

time=2024-05-23T01:58:19.827+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=196.244.217.74:554

time=2024-05-23T01:58:19.828+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.225.67:22

time=2024-05-23T01:58:19.832+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.225.247:22

time=2024-05-23T01:58:19.843+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=178.79.142.60:443

time=2024-05-23T01:58:19.849+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.51.3:443

time=2024-05-23T01:58:19.852+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=212.71.253.209:443

time=2024-05-23T01:58:19.855+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=213.171.211.68:53

time=2024-05-23T01:58:19.856+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=178.79.176.11:80

time=2024-05-23T01:58:19.858+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=196.244.217.68:22
time=2024-05-23T01:58:19.858+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.121.177:443

time=2024-05-23T01:58:40.999+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.88.69:22

time=2024-05-23T01:58:42.441+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.225.163:53

time=2024-05-23T01:58:42.937+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=213.219.38.224:23

time=2024-05-23T01:58:44.296+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=109.228.55.39:554

time=2024-05-23T01:58:45.371+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=j.sni.global.fastly.net:80

time=2024-05-23T01:58:48.709+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.55.175:554

time=2024-05-23T01:58:50.721+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.243.134:443

time=2024-05-23T01:58:58.668+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=104.18.164.46:443

time=2024-05-23T01:59:00.247+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.91.198:443

time=2024-05-23T01:59:04.383+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=165.231.33.38:554

time=2024-05-23T01:59:08.195+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.28.113:443

time=2024-05-23T01:59:09.552+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.55.165:443

time=2024-05-23T01:59:09.834+03:30 level=INFO msg="Unable to start psiphon" subsystem=psiphon !BADKEY="clientlib: tunnel establishment timeout" !BADKEY=reconnecting...

time=2024-05-23T01:59:09.889+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=a4197.b.akamai.net:443

time=2024-05-23T01:59:19.896+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.224.74:22

time=2024-05-23T01:59:19.897+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=165.231.33.38:22

time=2024-05-23T01:59:19.905+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.50.67:22

time=2024-05-23T01:59:19.910+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.225.163:53

time=2024-05-23T01:59:19.920+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.88.69:443

time=2024-05-23T01:59:19.921+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=104.18.164.46:443

time=2024-05-23T01:59:19.921+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.55.176:554

time=2024-05-23T01:59:19.925+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.48.51:443

time=2024-05-23T01:59:19.928+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=178.79.142.60:443

time=2024-05-23T01:59:19.936+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=196.244.217.68:80

time=2024-05-23T01:59:40.440+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.121.177:22

time=2024-05-23T01:59:42.060+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=213.219.38.224:80

time=2024-05-23T01:59:42.883+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=178.79.176.11:179

time=2024-05-23T01:59:43.153+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=185.3.94.87:80

time=2024-05-23T01:59:46.735+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.240.74:554

time=2024-05-23T01:59:47.195+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.77.31:80

time=2024-05-23T01:59:51.019+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=109.228.55.39:22

time=2024-05-23T02:00:03.689+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.197.229:53

time=2024-05-23T02:00:09.038+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=196.244.217.66:983

time=2024-05-23T02:00:09.156+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=77.68.91.198:554

time=2024-05-23T02:00:09.382+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=88.208.240.57:443

time=2024-05-23T02:00:09.911+03:30 level=INFO msg="Unable to start psiphon" subsystem=psiphon !BADKEY="clientlib: tunnel establishment timeout" !BADKEY=reconnecting...
time=2024-05-23T02:00:09.911+03:30 level=ERROR msg="unable to run psiphon psiphon handshake maximum time exceeded"

[2024-05-23 02:00:09.924] [info]  wp process exited.

**Comment by Aseptronn** [comment]
> از لایسنس دارین استفاده میکنین؟ @Aseptronn

سلام ، خیر

**Comment by kiomarzsss** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/202

**Comment by alirezaservatii** [comment]
منم رو نسخه های ویندوز ارور احراز هویت میگیرم فرقی نداره که تنظیمات اصلی باشه یا اندپوینت با ای پی  و پورت تمیز

[2024-05-26 11:46:12.729] [info]  past logs was deleted for new connection.
[2024-05-26 11:46:12.731] [info]  ------------------------MetaData------------------------
[2024-05-26 11:46:12.732] [info]  running on: win32 10.0.22631 x64
[2024-05-26 11:46:12.733] [info]  at od: 0.8.16-beta
[2024-05-26 11:46:12.733] [info]  at wp: v1.1.3
[2024-05-26 11:46:12.735] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-26 11:46:12.736] [info]  method: gool
[2024-05-26 11:46:12.736] [info]  proxyMode: true
[2024-05-26 11:46:12.737] [info]  endpoint: default
[2024-05-26 11:46:12.737] [info]  license: false
[2024-05-26 11:46:12.738] [info]  exe: C:\Users\<USERNAME>\AppData\Local\Programs\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-26 11:46:12.738] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-26 11:46:12.739] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-26 11:46:12.739] [info]  ------------------------MetaData------------------------
[2024-05-26 11:46:12.749] [info]  starting wp process...
[2024-05-26 11:46:12.749] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --scan --rtt 1s
[2024-05-26 11:46:12.757] [info]  trying to set system proxy...
time=2024-05-26T11:46:12.788+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-26T11:46:12.790+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-26T11:46:12.790+03:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-26 11:46:12.991] [info]  system proxy has been set.
time=2024-05-26T11:46:28.983+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-26T11:46:28.983+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": uTlsConn.Handshake() error: EOF"

[2024-05-26 11:46:28.991] [info]  wp process exited.
[2024-05-26 11:46:28.994] [info]  trying to disable system proxy...
[2024-05-26 11:46:29.143] [info]  system proxy has been disabled on your system.
