### ISSUE TITLE
add hard coded text to translation locals

### ISSUE THREAD

**Issue by kiomarzsss** [bepass-org/oblivion-desktop#156]

**Comment by Princeyadav05** [comment]
@kiomarzsss can you share more information on this issue?

**Comment by ircfspace** [comment]
The codes related to the multilingual feature have been refactored by @GhostByeBye and are currently not hardcoded, 
but we are facing issues for calling the language selected by the user in main.ts, proxy.ts, and wp.ts (in LIB)

We've tried solutions like using cookies, local storage, and electron-store, but they haven't been successful. 
For now, we've enforced English as the language until we find a solution to this problem

**Comment by ircfspace** [comment]
fixed
