### ISSUE TITLE
[Bug] gool not working

### ISSUE THREAD

**Issue by Daredevil74** [bepass-org/oblivion-desktop#157]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درود
برنامه کلا به مشکل خورده و نیازه که اسکنر آیپی و پورت های سالم بهش اضافه بشه. حتی تو گروه های تلگرامی دارن آیپی های تمیز رو واسه oblivion قرار میدن و اکثرا کار نمیدن. فک میکنم اگه نمیشه که فرآیند جایگزینی خودکار و هوشمند آیپی/پورت یا همون اندپوینت به برنامه اضافه شه، حداقل اسکنر آیپی به برنامه اضافه شه. چون فیلترینگ و اختلال اینترنت ایران سینوسی و آزاردهنده‌اس.
روی نسخه جدید یکبار موفق به اتصال شدم و اونم در حالت وارپ ساده بود. گول از کار افتاده گویا. پینگ هم کلا یکبار به درستی نشون داده شد تو نسخه جدید و آیپی لوکیشن هم نمایش داده نمیشه. 

### Minimal Reproducible Example (MRE)

...

### Oblivion Version

v0.4.7-beta

### Platform/OS

Windows

### Version / Architecture

windows 11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
برنامه اسکنر داخلی داره و درصورتی که اندپوینت پیشفرض ست بشه، فعال میشه
اما قرار نیست بتونه اختلال‌های شدید و محدودیت‌هایی که روی اینترنت میذارن رو دور بزنه
