### ISSUE TITLE
Hope to add multiple proxy modes support.

### ISSUE THREAD

**Issue by ArtHuge** [bepass-org/oblivion-desktop#158]
### Feature description

Sometimes when I'm using the Windows client, I don't want to use a global proxy. I just need certain applications to use SOCKS5 or HTTP(S) proxy traffic. Can we add multiple proxy modes instead of just one system proxy? Thank you for your selfless development efforts.

**Comment by kiomarzsss** [comment]
you have the option to don't proxy your system if you want. (set proxy mode to none in application settings). it will just create a proxy(at 127.0.0.1:8086 by default)

**Comment by mingxing0769** [comment]
通过V2rayN IP规则来代理流量.在V2ray中加一个socks代理  地址127.0.0.1 端口：8086（或你自己设置的）。Oblivion Desktop里设置允许局域网访问，并且代理设置为无。

**Comment by ircfspace** [comment]
You can use v2rayN for TUN :

https://shorturl.at/mNNMm
