### ISSUE TITLE
Linux openwrt version

### ISSUE THREAD

**Issue by khosro0** [bepass-org/oblivion-desktop#16]
### Feature description

Please provide openwrt versions, iranian people need it, Especially openwrt for mipsel_24kc, for mt7621 cpu we need mipsel_24kc version 
thank you

**Comment by ircfspace** [comment]
سلام

متاسفانه فکر نمیکنم بشه ازش ساپورت کرد :
https://github.com/nodejs/node/blob/HEAD/BUILDING.md#platform-list
