### ISSUE TITLE
portable version language setting

### ISSUE THREAD

**Issue by Bannyc** [bepass-org/oblivion-desktop#161]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i use portable version for windows and when i try to change my language i find there is no way to do so

### Minimal Reproducible Example (MRE)

i use portable version for windows and when i try to change my language i find there is no way to do so

### Oblivion Version

0.2.52-beta

### Platform/OS

Windows

### Version / Architecture

win10 x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
hi,
Try the latest version:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.7-beta
