### ISSUE TITLE
مشکل اتصال در نسخه 0.4.7 و اتصال بهتر در نسخه 0.2.44 

### ISSUE THREAD

**Issue by paulvek** [bepass-org/oblivion-desktop#162]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

نسخه 0.2.44 پرتابل تا حالا در عرض چند ثانیه متصل شده و اغلب اوقات متصل میشه و با سرعت و کیفیت خوب کار میکنه.
امروز نسخه 0.4.7 رو تست کردم همچنین نسخه قبلتر، اغلب یا متصل نمیشه یا خیلی کند متصل میشه.
از نظر مکانیزم سرچ و اتصال نسخه قدیمی 0.2.44 خیلی عملکرد خوب و بدون ایرادی داره و اغلب به سرعت کانکت میشه اما نسخه های جدیدتر، نه...
ویدیوی زیر رو ببینید

https://github.com/bepass-org/oblivion-desktop/assets/153482922/b2893c78-89f3-4b0b-8ddd-03117198be5d

### Minimal Reproducible Example (MRE)

-

### Expected Behavior

امکانات نسخه های جدید رو حفظ کنید اما از مکانیزم اتصال نسخه های قدیمی تر استفاده کنید تا بدون اختلال و به سرعت بتونیم کانکت بشیم.

### Oblivion Version

0.4.7 and 0.2.44

### Platform/OS

Windows

### Version / Architecture

v11 x64

### Additional Context

-

### Application Config Options

```shell
دیفالت
گول یا warp in warp
اندپوینت engage.cloudflareclient.com:2408
لایسنس فری
در نسخه 0.4.7
-------------
دیفالت
تیک اسکنر فعال
نوع آی پی اتوماتیک
پورت پروکسی 8086
گول warp in warp فعال
لایسنس فری
در نسخه 0.2.44
```

### Relevant log output

```shell
-
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Aseptronn** [comment]
> از دیشب ساعت 12 شب وارپ کاملا روی مخابرات قطع شده هم پروژه وارپ کامندلاین مهندس قبادی (warp-plus) و هم oblivion (البته که هردو یکی هستن) میخاستم ببینم مشکل برای همه پیش اومده و فقط روی مخابرات چنین مشکلی هست؟

من مخابرات روی گوشی وصلم اما پی سی خیر

**Comment by ircfspace** [comment]
@paulvek 
ضمن تشکر از بازخورد شما،
فرایند اتصال در بتای نخست دقیق نبود (و اگر دقت کنین عملن بعد از اتصال آی‌پی خودتون رو نمایش میداد). در نسخه‌های بعدی سعی کردیم که تا زمانی‌که مقدار warp=on نشه، اعلام نکنیم که پروکسی به صورت کامل متصل شده. علت وقفه زمانی اینه، وگرنه نسخه جدید از نظر پیکربندی سیستم چندین‌ثانیه سریع‌تر هم شده و زمانی‌که منتظر اتصال هستین مربوط میشه به CLI و همینطور وضعیت پراختلال اینترنت.
