### ISSUE TITLE
مشکل اتصال به فیلترشکن

### ISSUE THREAD

**Issue by Hamidrezamrs** [bepass-org/oblivion-desktop#164]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در نت « های وب» از امروز به مشکل اتصال برخوردم برنامه در ۳ حالت اتصالی که در برنامه وجود دارد در مرحله دریافت اطلاعات باقی می‌ماند و متصل نمی‌شود.

### Minimal Reproducible Example (MRE)

۱- کلیک بر روی دکمه اتصال
۲- در حال اتصال 
۳- دریافت اطلاعات 

### Oblivion Version

0.4.7

### Platform/OS

Windows

### Version / Architecture

v10 x64

### Relevant log output

```shell
[2024-05-20 19:24:30.920] [info]  past logs was deleted for new connection.
[2024-05-20 19:24:30.927] [info]  starting wp process...
[2024-05-20 19:24:30.928] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --scan
[2024-05-20 19:24:30.935] [info]  trying to set system proxy...
time=2024-05-20T20:24:30.974+04:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T20:24:30.977+04:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-20T20:24:30.978+04:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-20 19:24:31.094] [info]  proxy has been set for your system successfully!
time=2024-05-20T20:24:32.981+04:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.98.139:894 RTT:196.1781ms CreatedAt:2024-05-20 20:24:32.89199 +0430 +0330 m=+1.927735501} {AddrPort:162.159.195.231:928 RTT:239.2141ms CreatedAt:2024-05-20 20:24:32.199366 +0430 +0330 m=+1.235111501}]"
time=2024-05-20T20:24:32.981+04:30 level=INFO msg="using warp endpoints" endpoints="[188.114.98.139:894 162.159.195.231:928]"
time=2024-05-20T20:24:32.981+04:30 level=INFO msg="running in normal warp mode"

time=2024-05-20T20:24:35.618+04:30 level=INFO msg="serving proxy" address=127.0.0.1:8086
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام،
از تنظیمات وارپ گزینه گول رو هم امتحان کنین
البته قبل از هرچیز از تنظیمات برنامه بر روی بازگردانی تنظیمات بزنین

**Comment by Hamidrezamrs** [comment]
مشکل پا برجاست با این لاگ 

time=2024-05-20T20:35:50.982+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:51.235+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:53.619+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:443

time=2024-05-20T20:35:55.233+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:55.487+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:55.969+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:56.235+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:35:58.314+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=self.events.data.microsoft.com:443

time=2024-05-20T20:35:59.577+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T20:36:13.851+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons4.gvt2.com:443

time=2024-05-20T20:36:15.022+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons3.gvt2.com:443

time=2024-05-20T20:36:17.931+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons3.gvt2.com:443

time=2024-05-20T20:36:18.387+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons4.gvt2.com:443

time=2024-05-20T20:36:18.896+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T20:36:20.985+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:21.238+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:25.235+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:25.492+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:25.971+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:26.237+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:33.133+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=self.events.data.microsoft.com:443

time=2024-05-20T20:36:44.154+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons3.gvt2.com:443

time=2024-05-20T20:36:45.025+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons2.gvt2.com:443

time=2024-05-20T20:36:47.934+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons4.gvt2.com:443

time=2024-05-20T20:36:48.389+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=beacons3.gvt2.com:443

time=2024-05-20T20:36:49.604+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T20:36:50.987+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T20:36:51.240+04:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

**Comment by mmnjrzdgn** [comment]
سلام. روی شاتل هم متصل نمیشه، روی دریافت اطلاعات میمونه.
[2024-05-20 23:00:09.276] [info]  past logs was deleted for new connection.
[2024-05-20 23:00:09.282] [info]  starting wp process...
[2024-05-20 23:00:09.283] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
[2024-05-20 23:00:09.312] [info]  trying to set system proxy...
time=2024-05-20T23:00:09.334+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-05-20T23:00:09.335+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-20T23:00:09.336+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-20 23:00:09.462] [info]  proxy has been set for your system successfully!
time=2024-05-20T23:00:15.559+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.192.199 error="read udp 192.168.1.199:50412->162.159.192.199:4198: i/o timeout"

time=2024-05-20T23:00:16.161+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:9d8c:52f:6687:bba9 error="dial udp [2606:4700:d1:0:9d8c:52f:6687:bba9]:8742: connect: A socket operation was attempted to an unreachable network."

time=2024-05-20T23:00:16.346+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:162.159.195.227:880 RTT:171.9929ms CreatedAt:2024-05-20 23:00:16.1609793 +0330 +0330 m=+6.831157401} {AddrPort:188.114.99.67:934 RTT:204.9559ms CreatedAt:2024-05-20 23:00:10.2796552 +0330 +0330 m=+0.949833301}]"
time=2024-05-20T23:00:16.346+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.227:880 188.114.99.67:934]"
time=2024-05-20T23:00:16.346+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-20T23:00:19.573+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-20T23:00:19.576+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:00:19.913+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=storeedgefd.dsx.mp.microsoft.com:443

time=2024-05-20T23:00:34.594+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

**Comment by kiomarzsss** [comment]
لطفا مشکل مورد نظر رو در:
https://github.com/bepass-org/warp-plus
مطرح کنید.

**Comment by Abolfaazl2011** [comment]
رو دریافت اطلاعات گیر میکه

**Comment by Alchemsit613** [comment]
> رو دریافت اطلاعات گیر میکه

دقیقا برای من هم همینه

**Comment by Hamidrezamrs** [comment]
> از اندپوینت دیفالت دارین استفاده میکنین؟

بله

**Comment by Alchemsit613** [comment]
> > از اندپوینت دیفالت دارین استفاده میکنین؟
> 
> بله



> از اندپوینت دیفالت دارین استفاده میکنین؟

بله از اندپوینت دیفالت:
engage.cloudflareclient.com:2408

البته برای من روی ایرانسل به راحتی وصل میشه و مشکل با همراه اول هست. هم رو اندروید و هم ویندوز

**Comment by Alchemsit613** [comment]
> از اندپوینت دیفالت دارین استفاده میکنین؟

بله از اندپوینت دیفالت:
engage.cloudflareclient.com:2408

البته برای من روی ایرانسل به راحتی وصل میشه و مشکل با همراه اول هست. هم رو اندروید و هم ویندوز

**Comment by Ahmad-2213** [comment]
> از اندپوینت دیفالت دارین استفاده میکنین؟
با توجه به عکس زیر که دیشب اسکن کردم به نظر میاد همراه اول کل رنج وارپ رو مورد اختلال شدید قرار داده. احتمالا باید دنبال راه تازه ای گشت که درصورت فیلترینگ کامل، بشه این محدودیت رو دور زد.
![image](https://github.com/bepass-org/oblivion-desktop/assets/106820058/5594256a-2eaf-4982-868f-b22663a68865)

**Comment by johhny1898** [comment]
روی همراه اول وارپ جواب نمبده ولی ایرانول چرا 
مشکل از فرستنده است به گیرنده های خود دست نزنید lol

**Comment by Alchemsit613** [comment]
> روی همراه اول وارپ جواب نمبده ولی ایرانول چرا مشکل از فرستنده است به گیرنده های خود دست نزنید lol

رو ویندوز بله وارپ با همراه اول کار نمیکرد. اما روی اندروید ابلیویون کار میکرد.

**Comment by ircfspace** [comment]
در رابطه با اندپوینت، در آپدیت بعدی تنظیمات اسکنر در دسترس قرار میگیره تا بتونین با تغییر RTT به طیف بیشتری از آی‌پی مناسب دسترسی پیدا کنین

**Comment by Amirmahdighasemi** [comment]
> در رابطه با اندپوینت، در آپدیت بعدی تنظیمات اسکنر در دسترس قرار میگیره تا بتونین با تغییر RTT به طیف بیشتری از آی‌پی مناسب دسترسی پیدا کنین

سلام وقت بخیر، در رابطه با مشکل که روی دریافت اطلاعات گیر میکنه ایپی و پینگ رو هم نمایش نمیده ربطی به نت نداره من با نت مخابرات برای اندروید مشکلی ندارم ولی برای ویندوز روی دریافت گیرمیکنه این مورد از شش هفت تا اپدیت قبل تر این مشکل برطرف نشده و هرنوع تنظیمات هم عوض میکنم بازم همینطور هست 
<img width="348" alt="image" src="https://github.com/user-attachments/assets/4186537b-e23e-4040-a6d2-807e202df194">
