### ISSUE TITLE
خطای زمان اجرا

### ISSUE THREAD

**Issue by Arashch405** [bepass-org/oblivion-desktop#165]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با سلام من نرم افزارو نصب و اجرا کردم اما موقع اجرا با این خطا روبرو شدم ویندوزسون 64بیتی

Oblivion Desktop.exe - Entry Point Not Found 
The procedure entry point Discard Virtual Memory could not be located in the dynamic link library KERNEL32.dll. 

### Minimal Reproducible Example (MRE)

Oblivion Desktop.exe - Entry Point Not Found 
The procedure entry point Discard Virtual Memory could not be located in the dynamic link library KERNEL32.dll. 

### Expected Behavior

Oblivion Desktop.exe - Entry Point Not Found 
The procedure entry point Discard Virtual Memory could not be located in the dynamic link library KERNEL32.dll. 

### Oblivion Version

v0-4-5

### Platform/OS

Windows

### Version / Architecture

64

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
از چه سیستم عامل ای استفاده میکنید؟

**Comment by Arashch405** [comment]
ویندوز7

**Comment by kiomarzsss** [comment]
> ویندوز7

https://github.com/bepass-org/oblivion-desktop/issues/76
