### ISSUE TITLE
رو دریافت اطلاعات گیر میکنه

### ISSUE THREAD

**Issue by Abolfaazl2011** [bepass-org/oblivion-desktop#166]
### Feature description

time=2024-05-20T23:41:22.224+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-20T23:41:22.229+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T23:41:22.232+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T23:41:23.948+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-20T23:41:23.948+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-20T23:41:23.950+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-20T23:41:25.211+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-20T23:41:27.366+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:7450:959d:49cb:da49 error="dial udp [2606:4700:d1:0:7450:959d:49cb:da49]:1014: connect: A socket operation was attempted to an unreachable network."

time=2024-05-20T23:41:27.370+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:e5ef:a6ab:9d4c:54bd error="dial udp [2606:4700:d0:0:e5ef:a6ab:9d4c:54bd]:928: connect: A socket operation was attempted to an unreachable network."

time=2024-05-20T23:41:29.215+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:162.159.195.185:3854 RTT:188.5435ms CreatedAt:2024-05-20 23:41:28.3366387 +0330 +0330 m=+6.121029501} {AddrPort:188.114.98.117:4198 RTT:1.2788865s CreatedAt:2024-05-20 23:41:27.3640665 +0330 +0330 m=+5.148457301}]"
time=2024-05-20T23:41:29.215+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.185:3854 188.114.98.117:4198]"
time=2024-05-20T23:41:29.215+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-20T23:41:32.413+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-20T23:41:32.420+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:32.478+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.google.com:443

time=2024-05-20T23:41:33.670+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.191 error="read udp 192.168.8.112:53399->162.159.193.191:8886: i/o timeout"

time=2024-05-20T23:41:36.771+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=optimizationguide-pa.googleapis.com:443

time=2024-05-20T23:41:36.788+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.google.com:443

time=2024-05-20T23:41:37.421+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:40.313+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:40.595+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:42.969+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:44.284+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:41:47.276+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T23:41:57.402+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=play.google.com:443

time=2024-05-20T23:42:00.906+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=accounts.opera.com:443

time=2024-05-20T23:42:01.421+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=safebrowsing.googleapis.com:443

time=2024-05-20T23:42:01.423+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=accounts.opera.com:443

time=2024-05-20T23:42:01.424+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=accounts.opera.com:443

time=2024-05-20T23:42:01.426+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=extension-updates.opera.com:443

time=2024-05-20T23:42:01.364+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=accounts.opera.com:443

time=2024-05-20T23:42:02.505+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gxcorner.games:443

time=2024-05-20T23:42:02.507+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gama.ir:443

time=2024-05-20T23:42:03.581+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:04.473+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=mtalk.google.com:5228

time=2024-05-20T23:42:04.605+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=android.clients.google.com:443

time=2024-05-20T23:42:04.905+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=android.clients.google.com:443

time=2024-05-20T23:42:04.909+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=android.clients.google.com:443

time=2024-05-20T23:42:04.907+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=android.clients.google.com:443

time=2024-05-20T23:42:06.055+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=suggestqueries-clients6.youtube.com:443

time=2024-05-20T23:42:06.772+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=sd-images.operacdn.com:443

time=2024-05-20T23:42:07.079+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=desktop-qualityclient-sub.osp.opera.software:443

time=2024-05-20T23:42:07.520+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:10.316+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:10.599+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:12.979+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:13.768+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.google.com:443

time=2024-05-20T23:42:14.306+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:14.680+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=autoupdate.geo.opera.com:443

time=2024-05-20T23:42:33.585+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:37.314+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T23:42:37.535+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:40.319+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:40.605+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:42.980+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:42:44.308+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:03.588+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:07.539+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:10.323+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:10.608+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:12.984+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:13.819+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.google.com:443

time=2024-05-20T23:43:14.311+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:19.253+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=clients4.google.com:443

time=2024-05-20T23:43:27.328+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T23:43:32.526+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:43351: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:32.671+03:30 level=ERROR msg="dial: lookup www.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:38965: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:34.278+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:36.832+03:30 level=ERROR msg="dial: lookup optimizationguide-pa.googleapis.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:62459: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:43:36.832+03:30 level=ERROR msg="dial: lookup www.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:24419: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:37.672+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:35806: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:38.278+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:40.327+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:40.613+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:40.639+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:57108: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:40.662+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:53261: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:42.988+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:43.169+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:38348: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:44.315+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:43:44.327+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:56207: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:45.439+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=clientservices.googleapis.com:443

time=2024-05-20T23:43:47.412+03:30 level=ERROR msg="dial: lookup www.youtube.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:52316: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:43:57.532+03:30 level=ERROR msg="dial: lookup play.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:23021: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:00.936+03:30 level=ERROR msg="dial: lookup accounts.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:52874: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:01.462+03:30 level=ERROR msg="dial: lookup extension-updates.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:28966: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:44:01.462+03:30 level=ERROR msg="dial: lookup safebrowsing.googleapis.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:29794: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:44:01.462+03:30 level=ERROR msg="dial: lookup accounts.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:37421: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:44:01.462+03:30 level=ERROR msg="dial: lookup accounts.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:25122: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:01.486+03:30 level=ERROR msg="dial: lookup accounts.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:40619: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:02.532+03:30 level=ERROR msg="dial: lookup gama.ir. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:28671: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:44:02.532+03:30 level=ERROR msg="dial: lookup gxcorner.games. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:63040: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:03.600+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:27401: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:04.283+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:04.498+03:30 level=ERROR msg="dial: lookup mtalk.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:49744: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:04.631+03:30 level=ERROR msg="dial: lookup android.clients.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:40737: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:04.926+03:30 level=ERROR msg="dial: lookup android.clients.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:60014: i/o timeout" gool=inner subsystem=vtun
time=2024-05-20T23:44:04.926+03:30 level=ERROR msg="dial: lookup android.clients.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:49864: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:04.933+03:30 level=ERROR msg="dial: lookup android.clients.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:20891: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:06.085+03:30 level=ERROR msg="dial: lookup suggestqueries-clients6.youtube.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:18463: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:06.798+03:30 level=ERROR msg="dial: lookup sd-images.operacdn.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:39013: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:07.103+03:30 level=ERROR msg="dial: lookup desktop-qualityclient-sub.osp.opera.software. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:37766: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:07.553+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:26963: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:08.282+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:10.330+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:10.338+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:63874: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:10.616+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:10.620+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:58517: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:12.992+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:13.008+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:29812: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:13.790+03:30 level=ERROR msg="dial: lookup www.google.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:27999: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:14.323+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:18239: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:14.703+03:30 level=ERROR msg="dial: lookup autoupdate.geo.opera.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:50124: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:15.277+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:15.444+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=clientservices.googleapis.com:80

time=2024-05-20T23:44:17.335+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-20T23:44:33.604+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:28255: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:35.278+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:37.383+03:30 level=ERROR msg="dial: lookup www.youtube.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:20386: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:37.403+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=autoupdate.geo.opera.com:443

time=2024-05-20T23:44:37.558+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:20223: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:38.287+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:40.333+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:40.338+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:16111: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:40.619+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:40.624+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:32104: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:42.995+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:43.014+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:26962: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:44.328+03:30 level=ERROR msg="dial: lookup cloudflare.com. on 2620:fe::9: read udp [2606:4700:110:8c7a:a415:982:17de:9e83]:32168: i/o timeout" gool=inner subsystem=vtun

time=2024-05-20T23:44:45.281+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-20T23:44:56.697+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=accounts.google.com:443

**Comment by kiomarzsss** [comment]
لطفا مشکل مورد نظر رو در:
https://github.com/bepass-org/warp-plus
مطرح کنید.
