### ISSUE TITLE
کانکت نشدن واتساپ دسکتاب با oblivion

### ISSUE THREAD

**Issue by hamidreza2000m** [bepass-org/oblivion-desktop#168]
### Feature description

واتساپ دسکتاپ با این فیلترشکن کار نمیکنه ، با nekoray کار میکنه
با اپ warp+ هم واتساپ اخیرا کار نمیکرد البته
تلگرام و سایتهای فیلتر شده به راحتی و با پینگ بالا دارن باز میشن

**Comment by ircfspace** [comment]
سلام

ویژگی TUN برای پروکسی شدن کل سیستم در آپدیت های بعدی در دسترس قرار میگیره
در حالت system proxy میتونین از تلگرام و همینطور مرورگرهای کروم و فایرفاکس استفاده کنین

در رابطه با واتس‌اپ هم از نسخه وب اون استفاده کنین


https://github.com/bepass-org/oblivion-desktop/wiki
