### ISSUE TITLE
سایفون کار نمیکه 

### ISSUE THREAD

**Issue by majid1992** [bepass-org/oblivion-desktop#17]
### Feature description

درود و خسته نباشی،
روی گوشی عالی کار میکنه ولی روی  pc یا نسخه ویندوز گول کار میکنه ولی سایفون کار نمیکنه کلا روی هیچ لوکیشنی جواب نمیده.
لطفا برسی کنید. ممنون

**Comment by Majidzam1101** [comment]
سلام و خسته نباشید خدمت سازنده محترم obvilin desktop برنامه شما بتا را دانلود و نصب کرد روی ویندوز 10 در لپ تاپ روی حالت معمولی و گول بدون مشکل کار می کنه ولی دو مشکل وباگ دارد اول روی حالت سایفون است وصل میشه ولی هیچی باز نمی کنه نه مرورگر و نه تلگرام دومین مشکل کل برنامه بتا اوبویلیون ویندوز کل سیستم تونل نمیکنه حالت پروکسی فقط داره حالت vpntunnel مثل هیدوفای نکست نداره در نتیجه فروشگاه ماکروسافت وماکروسافت استور وبرنامه های نصب شده مثل واتساپ دسکتاپ از فروشگاه ماکروسافت استور نصب می شوند باز نمی نمی کنه اود نمی کنه ارور میزنه روی ایرانسل تست کردم لطفا لین دو مشکل را برطرف کنید  با تشکر  
![Uploading Screenshot (6).png…]()
![Screenshot (7)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/aded163a-59ed-4725-ac36-9dc7bd7545bd)

**Comment by Majidzam1101** [comment]
سلام و خسته نباشید خدمت سازنده محترم obvilin desktop برنامه شما بتا را دانلود و نصب کرد روی ویندوز 10 در لپ تاپ روی حالت معمولی و گول بدون مشکل کار می کنه ولی دو مشکل وباگ دارد اول روی حالت سایفون است وصل میشه ولی هیچی باز نمی کنه نه مرورگر و نه تلگرام دومین مشکل کل برنامه بتا اوبویلیون ویندوز کل سیستم تونل نمیکنه حالت پروکسی فقط داره حالت vpntunnel مثل هیدوفای نکست نداره در نتیجه فروشگاه ماکروسافت وماکروسافت استور وبرنامه های نصب شده مثل واتساپ دسکتاپ از فروشگاه ماکروسافت استور نصب می شوند باز نمی نمی کنه لود نمی کنه ارور میزنه روی ایرانسل تست کردم لطفا این دو مشکل را برطرف کنید  با تشکر  

![Uploading Screenshot (6).png…]()

**Comment by raminr63** [comment]
دقیقا من هم همچین مشکلی دارم

**Comment by ircfspace** [comment]
مشکل گزینه سایفون در دست بررسیه و در تلاشیم برای آپدیت بعدی برطرفش کنیم

**Comment by Majidzam1101** [comment]
> مشکل گزینه سایفون در دست بررسیه و در تلاشیم برای آپدیت بعدی برطرفش کنیم

سلام   گزینه اسکنر ای پی اتومات نسخه اندروید ندارد ! در نسخه ویندوز دارد مورد بعد قسمت گول خواهشا ای پی کشور های دیگه غیر از المان اضافه کنید مثل سوِئد یا فنلاند و غیره
