### ISSUE TITLE
کانکت نشدن و کار نکردن با اینترنت همراه اول

### ISSUE THREAD

**Issue by paulvek** [bepass-org/oblivion-desktop#170]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

**ابتدا بینهایت تشکر میکنم از زحمات و خدمات شما.** در حال حاضر اینترنت همراه اول در بین اپراتورها بهترین و پرسرعت ترین اینترنت هستش. اینو مخصوصا اونهایی درک میکنن که در نقاط وسط شهر یا تحت پوشش عادی نیستن و حتی در روستاها هم همراه اول با سرعت و پایداری بسیار بهتری از ایرانسل کار میکنه و در مجموع طبق گزارشات و آمارها و تست هایی که در اینترنت هم میتونید جستجو کنید در اکثر نقاط کشور همراه اول همیشه برنده بیشترین سرعت بوده و هست.
از نظر به صرفه بودن هم بسته های متنوع تری از ایرانسل داره مثلا بسته دانلود نامحدود شبانه که از 1 شب تا 11 صبح هست اما ایرانسل زمان بسیار محدودتری برای چنین بسته ای با قیمت بیشتر و حجم خیلی کمتر در نظر گرفته.
**و اما مشکل وی پی ان شما** متاسفانه oblivion چه در نسخه دسکتاپ و چه در نسخه اندروید، مثل تمامی وی پی ان های دیگه، یا کلا دسترسی ای نداره یا اینکه بسیار به سختی و محدود کانکت میشه... شما خیلی زحمت کشیدید و خیلی لطف داشتید ولی اگه بتونید مشکل رو در اینترنت همراه اول حل کنید واقعا ممنون میشیم. چون در برخی جاها حتی ایرانسل آنتن هم نداره و امکان استفاده از ایرانسل نیست و دسترسی به خط تلفن و اینترنت ای دی اس ال هم وجود نداره که مناطق زیادی از کشور هستن که چنین شرایطی دارن و همراه اول هم در نقاط تحت پوشش و هم در نقاط خارج از محدوده سایر اپراتورها با آنتن دهی و سرعت بهتر کار میکنه منتهی پروتکل های متفاوتی داره و فیلترینگ اثر بیشتری روی اون میذاره
هرچند در بعضی از شرایط تفاوتی دیده نمیشد و تمامی اینترنت ها و اپراتورها مسدود و محدود بودن و این بستگی به زمان های مختلف داره.
اما در شرایط چند روز اخیر و حال حاضر همراه اول دسترسی بسیار سختی داره. توی این روزها فقط دسترسی کمی به argo و v2ray داریم. که کفایت نمیکنه و اگه oblivion برای همراه اول هم اوکی بشه، بسیار عالی میشه.

### Minimal Reproducible Example (MRE)

-

### Expected Behavior

-

### Oblivion Version

0.4.7 and older version

### Platform/OS

Windows, macOS, Linux

### Version / Architecture

v11 x64 and etc

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،
فارغ از موضوع اختلالات که دسترسی رو سخت کرده، در بروزرسانی بعدی نسخه دسکتاپ بخش تنظیمات اسکنر اضافه میشه، تا شاید بتونه توی شرایط فعلی گره‌ای از کار باز کنه
لطفن بعد از انتشار بررسیش کنین

**Comment by paulvek** [comment]
> سلام ضمن تشکر از بازخورد شما، فارغ از موضوع اختلالات که دسترسی رو سخت کرده، در بروزرسانی بعدی نسخه دسکتاپ بخش تنظیمات اسکنر اضافه میشه، تا شاید بتونه توی شرایط فعلی گره‌ای از کار باز کنه لطفن بعد از انتشار بررسیش کنین

متشکرم لطف میکنید
