### ISSUE TITLE
ارور و باز نشدن برنامه

### ISSUE THREAD

**Issue by aghajani82** [bepass-org/oblivion-desktop#171]
### Feature description

سلام 
برنامه رو من نصب کردم ولی باز نمیشه و ارور میده
اینم عکس ارور 
![New Picture (1)](https://github.com/bepass-org/oblivion-desktop/assets/38226451/05fef986-37b6-4bc6-8a3d-1bfa083f7bae)

ببخشید دیگه
من هر کاری کردم توی قسمت باگ ها مشکلم روارسال کنم نشد

**Comment by ircfspace** [comment]
سلام

لطفا مطالعه کنین : https://github.com/bepass-org/oblivion-desktop/issues/76#issuecomment-2100536535

**Comment by aghajani82** [comment]
اوکی
ممنونم از شما
موفق باشید
