### ISSUE TITLE
عدم اتصال با اینترنت مخابرات حانگی

### ISSUE THREAD

**Issue by rm-killer** [bepass-org/oblivion-desktop#173]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

بعد از اتفاق مرگ بعضی ها... دیگه با نت مخابرات نسخه دسکتاپ و حتی گوشی متصل نمیشه و فقط نت همراه کار میکنه... راهی هست حل بشه؟

### Minimal Reproducible Example (MRE)

....

### Oblivion Version

all of them

### Platform/OS

Windows

### Version / Architecture

10

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.
