### ISSUE TITLE
لطف کنین رو همراه اول اوکیش کنین

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/oblivion-desktop#174]
### Feature description

خیلی جا های دور افتاده فقط و فقط همراه اول به عنوان اینترنت در دست رس هست ، و رو همراه اول رسما هیچی وصل نمیشه! من همه جوره تست کردم وصل نشد رو همراه اندپوینت دست نزدم کلی صبر کردم نشد، یه اند پوینت که رو نت وای فای وصل میشد زدم رو همراه باز وصل نشد لطفا رو همراه اول قشنگ بررسیش کنین و اوکی کنین... دو روز دیگه فیلترینگ نت وای فای هم میشه مثل همراه اول و رسما هیچی وصل نمیشه دیگه... تشکر فراوان از شما عزیزان

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.

**Comment by ELIAWrecker** [comment]
ipv6 connect perfect BUT ...

we cant connect to gool 
please fix this

**Comment by ircfspace** [comment]
Please look out for the new version of Warp-Plus; it's on the way...
