### ISSUE TITLE
oblivion-desktop

### ISSUE THREAD

**Issue by Msaeed0001** [bepass-org/oblivion-desktop#175]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

از دوشنبه رو این حالت دریافت اطلاعات میمونه و کار نمیکنه نسخه ویندوز 0.4.7 0.4.5 adsl شاتل
![photo_2024-05-22_15-52-58](https://github.com/bepass-org/oblivion-desktop/assets/170528902/351f0889-718c-4f01-961f-d779d757745a)

### Minimal Reproducible Example (MRE)

.

### Expected Behavior

.

### Oblivion Version

0.4.7

### Platform/OS

Windows

### Version / Architecture

v10 x64

### Additional Context

.

### Application Config Options

```shell
.
```

### Relevant log output

```shell
.
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mrjaycodes** [comment]
> ### Search first
> * [x]  I searched and no similar issues were found
> 
> ### What Happened?
> از دوشنبه رو این حالت دریافت اطلاعات میمونه و کار نمیکنه نسخه ویندوز 0.4.7 0.4.5 adsl شاتل ![photo_2024-05-22_15-52-58](https://private-user-images.githubusercontent.com/170528902/332794420-351f0889-718c-4f01-961f-d779d757745a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTEyNDIsIm5iZiI6MTcxNjM5MDk0MiwicGF0aCI6Ii8xNzA1Mjg5MDIvMzMyNzk0NDIwLTM1MWYwODg5LTcxOGMtNGYwMS05NjFmLWQ3NzlkNzU3NzQ1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNTE1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzllN2E0ZmU3YTI5NTMyZmVmNjY2NGViMjJmMDU0OWM5YmFmYzc2MzAwODhhYmRjZmZmMWQ4MjIzODM3YzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TX8An7tQ1HAKghkOhgF-8L2ESLmyMqRg8j7Z1zarwwA)
> 
> ### Minimal Reproducible Example (MRE)
> .
> 
> ### Expected Behavior
> .
> 
> ### Oblivion Version
> 0.4.7
> 
> ### Platform/OS
> Windows
> 
> ### Version / Architecture
> v10 x64
> 
> ### Additional Context
> .
> 
> ### Application Config Options
> ```shell
> .
> ```
> 
> ### Relevant log output
> ```shell
> .
> ```
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [ ]  I'm willing to submit a PR (Thank you!)

سلام، اپلیکیشن ویندوزی ما رو استفاده کنید، oblivion desktop در ریپوزیتوری ما هم هست :) (البته یه نسخه دیگه)

**Comment by ircfspace** [comment]
سلام
لاگ برنامه رو ارسال کنین

**Comment by Msaeed0001** [comment]
[2024-05-22 17:53:58.244] [info]  past logs was deleted for new connection.
[2024-05-22 17:53:58.250] [info]  starting wp process...
[2024-05-22 17:53:58.250] [info]  C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\warp-plus.exe--bind 127.0.0.1:8086 --gool --scan
[2024-05-22 17:53:58.812] [info]  trying to set system proxy...
time=2024-05-22T17:53:58.860+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-22T17:53:58.863+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-22T17:53:58.863+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-22T17:53:59.525+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:e52c:3ee9:1328:1a27 error="dial udp [2606:4700:d0:0:e52c:3ee9:1328:1a27]:854: connect: A socket operation was attempted to an unreachable network."

[2024-05-22 17:54:00.445] [info]  proxy has been set for your system successfully!
time=2024-05-22T17:54:00.867+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:162.159.192.105:3581 RTT:217.1756ms CreatedAt:2024-05-22 17:54:00.1233277 +0330 +0330 m=+1.271600801} {AddrPort:188.114.96.43:4198 RTT:218.6392ms CreatedAt:2024-05-22 17:53:59.5239588 +0330 +0330 m=+0.672231901}]"
time=2024-05-22T17:54:00.867+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.192.105:3581 188.114.96.43:4198]"
time=2024-05-22T17:54:00.867+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-22T17:54:04.338+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-22T17:54:04.390+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-22T17:54:04.544+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws5.web.telegram.org:443

time=2024-05-22T17:54:04.544+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws4.web.telegram.org:443

time=2024-05-22T17:54:05.753+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.211 error="read udp 192.168.1.4:61965->162.159.193.211:5956: i/o timeout"

time=2024-05-22T17:54:15.565+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws5.web.telegram.org:443

time=2024-05-22T17:54:15.565+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws4.web.telegram.org:443

time=2024-05-22T17:54:19.390+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-22T17:54:19.929+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=x.com:443

time=2024-05-22T17:54:25.731+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:443

time=2024-05-22T17:54:25.734+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-22T17:54:26.098+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=rr3---sn-5hne6nzs.googlevideo.com:443

time=2024-05-22T17:54:26.101+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:26.293+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=rr1---sn-5hnekn76.googlevideo.com:443

time=2024-05-22T17:54:26.328+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:26.377+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:26.585+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws5.web.telegram.org:443

time=2024-05-22T17:54:26.586+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=zws4.web.telegram.org:443

time=2024-05-22T17:54:27.794+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=optimizationguide-pa.googleapis.com:443

time=2024-05-22T17:54:27.810+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.com:443

time=2024-05-22T17:54:27.994+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=rr1---sn-5hnekn76.googlevideo.com:443

time=2024-05-22T17:54:28.088+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=rr3---sn-5hne6nzs.googlevideo.com:443

time=2024-05-22T17:54:28.313+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=i.ytimg.com:443

time=2024-05-22T17:54:28.360+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:28.392+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:28.835+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=www.youtube.com:443

time=2024-05-22T17:54:28.934+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=outlook.office.com:443

time=2024-05-22T17:54:29.238+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=outlook.office.com:443

[2024-05-22 17:54:30.609] [info]  wp process exit successfully.
[2024-05-22 17:54:30.611] [info]  trying to disable system proxy...
[2024-05-22 17:54:31.416] [info]  proxy has been disabled for your system successfully!
[2024-05-22 18:51:59.781] [info]  exiting the app...
[2024-05-22 18:51:59.797] [info]  trying to disable system proxy...
[2024-05-22 18:52:00.647] [info]  proxy has been disabled for your system successfully!
[2024-05-22 20:41:31.213] [info]  creating new od instance...
[2024-05-22 20:41:31.216] [info]  exe: G:\Program Files\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-22 20:41:31.217] [info]  userData: C:\Users\USERNAME\AppData\Roaming\oblivion-desktop
[2024-05-22 20:41:31.218] [info]  logs: C:\Users\USERNAME\AppData\Roaming\oblivion-desktop\logs
[2024-05-22 20:41:31.290] [info]  wp binary was copied to userData directory.
[2024-05-22 20:41:31.376] [info]  od is ready!

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.

**Comment by mrjaycodes** [comment]
> سلام لاگ برنامه رو ارسال کنین

برای چی پاک میکنی!
مه مرض داری!

**Comment by mrjaycodes** [comment]
> please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.

It's a part of my job and bepass job if he or she dont delete this comment
