### ISSUE TITLE
feature request: kill switch, bypass by process name or ip/domain

### ISSUE THREAD

**Issue by Morrigan-Ship** [bepass-org/oblivion-desktop#176]
### Feature description

add support kill swich

**Comment by kiomarzsss** [comment]
please explain more

**Comment by rm-killer** [comment]
کیل سوییچ دیگه... یعنی وقتی که ارتباط فیلترشکن قطع شد. ارتباط اینترنت رو هم قطع کنه تا آیپی آیران لیک نشه

**Comment by kiomarzsss** [comment]
فیچر خوبیه سعی میکنیم تو آپدیت های بعدی اضافه‌اش کنیم

**Comment by alijason72** [comment]
vpn route via app رو هم اضافه کنین 
عالی می شه دیگه ممنون

**Comment by Morrigan-Ship** [comment]
قابلیت Split VPN رو اضافه کنید سرچ کنید متوجه میشید چی هست که من توضیح میدم:
*یک لیست که فایل های *.exe , *.dll انتخاب شده رو از vpn عبور نمیده و با اینترنت عادی عبور داده میشه
*یک لیست که رنج آیپی و دامین رو از vpn عبور نمیده و با اینترنت اصلی عبور داده میشه:
 مثل:
192.1681.1/24
*.sub.domain.co*

**Comment by kiomarzsss** [comment]
@Morrigan-Ship
چکش میکنم حتما. خودتون تمایل دارین روی این فیچر کار کنید؟

**Comment by Morrigan-Ship** [comment]
> چکش میکنم حتما. خودتون تمایل دارین روی این فیچر کار کنید؟

بلد نیستم وگرنه حتمن اینکارو میکردم

**Comment by zamindoost1360** [comment]
سلام 
ادمین عزیز نسخه 2 جدید اوبولیلون قابلیت TUN  چه زمانی دانلودش در سایت قرار می گیره ؟ خیلی وقته نسخه اندروید ونسخه ویندوز اپدیت جدید نداده است خواهشمندم از سازنده محترم برنامه در اپدیت جدید قابلیت TUN  و پروتکل جدید Messqu  وارپ اضافه بشه با تشکر

**Comment by Subaru-Natsuki-The-Knight** [comment]
سلام خدمت تمامی دوستان.
برای رفع این مشکل ابتدا باید بخش TUN به اتمام برسه تا بشه Split و Kill Switch رو راه اندازی کرد.

**Comment by ircfspace** [comment]
The "tun" feature was added in the second version, and we are working on stabilizing its conditions. 
After completing the process, we will focus on this feature. It is still part of our roadmap.

**Comment by Morrigan-Ship** [comment]
کارت درسته رفیق
