### ISSUE TITLE
add support tun mode

### ISSUE THREAD

**Issue by Morrigan-Ship** [bepass-org/oblivion-desktop#177]
### Feature description

you can use 3 option for tun mode:

you can add support tun mode via tun2socks repo:
https://github.com/xjasonlyu/tun2socks

or you can use tun2proxy:
https://github.com/tun2proxy/tun2proxy

or you can tun mode via singbox:
make a socks outbound in config.json of singbox
enable tun mode via singbox
read singbox documents

please support all these 3 tun mode speed of them are different

**Comment by kiomarzsss** [comment]
we(current main collaborators) are not experienced in singbox. if you could provide us the config.json example to make a socks outbound(with tun mode) or provide us with the links it could be helpful. in early days of development of Oblivion Desktop i tried to use sing box to make a socks outbound and tunnel all my network traffic but couldn't figure it out. so any guide/help would be appreciated.

**Comment by Morrigan-Ship** [comment]
> if you could provide us the config.json example to make a socks outbound(with tun mode) or provide us with the links it could be helpful.

i can but i need to temporary VPS for make a correct singbox config
i dont have it.
