### ISSUE TITLE
درخواست پورت برای مک 

### ISSUE THREAD

**Issue by alijason72** [bepass-org/oblivion-desktop#178]
### Feature description

با سلام روی چند تا آی اس پی تست کردم از جمله مبین نت و ایرانسل و همره اول خیلی خوب کار می کنه سرعت نور فقط یه نکته ای که هست زبان چینی رو اضافه کردید کار خوبیه ولی باعث کاهش سرعت این شبکه می شه به شدت چون یوزرهاشون خیلی تعدادشون بالاست نکته ی بعد برای نسخه ی مک رو  اگه تستش تموم شده قرار بدید فقط برای اپل سیلیکون رو تست باتری یوزیج بگیرین که باتری زیاد نخوره v2ray با اپل سیلیکون m1 تست کردم و دارم خیلی خیلی افتضاح باتری مصرف می کنه باتری رو می خوره با تشکر ممنون از زحماتتون ...

**Comment by ircfspace** [comment]
سلام
اپ Oblivion از سرویس وارپ کلودفلر استفاده میکنه و بالارفتن یوزرهاش در چین، تاثیری روی یوزرهای ایرانی نمیذاره
در رابطه با مک هم متاسفانه هنوز پیکربندی system proxy استیبل نیست، اما اواخر کاره و بزودی منتشر میکنیم.

**Comment by alijason72** [comment]
kill switch رو اضافه کنید 
routing specific apps through a vpn رو اضافه کنید 
این دو قابلیت رو به اپ اضافه کنید بی نظیر می شه ممنون
