### ISSUE TITLE
Switching between profiles

### ISSUE THREAD

**Issue by Ahmad-2213** [bepass-org/oblivion-desktop#179]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

It appears to be an issue on "handling the connections" when switching between methods.
it's completely coincedential , I've found no pattern for this behavior.
you need keep switching between profiles to fix this issue.

### Minimal Reproducible Example (MRE)

turn off system proxy
Run warp on any desired method
go to any desired website, for instance : iplocation.com
check the logs , you'll see the "handling the connections" message

### Expected Behavior

there's an issue for "handling the connections" behavior, when there's something wrong with "handling the connections" , it has to return an error exception so we can see where the issue is, however, for the warp settings ,  whenever connecting to one of the profiles[warp, warp in warp , psiphon] it has to work on every ordinary website , but nothing at all ! no websites would open.

### Oblivion Version

latest

### Platform/OS

Windows

### Version / Architecture

x64

### Relevant log output

```shell
level=INFO msg="serving proxy" address=127.0.0.1:8086

level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=iplocation.com:443
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
i have no idea did you get the same results testing this on core(warp-plus) or it's just happening on oblivion desktop?

**Comment by Ahmad-2213** [comment]
> i have no idea, did you get the same results testing this on core(warp-plus) or it's just happening on oblivion desktop?

It's been fixed through the updates ! 
Just two problems exist, which are dns problem and HTTP proxy for psiphon.
some domains can't be resolved through proxy , or might say proxifier. such as gateway.discord.gg and dns.google . you might check yourself to get to know ... it'd be fixed if you go on " set system proxy" 
anyways, as long as warp works for me, I can Handle it. just as an issue , I opened it so you know where the problem is.

**Comment by ircfspace** [comment]
It seems that the issue you mentioned is related to the core, and you should report it in warp-plus.
https://github.com/bepass-org/warp-plus/issues

Nevertheless, please try using the latest version of the application once.
https://github.com/bepass-org/oblivion-desktop/releases/latest
