### ISSUE TITLE
Discord gateway issue using proxifier

### ISSUE THREAD

**Issue by Ahmad-2213** [bepass-org/oblivion-desktop#180]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

as shown below in the picture , you can see gateway.discord.gg & dns.google haven't respond to http requests whereas the other domains working pretty fine.
It's working properly using system proxy.
![image](https://github.com/bepass-org/oblivion-desktop/assets/106820058/7c481fe7-b549-464c-a64a-8dcfc6604d49)

### Minimal Reproducible Example (MRE)

Run any warp methods on "none proxy mode" & proxifier to tunnel certain apps (discord) & tcp connections.

### Oblivion Version

latest

### Platform/OS

Windows

### Version / Architecture

x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
i haven't use proxifier and have no idea why this happening. maybe your issue will get resolved when tun feature added. Although as you know we have bigger problem at the moment...
