### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by Ahmad-2213** [bepass-org/oblivion-desktop#181]
### Feature description

Adding Home tab(VPN Connection Tab) to lower-bar-settings could be more efficient & user friendly,making it easier to  switch between settings' tabs , also, moving these Tabs, you can remove Tripple lines at the top right-corner & replace it with logs.

![image](https://github.com/bepass-org/oblivion-desktop/assets/106820058/1cafd0a4-a4ef-41c5-b940-8d455937b57a)

**Comment by ircfspace** [comment]
Thanks for your feedback,
Small changes were made and we will try to improve it more in the next updates
