### ISSUE TITLE
اضافه کردن قابلبت split tunneling

### ISSUE THREAD

**Issue by B3MH** [bepass-org/oblivion-desktop#184]
### Feature description

برای بهتر شدنش میخواستم خواهش کنم که از قابلیت split tunneling یا اگر اشتباه نکنم bypass به نرم افزار اضافه کنید
این قابلیت مثل این هستش که به نرم افزار بگی چه سایتی رو از VPN استفاده کنه و چه سایتی رو نکنه در عین حال VPN وصل باشه
برای ما ایرانی ها که بیشتر با گوشی همزمان از نرم افزارهای بانکی یا مشابه دولتی مجبوریم استفاده کنیم خیلی میتونه مفید باشه

**Comment by ircfspace** [comment]
سلام
لطفن مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/66#issuecomment-2099953139
