### ISSUE TITLE
new version not worked

### ISSUE THREAD

**Issue by VixenSugo** [bepass-org/oblivion-desktop#188]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درود
مشکل اتصال برنامه در نسخه جدید هم برقراره و با ست کردن اندپوینت و تغییر تنظیمات پیشفرض هم حل نمیشه
از دو آپدیت قبلی برنامه متصل نمیشه و بعد از اتصال پینگ و لوکیشن هم نمیزنه چون عملا وصل نیست. حتی همون لایسنس رو توی نسخه اندرویدی هم که بزنیم تو بخش منیج دیوایس برنامه اصلی روی اندروید، دستگاه متصل دیگه‌ای رو نشون نمیده، در واقع دستگاه دیگه‌ای متصل نشده که بخواد نشون بده.
مشکل اتصال هم تا زمانی که هسته warp-plus آپدیت نشه حل نمیشه. اون پروژه هم دیگه متصل نمیشه. مشکل از همون پروژه وارپ پلاسه @markpash 

### Minimal Reproducible Example (MRE)

...

### Oblivion Version

0.7.0-beta

### Platform/OS

Windows

### Version / Architecture

windows 11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by erfanwhat** [comment]
کار نمیکنههههههههههه نه نسخه ویندوز نه اندروید

**Comment by Wwllin** [comment]
> ### Search first 先搜索
> * [x]  I searched and no similar issues were found 我搜索了一下，没有发现类似的问题
> 
> ### What Happened? 发生了什么？
> درود 祝福 مشکل اتصال برنامه در نسخه جدید هم برقراره و با ست کردن اندپوینت و تغییر تنظیمات پیشفرض هم حل نمیشه连接程序的问题在新版本中也成立了，无法通过设置端点和更改默认设置来解决 از دو آپدیت قبلی برنامه متصل نمیشه و بعد از اتصال پینگ و لوکیشن هم نمیزنه چون عملا وصل نیست. حتی همون لایسنس رو توی نسخه اندرویدی هم که بزنیم تو بخش منیج دیوایس برنامه اصلی روی اندروید، دستگاه متصل دیگه‌ای رو نشون نمیده، در واقع دستگاه دیگه‌ای متصل نشده که بخواد نشون بده. 由于前两次更新，程序没有连接，连接后也没有给出 ping 和位置，因为实际上并没有连接。即使我们在Android主程序的设备管理器部分中单击Android版本中的相同许可证，它也不会显示其他已连接的设备，事实上，它也没有想要显示其他已连接的设备。 مشکل اتصال هم تا زمانی که هسته warp-plus آپدیت نشه حل نمیشه. اون پروژه هم دیگه متصل نمیشه. مشکل از همون پروژه وارپ پلاسه 连接问题要等到warp-plus核心更新后才能解决。该项目将不再连接。问题来自 Warp Place 项目@markpash
> 
> ### Minimal Reproducible Example (MRE)
> 最小可重复示例 (MRE)
> ...
> 
> ### Expected Behavior 预期行为
> _No response 没有反应_
> 
> ### Oblivion Version 遗忘版本
> 0.7.0-beta 0.7.0-测试版
> 
> ### Platform/OS 平台/操作系统
> Windows 视窗
> 
> ### Version / Architecture 版本/架构
> windows 11 视窗 11
> 
> ### Additional Context 附加背景
> _No response 没有反应_
> 
> ### Application Config Options
> 应用程序配置选项
> _No response 没有反应_
> 
> ### Relevant log output 相关日志输出
> _No response 没有反应_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> 你愿意提交 PR 吗？如果您知道如何修复该错误。
> * [ ]  I'm willing to submit a PR (Thank you!) 我愿意提交 PR（谢谢！）

Change the endpoint to: 188.114.98.224:2408
![Uploading `.png…]()

**Comment by Wwllin** [comment]
@Daredevil74 Change the endpoint to: 188.114.98.224:2408
![endpoint](https://github.com/bepass-org/oblivion-desktop/assets/150108125/3be63bb0-08bf-40be-8b86-e510b83299a4)

**Comment by Ahmad-2213** [comment]
> کار نمیکنههههههههههه نه نسخه ویندوز نه اندروید

روی ویندوز، نسخه جدید برای شاتل راحت وصل میشه.
فقط سایت هارو بالا نمیاره که احتمالا مشکل از دی ان اس باشه...

**Comment by tnhgm** [comment]
فکر میکنم خود کلود فلر آی پی هایی که از سمت ایران میره کلا بسته
