### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#189]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

از زمان مرگ این بابا رییسی دیگه کار نمیکنه. نه روی گول نه روی وارپ و نه روی سایفون.
اینترنت هم ADSL مخابرات.

### Minimal Reproducible Example (MRE)

!

### Oblivion Version

0.7

### Platform/OS

Windows

### Version / Architecture

windows 10

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

فیلترینگ از روز جمعه تشدید شده؛ با این‌وجود یکبار با این‌اندپوینت تلاش کنین:
`188.114.98.224:2408`

**Comment by behzadchtp** [comment]
> سلام
> 
> فیلترینگ از روز جمعه تشدید شده؛ با این‌وجود یکبار با این‌اندپوینت تلاش کنین: `188.114.98.224:2408`

بله دیدم این پستتون تو کانال تلگرام. همین ادرس هم وارد کردم تو قسمت Endpoint ولی بازم جواب نداد...روی نسخه دسکتاپ که غیر از ادرس cloudflare هیچی رو قبول نمیکنه.

**Comment by ircfspace** [comment]
یه دور با اندپوینتی که گفتم با حالت عادی متصل شین؛ بعد دوباره با گول یا سایفون تلاش کنین
ببینین حل میشه؟

**Comment by behzadchtp** [comment]
> یه دور با اندپوینتی که گفتم با حالت عادی متصل شین؛ بعد دوباره با گول یا سایفون تلاش کنین ببینین حل میشه؟

نسخه  0.8.16 رو نصب کردم. چه در حالت عادی با اندپوینت دیفالت و چه با اندپوینت 188.114.98.224:2408 با وارپ و گول کانکت میشه ولی هیچ ترافیکی رد و بدل نمیشه. هیچی رو باز نمیکنه.....سایفون که در هر دو حالت اصلا کانکت هم نمشه.
اینترنت هم ADSL مخابرات.
