### ISSUE TITLE
دکمه اتصال کار نمیکنه

### ISSUE THREAD

**Issue by mohsenzasa** [bepass-org/oblivion-desktop#19]
https://github.com/bepass-org/oblivion-desktop/assets/124595625/354c6d17-d0f6-4eb6-aa46-bc8734d2f3b2

### Search first

- [X] I searched and no similar issues were found

### What Happened?

وقتی دکمه اتصال را میزنی بر میگرده سر جاش.ویندوز ۱۰ و فایل نصبی 

### Version

0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by titancomputer** [comment]
first close the app, then run app as administrator and try again.

**Comment by mohsenzasa** [comment]
ohhh,yes.. thankyou titancomputer

**Comment by Majidzam1101** [comment]
> close the app, then run app as administrator and try again.

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه



![Uploading Screenshot (8).png…]()
![Uploading Screenshot (6).png…]()

**Comment by Majidzam1101** [comment]
> close the app, then run app as administrator and try again.

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه



![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/478fedd3-e4eb-40d6-8693-df953d6c37e7)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/9689b2f4-874a-4450-af27-e9b369641f8f)
