### ISSUE TITLE
feat: User Should be able to change Oblivion Desktop settings and talk to oblivion desktop through command line args

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#191]
### Feature description

درود بر شما...
اگر ممکن است در نسخه های آتی هم حالت Tun رو هم اضافه کنید که از طریق میکروتیک بشه به کارت شبکه مجازی Oblivion Desktop هم vpn  زد که تمام ترافیک شبکه داخلی از همین کارت شبکه tun عبور بدیم.
مورد بعدی اینکه از طریق خط فرمان cmd هم بشه کانفیگ و کنترل کرد. یعنی از طریق cmd بشه تنظیمات رو دستکاری کرد و هم بشه کانکت و دیزکانکت کرد....برای مانیتورینگ و قرار دادن تو Task Scheduler خیلی خوب میشه.

**Comment by kiomarzsss** [comment]
برای cmd چرا مستقیم از خود هسته warp-plus استفاده نمیکنید؟ در رابطه با tun هم در آینده براش برنامه داریم ولی با sing-box یسری چالش داریم که به کمک نیاز داریم. برای اینکه ایشو ها شلوغ نشه ممنون میشم بعد از پایان مکالمه اگه حرف دیگه ای از سمت شما نیست این ایشو رو ببندید چون برای tun جدا تسک و ایشو داریم...

**Comment by behzadchtp** [comment]
> برای cmd چرا مستقیم از خود هسته warp-plus استفاده نمیکنید؟ در رابطه با tun هم در آینده براش برنامه داریم ولی با sing-box یسری چالش داریم که به کمک نیاز داریم. برای اینکه ایشو ها شلوغ نشه ممنون میشم بعد از پایان مکالمه اگه حرف دیگه ای از سمت شما نیست این ایشو رو ببندید چون برای tun جدا تسک و ایشو داریم...
وارپ پلاس که  چند وختیه که دیگه کار نمیکنه.بستنش....من به جهت این میگم از cmd ، چون اگه میشد از خود cmd هم برای کانکت شدن و تنظیماتش استفاده کرد و درون Task Scheduler قرار داد معرکه میشد. مثلا فرایند کانکت شدن  Oblivion Desktop تو ساعت های خاصی auto با استفاده از batch file اجرا بشه و کانکت کنه.

**Comment by behzadchtp** [comment]
> > برای cmd چرا مستقیم از خود هسته warp-plus استفاده نمیکنید؟ در رابطه با tun هم در آینده براش برنامه داریم ولی با sing-box یسری چالش داریم که به کمک نیاز داریم. برای اینکه ایشو ها شلوغ نشه ممنون میشم بعد از پایان مکالمه اگه حرف دیگه ای از سمت شما نیست این ایشو رو ببندید چون برای tun جدا تسک و ایشو داریم...
> > وارپ پلاس که  چند وختیه که دیگه کار نمیکنه.بستنش....من به جهت این میگم از cmd ، چون اگه میشد از خود cmd هم برای کانکت شدن و تنظیماتش استفاده کرد و درون Task Scheduler قرار داد معرکه میشد. مثلا فرایند کانکت شدن  Oblivion Desktop تو ساعت های خاصی auto با استفاده از batch file اجرا بشه و کانکت کنه.
من صحبت دیگه ای ندارم. اگر شما چیزی نمیخواهید اضافه کنید من ببندم این ایشو رو ببندم.

**Comment by kiomarzsss** [comment]
اوکی من داخل بک‌لاگ قرار میدم اگر کسی خواست روش کار کنه ولی جزو اولویت هامون نیست این فیچر

**Comment by ircfspace** [comment]
تا آماده‌شدن TUN میتونین از v2rayN کمک بگیرید :

https://shorturl.at/Dmzsz
