### ISSUE TITLE
نسخه اندروید در اینترنت همراه فیلتر شده

### ISSUE THREAD

**Issue by sepahreza** [bepass-org/oblivion-desktop#192]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

نسخه اندروید در اینترنت همراه فیلتر شده

### Minimal Reproducible Example (MRE)

نسخه اندروید در اینترنت همراه فیلتر شده

### Expected Behavior

نسخه اندروید در اینترنت همراه فیلتر شده

### Oblivion Version

07

### Platform/OS

Windows

### Version / Architecture

64

### Additional Context

نسخه اندروید در اینترنت همراه فیلتر شده

### Application Config Options

```shell
نسخه اندروید در اینترنت همراه فیلتر شده
```

### Relevant log output

```shell
نسخه اندروید در اینترنت همراه فیلتر شده
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by NimaRa2N** [comment]
برای من هم همین مشکل هست p2p اسیاتک دارم و adsl مخابرات و همراه اول هیچکدوم کانکت نمیشه

**Comment by ircfspace** [comment]
در رابطه با نسخه اندروید باید اینجا ایشو ثبت کنین:

https://github.com/bepass-org/oblivion/issues/new
