### ISSUE TITLE
وصل نشدن

### ISSUE THREAD

**Issue by abdollahabdollah2021** [bepass-org/oblivion-desktop#193]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام ببخشیدازیکهفته میشه دیگه وصل نمیشه همش میزنه درحال دریافت اطلاعات هرچی تنظیماتش تغییرمیدم حتی آیپی تمیزهم اضافه کردم بازم وصل نمیشه ومیزنه (درحال دریافت اطلاعات)باتشکر

### Minimal Reproducible Example (MRE)

سلام ببخشیدازیکهفته میشه دیگه وصل نمیشه همش میزنه درحال دریافت اطلاعات هرچی تنظیماتش تغییرمیدم حتی آیپی تمیزهم اضافه کردم بازم وصل نمیشه ومیزنه (درحال دریافت اطلاعات)باتشکر

### Oblivion Version

v0.7.0-beta

### Platform/OS

Windows

### Version / Architecture

x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by abdollahabdollah2021** [comment]
روی اینترنت همراه اول وهای وب این مشکل وجودداردبرای من

**Comment by NimaRa2N** [comment]
درسته من روی سیستمم ارور هویت سنجی و احزار هویت کلود فلر میده و روی سه تا نت اسیاتک اشتراکی و مخابرات و همراه اول تست کردم و حتی منکه بعضی وقتا از hiddify استفاده میکنم کانفیگای وارپ اونم ار کار افتادع

**Comment by msabetm** [comment]
کلا دیگه با وصل نمیشه قبلش خوب بود. سرعتشم عالی بود. الان فقط دریافت اطلاعات میزنه

**Comment by ircfspace** [comment]
سلام

فیلترینگ از روز جمعه تشدید شده؛ با این‌وجود یکبار با این‌اندپوینت تلاش کنین:
`188.114.98.224:2408`
