### ISSUE TITLE
باگ حالت گول

### ISSUE THREAD

**Issue by AlirezaGh1993** [bepass-org/oblivion-desktop#194]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

نسخه [0.7.0-beta] در حالت گول بازی های کریپتو تلگرام رو باز نمیکنه ولی به نسخه قبلی که میرم درسته و بالا میاره

### Minimal Reproducible Example (MRE)

گول

### Oblivion Version

0.7.0-beta

### Platform/OS

Windows

### Version / Architecture

win x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
تا رسیدن به نسخه استیبل، میتونین از هر نسخه ای که براتون بهتر کار میکنه استفاده کنین
