### ISSUE TITLE
Ubuntu 

### ISSUE THREAD

**Issue by MostafaRostami72** [bepass-org/oblivion-desktop#195]
### Feature description

لطفا نسخه اوبونتو رو هم منتشر کنید .
ما هم گناه داریم دیگه 😅🫠

**Comment by mrjaycodes** [comment]
باسلام، اگر برای نسخه oblivion اون هم روی اوبونتو میخواهید لطفا درخواست خود را به گیت هاب بنده ارسال نمایید

**Comment by mrjaycodes** [comment]
> ### Feature description
> لطفا نسخه اوبونتو رو هم منتشر کنید . ما هم گناه داریم دیگه 😅🫠

آیا برای نسخه اوبونتو هم میخواهید از برنامه ما استفاده کنید که همان oblivion هست؟

**Comment by MostafaRostami72** [comment]
خسته نباشید فراوان 🖐
منتظر نسخه لینوکس هستیم تشکر 🫠

**Comment by MostafaRostami72** [comment]
> > ### Feature description
> > لطفا نسخه اوبونتو رو هم منتشر کنید . ما هم گناه داریم دیگه 😅🫠
> 
> نسخه مک همین چند دقیقه پیش کاراش تموم شد بعد یه سری تست داخلی pre-release اش میکنیم و هدف بعدی لینوکس خواهد بود 🐧😉
خسته نباشید فراوان 🖐
منتظر نسخه لینوکس هستیم تشکر 🫠

**Comment by Rezam82** [comment]
> > ### Feature description
> > لطفا نسخه اوبونتو رو هم منتشر کنید . ما هم گناه داریم دیگه 😅🫠
> 
> نسخه مک همین چند دقیقه پیش کاراش تموم شد بعد یه سری تست داخلی pre-release اش میکنیم و هدف بعدی لینوکس خواهد بود 🐧😉

کی منتشر میشه پسر؟
مُردیم دیگه🫠
اگه ممکنه زود تر نسخه بتا رو قرار بدین

**Comment by kiomarzsss** [comment]
moved to: https://github.com/bepass-org/oblivion-desktop/issues/235
