### ISSUE TITLE
Error spawn 

### ISSUE THREAD

**Issue by Jahboulan** [bepass-org/oblivion-desktop#2]
I really don't know what happened but when I try to connect to the servers I had this message from Windows

![20240503_225852](https://github.com/bepass-org/oblivion-desktop/assets/168860072/40acf1f8-39c7-49b7-9753-570a67c7a3f4)

**Comment by ircfspace** [comment]
We Will Fix It on next update

**Comment by Jahboulan** [comment]
With much gratitude when will it be
you think?

**Comment by Majidzam1101** [comment]
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه
