### ISSUE TITLE
وصل نشدن 

### ISSUE THREAD

**Issue by seyedyasi** [bepass-org/oblivion-desktop#20]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با زدن دکمه برنامه برای وصل شدن هیچ اتفاقی نیفته و پیغام متصل نیستید تغییری نمیکنه،تنضیمات psiphon  و warp و هم تیک زدم و غیر فعال کردم توی هیچ حالتی متصل نمیشه 

### Minimal Reproducible Example (MRE)

نمیدونم یعنی چی

### Version

Last

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Majidzam1101** [comment]
سلام و خسته نباشید خدمت سازنده محترم obvilin desktop برنامه شما بتا را دانلود و نصب کرد روی ویندوز 10 در لپ تاپ روی حالت معمولی و گول بدون مشکل کار می کنه ولی دو مشکل وباگ دارد اول روی حالت سایفون است وصل میشه ولی هیچی باز نمی کنه نه مرورگر و نه تلگرام دومین مشکل کل برنامه بتا اوبویلیون ویندوز کل سیستم تونل نمیکنه حالت پروکسی فقط داره حالت vpntunnel مثل هیدوفای نکست نداره در نتیجه فروشگاه ماکروسافت وماکروسافت استور وبرنامه های نصب شده مثل واتساپ دسکتاپ از فروشگاه ماکروسافت استور نصب می شوند باز نمی نمی کنه ل
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/c100a96b-9b52-43cb-938e-5e45044ad1eb)
ود نمی کنه ارور میزنه روی ایرانسل تست کردم لطفا لین دو مشکل را برطرف کنید  با تشکر

**Comment by titancomputer** [comment]
close the app, then run app as administrator and try again.

**Comment by titancomputer** [comment]
> ### Search first
> * [x]  I searched and no similar issues were found
> 
> ### What Happened?
> با زدن دکمه برنامه برای وصل شدن هیچ اتفاقی نیفته و پیغام متصل نیستید تغییری نمیکنه،تنضیمات psiphon و warp و هم تیک زدم و غیر فعال کردم توی هیچ حالتی متصل نمیشه
> 
> ### Minimal Reproducible Example (MRE)
> نمیدونم یعنی چی
> 
> ### Expected Behavior
> _No response_
> 
> ### Version
> Last
> 
> ### Platform/OS
> Windows
> 
> ### Additional Context
> _No response_
> 
> ### Application Config Options
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [ ]  I'm willing to submit a PR (Thank you!)

close the app, then run app as administrator and try again.

**Comment by titancomputer** [comment]
> با زدن دکمه برنامه برای وصل شدن هیچ اتفاقی نیفته و پیغام متصل نیستید تغییری نمیکنه،تنضیمات psiphon و warp و هم تیک زدم و غیر فعال کردم توی هیچ حالتی متصل نمیشه

close the app, then run app as administrator and try again.

**Comment by ghamirizadi** [comment]
Run as administrator

**Comment by ircfspace** [comment]
همونطور که دوستان گفتن به صورت Run as administrator اجراش کنین
در آپدیت بعدی احتمالن این مشکل رو برطرف کنیم

**Comment by Majidzam1101** [comment]
> همونطور که دوستان گفتن به صورت Run as administrator اجراش کنین در آپدیت بعدی احتمالن این مشکل رو برطرف کنیم

سلام اپدیت بعدی اش کی میاد ما تست کنیم ؟
