### ISSUE TITLE
ایجاد ایراد در پروکسی سیستم و درست خاموش نشدن 

### ISSUE THREAD

**Issue by alijason72** [bepass-org/oblivion-desktop#201]
### Feature description

با سلام متوجه ایرادی توی نسخه ی 0.7.0 شدم که وقتی که دیسکانت می کنم می خوام دوباره بدون vpn وصل بشم هیچ چیزی لود نمی شه ظاهرا پروکسی هنوز فعال می مونه توی این ورژن قبلی ها درست بود باید ریست کنم تنظیمات ابلیوین رو یک بار کانکت کنم و یک بار دوباره دیسکانت تا درست بشه درست خاموش نمی شه این ورژن پروکسیش هنوز روی سیستم ست می مونه تا وقتی ریست بزنی با تشکر ایشالله توی مک همچین چیزی نباشه خیلی منتظرشم خسته نباشین  با تشکر فراوان ...

**Comment by kiomarzsss** [comment]
سلام لطفا در کنار فرستادن لاگ برنامه بفرمایین منظورتون از «ریست زدن» چیه؟

**Comment by alijason72** [comment]
منظورم بازگردانی به تنظیمات اصلی خود برنامه هست در منو تنظیمات برنامه خود اوبلیوین

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ircfspace** [comment]
لاگ برنامه رو ارسال کنین تا بشه بهتر بررسی کرد

**Comment by alijason72** [comment]
[2024-05-25 12:50:45.958] [info]  past logs was deleted for new connection.
[2024-05-25 12:50:45.961] [info]  ------------------------MetaData------------------------
[2024-05-25 12:50:45.961] [info]  running on: win32 10.0.22631 x64
[2024-05-25 12:50:45.962] [info]  at od: 0.7.0-beta
[2024-05-25 12:50:45.962] [info]  at wp: v1.1.3
[2024-05-25 12:50:45.963] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-25 12:50:45.964] [info]  method: gool
[2024-05-25 12:50:45.964] [info]  proxyMode: true
[2024-05-25 12:50:45.965] [info]  endpoint: default
[2024-05-25 12:50:45.966] [info]  license: false
[2024-05-25 12:50:45.967] [info]  exe: C:\Program Files\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-25 12:50:45.968] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-25 12:50:45.971] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-25 12:50:45.972] [info]  ------------------------MetaData------------------------
[2024-05-25 12:50:45.986] [info]  starting wp process...
[2024-05-25 12:50:45.987] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --scan --rtt 1s
[2024-05-25 12:50:45.993] [info]  trying to set system proxy...
time=2024-05-25T12:50:46.035+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-25T12:50:46.038+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-25T12:50:46.039+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-25 12:50:46.205] [info]  system proxy has been set.
time=2024-05-25T12:50:51.750+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.137 error="read udp 192.168.2.6:59332->162.159.193.137:1701: i/o timeout"

time=2024-05-25T12:50:57.643+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.192.239 error="read udp 192.168.2.6:63383->162.159.192.239:1701: i/o timeout"

time=2024-05-25T12:50:57.645+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:7543:ee33:8b93:bc6b error="dial udp [2606:4700:d0:0:7543:ee33:8b93:bc6b]:1074: connect: A socket operation was attempted to an unreachable network."

time=2024-05-25T12:50:58.808+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:5dff:6b1:a969:3805 error="dial udp [2606:4700:d1:0:5dff:6b1:a969:3805]:8886: connect: A socket operation was attempted to an unreachable network."

time=2024-05-25T12:50:59.044+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.97.7:2506 RTT:183.1156ms CreatedAt:2024-05-25 12:50:58.807358 +0330 +0330 m=+12.781948601} {AddrPort:188.114.99.121:946 RTT:191.2089ms CreatedAt:2024-05-25 12:50:58.3366804 +0330 +0330 m=+12.311271001}]"
time=2024-05-25T12:50:59.044+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.97.7:2506 188.114.99.121:946]"
time=2024-05-25T12:50:59.044+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-25T12:51:01.903+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-25T12:51:01.910+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-25T12:51:03.068+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cp.cloudflare.com:80

time=2024-05-25T12:51:03.526+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.com:443

time=2024-05-25T12:51:03.527+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-25T12:51:04.675+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-25T12:51:04.677+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=avatars.githubusercontent.com:443

time=2024-05-25T12:51:04.979+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-25T12:51:05.048+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443
time=2024-05-25T12:51:05.049+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-25T12:51:05.049+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443
time=2024-05-25T12:51:05.049+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=github.githubassets.com:443

time=2024-05-25T12:51:06.009+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=content-autofill.googleapis.com:443

time=2024-05-25T12:51:06.168+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=collector.github.com:443

time=2024-05-25T12:51:06.480+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=collector.github.com:443

time=2024-05-25T12:51:06.554+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=collector.github.com:443

[2024-05-25 12:52:29.118] [info]  creating new od instance...
[2024-05-25 12:52:29.317] [info]  wp binary was copied to userData directory.
[2024-05-25 12:52:29.567] [info]  od is ready!
[2024-05-25 12:52:29.633] [info]  ------------------------MetaData------------------------
[2024-05-25 12:52:29.634] [info]  running on: win32 10.0.22631 x64
[2024-05-25 12:52:29.636] [info]  at od: 0.7.0-beta
[2024-05-25 12:52:29.636] [info]  at wp: v1.1.3
[2024-05-25 12:52:29.637] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-25 12:52:29.638] [info]  method: gool
[2024-05-25 12:52:29.639] [info]  proxyMode: true
[2024-05-25 12:52:29.640] [info]  endpoint: default
[2024-05-25 12:52:29.641] [info]  license: false
[2024-05-25 12:52:29.641] [info]  exe: C:\Program Files\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-25 12:52:29.642] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-25 12:52:29.642] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-25 12:52:29.643] [info]  ------------------------MetaData------------------------


کپی کردم براتون اینجاست
الان سیستم رو یهو ریست کردم در حالی که oblivion  باز بود بعد که سیستم بالا اومد مثلا هیچ چیزی لود نمی شد مثلا گوگل مثلا سایت  های داخلی. وقتی oblivion رو باز کردم دیدم دیسکانکت هست به محض این که کانکت زدم دیدم همه سایت ها وصل شد پروکسی هایی که این ورژن ست می کنه فکر می کنم هنوز می شینه روی سیستم و چون دیسکانکت می شم دیگه اون پورت و آیپی رو نمی تونه ببینه برا این اینطوری می شه با تشکر

**Comment by ircfspace** [comment]
درجریان هستین که از آخرین نسخه استفاده نمیکنین؟

https://github.com/bepass-org/oblivion-desktop/releases

**Comment by alijason72** [comment]
حتما خبر می دم نتیجه رو بابت نسخه ی مک ورژن آرم هم ممنون اونو هم اطلاع می دم تست می کنم اونو هم تشکر

**Comment by kiomarzsss** [comment]
برنامه رو به چه صورتی میبندین؟ آیا وقتی برنامه باز هستش و قبل از بستن برنامه یا زدن دکمه disconnect سیستم رو خاموش میکنید(یا موردی شبیه به این)؟
ظاهرا برنامه به درستی داره بسته نمیشه...

**Comment by alijason72** [comment]
مشکل در آخرین ورژن حل شده کاملا دوباره اون طور نشد ورژن 0.7.0 مشکل داشت با تشکر
<<<<<به یک مشکل جدید برخوردم در نسخه ی مک>>>>>
ورژن مک0.8.18  رو نصب کردم  برای arm64  روی مک m1 موقع نصب می گه فایل ایمیج خراب هستش چرا اینطور می شه به نظرتون
می زنه the oblivion file is damaged and cant be opened and must move to the trash 
آیا واقعا فایل خرابه یا مشکل از جای دیگه هست ؟

**Comment by alijason72** [comment]
<img width="928" alt="Screenshot 1403-03-06 at 01 52 59" src="https://github.com/bepass-org/oblivion-desktop/assets/136128853/2d2a288c-1728-459d-aaa9-fcbe0622ba0c">

**Comment by kiomarzsss** [comment]
در رابطه با ویندوز خوشحالم که مشکلتون حل شد. در رابطه با مک خودم تجربه زیادی ندارم اما نظرتون رو به این کامنت جلب میکنم:

https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223

**Comment by Majidzam1101** [comment]
> در رابطه با ویندوز خوشحالم که مشکلتون حل شد. در رابطه با مک خودم تجربه زیادی ندارم اما نظرتون رو به این کامنت جلب میکنم:
> 
> [#206 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223)

سلام کجا حل شد نسخه 0.9.5 روی حالت دریافت اطلاعات می ماند پرچم المان نشان نمیده هیچی باز نمی کنه سرویس tunهنوز غیر فعال است کل سیستم تونل نمی کنه 
![Screenshot (28)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/06647ecd-b11b-4466-a20a-d843ef66b262)

**Comment by ircfspace** [comment]
مشکل در نسخه ۲.۷۰ برطرف شد

دریافت و بررسی کنین:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v2.70.0
