### ISSUE TITLE
مشکل اتصال و وصل نشدن در اپراتور های مختلف

### ISSUE THREAD

**Issue by Miserableee** [bepass-org/oblivion-desktop#202]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام وقت بخیر، با نت مخابرات تا همین هفته پیش وصل میشد و مشکلی نداشت ولی الان موقع دریافت اطلاعات گیر میکنه و وصل نمیشه اصلا، با نت ایرانسل مشکلی نداره. 

### Minimal Reproducible Example (MRE)

.

### Oblivion Version

v0.7.0-beta

### Platform/OS

Windows

### Version / Architecture

x64

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by sinadavodi** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/183#issuecomment-2126400872

**Comment by Miserableee** [comment]
> [#183 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/183#issuecomment-2126400872)

تمام مورد های گفته شده رو امتحان کردم ولی بازم وصل نمیشه

**Comment by kiomarzsss** [comment]
مشکلات وصل نشدن در روز های اخیر بابت آپدیت سیستم فیلترینگ هست و از سمت Oblivion Desktop قابل حل نیست و نیازه که مشکل در سمت دوستانمون در [warp-plus](https://github.com/bepass-org/warp-plus) پیگیری بشه و لطفا مشکلات مربوط به کانکشن رو داخل این پروژه مطرح کنید. ایشو های آتی مربوط به این قضیه تگ داپلیکت خورده و به این ایشو رفرنس داده میشن. با تشکر از وقتی که برای مشارکت گذاشتین.

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the issue is not fixable from oblivion desktop part of job.

**Comment by Meysam8118** [comment]
سلام با اینترنت های شاتل و همراه اول اصلا کانکت نمیشه . نه توی اندروید و نه تو پی سی.

**Comment by Aseptronn** [comment]
> مشکل اتصال روی برخی اپراتور های با توجه به تغییرات هسته warp-plus و آپدیت به آخرین نسخه هسته در نسخه جدید برنامه باید حل شده باشه: https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.0-beta

سلام 
فعلا اوکیه 
ممنون ازتون

**Comment by reza1288** [comment]
من  روی  گول  استفاده  میکنم      وصل  میشع   سرعت  زیادی  دارع   ولی  قعط نمیشه   وقتی  هم   میپاکمش   اینترنت  قعط میشه

**Comment by ircfspace** [comment]
از کدوم نسخه استفاده میکنین؟

**Comment by MohammadTayebzadeh** [comment]
سلام چرا روی ویندوز وصل میشه ولی سایت های فیلتر مثل یوتیوب رو نمیاره واقعا عجیب ولی رو اندروید درست کار میکنه

**Comment by hamidreza55pa** [comment]
Your Hello VPN does not connect with the telecom fixed network. Please advise
Oblivion 0/7
