### ISSUE TITLE
نمایش ای پی ایران

### ISSUE THREAD

**Issue by cloner12** [bepass-org/oblivion-desktop#203]
### Feature description

خسته نباشید واقعا همچی به درستی کار میکنه، راحت کانکت میشه هم با اندپوینت دیفالت هم با این آدرس "188.114.98.224:2408" فقط نمیدونم چرا تو این سایت 

https://browserleaks.com/ip
ای پی ایران هم نمایش میده! هم IP هم ISP

**Comment by ircfspace** [comment]
اگر با متد وارپ وصل هستین، باید از گول یا سایفون استفاده کنین

**Comment by cloner12** [comment]
![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/69f6ac21-ad83-433b-bbf5-619d8d1a0479)
![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/23f47c73-bfc7-4916-91bf-4d90238492bf)


با هر دو متد تست کردم (WarpinWarp & Psiphon) ولی بازم ای پی ایران رو نشون میده

**Comment by ircfspace** [comment]
توی چه مرورگری دارین تست میگیرین؟
پیکربندی شبکه روی چه حالتی قرار داره؟
داخل صفحه اصلی برنامه لوکیشن آیپی رو ایران نشون میده؟

**Comment by cloner12** [comment]
با کروم، فایرفاکس و اج تست کردم همین مشکل رو داشتن حتا در اینکاگنیتو مد ( با چند آی‌اس‌پی مختلف)
بر روی سیستم پروکسی و پورت دیفالت (8086 & 2408)
خیر داخل برنامه ای‌پی لوکیشنی که کانکت شده رو نمایش میده

v0.8.16-beta & v0.7
