### ISSUE TITLE
روی دکمه Close کلیک کنید تا به سینی سیستم کوچک شود

### ISSUE THREAD

**Issue by zhouxinghong** [bepass-org/oblivion-desktop#204]
### Feature description

روی دکمه Close کلیک کنید تا به سینی سیستم کوچک شود
![image](https://github.com/bepass-org/oblivion/assets/54253524/e1610612-2407-4642-9795-ea31678ed5d5)
![image](https://github.com/bepass-org/oblivion/assets/54253524/4ecb3151-98e6-4a2f-b6e7-aac964000ef3)

**Comment by ircfspace** [comment]
Currently, it is possible to set the systemTray with minimize through the program settings. 
Further improvements will be considered in the next updates.
