### ISSUE TITLE
“Oblivion Desktop” is damaged and can’t be opened

### ISSUE THREAD

**Issue by meower1** [bepass-org/oblivion-desktop#206]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام روز بخیر و متشکرم از دولوپر های عزیز این پروژه. امروز برای اولین بار برنامه رو روی لپتاپم نصب کردم و متاسفانه اجرا نمیشه و ارور زیر رو دریافت میکنم

```
“Oblivion Desktop” is damaged and can’t be opened. You should move it to the Trash.
```

> Os version : macos sonoma 14.5 (23F79)
> cpu arch : m1
> downloaded version : 0.8.16-beta - arm

gate keeper غیر فعال هست
متاسفانه log مربوط بهش رو نتونستم توی Console پیدا کنم. توی /var/log/system.log هم همینطور و باز کردن برنامه با ترمینال هم خروجی ای نداشت. باز کردن برنامه با راست کلیک و open هم نتیجه ای نداد.

### Minimal Reproducible Example (MRE)

1- برنامه رو دانلود کن و فایل oblivion-desktop-mac-arm64.dmg رو باز کن
2- ایکون برنامه رو داخل فولدر Applications بکش
3- برو داخل /Applications و روی برنامه راست کلیک کن و دکمه open رو بزن

### Oblivion Version

v0.8.16-beta

### Platform/OS

macOS

### Version / Architecture

arm-M1

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by bitarea** [comment]
سلام. من هم دقیقا همین مشکل رو دارم روی mac m1 sonoma 14.5

**Comment by SharokhAtaie** [comment]
سلام

```
sudo spctl --master-disable
xattr -cr /Applications/Oblivion\ Desktop.app
```

اینم ویدیو یوتوبش:
https://www.youtube.com/watch?v=ZH8_XHzkKD4

**Comment by meower1** [comment]
> سلام
> 
> ```
> sudo spctl --master-disable
> xattr -cr /Applications/Oblivion\ Desktop.app
> ```
> 
> اینم ویدیو یوتوبش: https://www.youtube.com/watch?v=ZH8_XHzkKD4

ممنون. راه حلتون درست بود

**Comment by kiomarzsss** [comment]
@gdariushahmadi
if you have time. could you please take a look at this?

**Comment by jaymz61** [comment]
سلام 
نسخه 0.10.0 beta arm64 Mac هم همین پیام خطا رو میده
M3 pro - Sonoma 14.5

“Oblivion Desktop” is damaged and can’t be opened

**Comment by gdariushahmadi** [comment]
> @gdariushahmadi if you have time. could you please take a look at this? i think it might be because the app is not signed(identity: null). but maybe because we're not packaging the app the way it should be packaged.
we need apple developer membership.
https://www.electronforge.io/guides/code-signing/code-signing-macos#:~:text=Code%20signing%20certificates%20for%20macOS,to%20the%20Mac%20App%20Store.

**Comment by jaymz61** [comment]
البته اینجا برای سابمیت روی مک استور توضیح داده ولی شاید برای برای arm x64 هم این مسئله باشه. 
بنظرم بهتره بیلد armx64 رو متوقف کنید تا کسی که تجربه بیشتری داره زحمت انجام ادامه کار رو بکشه. 
سپاسگزارم

**Comment by gdariushahmadi** [comment]
> 
مشکل شما با این روش باید حل بشه چون مک خودم هم با همین کانفیگ است و اجرا شد
```
sudo spctl --master-disable
xattr -cr /Applications/Oblivion\ Desktop.app
```

**Comment by jaymz61** [comment]
انجام دادم این مراحل رو ولی همچنان این مشکل پابرجاست

**Comment by ararezaee** [comment]
> انجام دادم این مراحل رو ولی همچنان این مشکل پابرجاست

xattr -cr /Applications/Oblivion\ Desktop.app && codesign --force --deep --sign - /Applications/Oblivion\ Desktop.app

این برای من مشکل رو حل میکنه

**Comment by jaymz61** [comment]
با این اجرا شد. سپاسگزارم

**Comment by amr1402** [comment]
برای منم این ارور رو میده اصلا کانکت نمیشه
check or replace the endpoint value or try again

**Comment by narmian** [comment]
سلام
برای من هم پیام فایل خراب میاد و پاک میشه از روی سیستم mac book -M2

**Comment by narmian** [comment]
> سلام برای من هم پیام فایل خراب میاد و پاک میشه از روی سیستم mac book -M2

ورژن ۰.۳۵.۱

**Comment by ircfspace** [comment]
توضیحات مرتبط، برای نسخه 1.6 به بعد : [مشاهده](https://github.com/bepass-org/oblivion-desktop/wiki/%D8%B1%D9%81%D8%B9-%D8%AE%D8%B7%D8%A7%DB%8C-%E2%80%9COblivion-Desktop%E2%80%9D-is-damaged-and-can%E2%80%99t-be-opened)

**Comment by samimi67** [comment]
برای ایفون نمیاد؟

**Comment by reza1951** [comment]
سلام از همگی ممنون لطفا یکی به من کمک بده ...من داشتم کار می کردم یه دفعه پیام اومده تمایل داریدآبدیت کنید من هم آبدیت کردم دیگه برام باز نمی کنه نمیدونم چی شده روی بعضی حالتها اجرا میشه برنامه ولی هیچ سایتی رو باز نمیکنه در صورتی که قبلا خیلی خوب بود باید چیکار کنم ؟

**Comment by MohammadVahidiPro** [comment]
> سلام
> 
> ```
> sudo spctl --master-disable
> xattr -cr /Applications/Oblivion\ Desktop.app
> ```
> 
> اینم ویدیو یوتوبش: https://www.youtube.com/watch?v=ZH8_XHzkKD4

سلام امکانش هست برای اوبونتو هم راه حل معادلشو بگین؟پیشاپیش ممنون

**Comment by kingcool715** [comment]
سلام وقتتون بخیر اگه امکانش هست میشه یه راه حل یا توضیح بدید که چرا حتی با استفاده از فعالسالزی سایفون بازم نمیشه فیلترینگ بازی هارو دور زد؟ مثلا روشن کردن ابلیوین هیچ تاثیری رو دور زدن تحریم اپ ایکس باکس نداره و همچنان ارور "در کشور شما موجود نیست" میده کلا تو بازیا جواب نیست. خیلی ممنون میشم جواب بدید

**Comment by ircfspace** [comment]
> سلام وقتتون بخیر اگه امکانش هست میشه یه راه حل یا توضیح بدید که چرا حتی با استفاده از فعالسالزی سایفون بازم نمیشه فیلترینگ بازی هارو دور زد؟ مثلا روشن کردن ابلیوین هیچ تاثیری رو دور زدن تحریم اپ ایکس باکس و بازیای مربوط بهش نداره و همچنان ارور "در کشور شما موجود نیست" میده کلا تو بازیا جواب نیست. خیلی ممنون میشم جواب بدید

باید روی پیکربندی تانل باشید

**Comment by leadingtop** [comment]
xattr -cr /Applications/Oblivion-Desktop.app
if you run oblivion on mac based on arm64 architechture.

**Comment by thomaskuncewicz** [comment]
isn't the answer by @ararezaee superior?
- doesn't disable gatekeeper
- modifies only signature of DO 
- no sudo?

Sorry if it's a stupid question :)
