### ISSUE TITLE
اجرا نشدن نسخه مک پردازنده M2  

### ISSUE THREAD

**Issue by cenaei** [bepass-org/oblivion-desktop#212]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

متن ارور هنگام نصب چه فایل DMG و چه فایل داخل RAR:
"Oblivion Desktop” is damaged and can’t be opened. You should move it to the Trash."
نسخه سیستم عامل: 14.1 (23B74)

### Minimal Reproducible Example (MRE)

1. Download oblivion-desktop-mac-arm64.dmg
2. install the app
3. can't run the app

### Oblivion Version

v0.8.16-beta

### Platform/OS

macOS

### Version / Architecture

14.1 (23B74) - Apple Silicon M2

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
مشاهده کنین: https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223
