### ISSUE TITLE
روی مک بوک پرو M2 تشد

### ISSUE THREAD

**Issue by 0xCuttingEdge** [bepass-org/oblivion-desktop#213]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هر کاری کردم هر کدوم از فایل‌های DMG  رو که نصب کردم روی اپلیکیشن که کلیک می‌کنی پیغام زیر رو میده و اجرا نمیشه

![CleanShot 2024-05-25 at 22 48 34@2x](https://github.com/bepass-org/oblivion-desktop/assets/81967091/45d40896-38fa-455d-a2f6-cca889f257d1)

### Minimal Reproducible Example (MRE)

Don't know how

### Oblivion Version

v0.8.16-beta

### Platform/OS

macOS

### Version / Architecture

v14.4.1 arm64 (m2)

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
مشاهده کنین: https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223
