### ISSUE TITLE
سایفون هم کار نمیکنه...

### ISSUE THREAD

**Issue by fffarbod** [bepass-org/oblivion-desktop#215]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
حالا وارپ که از ريشه قطع شده...
سایفون چرا روی اینترنت مخابرات وصل نمیشه؟

### Minimal Reproducible Example (MRE)

قسمت سایفون

### Oblivion Version

v0.8.18-beta

### Platform/OS

macOS

### Version / Architecture

11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
لاگ برنامه لطفا

**Comment by fffarbod** [comment]
> لاگ برنامه لطفا

[2024-05-26 00:10:33.001] [info]  past logs was deleted for new connection.
[2024-05-26 00:10:33.004] [info]  ------------------------MetaData------------------------
[2024-05-26 00:10:33.005] [info]  running on: darwin 22.6.0 x64
[2024-05-26 00:10:33.005] [info]  at od: 0.8.18-beta
[2024-05-26 00:10:33.005] [info]  at wp: v1.1.3
[2024-05-26 00:10:33.006] [info]  ls assets/bin: LICENSE,README.md,warp-plus
[2024-05-26 00:10:33.006] [info]  method: psiphon
[2024-05-26 00:10:33.006] [info]  proxyMode: true
[2024-05-26 00:10:33.006] [info]  endpoint: default
[2024-05-26 00:10:33.007] [info]  license: true
[2024-05-26 00:10:33.007] [info]  exe: /Applications/Oblivion Desktop.app/Contents/MacOS/Oblivion Desktop
[2024-05-26 00:10:33.007] [info]  userData: /Users/<USERNAME>/Library/Application Support/oblivion-desktop
[2024-05-26 00:10:33.008] [info]  logs: /Users/<USERNAME>/Library/Logs/oblivion-desktop
[2024-05-26 00:10:33.008] [info]  ------------------------MetaData------------------------
[2024-05-26 00:10:33.018] [info]  starting wp process...
[2024-05-26 00:10:33.018] [info]  /Users/<USERNAME>/Library/Application Support/oblivion-desktop/warp-plus --bind 127.0.0.1:8086 --key AJr60l29-Bp851Jh7-V97C8wa1 --cfon --country AT --scan --rtt 1s
[2024-05-26 00:10:33.025] [info]  trying to set system proxy...
time=2024-05-26T00:10:33.035+03:30 level=INFO msg="psiphon mode enabled" country=AT
time=2024-05-26T00:10:33.035+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-26T00:10:33.037+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-26T00:10:33.038+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

[2024-05-26 00:10:33.102] [info]  An asterisk (*) denotes that a network service is disabled.
(1) Wi-Fi
(Hardware Port: Wi-Fi, Device: en0)

(2) iPhone USB
(Hardware Port: iPhone USB, Device: en4)

(3) Thunderbolt Bridge
(Hardware Port: Thunderbolt Bridge, Device: bridge0)

(4) Orbot
(Hardware Port: org.torproject.orbot, Device: )

(5) Karing
(Hardware Port: com.nebula.karing, Device: )


[2024-05-26 00:10:33.102] [info]  Active Hardware Port: Wi-Fi
[2024-05-26 00:10:33.103] [info]  using hardwarePort: Wi-Fi
[2024-05-26 00:10:33.522] [info]  system proxy has been set.
time=2024-05-26T00:10:35.040+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.98.37:880 RTT:239.474417ms CreatedAt:2024-05-26 00:10:33.761407 +0330 +0330 m=+0.729178088} {AddrPort:188.114.97.23:3581 RTT:401.408593ms CreatedAt:2024-05-26 00:10:34.965384 +0330 +0330 m=+1.933185858}]"
time=2024-05-26T00:10:35.040+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.98.37:880 188.114.97.23:3581]"
time=2024-05-26T00:10:35.040+03:30 level=INFO msg="running in Psiphon (cfon) mode"

time=2024-05-26T00:10:37.692+03:30 level=INFO msg="Handshaking, Please Wait..." subsystem=psiphon

err: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2024-05-25T20:40:38.695Z"}

time=2024-05-26T00:10:38.802+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=b-cdn.net:443

time=2024-05-26T00:10:48.811+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.238:22

time=2024-05-26T00:10:48.817+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.53.243:22

time=2024-05-26T00:10:48.834+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.81.140:53

time=2024-05-26T00:10:48.848+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.109:53

time=2024-05-26T00:10:48.865+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.236:53

time=2024-05-26T00:10:48.867+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=37.120.212.194:443

time=2024-05-26T00:10:48.874+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=94.198.41.220:983

time=2024-05-26T00:10:48.879+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.197:22

time=2024-05-26T00:10:48.889+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.194:443

time=2024-05-26T00:10:48.891+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.251:53

time=2024-05-26T00:11:09.882+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.114:22

time=2024-05-26T00:11:12.087+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.40.52.159:443

time=2024-05-26T00:11:17.485+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.53.243:22

time=2024-05-26T00:11:19.773+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.238:22

time=2024-05-26T00:11:20.053+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=94.198.41.220:22

time=2024-05-26T00:11:21.029+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.114:22

time=2024-05-26T00:11:22.608+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=37.120.212.194:554

time=2024-05-26T00:11:27.736+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.251:22

time=2024-05-26T00:11:31.480+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.109:22

time=2024-05-26T00:11:32.492+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.194:443

time=2024-05-26T00:11:35.548+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.236:443

time=2024-05-26T00:11:38.800+03:30 level=INFO msg="Unable to start psiphon" subsystem=psiphon !BADKEY="clientlib: tunnel establishment timeout" !BADKEY=reconnecting...

time=2024-05-26T00:11:38.854+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=j.sni.global.fastly.net:443

time=2024-05-26T00:11:48.867+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=37.120.212.194:554

time=2024-05-26T00:11:48.877+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.238:53

time=2024-05-26T00:11:48.878+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.194:22

time=2024-05-26T00:11:48.883+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.114:22

time=2024-05-26T00:11:48.899+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.236:22

time=2024-05-26T00:11:48.904+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.81.140:22

time=2024-05-26T00:11:48.909+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.197:22

time=2024-05-26T00:11:48.934+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.40.52.159:443

time=2024-05-26T00:11:48.935+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=94.198.41.220:22

time=2024-05-26T00:11:48.960+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.109:80

time=2024-05-26T00:12:13.291+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.53.243:80

time=2024-05-26T00:12:16.531+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.251:53

time=2024-05-26T00:12:21.117+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.251:53

time=2024-05-26T00:12:21.122+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.197:53

time=2024-05-26T00:12:21.122+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.40.52.159:22

time=2024-05-26T00:12:21.136+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=146.70.146.236:53

time=2024-05-26T00:12:21.141+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=37.120.212.194:443

time=2024-05-26T00:12:21.149+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.109:80

time=2024-05-26T00:12:23.402+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.83.114:983

time=2024-05-26T00:12:33.653+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.80.194:443

time=2024-05-26T00:12:37.493+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=94.198.41.220:983

time=2024-05-26T00:12:38.855+03:30 level=INFO msg="Unable to start psiphon" subsystem=psiphon !BADKEY="clientlib: tunnel establishment timeout" !BADKEY=reconnecting...
time=2024-05-26T00:12:38.856+03:30 level=ERROR msg="unable to run psiphon psiphon handshake maximum time exceeded"

[2024-05-26 00:12:38.858] [info]  wp process exited.
[2024-05-26 00:12:38.860] [info]  trying to disable system proxy...
[2024-05-26 00:12:38.872] [info]  default interface: en0
[2024-05-26 00:12:38.933] [info]  hardware ports list:  
Hardware Port: Thunderbolt Bridge
Device: bridge0
<EthernetAddress>

Hardware Port: Wi-Fi
Device: en0
<EthernetAddress>

Hardware Port: Thunderbolt 1
Device: en1
<EthernetAddress>

Hardware Port: Thunderbolt 2
Device: en2
<EthernetAddress>

VLAN Configurations
===================

[2024-05-26 00:12:38.933] [info]  using hardwarePort: Wi-Fi
[2024-05-26 00:12:39.176] [info]  system proxy has been disabled on your system.

**Comment by tnhgm** [comment]
لطفا یه کاری بکنید
هیچ مدی کار نمیکنه

**Comment by kiomarzsss** [comment]
متاسفانه اختلال چند روز اخیر روی اینترنت های مختلف از سمت Oblivion Desktop قابل حل نیست. لطفا برای اطلاعات تکمیلی به این ایشو مراجعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/202
