### ISSUE TITLE
listen port

### ISSUE THREAD

**Issue by samanbarzegar** [bepass-org/oblivion-desktop#219]
### Feature description | توضیحات ویژگی

شما میتوانید همانند کلاینت وایرگارد از لسن پورت استفاده کنید
در این صورت کابر میتواند از یک آیپی ثابت استفاده کند

**Comment by kiomarzsss** [comment]
please discuss this in [warp-plus](https://github.com/bepass-org/warp-plus) project. since the feature is not implementable in oblivion desktop part of job.
