### ISSUE TITLE
مشکل در حالت سایفون

### ISSUE THREAD

**Issue by ehsanna11111** [bepass-org/oblivion-desktop#22]
### Feature description

اول از همه خیلی ممنون بابت نرم افزار، برنامه روی نت مخابرات و ایرانسل تمام امکانات و بخش هاش کار میکنه منتهی روی نت مخابرات در حالت سایفون کانکت میشه ولی آی پی رو تغییر نمیده و فیلترینگ رو رد نمیکنه

**Comment by raminr63** [comment]
ممنون بابت یه همچین کلاینت عالیتون واقعا دست مریزاد.

فقط روی حالت سایفون کار نمیکنه و مرورگر خطای network reset میده.

**Comment by ehsanna11111** [comment]
time=2024-05-04T22:17:17.303+03:30 level=INFO msg="Psiphon started successfully on port 8086, handshake operation took 5.6146125s" subsystem=psiphon
time=2024-05-04T22:17:17.303+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-04T22:18:43.053+03:30 level=INFO msg="psiphon mode enabled" country=DE
time=2024-05-04T22:18:43.053+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-04T22:18:43.055+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T22:18:43.056+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T22:18:43.265+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:2fc7:2022:d5bc:efa1 error="dial udp [2606:4700:d1:0:2fc7:2022:d5bc:efa1]:955: connect: A socket operation was attempted to an unreachable network."

time=2024-05-04T22:18:45.059+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.97.93:3138 RTT:200.873ms CreatedAt:2024-05-04 22:18:44.6205712 +0330 +0330 m=+1.572792201} {AddrPort:162.159.192.235:1387 RTT:333.6599ms CreatedAt:2024-05-04 22:18:43.9149684 +0330 +0330 m=+0.867189401}]"
time=2024-05-04T22:18:45.059+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.97.93:3138 162.159.192.235:1387]"
time=2024-05-04T22:18:45.059+03:30 level=INFO msg="running in Psiphon (cfon) mode"

time=2024-05-04T22:18:48.566+03:30 level=INFO msg="Handshaking, Please Wait..." subsystem=psiphon

time=2024-05-04T22:18:49.895+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.105.246.43:554

time=2024-05-04T22:18:50.020+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.105.66.185:804

time=2024-05-04T22:18:50.020+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.18.138:443

time=2024-05-04T22:18:50.023+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.34.210:22

time=2024-05-04T22:18:50.024+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.34.204:80

time=2024-05-04T22:18:50.031+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.153.251:443

time=2024-05-04T22:18:50.034+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=5.254.16.218:443

time=2024-05-04T22:18:50.044+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.34.119:443

time=2024-05-04T22:18:50.044+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=a2794.na.akamai.net:80

time=2024-05-04T22:18:50.044+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=45.79.249.58:22

time=2024-05-04T22:18:50.049+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.104.214:554

time=2024-05-04T22:18:50.050+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=82.165.240.197:80

time=2024-05-04T22:18:50.053+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=192.46.232.63:80

time=2024-05-04T22:18:50.057+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=45.79.249.222:443

time=2024-05-04T22:18:50.062+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=a4236.g2.akamai.net:443

time=2024-05-04T22:18:50.071+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.33.160:443

time=2024-05-04T22:18:50.072+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.33.5:443

time=2024-05-04T22:18:50.077+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.104.154.161:443
time=2024-05-04T22:18:50.077+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.159.96:443

time=2024-05-04T22:18:50.079+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.105.73.113:443

time=2024-05-04T22:18:50.088+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.42.21:554

time=2024-05-04T22:18:50.093+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.104.239:443

time=2024-05-04T22:18:50.096+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=196.244.72.35:22

time=2024-05-04T22:18:50.101+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=194.233.168.83:22

time=2024-05-04T22:18:50.106+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=217.160.104.210:53

time=2024-05-04T22:18:50.107+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=57.129.2.59:22

time=2024-05-04T22:18:53.226+03:30 level=INFO msg="Psiphon started successfully on port 8086, handshake operation took 4.6595824s" subsystem=psiphon

time=2024-05-04T22:18:53.226+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

**Comment by Majidzam1101** [comment]
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه دومین مشکل اتصال به سایفون است هیچ سایتی باز نمی کنه

**Comment by MIS123456** [comment]
با سلام و با تشکر از زحمات شما عزیزان
اشکلالات برنامه
1:با تنطیمات دیفالت وصل نمیشه باید ای پی تمیز در حالت گول بهش بدین تا وصل بشه
2:حالت سایفون اصلا تانل نمیشه انگار سایفون عمل اپ استریمو نمیتونه انجام بده و مشکل به احتمال زیاد همینه
3:دوستانی که مشکل وصل شدن دارن تو قسمت فایروال در inbound و outbound new rule  تعریف کنن و اجازه ترافیکو بدن

**Comment by ircfspace** [comment]
مشکل گزینه سایفون در دست بررسیه و احتمالن در آپدیت بعدی برطرف میشه

**Comment by Majidzam1101** [comment]
> مشکل گزینه سایفون در دست بررسیه و احتمالن در آپدیت بعدی برطرف میشه

خواهشا مشکل تونل کردن کل سیستم در اپدیت بعدی حل کنید با تشکر
