### ISSUE TITLE
 خطای احراز هویت کلودفلر 

### ISSUE THREAD

**Issue by ssheyda** [bepass-org/oblivion-desktop#220]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

بعد از اینکه لایسنس کلودفلر رو به برنامه اضافه کردم، از اون موقع دیگه کانکنت نمیشه و "خطای احراز هویت کلودفلر، دوباره تلاش کنید" نمایش داده میشه.
لایسنس رو حذف کردم، هر سه آپشن وارپ، گول و سایفون رو امتحان کردم، روی سه اینترنت مختلف تست کردم، برنامه رو حذف و نصب کردم. نسخه پرتابل هم ریختم، بازم همین خطا میاد و حل نمیشه.

### Relevant log output | لاگ برنامه

```shell
[2024-05-27 12:01:59.792] [info]  past logs was deleted for new connection.
[2024-05-27 12:01:59.795] [info]  ------------------------MetaData------------------------
[2024-05-27 12:01:59.796] [info]  running on: win32 10.0.19042 x64
[2024-05-27 12:01:59.796] [info]  at od: 0.8.18-beta
[2024-05-27 12:01:59.797] [info]  at wp: v1.1.3
[2024-05-27 12:01:59.798] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-05-27 12:01:59.799] [info]  method: warp
[2024-05-27 12:01:59.800] [info]  proxyMode: true
[2024-05-27 12:01:59.800] [info]  endpoint: default
[2024-05-27 12:01:59.801] [info]  license: true
[2024-05-27 12:01:59.802] [info]  exe: C:\Users\<USERNAME>\AppData\Local\Programs\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-27 12:01:59.803] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-27 12:01:59.804] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-27 12:01:59.805] [info]  ------------------------MetaData------------------------
[2024-05-27 12:01:59.816] [info]  starting wp process...
[2024-05-27 12:01:59.816] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --key g4r9M35H-bZ59je84-9Mk5C7a3 --scan --rtt 1s
[2024-05-27 12:01:59.826] [info]  trying to set system proxy...
time=2024-05-27T12:01:59.893Z level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-27T12:01:59.967Z level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-27T12:01:59.968Z level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-27 12:02:00.090] [info]  system proxy has been set.
time=2024-05-27T12:02:15.291Z level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-27T12:02:15.291Z level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": uTlsConn.Handshake() error: EOF"

[2024-05-27 12:02:15.310] [info]  wp process exited.
[2024-05-27 12:02:15.314] [info]  trying to disable system proxy...
[2024-05-27 12:02:15.481] [info]  system proxy has been disabled on your system.
```

**Comment by ssheyda** [comment]
مشکل حل شد.
**راه حل:** حذف فولدر موجود در مسیر "C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop" که شامل  warp-plus.exe بود.
**باگ نرم افزار:** با uninstall کردن نرم افزار، فولدر موجود در مسیر بالا حذف نمیشد.

**Comment by black-birdB52** [comment]
سلام منم همین مشکل دارم خذف کردم پوشه هایی که اشاره کردیو ولی بدون کلید لایسنس فقط جواب میده وقتی لایسنس کلادفلر وارد میکنی دباره خطای اهراز هویت رو میگیره

**Comment by ssheyda** [comment]
اره تا کد لایسنس رو وارد میکنی خطا میده، نیازی هم بهش نیست فک کنم؛ چون به نظر میاد پهنای باند در حالت دیفالت هم نامحدودهه.

**Comment by ssheyda** [comment]
> سلام منم همین مشکل دارم خذف کردم پوشه هایی که اشاره کردیو ولی بدون کلید لایسنس فقط جواب میده وقتی لایسنس کلادفلر وارد میکنی دباره خطای اهراز هویت رو میگیره


اره تا کد لایسنس رو وارد میکنی خطا میده، نیازی هم بهش نیست فک کنم؛ چون به نظر میاد پهنای باند در حالت دیفالت هم نامحدودهه.

**Comment by kiomarzsss** [comment]
> مشکل حل شد. **راه حل:** حذف فولدر موجود در مسیر "C:\Users<USERNAME>\AppData\Roaming\oblivion-desktop" که شامل warp-plus.exe بود. **باگ نرم افزار:** با uninstall کردن نرم افزار، فولدر موجود در مسیر بالا حذف نمیشد.

مرسی بابت اشاره به این موضوع سعی میکنیم تو آپدیت های بعدی فیکس کنیم.

**Comment by black-birdB52** [comment]
موردی که الان متوجه شدم اینه که با نرم افزار warp رسمی خود کلادفلر کلید رو وارد میکنم تاییدیه که خورد همون کلید میدمش به oblivion دیگه خطای احراز هویت کلادفلر رو نمیگیره 
به نظر من باید در خواست کلیدی که از سمت oblivion به کلادفلر ارسال میشه از قبل یه هماهنگی با خود کلادفلر انجام بشه یا یه چیز تو این مایه ها که(درخواست) لایسنس وارد شده رو تایید کنه
![Untitled](https://github.com/bepass-org/oblivion-desktop/assets/66407452/b4a6cff9-21a4-4291-b915-d897c8a12a33)

**Comment by Arad-Afzali** [comment]
من این روش شما رو تست کردم. برای بار اول جواب میداد ولی وقتی یکبار قطع میکردم دوباره موقع وصل شدن همون ارور رو میگرفتم.

**Comment by ircfspace** [comment]
لطفن این‌موضوع رو با جزییات کامل در آدرس زیر گزارش کنین تا زودتر به نتیجه برسیم
https://github.com/bepass-org/warp-plus/issues/new/choose

@black-birdB52

**Comment by kooshadab** [comment]
من هم متاسفانه با همین خطا روبرو هستم و نمی تونم وصل بشم.

**Comment by haliloya** [comment]
منم همین مشکل رو داشتم که با حذف پوشه C:\Users\AppData\Roaming\oblivion-desktop مشکلم حل شد.

**Comment by dnlamiri** [comment]
برای حل مشکل خطای احراز هویت کلودفلر اول لایسنس جدید رو ست کنید وقتی کانکت شد وارد ادرس 
C:\Users\your-user\AppData\Roaming\oblivion-desktop
بشین و فایل settings رو باز کنید و قسمت لایسنس رو به این صورت بزارید
 "license":""
لایسنس ست شده میمونه

**Comment by es2008** [comment]
روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!

**Comment by dnlamiri** [comment]
> روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!

فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو

**Comment by dnlamiri** [comment]
> روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!


برای حل مشکل خطای احراز هویت کلودفلر اول لایسنس جدید رو ست کنید وقتی کانکت شد وارد ادرس
C:\Users\your-user\AppData\Roaming\oblivion-desktop
بشین و فایل settings رو باز کنید و قسمت لایسنس رو به این صورت بزارید
"license":""
لایسنس ست شده میمونه

کلا یه بار پاک کن وی پی ان رو و  از اول نصب کن و این مراحل رو برو

**Comment by dnlamiri** [comment]
> > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > 
> > 
> > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> 
> لایسنس از کجا بیارم؟

https://t.me/generatewarpplusbot

**Comment by dnlamiri** [comment]
> > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > 
> > 
> > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> 
> لایسنس از کجا بیارم؟

https://ircfspace.github.io/warpplus/

**Comment by dnlamiri** [comment]
> > > > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > > > 
> > > > 
> > > > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> > > 
> > > 
> > > لایسنس از کجا بیارم؟
> > 
> > 
> > https://t.me/generatewarpplusbot
> 
> با کلید لایسنس جدید هم که وارد کردم باز خطا میده!

از اول نصب کردی ؟ دفعه اول هم اگه وصل نشه مشکل چیز دیگه ای باید باشه.
شما هر وقت تونستی کانکت کنی مراحل بالا رو برو

**Comment by dnlamiri** [comment]
> > > > > > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > > > > > 
> > > > > > 
> > > > > > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> > > > > 
> > > > > 
> > > > > لایسنس از کجا بیارم؟
> > > > 
> > > > 
> > > > https://t.me/generatewarpplusbot
> > > 
> > > 
> > > با کلید لایسنس جدید هم که وارد کردم باز خطا میده!
> > 
> > 
> > از اول نصب کردی ؟ دفعه اول هم اگه وصل نشه مشکل چیز دیگه ای باید باشه. شما هر وقت تونستی کانکت کنی مراحل بالا رو برو
> 
> مشکل اینه بدون لایسنس و با لایسنس جدید که وارد میکنم اصلاً کانکت نمیشه و خطای احراز هویت رو میده

این رو هم انجام دادین ؟
https://github.com/bepass-org/oblivion-desktop/issues/220#issuecomment-2133387899

**Comment by zoghal** [comment]
متاسفانه در نسخه آخر(v0.10.0-beta) و نسخه پرتابل  همچنان این مشکل پابرجاست!
```
time=2024-05-29T16:19:25.233+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=C:\Users\<USERNAME>\AppData\Local\cache/warp-plus/primary error="CreateFile C:\\Users\\<USERNAME>\\AppData\\Local\\cache\\warp-plus\\primary\\wgcf-identity.json: The system cannot find the file specified."

time=2024-05-29T16:19:25.234+03:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-29 16:19:25.516] [info] system proxy has been set.
time=2024-05-29T16:19:26.821+03:30 level=INFO msg="updating account license key" subsystem=warp/account

time=2024-05-29T16:19:27.564+03:30 level=ERROR msg="couldn't load primary warp identity"
time=2024-05-29T16:19:27.564+03:30 level=ERROR msg="API request failed with status: 400 Bad Request"
```


در حقیقت اپ قادر به شناسایی نام کاربر ویندوز نیست، به همین خاطر مسیر درست را نمی‌تواند پیدا کند.

**Comment by dnlamiri** [comment]
> برای حل مشکل خطای احراز هویت کلودفلر اول لایسنس جدید رو ست کنید وقتی کانکت شد وارد ادرس C:\Users\your-user\AppData\Roaming\oblivion-desktop بشین و فایل settings رو باز کنید و قسمت لایسنس رو به این صورت بزارید "license":"" لایسنس ست شده میمونه

یه نکته جالب  با این روش برای من در سایت https://cloudflare.com/cdn-cgi/trace زده وارپ پلاس هستم ولی وقتی در اپ 1.1.1.1 چک میکنم هیچ دیوایسی رو نشون نمیده که لاگ این باشه!!

**Comment by kooshadab** [comment]
نکته عجیب اینجاست که برای من روی اینترنت مخابرات خطای احراز هویت میده اما روی همین لپ تاپ در منزلی که اینترنت مبین نت داره امتحان کردم و بدون مشکل وصل شد. به نظرم مشکل از اپراتور مخابرات باشه.

**Comment by dnlamiri** [comment]
> > > > > > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > > > > > 
> > > > > > 
> > > > > > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> > > > > 
> > > > > 
> > > > > لایسنس از کجا بیارم؟
> > > > 
> > > > 
> > > > https://t.me/generatewarpplusbot
> > > 
> > > 
> > > با کلید لایسنس جدید هم که وارد کردم باز خطا میده!
> > 
> > 
> > از اول نصب کردی ؟ دفعه اول هم اگه وصل نشه مشکل چیز دیگه ای باید باشه. شما هر وقت تونستی کانکت کنی مراحل بالا رو برو
> 
> بله. از اول نصب کردم. مشکل اینه بدون لایسنس و با لایسنس جدید که وارد میکنم اصلاً کانکت نمیشه و خطای احراز هویت رو میده

وقتی چه با لایسنس و بدون لایسنس پیام خطا میده به نظرم اشتباه نصب شده و درست هم پاک نمیشه فایل های برنامه از سیستم شما. اول این رو بر طرف کنید و بعد لایسنس بدین به برنامه

**Comment by es2008** [comment]
> > > > > > > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > > > > > > 
> > > > > > > 
> > > > > > > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> > > > > > 
> > > > > > 
> > > > > > لایسنس از کجا بیارم؟
> > > > > 
> > > > > 
> > > > > https://t.me/generatewarpplusbot
> > > > 
> > > > 
> > > > با کلید لایسنس جدید هم که وارد کردم باز خطا میده!
> > > 
> > > 
> > > از اول نصب کردی ؟ دفعه اول هم اگه وصل نشه مشکل چیز دیگه ای باید باشه. شما هر وقت تونستی کانکت کنی مراحل بالا رو برو
> > 
> > 
> > بله. از اول نصب کردم. مشکل اینه بدون لایسنس و با لایسنس جدید که وارد میکنم اصلاً کانکت نمیشه و خطای احراز هویت رو میده
> 
> وقتی چه با لایسنس و بدون لایسنس پیام خطا میده به نظرم اشتباه نصب شده و درست هم پاک نمیشه فایل های برنامه از سیستم شما. اول این رو بر طرف کنید و بعد لایسنس بدین به برنامه
اشتباه نصب شده؟! نصبش که چیز عجیبی نداره

**Comment by dnlamiri** [comment]
> درست هم پاک نمیشه فایل های برنامه از سیستم شما.

شما بیشتر به این مورد توجه کن

**Comment by ssheyda** [comment]
> > > > > > > > > روی نسخه قبلی مشکلی نبود. ولی رو این نسخه با این که فولدری که گفتین رو پاک کردم و قسمت لایسنس هم خالیه ولی باز هم ارور احراز هویت برام میاد!
> > > > > > > > 
> > > > > > > > 
> > > > > > > > فولدری نباید پاک کنید. شما یه لایسنس جدید بده وقتی با موفقیت وصل شد بدون اینکه قطع کنی مراحل بالا رو برو
> > > > > > > 
> > > > > > > 
> > > > > > > لایسنس از کجا بیارم؟
> > > > > > 
> > > > > > 
> > > > > > https://t.me/generatewarpplusbot
> > > > > 
> > > > > 
> > > > > با کلید لایسنس جدید هم که وارد کردم باز خطا میده!
> > > > 
> > > > 
> > > > از اول نصب کردی ؟ دفعه اول هم اگه وصل نشه مشکل چیز دیگه ای باید باشه. شما هر وقت تونستی کانکت کنی مراحل بالا رو برو
> > > 
> > > 
> > > مشکل اینه بدون لایسنس و با لایسنس جدید که وارد میکنم اصلاً کانکت نمیشه و خطای احراز هویت رو میده
> > 
> > 
> > این رو هم انجام دادین ؟ [#220 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/220#issuecomment-2133387899)
> > اول نرم افزار رو پاک کردم.
> > بعد رفتم اون فولدر رو هم پاک کردم. مجدداً نرم افزار رو نصب کردم. کد تولید شده از ربات تلگرام که گذاشتین رو تو قسمت لایسنس وارد کردم و بروزرسانی رو زدم. بعد اومدم دکمه اتصال رو زدم و خطای احراز هویت اومد مطابق عکسی که گذاشتم.
> > ![image](https://private-user-images.githubusercontent.com/117012559/334808157-ca4cf03d-abce-45da-9159-0c4b8541f9c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTk1NDgsIm5iZiI6MTcxNjk5OTI0OCwicGF0aCI6Ii8xMTcwMTI1NTkvMzM0ODA4MTU3LWNhNGNmMDNkLWFiY2UtNDVkYS05MTU5LTBjNGI4NTQxZjljMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNjE0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmE3YTQ4YzQzNjMyYTBmMzMzNzUyYTFiYzIxOTY3MTQ5YzY0Mzc1NjMxNjMxZmE4YjIzYmUzM2I5NmY3MWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PfTfxEQvXtmuwn9ADmIQimbUKKAqKAWFc1AeBGutGgQ)

کد لایسنس قرار نده چون باگ داره و نرم افزار کانکنت نمیشه. بدون لایسنس کار میکنه.

**Comment by ircfspace** [comment]
در رابطه با لایسنس، مشکل در آپدیت جدید برطرف شده :
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.8-beta

**Comment by asghar1988** [comment]
خطای احرازهویت در کلود فلر و چطوری رفع کنم ؟؟؟

**Comment by asghar1988** [comment]
سلاااام

**Comment by ircfspace** [comment]
مطالعه کنید:
https://github.com/bepass-org/oblivion-desktop/wiki/Fixing-proxy-connection-issues-on-certain-networks

**Comment by fixman0098** [comment]
> خسته نباشید.من هم این باگ رو دارم جوری که حل شد: تو قسمت Network setting حالت برنامه رو روی system proxy قرار بدین. اینجوری با اندپوینت های سفارشی خوب وصل میشه ولی اگر اصرار به TUN دارید ، بعد از این که با system proxy وصل شدید قطع کنید اتصال رو دوباره به حالت TUN برگردید تا وصل بشه.

عالی بود مشکلم رفع شد

**Comment by morettokish** [comment]
سلام. برای حل این خطا برنامه رو ران کنید و در تری بار روی آیکون برنامه راست کلیک کنید
از قسمت Configuration
از حالت None
بذارید روی System Proxy
مشکل حل میشه
