### ISSUE TITLE
the vpn cannot unlock BBC iplayer

### ISSUE THREAD

**Issue by cengzhijie3** [bepass-org/oblivion-desktop#224]
### Feature description | توضیحات ویژگی

the vpn cannot unlock bbc iplayer and they can identify the current location

**Comment by gdariushahmadi** [comment]
HI
You can select country by using Psiphone:

![image](https://github.com/bepass-org/oblivion-desktop/assets/68775308/a8da2ac6-7fae-4f29-a50b-694686d39985)

Then restart Oblivion and wait to connect. After connecting, clear the cookies on BBC sites and reload the page.

**Comment by cengzhijie3** [comment]
Yeah, I did it. Even if I used the psiphon, it also could not unlock the BBC iplayer

**Comment by gdariushahmadi** [comment]
Did you clean cookies?

**Comment by cengzhijie3** [comment]
Yeah, I cleaned it

**Comment by gdariushahmadi** [comment]
Check here to see if you have UK IPs: https://ping.eu/country-by-ip/

**Comment by cengzhijie3** [comment]
My address was UK but the BBC would not identify

**Comment by cengzhijie3** [comment]
![Screenshot_20240528-140908](https://github.com/bepass-org/oblivion-desktop/assets/89333400/1413a763-1587-4e48-9935-165c5c4048ec)
![Screenshot_20240528-140628](https://github.com/bepass-org/oblivion-desktop/assets/89333400/45faa65e-79b4-4a33-a10d-a37d4d7cc00d)

**Comment by gdariushahmadi** [comment]
You are right, it seems that the Warp IPs are flaged and don't allow streaming. I also tried disconnecting and reconnecting Oblivion several times with different IPs until finally one of them connected.

![image](https://github.com/bepass-org/oblivion-desktop/assets/68775308/b3075316-55cb-4b20-a2be-0c3b62851ead)
