### ISSUE TITLE
Please let us create a Secure Hotspot on a Windows device without third-party applications

### ISSUE THREAD

**Issue by dnlamiri** [bepass-org/oblivion-desktop#227]
### Feature description | توضیحات ویژگی

Please let us create a Secure Hotspot on a Windows device without third-party applications, allowing you to share your connection with others, or connect other devices such as game consoles that currently do not support VPNs.

**Comment by Ahmad-2213** [comment]
It's already been satisfied . you can go to Network Settings and then Check Share(LAN). 

![image](https://github.com/bepass-org/oblivion-desktop/assets/106820058/ce51725e-490d-4d94-ad7a-98267ec8054e)

**Comment by dnlamiri** [comment]
I mean in the Network Connections area in Windows we can share it directly on hotspots (Microsoft Wi-Fi Direct Virtual Adapter), like what the MYPUBLICWIFI app does 

https://mypublicwifi.com/publicwifi/en/index.html
