### ISSUE TITLE
Antivirus | اخطار آنتی ویروس

### ISSUE THREAD

**Issue by techjoyment** [bepass-org/oblivion-desktop#232]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

برنامه رو لانچ میکنیم. روی گزینه اتصال که میزنیم انتی ویروس مایکروسافت (ویندوز 11) اخطار میده و در نتیجه برنامه هم متصل نمیشه.
Trojan:Win32/Wacatac.B!ml

### Relevant log output | لاگ برنامه

```shell
[2024-05-29 10:31:07.074] [info]  past logs was deleted for new connection.
[2024-05-29 10:31:07.076] [info]  ------------------------MetaData------------------------
[2024-05-29 10:31:07.076] [info]  running on: win32 10.0.22631 x64
[2024-05-29 10:31:07.076] [info]  at od: 0.10.0-beta
[2024-05-29 10:31:07.076] [info]  at wp: v1.2.2
[2024-05-29 10:31:07.077] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe,wintun.dll
[2024-05-29 10:31:07.077] [info]  method: gool
[2024-05-29 10:31:07.077] [info]  proxyMode: true
[2024-05-29 10:31:07.077] [info]  endpoint: default
[2024-05-29 10:31:07.078] [info]  license: false
[2024-05-29 10:31:07.078] [info]  exe: C:\Program Files\Oblivion Desktop\Oblivion Desktop.exe
[2024-05-29 10:31:07.078] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-29 10:31:07.078] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-29 10:31:07.079] [info]  ------------------------MetaData------------------------
[2024-05-29 10:31:07.083] [info]  starting wp process...
[2024-05-29 10:31:07.083] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --scan -4
[2024-05-29 10:31:07.623] [info]  trying to set system proxy...
[2024-05-29 10:31:07.625] [info]  Routing Rules: Customized
[2024-05-29 10:31:07.780] [info]  system proxy has been set.
```

**Comment by ircfspace** [comment]
این‌مورد بعد از بروزرسانی به نسخه جدید از Warp-plus پیش اومده و متاسفانه درحال‌حاضر تنها گزینه گذاشتن برنامه در لیست سفید یا غیرفعال کردن دیفندر هست

برخی‌از نکات :

1. هشدار اشتباه با آپدیت‌های بعدی برطرف نمیشه، چون کد مخربی در سورس برنامه وجود نداره که بخوایم حذفش کنیم؛ راستی‌آزمایی هم به‌دلیل متن‌باز بودن کار ساده‌ای هست.

2. فعلن گزینه‌ای که در رابطه با false positive پیش‌رو داریم اضافه‌کردن برنامه توی استور مایکروسافت هست، تا شاید با ساین‌شدن جلوی خطاهای اینچنینی گرفته‌شه. اگر مشکلی برای دسترسی ندارین، میتونین تا اون‌تایم صبر کنین.

3. توضیحات تکمیلی :

https://github.com/bepass-org/warp-plus/issues/119#issuecomment-2131289597

**Comment by Tebjox** [comment]
مشکل مشابه در ویندوز 11
![2024-06-01_112913](https://github.com/bepass-org/oblivion-desktop/assets/169454523/8bacd6a8-8dc2-4d57-92df-bbe91d56e2b9)

**Comment by Onib93** [comment]
مشکل شدید با کسپراسکای داشت که باعث میشد فایل warp-plus.exe از دو مسیر 
resources\assets\bin
و
AppData\Roaming\oblivion-desktop
حذف بشه که با جایگزینی با فایل اورجینال از پروژه warp-plus حل شد
ایا فایل oblivion دستکاری شده؟

**Comment by kiomarzsss** [comment]
> مشکل شدید با کسپراسکای داشت که باعث میشد فایل warp-plus.exe از دو مسیر resources\assets\bin و AppData\Roaming\oblivion-desktop حذف بشه که با جایگزینی با فایل اورجینال از پروژه warp-plus حل شد ایا فایل oblivion دستکاری شده؟

خیر فایل استفاده شده در برنامه مستقیم از گیت‌هاب warp-plus دانلود شده و تنها تغییر انجام شده حذف فایل wintun.dll در ویندوز (به دلیل مورد فلگ قرار گرفتن به عنوان تروجان توسط آنتی ویروس ها) است.

**Comment by castell0riz0n** [comment]
سلام ، کسپرسکی فایل warp-plus رو به عنوان تهدید امنیتی میشناسه و تقریبا جلوی اجراش رو همه جوره میگیره ، بعد از غیرفعال کردن کسپرسکی ، Windows-Defender فایل رو پاک میکنه
![image](https://github.com/bepass-org/oblivion-desktop/assets/28252141/93c855eb-6dd4-435e-9067-8488c4908591)

**Comment by Onib93** [comment]
> سلام ، کسپرسکی فایل warp-plus رو به عنوان تهدید امنیتی میشناسه و تقریبا جلوی اجراش رو همه جوره میگیره ، بعد از غیرفعال کردن کسپرسکی ، Windows-Defender فایل رو پاک میکنه ![image](https://private-user-images.githubusercontent.com/28252141/337201005-93c855eb-6dd4-435e-9067-8488c4908591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzMwMzUsIm5iZiI6MTcxNzY3MjczNSwicGF0aCI6Ii8yODI1MjE0MS8zMzcyMDEwMDUtOTNjODU1ZWItNmRkNC00MzVlLTkwNjctODQ4OGM0OTA4NTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDExMTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YTAxYTI5MDBhODliNTVhZjhjY2I1ODc0NzUzZmJlM2JlNDZlNzg3ZGE4YmJlNDg4NTNiNGZhMWU0OTgzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WyjX1Q-Ao5kRjT8tckEWHoS2dddwewN9t35QnHoRi2k)

وقتی warp-plus.exe رو از پروژه اصلی خودش جایگزین میکنی مشکل حل میشه!

**Comment by b3hzad1** [comment]
آنتی ویروس AVG هم پیغام تروجان رو میده. البته فایل اصلی oblivion مشکلی نداره بلکه warp-plus رو بعنوان تروجان تشخیص میده. اسکرین شات رو هم قرار دادم. در کل بنظرم یک جای کار در فایل اجرایی warp-plus مشکل داره، حتی فایل رو از پروژه اصلی هم جایگزین کردم، همون مشکل را داره.

![avg](https://github.com/bepass-org/oblivion-desktop/assets/12196334/50bc7170-e7a4-4309-aa11-169f4adb2c2d)

![screenShot281](https://github.com/bepass-org/oblivion-desktop/assets/12196334/18a8e389-4ce3-4063-9c8c-d39f3bfee482)

**Comment by ElectronicBox** [comment]
فایل ورپ پلاس مثل اینکه شروع کرده به شیطونی اخیرا

Ma!ware warp-plus.exe 
C:\Users\BDTL\AppData\Roaming\oblivion-desktop (Command line parameters: "CAUsers\BDTL\AppData\Roaming\oblivion-desktop\warp-plus.exe" --bind 127.0.0.1:8086 --gool --scan --rtt 1s) 


C:\Users\BDTL\AppData\Local\Temp\44620355-aaab-42f0-81f0-e19e55405d38.tmp
C:\Users\BDTL\AppData\Local\Temp\bec83f7a-7740-49f2-92ce-870459cfa67f.tmp
C:\Users\BDTL\AppData\Local\Temp\ceb078c6-0e53-4ea2-9cc5-fa47bd6247d7.tmp
C:\Users\BDTL\AppData\Local\Temp\FXSAPIDebugLogFile.txt

**Comment by b3hzad1** [comment]
باید بررسی بشه ببینیم در آخرین ویرایش، چه بخشهایی به کد اضافه شده که این به اصطلاح false positive رو بوجود آورده. قبلاً این مشکل رو نداشت.

**Comment by rexmehrdad** [comment]
بیت دیفندر توتال سکوریتی چندین ملور تشخیص میده 😮‍💨

**Comment by ircfspace** [comment]
در آخرین ورژن Warp-Plus ویژگی TUN به‌صورت آزمایشی اضافه شده، که باعث شده آنتی‌ویروس‌ها به عنوان ویروس تشخیص بدن
این‌موضوع از سوی توسعه دهندگان CLI درحال پیگیریه

@b3hzad1

**Comment by rexmehrdad** [comment]
@mrdiabloo sur please give me your ovlivion versions that works for you

**Comment by ircfspace** [comment]
توضیحات تکمیلی درخصوص مشکل آنتی‌ویروس [اینجا](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) ارائه شده

**Comment by Dariush-ss** [comment]
متاسفانه مشکل ویروسی بودن حتی با لیست سفید هم حل نمیشه و برنامه اقدام به حذف میکنه. (Bitdefender ts) 2024.08.27

![Screenshot](https://github.com/user-attachments/assets/0cb558ef-4658-4893-b3de-a868690088d2)

**Comment by rexmehrdad** [comment]
> متاسفانه مشکل ویروسی بودن حتی با لیست سفید هم حل نمیشه و برنامه اقدام به حذف میکنه. (Bitdefender ts) 2024.08.27
> 
> ![Screenshot](https://private-user-images.githubusercontent.com/179570900/361709820-0cb558ef-4658-4893-b3de-a868690088d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDg5OTQsIm5iZiI6MTcyNDc0ODY5NCwicGF0aCI6Ii8xNzk1NzA5MDAvMzYxNzA5ODIwLTBjYjU1OGVmLTQ2NTgtNDg5My1iM2RlLWE4Njg2OTAwODhkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODUxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTIxNDFmOTQ0ZTdlOTM3ZTdhMWIzNGQwZjc5NjNjNWRmMzdhNTA4YzUxZjhkOGZkOWFkNjU1NjIxNWM3ZWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NVuaFHikVNzOKAkajpyJFIqfd6UoBHCIUNuwW9jxFxs)

مشکل برای من حل شد. من بیت دیفندر توتال سکوریتی دارم. اول فایر وال خود سیستم و قط کردم. بعد انتی ویروس و برای ۱۵ دقیقه قط کردم. بهتر هست نت رو هم کامل قط کنید که احتمال ویروسی شدن دستگاه کم بشه. بعد اوبلیویون رو نصب و فولدرش رو در وایت لیست فایروال و آنتی ویروس بزارید.

**Comment by yixin08** [comment]
检测到病毒，无法下载

**Comment by ElectronicBox** [comment]
نسب نکن. اینا به بهونه اینترنت اباد میخوان همرو هک کنن. اپ موبایلشونم از
کار اینداختن.

**Comment by ElectronicBox** [comment]
دوستان عزیز توجه کنید که اوپن سورس بودن کد اصلا موهم نیست، کانکشنی که بهش
وصل میشید و پس از اتصال چه اجازه هایی برای اون کانکشن رو سیستمتون میده
موهمه.
همین به قول ایشون فالس پازتیوی که میگه، بدلیل اینه که فایل  warp plus
دستکاری شدست که دهن هممونو سرویس میکنه.
پس نصب نکنید.

**Comment by ircfspace** [comment]
اگر در دو راهی تشخیص ارسال پیام از روی بی‌اطلاعی یا سایبری‌بودن قرار داشتم، الان کمی وضعیت برام روشن‌تر شد!
سایبری نامحترم، قبل از شانتاژ بهتره کمی تحقیق کنی، چون ما هیچ‌گروهی نداریم که بخوایم اونجا افراد رو بلاک کنیم

@nilofari700
