### ISSUE TITLE
add GNU/Linux(GNOME,KDE) proxy settings

### ISSUE THREAD

**Issue by kiomarzsss** [bepass-org/oblivion-desktop#235]
program should be able to set proxy setting like windows and mac for linux too.

if you're interested to contribute this feature in Oblivion Desktop please follow this steps:
- make sure no one else is working on this feature and if not coordinate with collaborators before starting to work on this.
- read our Contribution Guide.

this links should be helpful to solve the issue: 

Oblivion Desktop Proxy Lib:
https://github.com/bepass-org/oblivion-desktop/blob/main/src/main/lib/proxy.ts

Implementation of the feature in go lang:
https://github.com/SagerNet/sing-box/blob/84472d3ad2900d9cb3608584ba4522d841ebb38e/common/settings/proxy_linux.go

**Comment by amirsheikhan** [comment]
سلام وقت بخیر 
آیا کسی میتونه کمکم کنه تا یک برنامه عبور از فیلترینگ رایگان بسازم  ؟

**Comment by VenomScriptss** [comment]
Hello I work in Python I have been very active in the scanner discussion and I can help you I also work well with JavaScript If there is anything I can do, I will be happy to cooperate
