### ISSUE TITLE
let us share oblivion with (Microsoft Wi-Fi Direct Virtual Adapter)  in  Network Connections panel in windows

### ISSUE THREAD

**Issue by dnlamiri** [bepass-org/oblivion-desktop#236]
### Feature description | توضیحات ویژگی

let us share oblivion with (Microsoft Wi-Fi Direct Virtual Adapter)  in the Network Connections panel in Windows

I wish Oblivion had the option to share an internet profile with Microsoft Wi-Fi Direct Virtual Adapter in (win+r : ncpa.cpl)

**Comment by ircfspace** [comment]
Unfortunately, implementing this feature is not possible at the moment, but we will try to include it in future plans.
