### ISSUE TITLE
ForceIPv4

### ISSUE THREAD

**Issue by mikeesierrah** [bepass-org/oblivion-desktop#24]
### Feature description

i have noticed that app uses both ipv6 and ipv4 - itd be good if we could choose to only makes connection to websites via IPv4 only 
i have tried setting endpoint to IPv4 but it didnt work

**Comment by ircfspace** [comment]
The mentioned option, as stated in its description, is related to the scanning operation and does not have any connection to the user's IP address.

**Comment by ircfspace** [comment]
_Update:_ 
In order to prevent users from getting confused, this option will be hidden in the next update.
