### ISSUE TITLE
Can't run on my PC

### ISSUE THREAD

**Issue by zfateme** [bepass-org/oblivion-desktop#244]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![Untitled](https://github.com/bepass-org/oblivion-desktop/assets/171238339/87697644-71b3-459f-8896-ea9e8d252a3e)

### Relevant log output | لاگ برنامه

```shell
عرض سلام و خداقوت
با تشکر از زحمات شما . متاسفانه علیرغم چندین بار تلاش ناموفق این برنامه در سیستم من اجرا نمیشه. حتی بعد از نصب هم کار نمیکنه.
اگر لطف کنید و راهنمایی بفرمایید ممنون میشم.
به امید آزادی هر چه زودتر دو دوست عزیزمان یوسف قبادی و سگارو
```

**Comment by ircfspace** [comment]
سلام
موارد زیر رو اعلام کنین :

* ورژن و فایلی که دانلود کردین
* نسخه وبیلد ویندوز شما
