### ISSUE TITLE
مشکل شدید با کسپرسکی

### ISSUE THREAD

**Issue by armin9009** [bepass-org/oblivion-desktop#246]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

نه تنها ویندوز دیفندر، بلکه کسپرسکی هم اینو یه فایل مخرب شناسایی میکنن و مرتب پاکش میکنن و در نتیجه هر چند دقیقه یکبار باید دوباره نصب کنم
هربار هم add to exceptions میزنم 5 دقیقه دیگه یه چیز دیگه رو شناسایی میکنه.

### Relevant log output | لاگ برنامه

```shell
time=2024-05-30T15:45:34.058+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=mtalk.google.com:5228
```

**Comment by Frank97Tyler** [comment]
_[dic]()_language_
_server

**Comment by ircfspace** [comment]
سلام

اینجا جزییات رو توضیح دادم: https://github.com/bepass-org/oblivion-desktop/issues/232#issuecomment-2136708386

غیر از اون موارد، درحال‌حاضر یکی‌از ایده‌ها حذف فایل dll مربوط به پکیج warp-plus هست، که در نسخه بعدی این‌مورد رو لحاظ میکنیم و امیدواریم مساله تا حدی برطرف بشه.

**Comment by armin9009** [comment]
خیلی ممنون. فکر کنم بعد آپدیت امروز، کسپرسکی خیلی کمتر حساس شده. اخطار میده ولی پاک نمیکنه و مثل دیروز نیست که هر چند دقیقه نصب از صفر نیاز باشه.
