### ISSUE TITLE
Adding DOH 

### ISSUE THREAD

**Issue by JoeWalker12** [bepass-org/oblivion-desktop#247]
### Feature description | توضیحات ویژگی

لطفا این قسمت DOH2 و DOH3 هم ادد کنید

**Comment by kiomarzsss** [comment]
لطفا بیشتر توضیح بدید

**Comment by ircfspace** [comment]
اپ Oblivion Desktop یک GUI برای warp-plus هست
اضافه‌کردن فیچر درخواستی شما باید **[اینجا](https://github.com/bepass-org/warp-plus/issues)** مطرح بشه
