### ISSUE TITLE
Connectivity Problem

### ISSUE THREAD

**Issue by MrSaeid007** [bepass-org/oblivion-desktop#25]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

Hi Team, I have a problem while connecting the via app. This is the log:

time=2024-05-04T20:33:14.128+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:33:14.128+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:33:15.830+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:33:15.830+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:33:15.830+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

Can you help? Thanks.

### Minimal Reproducible Example (MRE)

.

### Version

v0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by titancomputer** [comment]
close the app, then run app as administrator and try again.

**Comment by seramo** [comment]
سلام
مشکل دسترسی برای ساخت دایرکتوری stuff وجود دارد

```
time=2024-05-04T20:13:31.813+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:31.813+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

e path specified."

time=2024-05-04T20:13:45.354+03:30 level=INFO msg="psiphon mode enabled" country=CZ

time=2024-05-04T20:13:45.354+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:45.355+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:45.355+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:13:45.984+03:30 level=INFO msg="psiphon mode enabled" country=CH

time=2024-05-04T20:13:45.985+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:45.985+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:45.985+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:13:46.875+03:30 level=INFO msg="psiphon mode enabled" country=FI

time=2024-05-04T20:13:46.875+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:46.876+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:46.876+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:13:47.066+03:30 level=INFO msg="psiphon mode enabled" country=EE

time=2024-05-04T20:13:47.067+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:47.067+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:47.067+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:13:47.255+03:30 level=INFO msg="psiphon mode enabled" country=BE

time=2024-05-04T20:13:47.256+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:47.257+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:47.257+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-04T20:13:47.406+03:30 level=INFO msg="psiphon mode enabled" country=CH

time=2024-05-04T20:13:47.407+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:13:47.408+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-04T20:13:47.408+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."
```

**Comment by seramo** [comment]
در زمان اجرا شدن با حالت administrator  هم خطا وجود دارد که لاگ این مورد هم به صورت زیر است

```
time=2024-05-04T20:15:36.093+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:15:36.093+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-04T20:15:37.581+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T20:15:37.582+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-04T20:15:37.582+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-04T20:15:38.680+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T20:15:38.680+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T20:15:38.680+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T20:15:38.690+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T20:15:38.690+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."

time=2024-05-04T20:15:40.172+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T20:15:40.179+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T20:15:40.179+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T20:15:40.179+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T20:15:40.183+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T20:15:40.183+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."

time=2024-05-04T20:15:40.829+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T20:15:40.830+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T20:15:40.830+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T20:15:40.830+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T20:15:40.833+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T20:15:40.833+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."

time=2024-05-04T20:16:50.052+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T20:16:50.053+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T20:16:50.053+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T20:16:50.053+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T20:16:50.056+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T20:16:50.056+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."
```

**Comment by seramo** [comment]
نمونه ویدیو عدم کارکرد بخش های مطرح شده

https://github.com/bepass-org/oblivion-desktop/assets/23317510/0098fa95-8ae7-45ff-9f35-3b30d63f4bd0

**Comment by MrSaeid007** [comment]
> close the app, then run app as administrator and try again.

I did but these are new log:

time=2024-05-04T22:36:37.332+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T22:36:37.338+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T22:36:37.338+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T22:36:37.338+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T22:36:37.350+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T22:36:37.350+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."

time=2024-05-04T22:36:38.159+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-04T22:36:38.160+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-05-04T22:36:38.160+03:30 level=INFO msg="using warp endpoints" endpoints="[engage.cloudflareclient.com:2048 engage.cloudflareclient.com:2048]"
time=2024-05-04T22:36:38.160+03:30 level=INFO msg="running in normal warp mode"

time=2024-05-04T22:36:38.162+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known." subsystem=wireguard-go
time=2024-05-04T22:36:38.162+03:30 level=ERROR msg="IPC error -22: failed to set endpoint engage.cloudflareclient.com:2048: No such host is known."

**Comment by Majidzam1101** [comment]
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه دومین مشکل اتصال به سایفون است هیچ سایتی باز نمی کنه


![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/dc05e348-eda6-4758-a748-be87d8e68a36)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/fc7c298b-2b6b-4cd1-9080-8908c9bef88b)
![Screenshot (7)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/a4dfb4f3-9b3f-4738-8738-200280547423)

**Comment by MIS123456** [comment]
با سلام و با تشکر از زحمات شما عزیزان
اشکلالات برنامه
1:با تنطیمات دیفالت وصل نمیشه باید ای پی تمیز در حالت گول بهش بدین تا وصل بشه
2:حالت سایفون اصلا تانل نمیشه انگار سایفون عمل اپ استریمو نمیتونه انجام بده و مشکل به احتمال زیاد همینه
3:دوستانی که مشکل وصل شدن دارن تو قسمت فایروال در inbound و outbound new rule  تعریف کنن و اجازه ترافیکو بدن

**Comment by Majidzam1101** [comment]
> > 3:دوستانی که مشکل وصل شدن دارن تو قسمت فایروال در inbound و outbound new rule تعریف کنن و اجازه ترافیکو بدن
> 
> به این شکل تعریف کنم درسته؟ ![image](https://private-user-images.githubusercontent.com/49529241/328006586-7774836e-6a7b-440a-b200-0572fa580c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDM2NjUsIm5iZiI6MTcxNDkwMzM2NSwicGF0aCI6Ii80OTUyOTI0MS8zMjgwMDY1ODYtNzc3NDgzNmUtNmE3Yi00NDBhLWIyMDAtMDU3MmZhNTgwYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEwMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2M2RhY2Y0NmYyZTE3NDlmYjgyNDRkMjIwNWE0YTEzZWI3ZGRkNDUzMGVlYmE5ZWUzM2MwZmFlM2VlZDM1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EpWzZ9spPSRzHGAI6Of6oAsKu_fix7gqrn-Fx_umJ4)
> 
> هر کاری می‌کنم برنامه متصل نمیشه! رفتم تو این [سایت](https://stock.hostmonit.com/CloudFlareYes) چند تا لینک تمیز برداشتم گذاشتم تو برنامه به این صورت: ![image](https://private-user-images.githubusercontent.com/49529241/328006698-d1deb2ba-18fa-4c6f-953c-3d1455ae4476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDM2NjUsIm5iZiI6MTcxNDkwMzM2NSwicGF0aCI6Ii80OTUyOTI0MS8zMjgwMDY2OTgtZDFkZWIyYmEtMThmYS00YzZmLTk1M2MtM2QxNDU1YWU0NDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEwMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzODczMDIxYTc0ZjliNDQ3YWQ4YmZmMGIwNDRhZTNlNTlkNDI5MDEzODY3NDk5YjUwNTQxM2M5ODQzNGMyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvL6d40wptx7uWWgeqVQM6kzuUHGeZtLFaSZxJG-jDg) ![image](https://private-user-images.githubusercontent.com/49529241/328006695-33efb95b-06fe-4a6c-bd21-9dd422533cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDM2NjUsIm5iZiI6MTcxNDkwMzM2NSwicGF0aCI6Ii80OTUyOTI0MS8zMjgwMDY2OTUtMzNlZmI5NWItMDZmZS00YTZjLWJkMjEtOWRkNDIyNTMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEwMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Njc5YjJhMGIwZWFhOWNjYzVkY2ExM2QxOGIxZTZkZmJlYzdiMTFlNzcwYWM5MjIwNWUxMGRiYmQ0YWQ0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pa8CNLNGNvFa5MtDCq7f10f2UaYebQKMqvfP0wEX0NE)
> 
> اما کار نمی‌کنه! دقیقا باید چی کار کنم که وصل بشه؟
> 
> البته یه برنامه دیگه دارم که از [اینجا](https://github.com/NIKJOO/WarpOnWarp-Windows-Client.git) دانلود کردم و به راحتی وصل میشه: ![image](https://private-user-images.githubusercontent.com/49529241/328006855-10bf9185-54cd-4614-971d-17f72975185d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDM2NjUsIm5iZiI6MTcxNDkwMzM2NSwicGF0aCI6Ii80OTUyOTI0MS8zMjgwMDY4NTUtMTBiZjkxODUtNTRjZC00NjE0LTk3MWQtMTdmNzI5NzUxODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEwMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MDg5NTM5NDA4NjBjOTYwNzAyZTdmNGU5ZjRmYmI4ZWIyN2M2MDRlYWI2MTI4ZDU1OWI5ODU0ZDgxNjNhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mR25aUd6BbaExxWrV5ASAioroS62HLHW9olgCczcTzw)
> 
> سپاس

سلام ای پی تمیز و تنظیمات بالا انجام دادم اصلا کار نمی کنه توی فایروال مجوزدادم هیچی باز نمی کنه

**Comment by ircfspace** [comment]
این آیپی‌هایی که از سایت مذکور برداشتین برای وارپ نیستن

مشکل گزینه سایفون و نداشتن سطح دسترسی stuff هم در دست بررسیه و احتمالن در آپدیت بعدی برطرف میشه

فعلن تیک اسکن رو بزنین و با گول به اینترنت آزاد متصل بشین

**Comment by ircfspace** [comment]
کاری انجام ندادیم
احتمالن اختلال از اینترنتتون بود

**Comment by ircfspace** [comment]
کاری انجام ندادیم
احتمالن اختلال از اینترنتتون بود

**Comment by Majidzam1101** [comment]
> کاری انجام ندادیم احتمالن اختلال از اینترنتتون بود
سلام چرا نسخه اندروید این برنامه اسکنر ای پی تمیز نداره بر خلاف نسخه ویندوز؟ و نسخه ویندوز چرا ای پی تمیز دستی از ترموکس می گیریم کار نمی کنه ؟ نسخه نهایی ویندوز این برنامه زمان انتشارش چه زمانی است ؟

**Comment by Majidzam1101** [comment]
> > فعلن تیک اسکن رو بزنین و با گول به اینترنت آزاد متصل بشین
> 
> نمیدونم چی کار کردید اما به طرز عجیبی برام وصل شد تا ظهر هر کاری می‌کردم متصل نمی‌شد.
> 
> سپاس
> 
> ![image](https://private-user-images.githubusercontent.com/49529241/328044499-dc4f8de7-5977-4e65-88e0-0114ebf1656a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NDEzNDEsIm5iZiI6MTcxNDk0MTA0MSwicGF0aCI6Ii80OTUyOTI0MS8zMjgwNDQ0OTktZGM0ZjhkZTctNTk3Ny00ZTY1LTg4ZTAtMDExNGViZjE2NTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDIwMzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZWM5NTczMDRmMzQ0NDAzZGM4ZTU1MGQyZjgxOTRhY2ZhOTJmMTE0YjBlMjQ1MjBmNGJkZmJjZTA2NTM0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tMyxJ_5HSjNh0kqYVnmwWqxw0O3jdYdBNezpQ0iqFDM)

سلام وقتی وصل میشه پرچم المان توی نسخه ویندوز نمی یاد ! چرا گول  تیک می زنیم کشور غیر المان نمی یاد   مثلا فنلاند یا  سوِئد وصل نمیشه فقط المان نمایش میده
