### ISSUE TITLE
Add ability to exclude apps (blacklist but for apps)

### ISSUE THREAD

**Issue by rti2** [bepass-org/oblivion-desktop#251]
### Feature description | توضیحات ویژگی

سلام ممنون از انتشار نسخه ی جدید 3>
خیلی خوب میشه اگه قابلیت exclude  رو برای برنامه ها هم اضافه کنید (مثل نکوری)

**Comment by ircfspace** [comment]
سلام
بعد از اضافه کردن فیچر TUN سراغ این مورد هم میریم، اما درحال‌حاضر میتونین از طریق ترکیب با نکوری موضوع رو هندل کنین

**Comment by rti2** [comment]
اوکی 
ممنون
