### ISSUE TITLE
اضافه کردن امکان کانت و تنطیم پروکسی به وسیله برنامه proxifier و حالت vpn mode با کمک tap\tun 

### ISSUE THREAD

**Issue by MehranAkbarii** [bepass-org/oblivion-desktop#253]
### Feature description | توضیحات ویژگی

اضافه کردن امکان کانت و تنطیم پروکسی به وسیله برنامه proxifier و حالت vpn mode با کمک tap\tun

**Comment by kiomarzsss** [comment]
قابلیت TUN در roadmap برنامه قرار داره
