### ISSUE TITLE
Add tun mode using last warp plus version

### ISSUE THREAD

**Issue by hossein-mohseni** [bepass-org/oblivion-desktop#260]
### Feature description | توضیحات ویژگی

![image](https://github.com/bepass-org/oblivion-desktop/assets/27780287/30da8c07-ab6a-4649-8019-1e01f6b0ff12)

https://www.speedtest.net/result/16320184502

https://github.com/hossein-mohseni/EP-Scanner

این تست با استفاده از tun mode آخرین نسخه warp plus و اندپوینتی که با اسکنر خودم زدم این نتیجه شد و البته برای من تا قبل از اسکنر متصل نمیشد 
روی چندین اپراتور هم تست کردم با پینگ پایین و سرعت بالا متصل شد.

 wintun.dll
 
 در آخرین نسخه لازم میشه
 
 در آینده نزدیک اندپوینت ها احتمالا فیلتر بشن اما با بردن پشت دامنه های کلودفلر با پروکسی روشن و استفاده از sni و آیپی تمیز و ... همچنان میشه اسکن کرد و متصل شد

**Comment by majidst-me** [comment]
سپاس بابت اشتراک گذاری اسکنر
اندپوینت رو پیدا میکنه تو oblivion که ست میکنم اتصال برقرار میشه پینگ هم میده ولی سایتی باز نمیشه چه داخلی چه خارجی
tun mode
 رو متوجه نشدم کجا باید فعال کنم؟

**Comment by hossein-mohseni** [comment]
> سپاس بابت اشتراک گذاری اسکنر اندپوینت رو پیدا میکنه تو oblivion که ست میکنم اتصال برقرار میشه پینگ هم میده ولی سایتی باز نمیشه چه داخلی چه خارجی tun mode رو متوجه نشدم کجا باید فعال کنم؟

از افزونه smart proxy استفاده کنید
![image](https://github.com/bepass-org/oblivion-desktop/assets/27780287/d08aba1d-59d3-438a-8e62-981a99284f04)

یک پروکسی سرور مانند تصویر اضافه کنید و بعد در هر صفحه از مرورگر روی پلاگین کلیک کنید و روی always Enable قرار بدین و سایت مد نظر رو باز کنید

Tun mode
هنوز به oblivion اضافه نشده ولی با زدن دستورات و استفاده از Warp plus core میتونید استفاده کنید که کمی تخصصی هست

**Comment by ircfspace** [comment]
فلگ TUN در هسته Warp-Plus به‌صورت آزمایشی گنجونده‌شده و طبیعتن ایراداتی داره؛ 
ضمن اینکه فعلن روی همه سیستم‌عامل‌ها ساپورت نشده. 

هرموقع به شرایط استیبل برسه، به نسخه دسکتاپ اضافه می‌کنیم
