### ISSUE TITLE
سازنده محترم قابلیت tun اضافه کنید 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#261]
### Feature description | توضیحات ویژگی

سلام 
سازنده محترم قابلیت tun اضافه کنید در اپدیت بعدی جهت تست

**Comment by ircfspace** [comment]
سلام
لطفا مطالعه کنین: https://github.com/bepass-org/oblivion-desktop/issues/260#issuecomment-2142933869
