### ISSUE TITLE
Display authentication error cannot be used. I don't know how to solve it

### ISSUE THREAD

**Issue by ssssdqer134** [bepass-org/oblivion-desktop#263]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Display authentication error cannot be used. I don't know how to solve it

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Display authentication error cannot be used. I don't know how to solve it

### Relevant log output | لاگ برنامه

```shell
Display authentication error cannot be used. I don't know how to solve it
```

**Comment by ircfspace** [comment]
Hi,
When you encounter an issue or error, please copy the application log and send it to us

**Comment by ssssdqer134** [comment]
[image: image.png]

IRCF ***@***.***> 于2024年6月4日周二 06:25写道：
