### ISSUE TITLE
YouTube, Instagram, and Twitter not working in the 0.10.8-beta version

### ISSUE THREAD

**Issue by Tebjox** [bepass-org/oblivion-desktop#265]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

YouTube, Instagram, and Twitter not working in the new version

OS: Windows 11 x64
ISP: TCI

I have raised this issue on the [warp-plus ](https://github.com/bepass-org/warp-plus/issues/139)page.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Enable Gool mode.
2. Click on Connect button.
3. Enter the youtube.com URL in your brower.

### Relevant log output | لاگ برنامه

```shell
[2024-06-01 11:52:06.746] [info]  past logs was deleted for new connection.
[2024-06-01 11:52:06.748] [info]  ------------------------MetaData------------------------
[2024-06-01 11:52:06.749] [info]  running on: win32 10.0.22000 x64
[2024-06-01 11:52:06.750] [info]  at od: 0.10.8-beta
[2024-06-01 11:52:06.751] [info]  at wp: v1.2.3
[2024-06-01 11:52:06.752] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-06-01 11:52:06.752] [info]  method: gool
[2024-06-01 11:52:06.753] [info]  proxyMode: false
[2024-06-01 11:52:06.754] [info]  endpoint: default
[2024-06-01 11:52:06.755] [info]  license: false
[2024-06-01 11:52:06.755] [info]  exe: C:\Users\<USERNAME>\AppData\Local\Programs\Oblivion Desktop\Oblivion Desktop.exe
[2024-06-01 11:52:06.756] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-06-01 11:52:06.756] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-06-01 11:52:06.757] [info]  ------------------------MetaData------------------------
[2024-06-01 11:52:06.765] [info]  starting wp process...
[2024-06-01 11:52:06.765] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --scan --rtt 1s
time=2024-06-01T11:52:06.831+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-06-01T11:52:06.833+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-01T11:52:16.405+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.51 error="read udp 192.168.1.3:59002->162.159.193.51:988: i/o timeout"

time=2024-06-01T11:52:18.845+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.99.181:890 RTT:156.4404ms CreatedAt:2024-06-01 11:52:18.3001611 +0330 +0330 m=+11.486609101} {AddrPort:162.159.192.197:955 RTT:204.3061ms CreatedAt:2024-06-01 11:52:09.839968 +0330 +0330 m=+3.026416001}]"
time=2024-06-01T11:52:18.845+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.99.181:890 162.159.192.197:955]"
time=2024-06-01T11:52:18.845+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-06-01T11:52:18.845+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-01T11:52:22.744+03:30 level=INFO msg="connection test successful"

time=2024-06-01T11:52:22.745+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-01T11:52:24.201+03:30 level=INFO msg="connection test successful"

time=2024-06-01T11:52:24.201+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-06-01T11:52:25.158+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:1c20:c6ad:8b12:40ad error="read udp [fe80::dbba:adf3:c261:80de%Wi-Fi]:61501->[2606:4700:d0:0:1c20:c6ad:8b12:40ad]:908: i/o timeout"

time=2024-06-01T11:52:36.438+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=140.82.113.25:443

time=2024-06-01T11:52:36.572+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.239.38.120:443

time=2024-06-01T11:52:36.698+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.239.38.120:443

time=2024-06-01T11:52:39.398+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:52:52.063+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:13773: i/o timeout" subsystem=vtun

time=2024-06-01T11:52:52.142+03:30 level=WARN msg="read tcp 172.16.0.2:35848->216.239.38.120:443: i/o timeout" subsystem=vtun

time=2024-06-01T11:53:00.687+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=140.82.113.25:443

time=2024-06-01T11:53:14.811+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:14.865+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=34.120.208.123:443

time=2024-06-01T11:53:14.906+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.58.213.106:443

time=2024-06-01T11:53:15.871+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:15.873+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:15.873+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443
time=2024-06-01T11:53:15.874+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:15.889+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:15.892+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T11:53:16.391+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:13781: i/o timeout" subsystem=vtun

time=2024-06-01T11:53:17.227+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=140.82.112.25:443
```

**Comment by ircfspace** [comment]
از یکی‌از اندپوینت‌های پیشنهادی استفاده کرده و مجدد تست بگیرین

**Comment by Tebjox** [comment]
> Use one of the recommended endpoints (in the scanner settings) and take the test again
> 
> از یکی‌از اندپوینت‌های پیشنهادی (در تنظیمات اسکنر) استفاده کرده و مجدد تست بگیرین

جواب نداد.

[2024-06-01 12:11:32.407] [info]  past logs was deleted for new connection.
[2024-06-01 12:11:32.410] [info]  ------------------------MetaData------------------------
[2024-06-01 12:11:32.411] [info]  running on: win32 10.0.22000 x64
[2024-06-01 12:11:32.412] [info]  at od: 0.10.8-beta
[2024-06-01 12:11:32.413] [info]  at wp: v1.2.3
[2024-06-01 12:11:32.414] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-06-01 12:11:32.415] [info]  method: gool
[2024-06-01 12:11:32.415] [info]  proxyMode: false
[2024-06-01 12:11:32.416] [info]  endpoint: custom
[2024-06-01 12:11:32.416] [info]  license: false
[2024-06-01 12:11:32.417] [info]  exe: C:\Users\<USERNAME>\AppData\Local\Programs\Oblivion Desktop\Oblivion Desktop.exe
[2024-06-01 12:11:32.417] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-06-01 12:11:32.418] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-06-01 12:11:32.418] [info]  ------------------------MetaData------------------------
[2024-06-01 12:11:32.428] [info]  starting wp process...
[2024-06-01 12:11:32.429] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --endpoint 162.159.192.175:891
time=2024-06-01T12:11:32.495+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.192.175:891 162.159.192.175:891]"
time=2024-06-01T12:11:32.496+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-06-01T12:11:32.496+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-01T12:11:36.355+03:30 level=INFO msg="connection test successful"

time=2024-06-01T12:11:36.356+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-01T12:11:37.704+03:30 level=INFO msg="connection test successful"

time=2024-06-01T12:11:37.704+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-06-01T12:11:50.539+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=140.82.112.21:443

time=2024-06-01T12:11:51.033+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.239.38.120:443

time=2024-06-01T12:11:51.120+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.239.38.120:443

time=2024-06-01T12:11:51.385+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:06.157+03:30 level=WARN msg="read tcp 172.16.0.2:47314->140.82.112.21:443: i/o timeout" subsystem=vtun

time=2024-06-01T12:12:06.469+03:30 level=WARN msg="read tcp 172.16.0.2:17171->216.239.38.120:443: i/o timeout" subsystem=vtun

time=2024-06-01T12:12:32.405+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=34.120.208.123:443

time=2024-06-01T12:12:32.486+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:32.777+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=216.58.213.99:443

time=2024-06-01T12:12:33.414+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:33.417+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:33.417+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:33.419+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:33.421+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:33.432+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:37.670+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=10.10.34.36:443

time=2024-06-01T12:12:37.729+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.217.17.131:443

time=2024-06-01T12:12:38.962+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=172.217.20.74:443

**Comment by ircfspace** [comment]
پیکربندی شبکه رو روی system proxy نذاشتین؟
این مورد رو بررسی کنین

**Comment by Tebjox** [comment]
> پیکربندی شبکه رو روی system proxy نذاشتین؟ این مورد رو بررسی کنین

خیر روی حالت None تنظیم کردم.
* پس از هر آپدیت هم تنظیمات اپ رو Reset می کنم معمولا.

**Comment by ircfspace** [comment]
برای رفع مشکل، تنظیمات رو روی system proxy ست کنین تا PAC اعمال بشه روی مرورگر کروم
