### ISSUE TITLE
Most of the time, the CPU usage is pretty high on windows 11

### ISSUE THREAD

**Issue by RayneScofield** [bepass-org/oblivion-desktop#268]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![image](https://github.com/bepass-org/oblivion-desktop/assets/45684550/a8b0a191-872d-47a6-96ae-eebef3814c6d)

### Relevant log output | لاگ برنامه

```shell
From the task manager, we can see the cpu usage of  Oblivion is constantly running at around 20%, it may down to 2%  for a few seconds, but it goes up later on.
```

**Comment by ircfspace** [comment]
This application serves as a graphical user interface (GUI) for Warp-Plus.

Please use the provided link to discuss and exchange ideas on all topics related to Warp-Plus:
https://github.com/bepass-org/warp-plus
