### ISSUE TITLE
ایراد در اتصال در حالت سایفون و گول

### ISSUE THREAD

**Issue by davidzmn** [bepass-org/oblivion-desktop#27]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با درود و عرض احترام
برای اتصال حتما باید از ای پی و پورت دستی استفاده بشه ای پی دیفالت وارپ تو اتصال دچار مشکل هست
موقع استفاده از سایفن برنامه کانکت نمیشه و بعد از برگردوندن به حالت گول برنامه اصلا کانکت نمیشه
اگر مثل نسخه اندروید لاگ برنامه روی صفحه اصلی باشه خیلی عالی میشه
و در اخر برنامه اگر رو حالت VPN Service هم اجرا بشه برای تانل کردن کل سیستم که عالی میشه
پاینده باشید

### Minimal Reproducible Example (MRE)

Log section

### Version

0.2.44-Beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by Majidzam1101** [comment]
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه دومین مشکل اتصال به سایفون است هیچ سایتی باز نمی کنه 


![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/83e01bb6-2a62-4b5e-a5c2-5225abfb24e2)

![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/672d5e66-e801-4c38-8ea1-a284fb7bef42)

**Comment by MIS123456** [comment]
با سلام و با تشکر از زحمات شما عزیزان
اشکلالات برنامه
1:با تنطیمات دیفالت وصل نمیشه باید ای پی تمیز در حالت گول بهش بدین تا وصل بشه
2:حالت سایفون اصلا تانل نمیشه انگار سایفون عمل اپ استریمو نمیتونه انجام بده و مشکل به احتمال زیاد همینه
3:دوستانی که مشکل وصل شدن دارن تو قسمت فایروال در inbound و outbound new rule  تعریف کنن و اجازه ترافیکو بدن

**Comment by ircfspace** [comment]
سلام

مشکل سایفون در دست بررسیه و احتمالن در آپدیت بعدی اضافه بشه
موضوع پروکسی‌کردن کامل سیستم هم در آپدیت‌های بعدی می‌گنجونیم
