### ISSUE TITLE
 بررسی ست شدن پراکسی 

### ISSUE THREAD

**Issue by gdariushahmadi** [bepass-org/oblivion-desktop#270]
### Feature description | توضیحات ویژگی

به دلایل تا الان نامشخص ممکن است پراکسی روی سیستم ست نشود ولی اتصال برقرار شده است. به نظر بد نیست قبل از مرحله‌ی چک آی‌پی وضعیت ست کردن پراکسی هم باشه که علاوه بر ست کردن پراکسی بررسی کند به درستی انجام شده یا نه  و در صورت وجود مشکل با یکبار سعی مجدد پیام مناسب به کاربر نمایش داده شود.

**Comment by ircfspace** [comment]
در چه سیستم عاملی؟
جزییات بیشتر ارائه کنید

**Comment by kiomarzsss** [comment]
@gdariushahmadi 
درود. قبل از enable شدن دکمه connect/disconnect برنامه مطمئن میشه که هر 2 پروسه wp و ست شدن پروکسی کارشون رو به درستی انجام داده باشن(برای بررسی فایل `wp` در دایرکتوری `ipcListeners` رو چک کنین) و بنظرم هرگونه مطمئن شدن از عملکرد صحیح پروسه ست کردن پروکسی باید به عهده خود پروسه و که داخل فایل `proxy` هست انجام بشه). حاضرم نظر شمارو هم در این رابطه بشونم و اگر بهتر بود اون رو اجرا کنیم. و اینکه چه مشکلی باعث شد که چنین پیشنهادی بدین؟

**Comment by gdariushahmadi** [comment]
چند تا از گزارش‌‌های خطا که به دلیل ست نشدن پراکسی بوده با عنوان دیگری گزارش شده. در حال حاضر ست شدن پراکسی در هر ۳ سیستم عامل بخشی از پروسه اتصال است نظرم اینه که این مرحله  رو به صورت مجزا در نظر بگیریم و نمایش بدیم تا اگر این قسمت به مشکل برخورد خطای مناسب نشون داده بشه. حالا این بررسی ست شدن پراکسی بخش از خود پروسه کلی باشه هم مشکلی نیست.
بررسی هم شامل این باشه که ببینیم پراکسی با چه مقادیری رو سیستم عامل ست شده و مطابق آنچیزی که ما می‌خواستیم است یا نه. 
البته مقادیر تنظیمات پراکسی فعالی در صورتی که بخواهیم بعد از قطع شدن پراکسی به مقدار اولیه بربگردونیم هم لازم میشه.

**Comment by kiomarzsss** [comment]
> چند تا از گزارش‌‌های خطا که به دلیل ست نشدن پراکسی بوده با عنوان دیگری گزارش شده. در حال حاضر ست شدن پراکسی در هر ۳ سیستم عامل بخشی از پروسه اتصال است نظرم اینه که این مرحله رو به صورت مجزا در نظر بگیریم و نمایش بدیم تا اگر این قسمت به مشکل برخورد خطای مناسب نشون داده بشه. حالا این بررسی ست شدن پراکسی بخش از خود پروسه کلی باشه هم مشکلی نیست. بررسی هم شامل این باشه که ببینیم پراکسی با چه مقادیری رو سیستم عامل ست شده و مطابق آنچیزی که ما می‌خواستیم است یا نه. البته مقادیر تنظیمات پراکسی فعلی در صورتی که بخواهیم بعد از قطع شدن پراکسی به مقدار اولیه بربگردونیم هم لازم میشه.


متوجه منظورتون هستم. در حال حاضر هم امکان نمایش خطا به کاربر از داخل خود پروسه پروکسی فراهمه(مثال: https://github.com/bepass-org/oblivion-desktop/blob/99e4d8fd479f2fc6d94ffcfd646feef6476c2bb9/src/main/lib/proxy.ts#L451).
با پروسه چک کردن دوباره مشکلی ندارم و بنظرم میتونه بعد از پروسه ست کردن پروکسی یه پروسه هم به صورت اتوماتیک اجرا بشه که چک کنه آیا پروکسی ست شده یا نه.
اگر مایل بودید کد مربوط به مک رو زحمتش رو بکشید خودتون و بقیه سیستم عامل ها هم به عهده من.
اینم بگم به احتمال خیلی زیاد به گزینه های `پیکربندی شبکه` گزینه جدیدی با عنوان `system proxy (sing-box)` اضافه خواهد شد که احتمالا مشکل کاربر هایی که با پروسه برای ست شدن پروکسی مشکل دارند رو حل خواهد کرد. با تشکر از مشارکتتون اگر تمایل به پیاده سازی قابلیت مطرح شده روی مک دارید لطفا اطلاع بدید.

**Comment by gdariushahmadi** [comment]
من کد مربوط به مک رو اضافه می‌کنم.

**Comment by kiomarzsss** [comment]
حله

> من کد مربوط به مک رو اضافه می‌کنم.

**Comment by DreamXlite** [comment]
لطفا اگه شد راحلی برای این مشکل ست شدن پروکسی تو ویندوز 11 در نظر بگیرید من امتحان کردم دوتا نسخه  نصبی و پرتابل ولی هم چنان مشکل هست فکر کنم از   vbscript باشه که برای ست کردن پروکسی استفاده میشه  اگر شد از روشی دیگری استفاده شود برای ست پروکسی

**Comment by kiomarzsss** [comment]
> لطفا اگه شد راحلی برای این مشکل ست شدن پروکسی تو ویندوز 11 در نظر بگیرید من امتحان کردم دوتا نسخه نصبی و پرتابل ولی هم چنان مشکل هست فکر کنم از vbscript باشه که برای ست کردن پروکسی استفاده میشه اگر شد از روشی دیگری استفاده شود برای ست پروکسی

در آینده و با اضافه شدن قابلیت tun یه قابلیت دیگه هم به اسم system proxy(sing-box) به گزینه های پیکربندی شبکه اضافه خواهد شد که احتمالا مشکلتون رو حل کنه.
