### ISSUE TITLE
Oblivion Desktop in Mac is damaged and can not be opened

### ISSUE THREAD

**Issue by aminsamizadeh** [bepass-org/oblivion-desktop#272]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

After Installation on M3 MacBook the App can't open and says it's damaged.
![Screenshot 2024-06-02 at 10 01 30 AM](https://github.com/bepass-org/oblivion-desktop/assets/49447947/d4543768-248a-487f-885a-37ffff0ee5f1)

### Relevant log output | لاگ برنامه

```shell
It has no log ...
```

**Comment by ircfspace** [comment]
سلام
مشاهده کنین: https://github.com/bepass-org/oblivion-desktop/issues/206
