### ISSUE TITLE
IP Address Displayed in WebRTC Test

### ISSUE THREAD

**Issue by cloner12** [bepass-org/oblivion-desktop#283]
### Feature description | توضیحات ویژگی

برنامه به خوبی با متدهای **WarpinWarp** و **Psiphon** بدون مشکل کانکت می‌شه (با استفاده از [اندپوینت اسکنر](https://shorturl.at/eqGqT) ).
تنها مشکل اینه که هنگام تست WebRTC، آی‌پی ایران را نمایش می‌ده. من با اینترنت مخابرات، شاتل، ایرانسل و همراه اول و رایتل این مشکل رو تست کردم با چند مرورگر مختلف.
در حال حاضر از نسخه آخر (v0.10.8-beta) استفاده می‌کنم و دو نسخه قبلی نیز همین مشکل رو داشتند.

![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/1d6764ad-9e44-4493-9411-c0a410e14aa7)

در تمام این سایت ها تست کردم.
https://surfshark.com/webrtc-leak-test
https://www.expressvpn.com/webrtc-leak-test
https://hide.me/en/webrtc-leak-test
https://www.perfect-privacy.com/en/tests/dns-leaktest
https://www.experte.com/webrtc-leak

**Comment by ircfspace** [comment]
سلام
از چه پیکربندی و مرورگری برای تست استفاده میکنین؟

**Comment by iran-free-net** [comment]
> ### Feature description | توضیحات ویژگی
> برنامه به خوبی با متدهای **WarpinWarp** و **Psiphon** بدون مشکل کانکت می‌شه (با استفاده از [اندپوینت اسکنر](https://shorturl.at/eqGqT) ). تنها مشکل اینه که هنگام تست WebRTC، آی‌پی ایران را نمایش می‌ده. من با اینترنت مخابرات، شاتل، ایرانسل و همراه اول و رایتل این مشکل رو تست کردم با چند مرورگر مختلف. در حال حاضر از نسخه آخر (v0.10.8-beta) استفاده می‌کنم و دو نسخه قبلی نیز همین مشکل رو داشتند.
> 
> ![image](https://private-user-images.githubusercontent.com/53141535/336261790-1d6764ad-9e44-4493-9411-c0a410e14aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQwNjMsIm5iZiI6MTcxNzQ4Mzc2MywicGF0aCI6Ii81MzE0MTUzNS8zMzYyNjE3OTAtMWQ2NzY0YWQtOWU0NC00NDkzLTk0MTEtYzBhNDEwZTE0YWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNWU5YTIxYWU2YmM4MTM4MTllNGJlNDRkN2ZhMTcxMThmMWFkYWRiMWVlZjU4Y2ZhOTdkOTMwNjNlNTRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asfAF_xrZXkLaJu47jjk8lheYy4YAPUrxEt6hDP7fOA)
> 
> در تمام این سایت ها تست کردم. https://surfshark.com/webrtc-leak-test https://www.expressvpn.com/webrtc-leak-test https://hide.me/en/webrtc-leak-test https://www.perfect-privacy.com/en/tests/dns-leaktest https://www.experte.com/webrtc-leak

در مجموع اصولا VPN ها نمیان جلو DNS Leakage رو تو مرورگرتون بگیرن
برای این مهم باید از اکستنشن هایی مثل [https://chromewebstore.google.com/detail/webrtc-leak-shield/bppamachkoflopbagkdoflbgfjflfnfl](url) استفاده کنین که خوب کاملا جلوی websocket رو میگیره

**Comment by cloner12** [comment]
> سلام از چه پیکربندی و مرورگری برای تست استفاده میکنین؟

هم با System proxy تست کردم و هم None گذاشتم

**Comment by cloner12** [comment]
> > ### Feature description | توضیحات ویژگی
> > برنامه به خوبی با متدهای **WarpinWarp** و **Psiphon** بدون مشکل کانکت می‌شه (با استفاده از [اندپوینت اسکنر](https://shorturl.at/eqGqT) ). تنها مشکل اینه که هنگام تست WebRTC، آی‌پی ایران را نمایش می‌ده. من با اینترنت مخابرات، شاتل، ایرانسل و همراه اول و رایتل این مشکل رو تست کردم با چند مرورگر مختلف. در حال حاضر از نسخه آخر (v0.10.8-beta) استفاده می‌کنم و دو نسخه قبلی نیز همین مشکل رو داشتند.
> > ![image](https://private-user-images.githubusercontent.com/53141535/336261790-1d6764ad-9e44-4493-9411-c0a410e14aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQwNjMsIm5iZiI6MTcxNzQ4Mzc2MywicGF0aCI6Ii81MzE0MTUzNS8zMzYyNjE3OTAtMWQ2NzY0YWQtOWU0NC00NDkzLTk0MTEtYzBhNDEwZTE0YWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNWU5YTIxYWU2YmM4MTM4MTllNGJlNDRkN2ZhMTcxMThmMWFkYWRiMWVlZjU4Y2ZhOTdkOTMwNjNlNTRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asfAF_xrZXkLaJu47jjk8lheYy4YAPUrxEt6hDP7fOA)
> > در تمام این سایت ها تست کردم. https://surfshark.com/webrtc-leak-test https://www.expressvpn.com/webrtc-leak-test https://hide.me/en/webrtc-leak-test https://www.perfect-privacy.com/en/tests/dns-leaktest https://www.experte.com/webrtc-leak
> 
> در مجموع اصولا VPN ها نمیان جلو DNS Leakage رو تو مرورگرتون بگیرن برای این مهم باید از اکستنشن هایی مثل [https://chromewebstore.google.com/detail/webrtc-leak-shield/bppamachkoflopbagkdoflbgfjflfnfl](url) استفاده کنین که خوب کاملا جلوی websocket رو میگیره



کلا هدف اصلی استفاده از VPN جلوگیری از انتشار آی پی نیست؟

با ExpressVPN و HotspotShield و Hiddify هم امتحان کردم اما این مشکل رو نداشتم

![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/043ffb84-7c96-41e2-862c-56f7ecda5eae)

![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/eadf9fba-abfd-434d-bcaa-665dbf6b85ad)

**Comment by ircfspace** [comment]
امکان تست توسط **[Warp-plus](https://github.com/bepass-org/warp-plus)** رو دارین؟

**Comment by cloner12** [comment]
بله با وارپ پلاس هم تست انجام دادم و ای‌پی لیک میشود

![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/f36db5e1-3abb-4880-85c0-66a273375269)

**Comment by cloner12** [comment]
> امکان تست توسط **[Warp-plus](https://github.com/bepass-org/warp-plus)** رو دارین؟


بله با وارپ پلاس هم تست انجام دادم و ای‌پی لیک میشود

![image](https://github.com/bepass-org/oblivion-desktop/assets/53141535/f36db5e1-3abb-4880-85c0-66a273375269)

**Comment by Lanius-collaris** [comment]
@cloner12 Open `about:config` and set `media.peerconnection.ice.proxy_only_if_behind_proxy` to true ( firefox ).

**Comment by ircfspace** [comment]
تشکر از تستی که انجام دادین،
درصورت امکان **[اینجا](https://github.com/bepass-org/warp-plus/issues)** ایشو کنید، تا موضوع رو پیگیری کنن
