### ISSUE TITLE
پشتیبانی Routing rules از پروتکل های دیگر

### ISSUE THREAD

**Issue by iran-free-net** [bepass-org/oblivion-desktop#286]
### Feature description | توضیحات ویژگی

یک مشکلی که برخورد داشتم این هست که Routing rules رو نمیشه با آدرس هایی مثل wss که برای وب سوکت هست مقدار دهی کردش
در بعضی از سرویس ها نیاز هست به جز ترافیک http ترافیک های دیگه ای رو هم bypass کرد

همچنین سوالی داشتم که Routing rules داخل این اپلیکیشن از geoip هم استفاده میکنه؛ موضوع آپدیت این فایل به چه صورتی هست و آیا موارد دیگری که داخل Routing rules پروکسی های دیگه ای مثل V2ray وجود داره (مثل geosite) رو قرار هست اضافه کنید؟

**Comment by ircfspace** [comment]
موردی‌که بهش اشاره دارین در آپدیت‌های بعدی با اضافه‌کردن ویژگی TUN امکان‌پذیر میشه
درحال‌حاضر ویژگی RoutingRules با system proxy کار میکنه و عملن یه‌چیز صرفن کارراه‌اندازه
