### ISSUE TITLE
Warp Plus license is not applying

### ISSUE THREAD

**Issue by bia-pain-bache** [bepass-org/oblivion-desktop#288]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Warp plus license has been set (in Gool mode), however checking on https://cloudflare.com/cdn-cgi/trace you can find the normal warp not plus account:

h=cloudflare.com
ip=104.28.197.7
ts=1717491009.989
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
colo=FRA
sliver=none
http=http/2
loc=DE
tls=TLSv1.3
sni=plaintext
warp=on
gateway=off
rbi=off

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Set warp plus license
2. Scanned warp endpoint and set it.
3. Activated Gool mode.
4. Connected

### Relevant log output | لاگ برنامه

```shell
time=2024-06-04T12:23:36.542+03:30 level=INFO msg="updating account license key" subsystem=warp/account
time=2024-06-04T12:23:41.179+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account
time=2024-06-04T12:23:46.952+03:30 level=INFO msg="connection test successful"
```

**Comment by ircfspace** [comment]
سلام
از کدوم نسخه استفاده میکنین؟
امکان تست این مورد رو با warp-plus هم دارید؟
