### ISSUE TITLE
کل سیستم ویندوز تونل نمی کنه

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#29]
### Feature description

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه

![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/0ab7832c-3c34-4803-b7d5-258c04c6fc47)

![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/6d8e266d-58e8-41c6-a77e-2ae4af55e72d)

**Comment by ircfspace** [comment]
بالای 10 بار این‌موضوع رو به صورت مستقل یا زیر ایشوهای غیرمرتبط باز کردید

**لطف کنین از ارسال اسپم خودداری کنید**

**Comment by Bifckr** [comment]
سلام  همه این مشکل رو گزارش کردن فعلا باید منتظر باشید تا درست کن
و میتونی با نکوری تان مود رو روشن کنی البته که باید خود اپ اصلی رو تو نکوری بایپس کنی که تان مود رو برنامه اجرا نشه
و اصولاً تان مود پیشنهاد خوبی نیست چون کل سیستم درگیر میشه و سیپیو زیادی مصرف می‌کنه شما میتونین در همه برنامه ها از جمله کروم تلگرام اسپانیا فای واتساپ و.... با سیستم پروکسی با اجرای بهینه و رون فیلتر لندازین

**Comment by Majidzam1101** [comment]
> سلام همه این مشکل رو گزارش کردن فعلا باید منتظر باشید تا درست کن و میتونی با نکوری تان مود رو روشن کنی البته که باید خود اپ اصلی رو تو نکوری بایپس کنی که تان مود رو برنامه اجرا نشه و اصولاً تان مود پیشنهاد خوبی نیست چون کل سیستم درگیر میشه و سیپیو زیادی مصرف می‌کنه شما میتونین در همه برنامه ها از جمله کروم تلگرام اسپانیا فای واتساپ و.... با سیستم پروکسی با اجرای بهینه و رون فیلتر لندازین

سلام من تگلرام مشکل ندارم واتساپ مشکل دارم با اوبویلیون ویندوز لود نمیشه ماکروسافت استور باز نمی کنه

**Comment by Majidzam1101** [comment]
> بالای 10 بار این‌موضوع رو به صورت مستقل یا زیر ایشوهای غیرمرتبط باز کردید
> 
> **لطف کنین از ارسال اسپم خودداری کنید**

سلام من تگلرام مشکل ندارم واتساپ مشکل دارم با اوبویلیون ویندوز لود نمیشه ماکروسافت استور باز نمی کنه نسخه نهایی ویندوز چه زمانی منتشر میشه ؟

**Comment by javad490** [comment]
https://github.com/bepass-org/oblivion-desktop/issues/37#issuecomment-2094795896

**Comment by javad490** [comment]
👇پروکسی کردن سیستم ویندوز بدون نیاز به تنظیم پروکسی مجدد داخل فایرفاکس ، کروم و....
https://github.com/bepass-org/oblivion-desktop/issues/37#issuecomment-2094795896

**Comment by Majidzam1101** [comment]
> 👇پروکسی کردن سیستم ویندوز بدون نیاز به تنظیم پروکسی مجدد داخل فایرفاکس ، کروم و.... [#37 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/37#issuecomment-2094795896)

سلام این روش امتحان کردم جواب نداد

**Comment by javad490** [comment]
داخل ip پروکسی ویندوز اینطوری وارد کن و تست کن:

http://socks=127.0.0.1

**Comment by Paaayman** [comment]
> داخل ip پروکسی ویندوز اینطوری وارد کن و تست کن:
> 
> http://socks=127.0.0.1

این روش توی حالت سایفون جواب نمیده

**Comment by johhny1898** [comment]
دوستانی که با اوبلیون نسخه ویندوز با سایفون مشکل دارن و براشون وصل نمیشه از این ترفند استفاده کنن تا اشکالاتش بر طرف بشه

راه حل:
تو قسمت پراکسی سیستم /قسمت ادرس socks=127.0.0.1 باید وارد بشه تا وصل بشه و کل سیستم تانل میشه
با تغیر کشور باید مراحلو از اول برین

کلیپ اموزشو آپ کردم



https://github.com/bepass-org/oblivion-desktop/assets/134100252/61e80e63-1a32-4145-b625-de9ece327fe9

**Comment by Wnb369** [comment]
سلام ممنون از زحماتی که برای دسترسی آزاد به اینترنت میکشید اگر امکانش وجود داره گزینه Clear system proxy رو به برنامه اضافه کنید تا کل سیستم پروکسی نشه، اگر تنظیماتی برای این مورد وجود داره ممنون میشم راهنمایی کنید تشکر🌱

**Comment by ircfspace** [comment]
سلام

گزینه تنظیم‌شدن اختیاری پروکسی سیستم در تنظیمات برنامه قرار گرفت
یک سری از مشکلات هم حل شدن

این تغییرات بزودی در دسترس قرار میگیرن

**Comment by Majidzam1101** [comment]
> سلام
> 
> گزینه تنظیم‌شدن اختیاری پروکسی سیستم در تنظیمات برنامه قرار گرفت یک سری از مشکلات هم حل شدن
> 
> این تغییرات بزودی در دسترس قرار میگیرن
سلام دوست عزیز نسخه جدید 0.2.52 واقعا گند زدید به برنامه حتی حالت گول وصل نمیشه نه سایفون افتضاحه  خطای اعبترسنجی میزنه روی حالت گول روی دریافت اطلاعات می ماند گند زدید به برنامه نسخه 0.252 افتضاحه امروز منتشر کرد مشکل تونل کردن کل سیستم همچنان دارد سایفون وصل نمیشه گول هم وصل نمیشه واقعا برای سازنده برنامه متاسفم 

![Screenshot (18)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/f9d0a602-5897-4ac3-8df8-29e4eb0a6f1a)

![Screenshot (17)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/497fc72e-b630-4a66-adcc-83c795dd9342)
![Screenshot (15)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/78a415b5-c65b-4b3d-a58a-a3196a21ebed)
![Screenshot (15)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/b4399589-e429-4a98-8170-197a9643ca66)
