### ISSUE TITLE
a javascript error occurred in the main process

### ISSUE THREAD

**Issue by pooyamoosa** [bepass-org/oblivion-desktop#291]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

a javascript error occurred in the main process

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

a javascript error occurred in the main process

### Relevant log output | لاگ برنامه

```shell
a javascript error occurred in the main process
```

**Comment by kiomarzsss** [comment]
please provide a screenshot of the error modal

**Comment by ircfspace** [comment]
احتمالا آنتی‌ویروس به اشتباه فایل warp-plus رو حذف کرده.
برنامه رو مجددا دانلود کنید
