### ISSUE TITLE
نحوه راه اندازی تقسیم، استفاده از شبکه محلی به صورت محلی و استفاده از شبکه خارجی در خارج از کشور

### ISSUE THREAD

**Issue by jonerey** [bepass-org/oblivion-desktop#294]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

قادر به استفاده از پراکسی سیستم من دسترسی محلی و ملی, شبکه و نمی تواند باز کردن صفحه وب. این نرم افزار است که هنوز هم یک جهانی پروکسی. باید چه کار کنم ؟

### Relevant log output | لاگ برنامه

```shell
من از نرم افزار استفاده می کنم و نمی دانم کجا به گزارش ها نگاه کنم.
```

**Comment by ircfspace** [comment]
Unfortunately, I couldn't understand the inaccurate translation of your message in Farsi. 
Please send your message in English
