### ISSUE TITLE
Warp in Warp feature is not work

### ISSUE THREAD

**Issue by HaroldArpanet** [bepass-org/oblivion-desktop#3]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

# Warp in Warp
- Warp in Warp is not working when i activate it already have one layer warp.
(Platform: Gnu/Linux Debian Based) 

### Minimal Reproducible Example (MRE)

1. Settings
2. Warp in Warp feature

### Version

v0.2.29-beta

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by HaroldArpanet** [comment]
# Update
- When i build project this feature is ok but in development mode is not

**Comment by kiomarzsss** [comment]
thank you for you contribution.

warp in warp should work.
i think the issue you faced was due the problem that default warp-plus settings(flags) were not getting passed to warp-plus binary. try to enable and disable warp in warp by hand and it should work on dev and prod.

also [the bug](https://github.com/orgs/bepass-org/projects/4?pane=issue&itemId=61864933) is under development to get fixed.

please let me now the result of you test

**Comment by ircfspace** [comment]
@HaroldArpanet 
Oblivion Desktop v0.2.44-beta is now out!

**Comment by Majidzam1101** [comment]
> @HaroldArpanet Oblivion Desktop v0.2.44-beta is now out!
ببخشید کانال زیر بر علیه برنامه شما مطلب نوشته که برنامه شما ناامن است ایا حقیقت داره گفته سازنده اوبویلیون فیک است 
https://t.me/PewezaVPN

**Comment by ircfspace** [comment]
مطلبی ندیدم، اما قبلن توضیح داده شد :

> این‌برنامه به‌صورت متن‌باز، تحت یک‌لایسنس محدود ارائه شده و بیلد اون به‌صورت اتوماتیک توسط گیت‌هاب اکشن صورت می‌گیره. نتایج بررسی در virusTotal هم فاقد هرگونه مشکل بوده و امکان بررسی کد توسط افراد متخصص وجود داره.
