### ISSUE TITLE
با زدن x برنامه کلا خارج میشه

### ISSUE THREAD

**Issue by iHMahmoodi** [bepass-org/oblivion-desktop#30]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
اول خسته نباشید بچه ها
2 تا مشکل دیدم
1- برنامه رو که کلوز میکنی، کلا خارج میشه، بهتره که بره داخل tray ویندوز و یا تنظیمات براش قرار بدید که با اولین کلوز پیام بده که میخواد کلا بسته بشه یا همیشه بره داخل tray
2- آیکان برنامه در tray وضعیت connect یا desconnect رو نشون بده مثلا دیسکانت سفید یا خاکستری باشه و کانکت همون نارنجی خودش
3- اگر قابلیت white list یا split رو هم در آپدیت های بعدی اضافه کنید عالیه یا اینکه آیپی های که داخل ایران هستن مثل بقیه برنامه ها v2ray و ... خودش اتوماتیک bypass کنه

مرسی ازتون
همه چی عالیه

### Minimal Reproducible Example (MRE)

1- click on close button >> close the entire app
2- it's better to show a meassge and let user to choose between minize or closing the app

### Version

2.44 beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از پیشنهاداتتون،

1. اگر در تنظیمات برنامه گزینه systemTray رو فعال کنین، در حالت مینیمایز به کنار ساعت میره
2. در تسک‌های تعریف‌شده هست
3. در تسک‌های تعریف‌شده و درحال رسیدگی هست

**Comment by iHMahmoodi** [comment]
مرسی ازتون

اون پیشنهادی که گفتم با زدن ضربدر یک پیام به کاربر نشون بده که میخواد کامل بسته بشه یا مینیمایز رو به نظرم بگذارید داخل لیستتون و یک چک باکس هم زیرش بگذارید که "این گزینه رو همیشه به خاطر بسپار"

در واقع کاربران چون با انواع مختلف فیلترشکن کار کردن و مدل ذهنیشون اینه که با ضربدر فیلترشکن بسته نمیشه، همه میزنن روی اون و میبینن فیلترشکن قطع شده
نمونه اش مثلا Windscribe هست که با ضربدر دقیقا قیلترشکن رو قطع میکنه و حتما باید بری در تنظیمات تغییرش بدی خودت
ولی این پیام اولیه به نظرم UX بهتری رو به کاربر ارائه میده 

( هرچند من اون گزینه رو هم اول در تنظیمات دیدم، ولی به نظر متن فارسی اون خوب نیست(انگلیسی قطعا مشخص و خوبه اگر باشه)، می تونید متن رو به این تغییر بدید "کوچک کردن برنامه در کنار ساعت"

اگر وقت کردم یک UI خوب با تجربه بهتر رو براش دیزاین میکنم و عکسش رو اینجا قرار میدم براتون (یا دسترسی به فایل فیگماش اگر بخواید استفاده کنید)

**Comment by ircfspace** [comment]
تشکر از شما،
نسخه بتا هست و اینقد ایرادات و پیشنهادات زیاده که به مرور باید بهشون رسیدگی کنیم

**Comment by ircfspace** [comment]
سلام
تغییرات درخواستی اعمال شد و در آپدیت بعدی در دسترس قرار میگیره
