### ISSUE TITLE
can't closing app in MacOS

### ISSUE THREAD

**Issue by ZhiaDev** [bepass-org/oblivion-desktop#305]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

In Mac, you can't close the app with the  `Command + Q`

### Relevant log output | لاگ برنامه

```shell
nothing
```

**Comment by waitingyou** [comment]
Me too... 
Oblivion Desktop can not connect to server in China, and cannot quit app
