### ISSUE TITLE
کارنکردن برنامه ی ویندوزی و اندروید در مبین نت  از امروز

### ISSUE THREAD

**Issue by alijason72** [bepass-org/oblivion-desktop#306]
### Feature description | توضیحات ویژگی

کار نمی ده این نه در ویندوز نه در اندروید در مبین نت همیشه کار می کرد احتمالا بلاک شده ولی کماکان در ایرانسل کار می کنه

**Comment by alijason72** [comment]
چرا ورژن 0.20 اضافه نشده داخل assets لطفا اضافه کنینش با تشکر

**Comment by ircfspace** [comment]
سلام

این‌مورد رو تست کنین :‌ https://github.com/bepass-org/oblivion-desktop/issues/280#issuecomment-2146222913

آپدیت جدید بعد از تست در دسترس عموم قرار میگیره
