### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by ea1370** [bepass-org/oblivion-desktop#308]
### Feature description | توضیحات ویژگی

با درود. سپاس بی کران بابت ایجاد چنین پروژه خفنی. خواستم بدونم آیا نسخه CLI هم برای لینوکس خواهد داشت، مثل hiddify؟

**Comment by xiaolan610** [comment]
你想多了...

**Comment by ircfspace** [comment]
سلام

این ریپازیتوری رو مشاهده کردین؟ https://github.com/bepass-org/warp-plus
