### ISSUE TITLE
可以尝试支持一下ZeroTrust/Add ZeroTrust support

### ISSUE THREAD

**Issue by xiaolan610** [bepass-org/oblivion-desktop#309]
### Feature description | توضیحات ویژگی

可以尝试支持一下ZeroTrust/Add ZeroTrust support

**Comment by ircfspace** [comment]
thanking you for your suggestion,
the oblivion desktop application is a GUI for warp-plus, and to add features such as ZeroTrust, you need to create an issue at the following address:
https://github.com/bepass-org/warp-plus
