### ISSUE TITLE
Logs scrolling

### ISSUE THREAD

**Issue by Anonyms-david83** [bepass-org/oblivion-desktop#313]
### Feature description | توضیحات ویژگی

in logs page , it dosn't auto scroll the logs . the client should scroll down to see the lastest logs

**Comment by ircfspace** [comment]
You can click on the play icon to activate auto-scroll mode

![image](https://github.com/bepass-org/oblivion-desktop/assets/128790947/8a701786-58a3-4a26-9090-aba3c45c9474)

**Comment by Anonyms-david83** [comment]
ok ! i missed that one !
