### ISSUE TITLE
مشکل در نحوه استفاده از حالت TUN توسط V2rayN

### ISSUE THREAD

**Issue by S1ipKn0T** [bepass-org/oblivion-desktop#314]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

من تمام مراحل رو با توجه به ویکی شما پیش بردم ولی متاسفانه به ارور میخورم برای وصل کردن TUN که در لاگ مشاهده می کنید.

### Relevant log output | لاگ برنامه

```shell
[Socks] OblivionDesktop(127***1:8086)
Microsoft Windows NT 10.0.19045.0 - 64
Start service (2024/06/09 01:43:26)...

2024/06/09 01:43:27 System proxy setting is changedForcedChange
2024/06/09 01:43:30 The ping of current service: 423 ms
Microsoft Windows NT 10.0.19045.0 - 64
Start service (2024/06/09 01:43:42)...
Tun mode restart the core once
FATAL[0001] start service: initialize inbound/tun[tun-in]: configure tun interface: set ipv6 address: Element not found.
```

**Comment by ircfspace** [comment]
برنامه + هسته سینگ‌باکس رو بروز کردین؟

**Comment by S1ipKn0T** [comment]
> برنامه + هسته سینگ‌باکس رو بروز کردین؟

بله دونه دونه آپدیت کردم!

**Comment by kiomarzsss** [comment]
@S1ipKn0T 
این رو امتحان کنید https://github.com/bepass-org/oblivion-desktop/wiki/%D8%AA%D8%A7%D9%86%D9%84-%DA%A9%D8%B1%D8%AF%D9%86-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-%D8%A8%D8%A7-%D9%86%DA%A9%D9%88%D8%B1%DB%8C

**Comment by S1ipKn0T** [comment]
> @S1ipKn0T این رو امتحان کنید https://github.com/bepass-org/oblivion-desktop/wiki/%D8%AA%D8%A7%D9%86%D9%84-%DA%A9%D8%B1%D8%AF%D9%86-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-%D8%A8%D8%A7-%D9%86%DA%A9%D9%88%D8%B1%DB%8C

با استفاده از این راه درست شد ولی برای بعضی برنامه ها باز به یک اروری میخورم! ارور هاشون شبیه به هم هست!
`2024/06/11 13:41:33 [Warning] [290772288] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:2081->127.0.0.1:4055: wsasend: An existing connection was forcibly closed by the remote host.
2024/06/11 13:41:33 [Warning] [2150538690] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:2081->127.0.0.1:4056: wsasend: An existing connection was forcibly closed by the remote host.`

**Comment by ircfspace** [comment]
متاسفانه در رابطه با خطای برنامه‌های جانبی کمکی از دستمون ساخته نیست

راه‌حل اضافه‌کردن ویژگی TUN هستی که @kiomarzsss مشغول کار روی اونه، ولی مشخص نیست چه‌زمانی آماده بشه
