### ISSUE TITLE
مشکل دانلود با oblivion-desktop

### ISSUE THREAD

**Issue by hamid3pnn** [bepass-org/oblivion-desktop#317]
### Feature description | توضیحات ویژگی

سلام متاسفانه با این برنامه برخلاف vpn های دیگه ، نمیشه از یوتیوب با idm دانلود کرد و کلا دانلود idm کار نمیکنه و ارور میده

**Comment by ircfspace** [comment]
سلام
اگر از طریق متدهای گول و سایفون به نتیجه نرسیدین، این‌موضوع رو لطفن در [warp-plus](https://github.com/bepass-org/warp-plus/issues) مطرح کنین
