### ISSUE TITLE
درخواست قرار دادن سایتهای ایران درrule

### ISSUE THREAD

**Issue by B3MH** [bepass-org/oblivion-desktop#318]
### Feature description | توضیحات ویژگی

![Screenshot 2024-06-10 191830](https://github.com/bepass-org/oblivion-desktop/assets/128364397/bb136aa6-6025-45de-985a-9bf98ef80e8e)
در نرم افزار مشابه چینی geph خودش به صورت پیش فرض bypass سایتهای چینی رو داره و فقط کافیه فعالش کنیم
اگر مشابهش در اپ oblivion اضافه بشه واقعا خوب میشه
(البته امیدوارم اون عکسی که گذاشتم همین مفهوم رو برسونه)
کلا خودتون بصورت پیش فرض میتونید روی اپ oblivion این قانون رو بزارید تا کمتر احتیاج به اضافه کردن به لیست باشه
امیدوارم تونسته باشم منظورم رو رسونده باشم
با تشکر

**Comment by ircfspace** [comment]
سلام
برای این‌منظور میتونین به تنظیمات شبکه » لیست سیاه رفته و بر روی باتن نمونه کلیک کنید

توضیحات بیشتر:
https://github.com/bepass-org/oblivion-desktop/wiki/%D9%86%D8%AD%D9%88%D9%87-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-Routing-Rules
