### ISSUE TITLE
مشکل نمایش ای پی

### ISSUE THREAD

**Issue by ErNader** [bepass-org/oblivion-desktop#32]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

بیشتر اوقات آی پی قبل از اتصال را نشان میدهد و باید بروزرسانی کرد تا ای پی متصل شده را نشان دهد

### Minimal Reproducible Example (MRE)

در صفحه اصلی متصل به حالت گول

### Version

0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
بله، این‌مشکل هست و سعی میکنیم به زودی برطرفش کنیم

**Comment by ircfspace** [comment]
مشکل برطرف شده و تغییرات در آپدیت بعدی در دسترس قرار میگیره
