### ISSUE TITLE
خطا جاوا در ویندوز هنگام اتصال

### ISSUE THREAD

**Issue by freedomOfIR** [bepass-org/oblivion-desktop#33]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درود بر شما
این خطا زیر هنگام اتصال داده میشه 
لطفا بررسی کنید
تشکر

![Untitled](https://github.com/bepass-org/oblivion-desktop/assets/168939491/5d5ef715-ca0a-4771-8dd8-1076aa8d2558)

### Minimal Reproducible Example (MRE)

when click connection

### Version

0.2.44

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by javad490** [comment]
جدیدترین ورژن java runtime  را دانلود و نصب کن تا جاوا روی سیستم آپدیت بشه

**Comment by ircfspace** [comment]
روی سیستمتون به طور پیشفرض powershell نصب نیست؟

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#installing-the-msi-package

**Comment by ircfspace** [comment]
در نسخه بتای ۲ (که بزودی منتشر میشه) اگر Powershell روی سیستم نصب نباشه هشدار داده میشه

**Comment by rostamzad1900** [comment]
آخرین نسخه پاور شل طبق لینکی که گذاشتید نصب شده ولی همچنان ارور میده
![image](https://github.com/bepass-org/oblivion-desktop/assets/89634871/72e2a288-38ac-41e8-be85-2f3ee84c25eb)

**Comment by ircfspace** [comment]
بعد از نمایش این خطا فرایند اتصال لغو میشه یا نه، متصل هم میشه؟

**Comment by rostamzad1900** [comment]
"در حال اتصال" باقی می ماند ولی متصل نمیشود.
![image](https://github.com/bepass-org/oblivion-desktop/assets/89634871/dcba1602-8c31-4815-ba89-295fd4205179)

**Comment by ircfspace** [comment]
یک دور برنامه رو بسته و مجددا باز کنین؛ ببینین بازم خطای پاورشل میگیرین؟

**Comment by amirhz** [comment]
بله انواع و اقسام پاور شل اعم x86 x64 نصب شد ولی همچنان خطای پاورشل نمایش داده میشه

**Comment by rostamzad1900** [comment]
پس از بستن و باز کردن دوباره برنامه، هنگام اتصال پیام اخطار پاورشل دوباره نشون داده میشه و تفاوتی حاصل نشد

**Comment by amirhz** [comment]
خطا همچنان وجود داره و باز و بسته کردن برنامه نیز برطرف نمیشه، جالبه روی چند تا کلایت تست شده و مشکلی نداره ولی برروی برخی کلاینت ها این پیام نمایش داده میشه

**Comment by amirhz** [comment]
با نصب نسخه جدید مشکل برطرف شد

**Comment by rostamzad1900** [comment]
با نصب نسخه 0.4.5-beta مشکل حل شد.
ممنون و خسته نباشید
