### ISSUE TITLE
موندن تو حالت دریافت اطلاعات

### ISSUE THREAD

**Issue by coldwater-10** [bepass-org/oblivion-desktop#334]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

نسخه ویندوز به خوبی کار میکنه ولی تو حالت دریافت اطلاعات ... میمونه

### Relevant log output | لاگ برنامه

```shell
خواستم لاگ بفرستم ارور ماکسیموم کارکتر داد
```

**Comment by ircfspace** [comment]
سلام
تغییر جزئی در API کلودفلر پیش اومده که باعث این‌مشکل شده. این‌مورد رو فیکس کردیم ولی باید تا ریلیز آپدیت بعدی منتظر بمونین.
