### ISSUE TITLE
in exclude part , [range: & ip:] arent working

### ISSUE THREAD

**Issue by rti2** [bepass-org/oblivion-desktop#335]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

When I want exclude an ip range (e.g:_192.168.1.*_) , it wont add :| I click ok but it's not appllying . 
(after i couldn't exclude iprange i tried excluding ip (e.g:_ip192.168.1.1_) again the same happend )
None of the _ip:_ and _range_ worked but all the other rules (domain,geoip)
It would be great if you exclude local network by default (192.168.1.*)
Thank you for oblivion it's working PERFECT :D

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

In settings , Network , exclude

### Relevant log output | لاگ برنامه

```shell
No change in log (log is just showing connection info nothing related t othis issue)
```

**Comment by ircfspace** [comment]
Hi. Are you experiencing this issue with the Psiphon connection method?
We have fixed it, and it will be included in the next update.
However, there should not be any issues with the Gool method right now.

**Comment by rti2** [comment]
No it was with gool and normal warp . The problem is solved in the new version. Thanks a lot.
(I faced that issue because I set configuration to "None" , thats not possible in new version to have blacklist and "None" )
