### ISSUE TITLE
Not start on ubuntu 24.04

### ISSUE THREAD

**Issue by papampi** [bepass-org/oblivion-desktop#338]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Not starts ... 

### Relevant log output | لاگ برنامه

```shell
Run from command:
#:oblivion-desktop 
LaunchProcess: failed to execvp:
/opt/Oblivion
[1530804:0617/201335.815066:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
```

**Comment by omidmousavi** [comment]
I encountered this problem too :(

**Comment by kiomarzsss** [comment]
checkout: https://github.com/bepass-org/oblivion-desktop/wiki/LaunchProcess:-failed-to-execvp(Ubuntu-24.04)

**Comment by omidmousavi** [comment]
> checkout: https://github.com/bepass-org/oblivion-desktop/wiki/LaunchProcess:-failed-to-execvp(Ubuntu-24.04)

Thank you very much🙏🏻
Solved and it works now ❤️🥹

**Comment by kiomarzsss** [comment]
> > checkout: https://github.com/bepass-org/oblivion-desktop/wiki/LaunchProcess:-failed-to-execvp(Ubuntu-24.04)
> 
> Thank you very much🙏🏻 Solved and it works now ❤️🥹

happy it helped ✌️
