### ISSUE TITLE
تنظیمات پروکسی

### ISSUE THREAD

**Issue by mostafavahdanideh** [bepass-org/oblivion-desktop#34]
### Feature description

سلام، لطفا تنظیمات پروکسی مود رو فعال کنین و مواردی مثل آدرس هاست و پروتکلش رو در دسترس قرار بدین الان فقط پورت اتصال برنامه معلومه و تا جایی که فهمیدم تنظیمات پروکسی اَپ الان روی:

Host : 127.0.0.1
Port : 8086
Protocol : SOCKS5

هستش.

**Comment by ircfspace** [comment]
سلام

تنظیمات پروکسی‌شدن سیستم رو در آپدیت‌های بعدی اضافه میکنیم

البته امکان تغییر هاست و پروتکل در warp-plus تعریف نشده:
https://github.com/bepass-org/warp-plus
