### ISSUE TITLE
Support virtual network adapter

### ISSUE THREAD

**Issue by adasdasfdvsd** [bepass-org/oblivion-desktop#342]
### Feature description | توضیحات ویژگی

سلام
در بعضی از نرم افزار ها مثل Android Studio متصل شدن به proxy سخت هستش. برنامه های vpn دیگر که این مشکل را حل کرده اند و این مشکل را ندارن مثل OpenVPN بعد متصل شدن به سرور, یک virtual network adapter در ویندوز ایجاد میکنند و از ان برای متصل شدن استفاده میکنن. من پیشنهاد میکنم بجای استفاده از proxy از virtual network adapter هم بشود استفاده کرد.
ممنون

**Comment by ircfspace** [comment]
سلام
لطفا مطالعه کنین: https://github.com/bepass-org/oblivion-desktop/issues/327#issuecomment-2164853674

**Comment by adasdasfdvsd** [comment]
> سلام لطفا مطالعه کنین: [#327 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/327#issuecomment-2164853674)

یعنی اگر TUN اکی بشه خودکار یک virtual network adapter میسازه ؟

**Comment by adasdasfdvsd** [comment]
![image](https://github.com/bepass-org/oblivion-desktop/assets/173128442/9da71f73-a30e-4772-ab70-5c7c49c36393)

بله مثل اینکه یک virtual network adapter میسازد با nekoray و  توی اندروید استدیو مشکل حل شد ولی بهتره یکیشون کنید که با یک برنامه وصل بشیم در کل عالیه خسته نباشید
