### ISSUE TITLE
قابلیت آپدیت 

### ISSUE THREAD

**Issue by mehran7400** [bepass-org/oblivion-desktop#347]
### Feature description | توضیحات ویژگی

سلام
تشکر از هر کسی که در توسعه این برنامه کمکی میکنه
خواستم امکان اضافه کردن قابلیت آپدیت برنامه از طریق خود برنامه رو اضافه کنید
ممنون

**Comment by ircfspace** [comment]
سلام

برای این‌مورد قبلا [تسک ایجاد شده](https://github.com/orgs/bepass-org/projects/4/views/1?pane=issue&itemId=61731720) و در آینده بهش رسیدگی میکنیم

**Comment by ircfspace** [comment]
خود الکترون (که Oblivion Desktop با اون نوشته‌شده) یه قابلیت آپدیت داخلی داره که قصد فعالسازی اونو داریم
درصورتی‌که کاربر مجوز بروزرسانی هم نده، این‌اقدام رو انجام نمیده
