### ISSUE TITLE
اضافه شدن قابلیت whitelist/blacklist برنامه یا EXE

### ISSUE THREAD

**Issue by ExSgt3779** [bepass-org/oblivion-desktop#349]
### Feature description | توضیحات ویژگی

کسی مثل من کلا میخواد فقط discord رو باز کنه ولی نمیخواد همه چیز روی سیستم تونل شه این قابلیت حیاتیه واقعا. ممنون میشم اگه توی اپدیت های بعدی قرارش بدید. قابلیت WarpInWarp هم فوق العاده هست واقعا همین که ارور بلوک کلودفلر رو هیچ سایتی نمیده و روی نت های همراه به راحتی وصل میشه واقعا جای تشکر داره. قوی ادامه بدید.

**Comment by ircfspace** [comment]
سلام
متاسفانه تا زمانی که ویژگی TUN اضافه‌نشده نمیتونیم سراغ این‌مورد بریم، ولی تسکشو توی بک‌لاگ میذارم که بعدن رسیدگی بشه
