### ISSUE TITLE
اتصال از طریق ترمینال در لینوکس بدون داشتن GUI

### ISSUE THREAD

**Issue by p0mad** [bepass-org/oblivion-desktop#351]
### Feature description | توضیحات ویژگی

سلام
خیلی خوب میشه اگر بتونیم بدون نیاز به رابط گرافیکی داخل اوبونتو از oblivion استفاده کرد!
کانفیگ فایل داشته باشه که بشه تنظیمات رو از همون طریق انجام داد

در واقع بتونیم داخل Ubuntu Server از oblivion استفاده کرد!

**Comment by ircfspace** [comment]
سلام
برنامه Oblivion Desktop یک GUI برای Warp-plus هست.
برای موردی که مدنظرتونه باید سراغ [Warp-plus](https://github.com/bepass-org/warp-plus) برید.
