### ISSUE TITLE
فایل اجرایی شما ویروسی است 

### ISSUE THREAD

**Issue by hossyavr9** [bepass-org/oblivion-desktop#352]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

فایل اجرایی شما ویروسی است 

### Relevant log output | لاگ برنامه

```shell
فایل اجرایی شما ویروسی است
```

**Comment by ircfspace** [comment]
سلام
مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/232#issuecomment-2136708386
