### ISSUE TITLE
Oblivion Desktop Application Won't Close on MacBook

### ISSUE THREAD

**Issue by 0xCuttingEdge** [bepass-org/oblivion-desktop#353]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

بعد از نصب نسخه ۰.۲۳.۱۵ و باز کردن اپلیکیشن دیگه اپلیکیشن بسته نمیشه! حتی با Force Quit حتی دیگه سیستم ریاستارت نمیتونه بشه و ارور میده که این اپلیکین رو نمیتونه ببنده!
![CleanShot 2024-06-19 at 11 51 57@2x](https://github.com/bepass-org/oblivion-desktop/assets/81967091/0ae15db5-6079-4d56-97ef-60804efb5e9d)
Your Mac hasn't restarted because "Oblivion Desktop" failed to quit. To continue restarting, quit "Oblivion Desktop".

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Open the Oblivion Desktop application on a MacBook.
2. Attempt to close the application using the standard methods (clicking the close button, selecting Quit.).
3. Try to restart the MacBook.

### Relevant log output | لاگ برنامه

```shell
-
```

**Comment by ircfspace** [comment]
این‌مورد توسط @gdariushahmadi عزیز بررسی میشه

**Comment by ircfspace** [comment]
این‌مورد توسط @gdariushahmadi برطرف شده و در آپدیت بعدی در دسترس قرار میگیره

**Comment by 0xCuttingEdge** [comment]
اگه امکانش هست بگین طریقه گرفتن لاگ این رنامه در MacOS به چه صورتی هستش؟
