### ISSUE TITLE
مشکل آسیب دیدگی در اپلیکیشن و حذف اجباری

### ISSUE THREAD

**Issue by behrooznmr** [bepass-org/oblivion-desktop#356]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی روی مک این اپ رو نصب میکنم موقع باز کردن چنین پیغامی رو میبینم
چطوری باید رفع بشه؟
![2024-06-20_09-59](https://github.com/bepass-org/oblivion-desktop/assets/90711773/e00b272d-42eb-449a-af42-35b680a2fcf0)

### Relevant log output | لاگ برنامه

```shell
لاگی نداره
```

**Comment by ircfspace** [comment]
سلام
لطفا مطالعه کنین : https://github.com/bepass-org/oblivion-desktop/issues/206
