### ISSUE TITLE
اخطار ویروس وراهکار حل مشکل

### ISSUE THREAD

**Issue by hossyavr9** [bepass-org/oblivion-desktop#357]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

 اخطار ویروس وراهکار حل مشکل  

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

اخطلار ویروس روی برنامه نصب هست . روی فایل اصلی نیست . فایل فشرده که حالت پرتابل دارد مشکلی ندارد . پیشنهاد میشود مشکل setup file  برطرف شود . یا  انکه دوستان استفاده کننده فایل فشرده را در جای قبلی نصب از حالت فشرد خارج و جایگزین فایلهای قبلی کنند . من اینکار را کردم و اکی شد .

### Relevant log output | لاگ برنامه

```shell

```

**Comment by kiomarzsss** [comment]
جالبه 🤔.
باید دید چرا آنتی ویروس ها وقتی پروسه توسط اسکریپت اجرا میشه ویروس تشخیص میدن ولی اگه همون پروسه توسط خود کاربر اجرا بشه مشکلی باهاش ندارن.

**Comment by Bernar0d** [comment]
![image](https://github.com/bepass-org/oblivion-desktop/assets/95563850/3742618b-805a-48c3-86fa-8f52ea3148b4)
سلام این خطاهایی که این سایت میده هم به همین مربوطه؟
https://www.virustotal.com/gui/file/da19ce4caac0602caa00ced9ff3354528d0296b22386fd55e4169f66ad3f82f7

**Comment by b3hzad1** [comment]
آنتی ویروس AVG هم به پیغام تروجان رو میده. البته فایل اصلی oblivion مشکلی نداره بلکه warp-plus رو بعنوان تروجان تشخیص میده. اسکرین شات رو هم قرار دادم.

![avg](https://github.com/bepass-org/oblivion-desktop/assets/12196334/50bc7170-e7a4-4309-aa11-169f4adb2c2d)

**Comment by ircfspace** [comment]
مشکل به خاطر اضافه شدن ویژگی TUN به هسته هست (که به طور آزمایشی اضافه شده)
توسعه دهندگان Warp-Plus پیگیر رفع مشکل هستند
