### ISSUE TITLE
مشکل وصل بودن نرم افزار ولی عدم دانلود بازی های epic

### ISSUE THREAD

**Issue by B3MH** [bepass-org/oblivion-desktop#359]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام بابت پیگیری و آپدیت oblivion واقعا ممنونم
یکم عجیبه که oblivion متصل هستش، یوتیوب به بهترین شکل باز میشه ولی نمیتونم از epic games بازی دانلود کنم، یکجورایی تحریم epic هنوز پابرجا میمونه
اگر میشه خودتون هم یک تستی کنید تا ببینید
با تشکر

### Relevant log output | لاگ برنامه

```shell
time=2024-06-20T17:53:15.447+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:6087: i/o timeout" subsystem=vtun
```

**Comment by ircfspace** [comment]
سلام
منظورتون سایت store.epicgames.com هست؟
اگر آره، من توسط متد گول (با آیپی آلمان) میتونم بازش کنم

**Comment by B3MH** [comment]
دوباره سلام
منظورم فقط باز کردن سایتش نیست
اگر لانچر epic رو دانلود کنید
و بخواید یک بازی خریداری شده، یا رایگان دانلود کنید، دانلودی انجام نمیشه
خود لانچر هم اگر فیلتر شکن فعال نباشه باز هم نمیشه
بازم میگم oblivion وصله، یوتیوب و خود لانجر epic بالا میاد، حتی از یوتیوب دانلودم میتونم بکنم
ولی متاسفانه بازی های epic رو دانلود نمیکنه
میخواستم اول براتوت رکورد از سیستم بزارم که یک مشکلی پیش اومد و نشد
ولی اگر بخواین فردا انجامش میدم

**Comment by ircfspace** [comment]
موردی که اشاره دارین با استفاده از ویژگی TUN حل میشه
فعلن باید از برنامه‌های جانبی نظیر [v2rayN](https://github.com/bepass-org/oblivion-desktop/wiki/%D9%86%D8%AD%D9%88%D9%87-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%AD%D8%A7%D9%84%D8%AA-TUN-%D8%AA%D9%88%D8%B3%D8%B7-V2rayN) یا [نکوری](https://github.com/bepass-org/oblivion-desktop/wiki/%D8%AA%D8%A7%D9%86%D9%84-%DA%A9%D8%B1%D8%AF%D9%86-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-%D8%A8%D8%A7-%D9%86%DA%A9%D9%88%D8%B1%DB%8C) کمک بگیرید
