### ISSUE TITLE
مشکل در نصب در اوبونتو

### ISSUE THREAD

**Issue by Mahyar88** [bepass-org/oblivion-desktop#365]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام در نصب مشکل دارد :

(Reading database ... 210228 files and directories currently installed.)
Preparing to unpack oblivion.deb ...
Unpacking oblivion-desktop (0.23.15~beta) ...
dpkg: error processing archive oblivion.deb (--install):
 error creating hard link './usr/share/icons/hicolor/512x512/apps/oblivion-desktop.png': Invalid cross-device link
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 oblivion.deb

### Relevant log output | لاگ برنامه

```shell
سلام در نصب مشکل دارد :

(Reading database ... 210228 files and directories currently installed.)
Preparing to unpack oblivion.deb ...
Unpacking oblivion-desktop (0.23.15~beta) ...
dpkg: error processing archive oblivion.deb (--install):
 error creating hard link './usr/share/icons/hicolor/512x512/apps/oblivion-desktop.png': Invalid cross-device link
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 oblivion.deb
```

**Comment by kiomarzsss** [comment]
برای نصب از چه دستوری استفاده کردین؟

**Comment by abs110110** [comment]
سلام 
من از دستور dpkg -i استفاده کردم نصب میشه اما وقتی باز میکنم error میده و ران نمیشه

**Comment by kiomarzsss** [comment]
لطفا خروجی دستور زیر +‌ اینکه بعد از نصب موقع تلاش برای اجرای برنامه چه اروری میده رو بفرستین:

```sh
uname -a
```

**Comment by saeedhasanpoorniary** [comment]
سلام من نصب کردم ولی هنگام اجرا این خطا رو می ده (عکس ارور رو گرفتم ضمیمه کردم) لطفا کمکم کنید تشکر
![Uploading ۲۰۲۴۰۸۰۲_۱۷۰۵۵۵.jpg…]()

**Comment by ELIAWrecker** [comment]
oblivion desktop
LaunchProcess: failed to execvp:
/opt/Oblivion
[15840:0803/105440.497912:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
[1]    15840 trace trap (core dumped)  oblivion-desktop

uname -a
Linux UBU 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
<pre>uname -a
Linux UBU 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux</pre>

**Comment by ELIAWrecker** [comment]
برای منم مشکل داره هم ورژن اخر بتا  تست کردم
[v0.51.0-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.51.0-beta)
هم ورژن اخر رسمی 
[v0.47.0-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.47.0-beta)

در هر دو مورد این ارور میخوره

**Comment by mojitaleghani** [comment]
```
moji@august:~/Downloads$ sudo dpkg --install oblivion-desktop-linux-amd64.deb
(Reading database ... 192371 files and directories currently installed.)
Preparing to unpack oblivion-desktop-linux-amd64.deb ...
Unpacking oblivion-desktop (1.1.0) over (1.1.0) ...
Setting up oblivion-desktop (1.1.0) ...
update-alternatives is /usr/bin/update-alternatives
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
```



```
moji@august:~/Downloads$ oblivion-desktop 
LaunchProcess: failed to execvp:
/opt/Oblivion
[23350:0809/105843.559081:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
moji@august:~/Downloads$ uname -a
Linux august 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
moji@august:~/Downloads$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by kiomarzsss** [comment]
checkout https://github.com/bepass-org/oblivion-desktop/issues/338 for solution.
