### ISSUE TITLE
Warp+ Error

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/oblivion-desktop#368]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با سلام و تشکر فراوان از زحمات شما عزیزان و قهرمانان واقعی 
عزیزان وارپ پلاس کار نمیده چند تا کد وارپ پلاس رو امتحان کردم این ارور رو میدن اخرین نسخه پی سی نت همراه اول
https://i.ibb.co/XL19CRX/image.png

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

.

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by ircfspace** [comment]
سلام
لاگ برنامه رو ارسال کنین
