### ISSUE TITLE
libuuid version error on opensuse

### ISSUE THREAD

**Issue by AbolfazlMoradpour** [bepass-org/oblivion-desktop#369]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام . در هنگام نصب در opensuse با خطا عدم موجودبت libuuid موجه میشویم و این در صورتی است مه در این توزیع به جای libuuid ما libuuid1 داریم و اینگونه به پیش نیاز ها هنگام نصب خطا گرفته میشود.
این خطا با نصب libuuid-develop نیز حل نشد .
سپاس.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. rpm -Uvh obilivion.rpm

### Relevant log output | لاگ برنامه

```shell
Terminal ~> .......
              Nothing provides package libuuid
         ..........
```

**Comment by xONEIROS** [comment]
**یک راه میگم زیاد اکادمیک نیست ولی شاید جواب بده تست کن**

1- اول بیا `libuuid` رو نصب کن : sudo zypper install libuuid

2- بعد یک `Symbolic Link` ایجاد کن به این شکل 
```sudo ln -s /usr/lib64/libuuid.so.1 /usr/lib64/libuuid.so```
**حتما قبلش مسیر هارو چک کن درست باشه** یعنی `find` رو بزن که ادرس کتاب خونه هارو درست پیدا کنی این میشه دستورش :
`find /usr -name "libuuid.so*"`

احتمالا بعدش بتونی بدون دردسر نصبش کنی ، اگر این روش جواب داد برات حتما خبرش رو بده :) مرسی

**Comment by kiomarzsss** [comment]
dear @AbolfazlMoradpour if the @xONEIROS answer fixed your issue please consider closing it. or it will be closed in few days.

**Comment by AbolfazlMoradpour** [comment]
سلام وقت بخیر .
خسته نباشید . ممنون .
ولی مشکل اینجاد بود که اسم بسته در این distro فرق داشت و اسمش ....libuuid-1
بود و من برای حل مشکل بسته رو استخراج کردم و قسمت ها رو جداگونه جای
گذاری کردم و برنامه بدون مشکل کار کرد .
باز هم مننون که پیگیر بودین .
