### ISSUE TITLE
عدم اتصال به تلگرام ، توییتر ، یوتیوپ و .... 

### ISSUE THREAD

**Issue by hosseinkazemi7400** [bepass-org/oblivion-desktop#37]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و درود خدمت سازندگان محترم برنامه ، برنامه متصل می شود ولی  هیچ سایتی را باز نمی کند تمامی حالت های گول و سایفون را هم امتحان کردم نشد حتی از نسخه پرتابل هم  همین مشکل را دارد.  مرورگر مورد استفاده گوگل کروم هست. 

### Minimal Reproducible Example (MRE)

time=2024-05-05T09:30:09.914+03:30 level=INFO

### Version

0.2.44-beta

### Platform/OS

Windows

### Relevant log output

```shell
time=2024-05-05T09:30:09.914+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-05T09:30:09.916+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-05T09:30:09.919+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-05T09:30:12.358+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-05T09:30:12.358+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-05T09:30:12.360+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-05T09:30:13.532+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-05T09:30:19.133+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.96.179 error="read udp 172.19.0.1:60256->188.114.96.179:1387: i/o timeout"

time=2024-05-05T09:30:20.587+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:c642:ac2e:7adc:1bed error="dial udp [2606:4700:d0:0:c642:ac2e:7adc:1bed]:928: connect: A socket operation was attempted to an unreachable network."

time=2024-05-05T09:30:20.588+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:dc5:20c1:2d41:51ab error="dial udp [2606:4700:d1:0:dc5:20c1:2d41:51ab]:1014: connect: A socket operation was attempted to an unreachable network."

time=2024-05-05T09:30:21.549+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.99.231:1180 RTT:155.3006ms CreatedAt:2024-05-05 09:30:20.5855527 +0330 +0330 m=+10.683822101} {AddrPort:162.159.192.149:1014 RTT:177.2195ms CreatedAt:2024-05-05 09:30:20.167754 +0330 +0330 m=+10.266023401}]"
time=2024-05-05T09:30:21.549+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.99.231:1180 162.159.192.149:1014]"
time=2024-05-05T09:30:21.549+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-05T09:30:24.959+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-05T09:30:46.199+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gateway.discord.gg:443

time=2024-05-05T09:30:48.666+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=discord.com:443

time=2024-05-05T09:32:31.524+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-05T09:32:32.145+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cdn.jsdelivr.net:443

time=2024-05-05T09:33:42.158+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=login.live.com:443

time=2024-05-05T09:33:51.534+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=t.kite.com:443

time=2024-05-05T09:34:03.143+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gateway.discord.gg:443

time=2024-05-05T09:34:05.665+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=discord.com:443

time=2024-05-05T09:37:45.854+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=self.events.data.microsoft.com:443

time=2024-05-05T09:38:16.143+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=gateway.discord.gg:443
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by KRU3L** [comment]
درود و احترام
ضمن تشکر از زحمات تک تک عزیزان، احتمالا مشکلی که شما دارید عدم هماهنگی تنظیمات پراکسی مرورگر با Oblivion هست.
از منوی اصلی نرم افزار میتونید تنظیمات پراکسی رو مشاهده کنید که احتمالا بصورت پیشفرض پورت 8086 خواهد بود.
بصورت دستی روی مرورگر یا سیستمتون Proxy اعمال کنید.
آدرس لوکال (127.0.0.1)
پورت هم که طبق برنامه (8086)
یوزر و پسورد خالی بمونه.

**Comment by aenimaa** [comment]
من هم همین مشکل رو داشتم.
یک extension  وی‌پی‌ان روی کروم بود که بعد از غیرفعال کردنش درست شد.
ولی کاش امکان این باشه که جدا کار کنه و تاثیر نداشته باشه
چون بعد از مدتی، وی‌پی‌ان هایی مثل oblivion و یا کانفیگ‌های ‌v2ray قابل تشخصی می‌شن و سایت‌هایی مثل اسپاتیفای یا کلادفلر تشخیص میدن و ردشون می‌کنن. این‌جوری مواقع extensionها کار می‌کنن (من خودم روی v2ray یک Extension کروم فعال می‌کنم) و می‌شه کامل دور زد اونجوری

**Comment by javad490** [comment]
با تنظیم و فعال کردن پروکسی ویندوز اکثر برنامه ها از پروکسی استفاده می کنن که میشه همون پروکسی سیستم . با استفاده از proxifier هم میتونی کل سیستم را تانل کنی
![windows proxy](https://github.com/bepass-org/oblivion-desktop/assets/123890771/42bb9d97-131e-4975-a612-b44676b6bf7c)

**Comment by Majidzam1101** [comment]
> با تنظیم و فعال کردن پروکسی ویندوز اکثر برنامه ها از پروکسی استفاده می کنن که میشه همون پروکسی سیستم . با استفاده از proxifier هم میتونی کل سیستم را تانل کنی ![windows proxy](https://private-user-images.githubusercontent.com/123890771/328018437-42bb9d97-131e-4975-a612-b44676b6bf7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjEzNDQsIm5iZiI6MTcxNDkyMTA0NCwicGF0aCI6Ii8xMjM4OTA3NzEvMzI4MDE4NDM3LTQyYmI5ZDk3LTEzMWUtNDk3NS1hNjEyLWI0NDY3NmI2YmY3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNDU3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDRmMDljZWMxNGY4OWY4NDg4NTAzZmUxNWRhNmUzNzgzYzc1M2FiZTlhMDdjYTBmMmQ4ZjUxZDUzN2FjZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nFJbNcTv4mtnxh1S0p512kWeSClNXZZXYIFBBzJNEAA)

سلام این روش انجام دادم جواب نداد در ویندوز 

![Screenshot (10)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/aa04776b-3112-4b05-9306-2f8ebc00406a)

**Comment by javad490** [comment]
> > با تنظیم و فعال کردن پروکسی ویندوز اکثر برنامه ها از پروکسی استفاده می کنن که میشه همون پروکسی سیستم . با استفاده از proxifier هم میتونی کل سیستم را تانل کنی ![windows proxy](https://private-user-images.githubusercontent.com/123890771/328018437-42bb9d97-131e-4975-a612-b44676b6bf7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjEzNDQsIm5iZiI6MTcxNDkyMTA0NCwicGF0aCI6Ii8xMjM4OTA3NzEvMzI4MDE4NDM3LTQyYmI5ZDk3LTEzMWUtNDk3NS1hNjEyLWI0NDY3NmI2YmY3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNDU3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDRmMDljZWMxNGY4OWY4NDg4NTAzZmUxNWRhNmUzNzgzYzc1M2FiZTlhMDdjYTBmMmQ4ZjUxZDUzN2FjZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nFJbNcTv4mtnxh1S0p512kWeSClNXZZXYIFBBzJNEAA)
> 
> سلام این روش انجام دادم جواب نداد در ویندوز
> 
> ![Screenshot (10)](https://private-user-images.githubusercontent.com/167671244/328027438-aa04776b-3112-4b05-9306-2f8ebc00406a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjQxMTcsIm5iZiI6MTcxNDkyMzgxNywicGF0aCI6Ii8xNjc2NzEyNDQvMzI4MDI3NDM4LWFhMDQ3NzZiLTMxMTItNGIwNS05MzA2LTJmOGViYzAwNDA2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNTQzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTgwODA5ZTFjZjNiYzBiNWIxZWNlMTlkZmI3OWUzNjY5YTdiMDYyNmM3NmY2ZTM3OGU5OWRjMGZlMmIzYTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K5FlSh13108nFc6tae6FcspHrVWBh_ec4USxd3LFqRM)

بجای ip پروکسی ویندوز این را وارد کن و تست کن ، اینطوری بیشتر برنامه ها از پروکسی استفاده میکنن اما اگه بخوای 100 درصد برنامه ها از پروکسی استفاده کنن باید با proxifier کل ویندوز را تانل کنی
http://socks=127.0.0.1

**Comment by Majidzam1101** [comment]
> proxifier
بی خیال امیدوارم  توی ورژن نهایی obvion desktop این مشکل برطرف کند هم این مشکل تونل کردن کل سیستم  وهم اتصال  سایفون  این دو مشکل حل کنه بی رقیب میشه حتی از هیدوفای نکست میزنه جلو

**Comment by ircfspace** [comment]
یکبار برنامه رو با run as administrator اجرا کرده و تست بگیرید
تلگرام و کروم مشکلی نباید داشته باشن

اما فرایند پروکسی‌شدن سیستم رو در بروزرسانی‌های بعدی بهبود میدیم
