### ISSUE TITLE
مشکل در اجرا برنامه در ابونتو

### ISSUE THREAD

**Issue by mnakhaei** [bepass-org/oblivion-desktop#370]
### Attention | توجه

- [ ] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در زمان باز کردن برنامه در ابونتو به خطار خورده ام
kubuntu 22.04

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

```
/opt/Oblivion\ Desktop/oblivion-desktop
```

### Relevant log output | لاگ برنامه

```shell
LaunchProcess: failed to execvp:
/opt/Oblivion
[17735:0628/180242.125667:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
[1]    17735 trace trap (core dumped)  /opt/Oblivion\ Desktop/oblivion-desktop
```

**Comment by ircfspace** [comment]
سلام
مطالعه کنین: https://github.com/bepass-org/oblivion-desktop/issues/338#issuecomment-2173888695
