### ISSUE TITLE
اضافه کردن حالت VPN or TUN

### ISSUE THREAD

**Issue by Amohasan23** [bepass-org/oblivion-desktop#372]
### Feature description | توضیحات ویژگی

با سلام مدتی هست که ما منتظر هستیم نسخه که مثل VPN وصل بشه رو ویندوز رو منشتر کنید لطفا با پروکسی خیلی مشکل داریم ممنون میشیم زود تر این قابلیت رو اضافه کنید

**Comment by ircfspace** [comment]
سلام
این‌پروسه با توجه به تایمی‌که داریم زمان‌بر هست
درصورتی‌که به ویژگی TUN نیاز دارین فعلن میتونین از نکوری یا v2rayN کمک بگیرین ([+](https://github.com/bepass-org/oblivion-desktop/wiki))
