### ISSUE TITLE
The deb package installation extracts in wrong dir

### ISSUE THREAD

**Issue by mh-firouzjah** [bepass-org/oblivion-desktop#376]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

I've used the .deb package to install on kubuntu 23.04 using discover app from kde, after it finished I tried to run the app using both terminal and the app icon form the start menu but it didn't run then I noticed the output from terminal and the following text was there, so I moved everything to /opt/Oblivion and then run it using command and it worked.
thanks for the great job, best regards!

```sh
oblivion-desktop 
LaunchProcess: failed to execvp:
/opt/Oblivion
[12599:0629/190923.346499:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
zsh: trace trap (core dumped)  oblivion-desktop
```
to solve the problem:
```sh
sudo mv /opt/Oblivion\ Desktop/* /opt/Oblivion/
```
check if it works:
```sh
 /opt/Oblivion/oblivion-desktop
 ```

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

just installed the app

### Relevant log output | لاگ برنامه

```shell
/opt/Oblivion\ Desktop/oblivion-desktop   
LaunchProcess: failed to execvp:
/opt/Oblivion
[12722:0629/191020.992196:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
zsh: trace trap (core dumped)  /opt/Oblivion\ Desktop/oblivion-desktop
```

**Comment by ircfspace** [comment]
سلام
مطالعه کنین: https://github.com/bepass-org/oblivion-desktop/issues/338#issuecomment-2173888695

**Comment by mh-firouzjah** [comment]
> سلام مطالعه کنین: [#338 (comment)](https://github.com/bepass-org/oblivion-desktop/issues/338#issuecomment-2173888695)

سلام، البته راه حل من در تغییر اسم پوشه‌ی محل نگهداری فایلها هست‌، به نظر میرسه وجود یک فاصله در نامگذاری پوشه مشکل ساز هست و استفاده از نام کوتاهتر که کاراکتر اسپیس نداره مشکل رو حل کرد. مراحلی که در لینک پین شده وجود دارند رو طی نکردم اما بازم روش مورد استفاده خودم مشکل رو حل کرد.
ضمنا اگر از روش تغییر نام پوشه در زیر دایرکتوری opt استفاده کنیم باید آدرس موجود در آیکون برنامه که در منوی استارت هست هم اصلاح بشود و به آدرس جدید اشاره کند.
فایل desktop منظورم هست.
سپاس فراوان
