### ISSUE TITLE
MacOS 10.15 menu icon miss

### ISSUE THREAD

**Issue by waitingyou** [bepass-org/oblivion-desktop#378]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

When connected，Menu Bar icon will miss，close window cannot open again。

MacOS 10.15.6 
Macbook Pro 2011 

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. open app
2. connented
3. Menu Bar icon miss
4. click on close window, click on dock icon, window will not show again.

### Relevant log output | لاگ برنامه

```shell
3. Menu Bar icon miss
4. click on close window, click on dock icon, window will not show again.
```

**Comment by morealaz** [comment]
This problem has been mentioned in #348 and has been fixed in https://github.com/bepass-org/oblivion-desktop/commit/0ec7acec85bb30dffdf78a811dd1b3808bdf7bc9. Wait till next release for these fixes.
