### ISSUE TITLE
 قابلیت ایجاد روتینگ دلخواه کاربر و حالت تانل کردن

### ISSUE THREAD

**Issue by gigplus** [bepass-org/oblivion-desktop#38]
### Feature description

قابلیت ایجاد روتینگ دلخواه که که قابل تنظیم از سمت کاربر باشه 
دقیقا مثل روتینگ نویسی در v2rayn یا نکوری در ویندوز که کمک شایانی برای گیمر ها هست برای اتصال به دیسکورد بدون افزایش پینگ در گیم 
و اضافه شده قابلیت تانل فعال کردن تانل در ویندوز

**Comment by javad490** [comment]
جهت تانل کامل در ویندوز میتونی از proxifier استفاده کنی

**Comment by ircfspace** [comment]
> ### Feature description
> قابلیت ایجاد روتینگ دلخواه که که قابل تنظیم از سمت کاربر باشه دقیقا مثل روتینگ نویسی در v2rayn یا نکوری در ویندوز که کمک شایانی برای گیمر ها هست برای اتصال به دیسکورد بدون افزایش پینگ در گیم و اضافه شده قابلیت تانل فعال کردن تانل در ویندوز

در لیست تسک‌ها قرار داره و در آپدیت‌های بعدی در دسترس قرار میگیره:
https://github.com/orgs/bepass-org/projects/4/views/1?pane=issue&itemId=61731705
