### ISSUE TITLE
check or replace the endpoint value or try again

### ISSUE THREAD

**Issue by amr1402** [bepass-org/oblivion-desktop#381]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

برای منم این ارور رو میده اصلا کانکت نمیشه
check or replace the endpoint value or try again

### Relevant log output | لاگ برنامه

```shell
برای منم این ارور رو میده اصلا کانکت نمیشه
check or replace the endpoint value or try again
```

**Comment by amr1402** [comment]
این ارور رو میده اصلا کانکت نمیشه
check or replace the endpoint value or try again

**Comment by ircfspace** [comment]
سلام
مطالعه کنین: https://github.com/bepass-org/oblivion-desktop/issues/280#issuecomment-2146222913
