### ISSUE TITLE
چند مشکل دسترسی پذیری جدی برای معلولین در بخش تنظیمات

### ISSUE THREAD

**Issue by shadyar** [bepass-org/oblivion-desktop#382]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

توضیح در مورد دسترسپذیری:
نابینایان یا افرادی که دارای مشکلات حرکتی هستند از موس برای کنترل کامپیوتر استفاده نمی کنند و بسیار مهم است که برنامه توسط صفحه کلید بویژه جهتنماها کلید تب و کلید اینتر قابل کنترل باشد.

مشکلات اصلی متوقف کننده:
1. در بخش تنظیمات نمی توان بر روی برخی گزینه ها با فشردن کلید اینتر یا اسپیس آن گزینه را انتخاب کرد.
برای مثال در تنظیمات وارپ با فشردن کلید اینتر یا اسپیس نمی توان گزینه گول را تیک زد یا تیک آن را برداشت.
2. تیک دار بودن یا نبودن گزینه ها مثلا همین گزینه گول توسط برنامه های صفحه خوان برای نابینایان اعلام نمی شود.
نکته: بطور استاندارد این موضوع روی کامپوننتهایی مانند چک باکسها یا رادیو باتونها اعلام می شود در نتیجه این یک نقص در یو آی برنامه است. احتمالا استفاده از کامپوننتها یا لایبرری های غیر استاندارد که اطلاعات دسترسپذیری را برای سیستم عامل ارسال نمی کنند و علت آن خالی بودن ویژگیهای دسترس پذیری آن کامپوننت است، علت بروز این مشکل است.
3. در چند نسخه قدیمیتر با چند بار فشار دادن کلیدهای جهتنمای پایین می توانستید فکوس را روی گزینه تنظیمات برده و سپس کلید اینتر را فشار دهید تا تنظیمات باز شود اما این کار در نسخه جدید باعث باز شدن چیزی احتمالا یک منو می شود و با کلیدهای جهتنما یا کلید تب نمی توان روی گزینه های آن حرکت کرد. در نتیجه نمی شود تنظیمات را باز کرد.

نکات اضافی برای طراحهای برنامه:
دسترسپذیری: 
Accessibility
در مورد این مفهوم و رابطهای کاربری که قواعد آن را رعایت می کنند می توانید این واژه را سرچ کنید.
برنامه صفحه خوان:
Screen reader
یک برنامه صفحه خوان رایگان که معمولا نابینایان از آن استفاده می کنند
NVDA
از این سایت قابل دانلود است.
www.NVAccess.org

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

هر مورد به طور جداگانه در بخش اصلی متن شرح داده شده است.

### Relevant log output | لاگ برنامه

```shell
این مورد نیازی به لاگ ندارد.
```

**Comment by ircfspace** [comment]
درصورت امکان این‌مورد رو بررسی و پیگیری کن
@GhostByeBye

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،
این‌مورد توسط @GhostByeBye در https://github.com/bepass-org/oblivion-desktop/pull/390 رفع شده و در آپدیت بعدی در دسترستون قرار میگیره
