### ISSUE TITLE
‫ برای isp مخابرات وصل نمیشه. اگرم وصل بشه سرعتش خیلی بده. اندپوینت های مختلف هم تست کردم

### ISSUE THREAD

**Issue by yazbod** [bepass-org/oblivion-desktop#384]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

هم برای oblivion نسخه دسکتاپ و هم نسخه موبایل. اصلا وصل نمیشه. اگر هم وصل بشه (که زیاد این اتفاق نمیفته)، سرعتش به شدت پایینه و به دردی نمیخوره.
اندپوینت های مختلف هم تست کردم. حالات گول و وارپ و سایفون رو هم تست کردم.

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by B3MH** [comment]
همین مشکل رو برای نسخه دسکتاپ برای اینترنت زی تل دارم. الان 2 روزی هستش که این مشکل رو دارم

**Comment by mahdiu1374** [comment]
> همین مشکل رو برای نسخه دسکتاپ برای اینترنت زی تل دارم. الان 2 روزی هستش که این مشکل رو دارم

منم روی اینترنت زیتل اصلا نمیتونم وصل بشم  شاید ۱ درصد وصل بشه ولی سرعت بشدت پایین

**Comment by xONEIROS** [comment]
![image](https://github.com/bepass-org/oblivion-desktop/assets/174752031/b6b1bfad-7f28-469c-bbd5-89b21d2922e6)

+++++++++++++++++++++++++++
اگر مشکل اتصال دارید میتونید **اندپوینت** رو تغییر بدید | برای به دست اوردن اندپوینت مطابق اینترنت خودتون میتونید از ابزار زیر استفاده کنید


[https://github.com/Ptechgithub/warp/blob/main/README.md](https://github.com/Ptechgithub/warp/blob/main/README.md)

> **نکته ای که مهم اینه ، بعد از دانلود برای به دست اوردن اند پوینت درست حتما باید فیلترشکنی که استفاده میکنید رو خاموش کنید و با نت بدون فیلتر از این ابزار استفاده کنید**
+++++++++++++++++++++++++++

**Comment by yazbod** [comment]
> ![image](https://private-user-images.githubusercontent.com/174752031/346295870-b6b1bfad-7f28-469c-bbd5-89b21d2922e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzgzMTQsIm5iZiI6MTcyMDMzODAxNCwicGF0aCI6Ii8xNzQ3NTIwMzEvMzQ2Mjk1ODcwLWI2YjFiZmFkLTdmMjgtNDY5Yy1iYmQ1LTg5YjIxZDI5MjJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNzQwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDcwMTc1MTAzYzZlZjg3YTNkODA2YTMwNmM2MDYyYTI4OGI0OTUwOGJkZWJkNWE0YTE4YzJjYzA5ZWRhNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U6AmX0ShxM_qWLC4NrFHf2Ah2TG3Mvez3h3rtOeljho)
> 
> +++++++++++++++++++++++++++ اگر مشکل اتصال دارید میتونید **اندپوینت** رو تغییر بدید | برای به دست اوردن اندپوینت مطابق اینترنت خودتون میتونید از ابزار زیر استفاده کنید
> 
> https://github.com/Ptechgithub/warp/blob/main/README.md
> 
> > **نکته ای که مهم اینه ، بعد از دانلود برای به دست اوردن اند پوینت درست حتما باید فیلترشکنی که استفاده میکنید رو خاموش کنید و با نت بدون فیلتر از این ابزار استفاده کنید**
> > +++++++++++++++++++++++++++

ممنون از پاسختون اما من یه کاربر ساده م و اونقدری دانش ندارم که بدونم این ابزاری که لینکشو دادید چطور نصب کنم (دستور bash چیه و این چیزارو نمیدونم(. و خیلی ها هم مثل من یه کاربر ساده هستن. پس اگه میشه لطف کنید اگه یه آموزش ویدیویی از نصب و استفاده از این ابزار هست لینکشو بدید و رویکرد حتی بهتر اینه که یه چنین ابزاری توی برنامه oblivion اگه میشه تعبیه بشه که باهاش به سادگی بشه اندپوینت های مخصوص اینترنت خودمون رو اسکن و دریافت کنیم.

**Comment by Efileep** [comment]
> همین مشکل رو برای نسخه دسکتاپ برای اینترنت زی تل دارم. الان 2 روزی هستش که این مشکل رو دارم

سلام. میخواستم نت زیتل یک ساله بگیرم. خواستم ببینم از نتش راضی هستی؟
اگه میشه راهنمایی کنی ممنون میشم

**Comment by Efileep** [comment]
> > همین مشکل رو برای نسخه دسکتاپ برای اینترنت زی تل دارم. الان 2 روزی هستش که این مشکل رو دارم
> 
> منم روی اینترنت زیتل اصلا نمیتونم وصل بشم شاید ۱ درصد وصل بشه ولی سرعت بشدت پایین

سلام. میخواستم نت زیتل یک ساله بگیرم. خواستم ببینم از نتش راضی هستی؟
اگه میشه راهنمایی کنی ممنون میشم
