### ISSUE TITLE
Bug Report - Error loading shared libraries: libasound.so.2

### ISSUE THREAD

**Issue by silimore** [bepass-org/oblivion-desktop#387]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در لینوکس rhel 7 زمانی که برنامه را اجرا میکنم برنامه با خطا مواجه میشود .
oblivion-desktop: error while loading shared libraries: libasound.so.2: wrong ELF class: ELFCLASS32

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

بعد از نصب و اجرا با این خطا مواجه میشوم .

### Relevant log output | لاگ برنامه

```shell
oblivion-desktop: error while loading shared libraries: libasound.so.2: wrong ELF class: ELFCLASS32
```

**Comment by silimore** [comment]
› creating new od instance...
Couldn't open libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
Aborted (core dumped)

**Comment by xONEIROS** [comment]
مشکلی که داری به این خاطر هست که کتابخونه libasound.so.2 که روی سیستمت نصب شده 32-بیتی هست، ولی سیستمت 64-بیتی هست. برای حل این مشکل می‌تونی این کارها رو انجام بدی:

نصب نسخه 64-بیتی کتابخونه: باید نسخه 64-بیتی libasound2 رو نصب کنی.

**این مسیر احتمالا مشکلت رو حذف میکنه :**

**اول نسخه 32 بیت رو حذف کن**
`sudo apt-get remove libasound2:i386`

**حالا نسخه جدید رو نصب کن**
`sudo apt-get update`
`sudo apt-get install libasound2`


**توضیحات تکمیلی رو هم میدم که خواستی تک بررسی کنی**

با انجام این مراحل، باید بتونی مشکل wrong ELF class: ELFCLASS32 رو حل کنی و مطمئن بشی که نسخه 64-بیتی libasound.so.2 استفاده می‌شه.

می‌تونی با دستور ldd کتابخونه‌ها رو چک کنی:
`ldd /path/to/your/application`
مطمئن شو که نسخه 64-بیتی libasound.so.2 لینک شده.

تنظیم LD_LIBRARY_PATH: اگه نسخه 64-بیتی نصب هست ولی سیستمت هنوز داره نسخه 32-بیتی رو استفاده می‌کنه، می‌تونی متغیر  LD_LIBRARY_PATH رو تنظیم کنی که به مسیر درست اشاره کنه:
`export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH`

**Comment by silimore** [comment]
بسیار ممنونم
