### ISSUE TITLE
چرا اپکیشن کل سیستم رو تونل نمی کنه؟

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#39]
### Feature description

چرا اپکیشن شما کل سیستم تونل نمی کنه مثل هیدوفای واتساپ لود نمی کنه چکار باید کرد ؟

**Comment by ircfspace** [comment]
توی نسخه‌های آتی TUN به برنامه اضافه میشه و میشه کل سیستم رو پروکسی کرد

فعلن برای استفاده از واتس‌اپ میتونین از نسخه تحت وبش استفاده کنین

**Comment by Majidzam1101** [comment]
> توی نسخه‌های آتی TUN به برنامه اضافه میشه و میشه کل سیستم رو پروکسی کرد
> 
> فعلن برای استفاده از واتس‌اپ میتونین از نسخه تحت وبش استفاده کنین
سلام نسخه نهایی اش  ویندوز مشخص است چه زمانی منتشر می شود در گیتهاپ قرار می گیرد ؟در صورت اپدیت شدن چطوری باید اپدیت کرد از کدام برنامه نسخه ویندوز اپدیت کرد ؟

**Comment by Majidzam1101** [comment]
> توی نسخه‌های آتی TUN به برنامه اضافه میشه و میشه کل سیستم رو پروکسی کرد
> 
> فعلن برای استفاده از واتس‌اپ میتونین از نسخه تحت وبش استفاده کنین

سلام نسخه ویندوز obvilion دسکتاپ ای پی تمیز میدی دستی کار نمی کنه روی ایرانسل و همراه اول ومخابرات وشاتل   دوم سایفون مشکل داره وصل میشه هیچی باز نمی کنه سوم با اینترنت دانلود منینجر هیچی دانلود نمیشه کرد از سایت فیلتر شده

**Comment by ircfspace** [comment]
> سلام نسخه ویندوز obvilion دسکتاپ ای پی تمیز میدی دستی کار نمی کنه روی ایرانسل و همراه اول ومخابرات وشاتل دوم سایفون مشکل داره وصل میشه هیچی باز نمی کنه سوم با اینترنت دانلود منینجر هیچی دانلود نمیشه کرد از سایت فیلتر شده

اینجا پاسخ داده شد:

https://github.com/bepass-org/oblivion-desktop/issues/46
