### ISSUE TITLE
kde system proxy doesn't work correctly

### ISSUE THREAD

**Issue by khodedawsh** [bepass-org/oblivion-desktop#394]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

مدتی قبل #245 رو باز کردم و اون موقع فقط به gsettings دسترسی داشتم. پس متوجه طرز کار دقیق kwriteconfig5 نشدم.
اخیرا کاربری رو دیدم که تنظیماتش روی میزکار kde درست اعمال نمیشد، بعد بررسی متوجه شدم ظاهرا نیازه که دو متغیر socksProxy و socksProxyPort به شکل جدا ست بشن در حالی که من توی اون پول‌ریکوست فقط socksProxy رو ست کردم.

### Relevant log output | لاگ برنامه

```shell
-
```

**Comment by ircfspace** [comment]
سلام
ضمن تشکر، امکان توسعه بخش مذکور و ارسال یک PR تکمیلی رو دارین؟

**Comment by khodedawsh** [comment]
اگر وقتم آزاد باشه انجام میدم

**Comment by kiomarzsss** [comment]
> ### Attention | توجه
> * [x]  I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
> 
> ### What Happened? | چه اتفاقی افتاده؟
> مدتی قبل #245 رو باز کردم و اون موقع فقط به gsettings دسترسی داشتم. پس متوجه طرز کار دقیق kwriteconfig5 نشدم. اخیرا کاربری رو دیدم که تنظیماتش روی میزکار kde درست اعمال نمیشد، بعد بررسی متوجه شدم ظاهرا نیازه که دو متغیر socksProxy و socksProxyPort به شکل جدا ست بشن در حالی که من توی اون پول‌ریکوست فقط socksProxy رو ست کردم.
> 
> ### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟
> _No response_
> 
> ### Relevant log output | لاگ برنامه
> ```shell
> -
> ```

کد مربوط به ست شدن ست شدن پروکسی روی KDE درست کار میکنه در حال حاضر. چه پروسه ای رو طی کردین برای اینکه چک کنین تنظیمات پروکسی درست اعمال شده یا نه؟
از کامندلاین چک کردین یا خود system setting gui؟

**Comment by khodedawsh** [comment]
این چیزی که میبینم بنظر میاد درست کار نمیکنه. حالا خودم نه تست کردم نه kde دارم که تست کنم
https://t.me/irgfwgroup/85531
https://t.me/irgfwgroup/85499

**Comment by kiomarzsss** [comment]
> این چیزی که میبینم بنظر میاد درست کار نمیکنه. حالا خودم نه تست کردم نه kde دارم که تست کنم https://t.me/irgfwgroup/85531 https://t.me/irgfwgroup/85499

تا جایی که میدونم دستور kwriteconfig5 برای ست کردن تنظیمات استفاده میشه نه خوندن تنظیمات. پیشنهاد میکنم برای خوندن تنظیمات مستقیم فایل مربوط به تنظیمات پروکسی رو بخونید
`cat ~/.config/kioslaverc`
یا از تنظیمات خود kde قسمت proxy چک کنین. (فقط دقت کنین که برای دیدن آخرین تغییرات نیازه هربار برنامه system settings رو باز و بسته کنین).

خودم یکبار دیگه رو kde تست کردم و پروکسی ست میشه. گزارشی هم در رابطه با این مسئله از کاربر ها دریافت نکردیم. 
اسکرین شات دوم میتونه دلیل دیگه ای داشته باشه که وصل نمیشه کاربر.
با این حال اگه مطمئن شدین که مشکل داره خوشحال میشم بیشتر سرش صحبت کنیم.
