### ISSUE TITLE
حالت tun 

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/oblivion-desktop#398]
### Feature description | توضیحات ویژگی

ببخشین اگه خیلی سوال پر تکراری هست ولی میشه بگین کی اضافه میشه این قابلیت؟ چون بازی های تحریم و فیلتر با نسخه پی سی رد نمیشن چون کل سیستم تونل نمیشه سوال میکنم 
تشکر

**Comment by yjavaherian** [comment]
سلام. تا موقعی که پیاده سازی میکنن می تونین از خود warp-cli استفاده کنین. اگر در لینوکس هستین برای رفع مشکل اتصال warp به سرور هاش میتونین دستور زیر رو اجرا کنین:
warp-cli tunnel endpoint set 162.159.192.175:891
به جای endpoint که قرار دادم می تونین هر endpoint دیگه ای که براتون کار میکنه رو قرار بدین.
خوشبختانه خود warp-cli رسمی ترافیک کل سیستم رو از پروکسی رد میکنه و برای بازی یا مصارف دیگه می تونین ازش استفاده کنین.

* در سیستم های دیگه هم به احتمال زیاد از خود setting برنامه میتونین قسمت tunnel endpoint رو پیدا کنین و تغییرش بدین.

**Comment by ircfspace** [comment]
متاسفانه زمانش مشخص نیست، اما یکی از موارد مهمی هست که در دستور رسیدگی قرار داره
