### ISSUE TITLE
Psiphon tunneling automatic mode

### ISSUE THREAD

**Issue by HaroldArpanet** [bepass-org/oblivion-desktop#4]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

# Psiphon tunneling
- For psiphon tunneling when is on automatic mode is only just a warp connection ( i think ) this will be need to select a country manually.
(Platform: Gnu/Linux Debian Based) 

### Minimal Reproducible Example (MRE)

1. Settings
2. Psiphon

### Version

v0.2.29-beta

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
hi

if the option to enable psiphon and select automatic location is activated, one of the defined locations in the list is randomly selected.

the issue that I personally encountered is that immediately after connecting, the IP does not change to the desired location and it takes at least 10 seconds for the IP to be changed. This issue needs to be investigated.

**Comment by ircfspace** [comment]
It seems that the Psiphon option is facing an issue. It has been reported and is currently being investigated. It is likely that the problem will be resolved in the next update.

https://github.com/orgs/bepass-org/projects/4/views/1?pane=issue&itemId=61910603
