### ISSUE TITLE
همراه اول 

### ISSUE THREAD

**Issue by Bifckr** [bepass-org/oblivion-desktop#40]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام یک سوال دارم چرا برای همراه اول هم ویندوز هم اندروید برنامه سرعت به شدت پایینی داره ولی برای ایرانسل سرعت خوبی داره حتی همراه دوستم هم سرعتش خوبه ولی از من افتضاحه راه حلی چیزی کسی داره این مشکل حل بشه ؟
![Screenshot_۲۰۲۴-۰۵-۰۵-۱۲-۱۵-۱۵-۶۷۷_org zwanoo android speedtest](https://github.com/bepass-org/oblivion-desktop/assets/117599163/cfd4325e-3e66-4900-b9e3-586ec717162f)
اینجا سرعت همراه رو گوشی خودم 
![IMG_۲۰۲۴۰۵۰۵_۱۲۲۷۵۴](https://github.com/bepass-org/oblivion-desktop/assets/117599163/a7fc990a-fa2a-43b0-94de-5c660727de9c)
اینجا سرعت همراه رو لب تاب با یه گوشی دیگه 

### Minimal Reproducible Example (MRE)

نمیدانم 

### Version

همین نسخه جدید

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
ممکنه تا حدی به اختلال اینترنت یا اختلال‌های منطقه‌ای مربوط باشه

یکبار با فعالسازی گزینه گول (در تنظیمات) و یکبار بدون اون تست بگیرید
