### ISSUE TITLE
The red X should close the application.

### ISSUE THREAD

**Issue by Mishasama** [bepass-org/oblivion-desktop#402]
### Feature description | توضیحات ویژگی

Close should always mean close, not minimized to tray.
Please consider change back the close button's behavior to close the app. Or add an option for the user to choose the behavior when clicking the close button.

It's really annoying to have to go to the system tray every time to come and click the left button to expand the tray, then the right button to open the menu, and finally the left button to close the app.

**Comment by ircfspace** [comment]
Thank you for your feedback.
Initially, the behavior after clicking the Close button was as you requested, but after repeated requests from both Iranian and foreign users, we decided to change it to the current form.
It’s worth mentioning that many VPN programs also have a similar behavior to the current OblivionDesktop behavior, and closing the program is done through the SystemTray.

**Comment by Mishasama** [comment]
If, due to unforeseen circumstances such as system or program bugs, the right-click menu fails to appear when clicking the icon in the system tray, the program cannot be closed through standard means. The only solution becomes forcibly terminating the process through the Task Manager.

A well-designed program should always offer multiple ways to close the program, preventing situations where a specific method becomes unusable due to unexpected issues. This ensures a smooth user experience and avoids the frustration of being unable to close the program.

While you draw a comparison to other similar products, these products often provide settings to determine whether the Close button terminates the program or minimizes it to the system tray. They might even include an explicit "Close" option within the program's menu. This flexibility is absent in Oblivion Desktop.

**Comment by ircfspace** [comment]
Thank you for your feedback.

In addition to closing the program via the system tray, you can also close it using **CTRL+Q**. 
Does this help?

**Comment by Mishasama** [comment]
> close it using **CTRL+Q**.

No, the system tray icon no longer pops up a right-click menu, and clicking the left button doesn't show the program's window, it's a completely dead (non-interactive) state.

**Comment by ircfspace** [comment]
We could probably move the option to either close the program completely or minimize it to the system tray when clicking the close button to the program settings and make it optional. Sounds good?

**Comment by ircfspace** [comment]
The option to force close the program has been added to the settings section:
https://github.com/bepass-org/oblivion-desktop/commit/93370e1dcd651635203cfb0a35800ce86fcc7367

You can use this feature in the next program update.
