### ISSUE TITLE
Profile editing

### ISSUE THREAD

**Issue by Mishasama** [bepass-org/oblivion-desktop#403]
### Feature description | توضیحات ویژگی

Right now you can only add or delete, would like to be able to show specifics and edit it.

**Comment by ircfspace** [comment]
Addition, deletion, and viewing are possible.
You can see the added items in the endpoint section.

Regarding editing, I doubt it’s particularly necessary.
Nevertheless, I’ll close the issue and add it as a task in the backlog so that we might work on it when we have the opportunity.

**Comment by ircfspace** [comment]
The ability to edit saved endpoints in the profile section has been enabled by @ShadowZagrosDev.
This feature will be available in the next update.
