### ISSUE TITLE
در ویندوز 7 من هر کار میکنم تا این برنامه را اجرا کنم با خطای KERNAL32.DLL. مواجه میشوم در صورتی که این فایل وجود دارد و هیچ مشکلی ندارد 

### ISSUE THREAD

**Issue by MOOMAX-84** [bepass-org/oblivion-desktop#404]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![Untitled](https://github.com/user-attachments/assets/4b554379-b24c-4b01-b222-cc6d5130a2dd)

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

UPDATE WINDOWS 
update driver 
install and remove , install file (KERNAL.dll.)
restart system
download obilvion other website
![Untitled](https://github.com/user-attachments/assets/e276f83a-ba5f-452b-bf22-fd6f700ccd67)

### Relevant log output | لاگ برنامه

```shell
the procedure entry point diskard virtual Memory could not be located in the dynamic link library KERNAL32.dll.
```

**Comment by mahdiu1374** [comment]
سلام گفته که روی ویندوز ۱۰ و ۱۱ فقط اجرا میشه نمیتونی اجراش کنی تو ویندوز ۷
