### ISSUE TITLE
باگ پروفایل اندپوینت

### ISSUE THREAD

**Issue by coldwater-10** [bepass-org/oblivion-desktop#405]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

قسمت پروفایل اندپوینت هارو که فعال کردم از اول دوتا ذخیره شده بود که نمیزاره ببینمشون
جدید هم میخوام اضافه کنم هیچ اتفاقی نمی افته
بنظرم بهتره ایپی های ذخیره شده رو نمایش بده و قابلیت حذف و اضافشون هم درست کار کنه

![image](https://github.com/user-attachments/assets/71a62881-1b03-4c84-8533-0f1c6030363c)

### Relevant log output | لاگ برنامه

```shell
طولانی بود جا نمیشد
```

**Comment by ircfspace** [comment]
از چه نسخه‌ای استفاده میکنین؟

**Comment by coldwater-10** [comment]
> از چه نسخه‌ای استفاده میکنین؟

v0.35.1-beta

**Comment by ircfspace** [comment]
با آخرین آپدیت چک کنین:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.40.0-beta

**Comment by coldwater-10** [comment]
> با آخرین آپدیت چک کنین: https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.40.0-beta

بازم فیکس نشد

**Comment by ircfspace** [comment]
یکبار تنظیمات برنامه رو بازیابی کرده و درصورت ادامه مشکل، ویدئوئی از صفحه برنامه تهیه و برام ارسال کنین

**Comment by ircfspace** [comment]
بله، فعلن چنین محدودیتی لحاظ شده

**Comment by coldwater-10** [comment]
اها اخه نشون نمیده کدوما کار نمیکنه جایگزین کنم

**Comment by ircfspace** [comment]
در بخش پروفایل، ماوس رو روی هرکدوم نگه‌دارین مقدار اندپوینت رو نشون میده
البته باید نسخه 0.41.3-beta رو نصب داشته باشین

**Comment by coldwater-10** [comment]
> در بخش پروفایل، ماوس رو روی هرکدوم نگه‌دارین مقدار اندپوینت رو نشون میده البته باید نسخه 0.41.3-beta رو نصب داشته باشین

اها مرسی
