### ISSUE TITLE
v0.40.0-beta Ubuntu 24.04 core dunp

### ISSUE THREAD

**Issue by papampi** [bepass-org/oblivion-desktop#406]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Not start on ubuntu 24.04

### Relevant log output | لاگ برنامه

```shell
~$ oblivion-desktop 
LaunchProcess: failed to execvp:
/opt/Oblivion
[331464:0716/123914.530360:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
```

**Comment by ircfspace** [comment]
Check it :
https://github.com/bepass-org/oblivion-desktop/wiki/LaunchProcess:-failed-to-execvp(Ubuntu-24.04)

**Comment by papampi** [comment]
> Check it : https://github.com/bepass-org/oblivion-desktop/wiki/LaunchProcess:-failed-to-execvp(Ubuntu-24.04)

Thanks... 
When it's this simple why not edit .desktop file to solve the future issue for everyone?

**Comment by papampi** [comment]
For anyone whome has this issue just edit .desktop file:
` /usr/share/applications/oblivion-desktop.desktop`

Change Exec command 

From:
`Exec="/opt/Oblivion Desktop/oblivion-desktop" %U`

To:
`Exec="/opt/Oblivion Desktop/oblivion-desktop" --no-sandbox %U`
