### ISSUE TITLE
امکان تغییر dns

### ISSUE THREAD

**Issue by Pinaxy1234** [bepass-org/oblivion-desktop#409]
### Feature description | توضیحات ویژگی

امکان تغییر dns چون وقتی من connect رو میزنم ارور 1.1.1.1 میده

**Comment by ircfspace** [comment]
داخل Warp-plus یه فلگ به نام DNS هست، که در رابطه با TUN کاربرد داره و کمکی به رفع مشکل اتصال نمیکنه.
