### ISSUE TITLE
لینک های دانلود ویندوز کار نمی کند

### ISSUE THREAD

**Issue by soheilbayat1382** [bepass-org/oblivion-desktop#41]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

به هنگام کلیک بر لینک دانلود نسخه ویندوز ارور 404 می دهد

### Minimal Reproducible Example (MRE)

nothing

### Version

V..

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mehrdadjey** [comment]
هیچکدام از لینک های ویندوز کار نمیکنند

**Comment by seramo** [comment]
موقتا از لینک های موجود در بخش مشخص شده استفاده کنید
![2024-05-05_22-26](https://github.com/bepass-org/oblivion-desktop/assets/23317510/fc0934d8-4e2f-4122-b5f4-06280c0bca09)

**Comment by ircfspace** [comment]
لینکهای دانلود :

https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.2.44-beta
