### ISSUE TITLE
Faster access to the profile

### ISSUE THREAD

**Issue by Alireza-F-kenedy** [bepass-org/oblivion-desktop#418]
### Feature description | توضیحات ویژگی

Hello, My Dear Mark. 
Thanks for adding the endpoint profile. 
To improve this feature better, like the Android version, which has the language option at the bottom of the screen. 
Add it to the Windows version, but to change the profile,

**Comment by ircfspace** [comment]
Hello,
Thank you for your suggestion.

We will try to consider solutions to improve accessibility. 
The issue has been closed, but it has been added to the backlog as a task.

Best regards.
