### ISSUE TITLE
مشکل فتوشاپ!

### ISSUE THREAD

**Issue by SimaSiahposh** [bepass-org/oblivion-desktop#42]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با وجود اینکه دسترسی فتوشاپ به اینترنت از طریق فایروال مسدود شده، اما هر چند دقیقه یا ثانیه یکبار فتوشاپ پیغام خطای عجیب غریبی می‌دهد و امکان حتی ذخیره کردن هرچیزی که مشغول کار روی آن هستیم هم مقدور نیست و باید برنامه را بطور کلی از طریق تسک‌بار بست. اگر امکان مجزا کردن دسترسی نرم‌افزار هم در نسخه جدید گنجانده شود عالی می‌شود چون اینطور عملا برای هربار استفاده از نرم‌افزارهای مشابه، باید فیلترشکن را بست و مشغول کار شد.
![Screenshot (253)](https://github.com/bepass-org/oblivion-desktop/assets/120381602/ba48ab75-4d3b-41c0-8903-e34da5e997b5)

### Minimal Reproducible Example (MRE)

۱. نرم افزار در حال اجراست
۲. فایل یا نرم‌افزار فتوشاپ باز می‌شود
۳. چند دقیقه بعد پیغام خطای زیر ظاهر میشود
![Screenshot (253)](https://github.com/bepass-org/oblivion-desktop/assets/120381602/31bb99d0-e956-47bc-8eea-6e4c97a5cb0f)

### Version

0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by javad490** [comment]
فایل اجرایی exe فتوشاپ را از طریق فایروال ویندوز مسدود کنید تا بصورت بک گراند نتونه به اینترنت وصل بشه

**Comment by ircfspace** [comment]
در نسخه‌های آتی تغییراتی در نحوه پروکسی‌کردن سیستم اعمال میشه و گزینه قوانین مسیریابی رو اضافه میکنیم.
