### ISSUE TITLE
faceit باز نشدن سرور های 

### ISSUE THREAD

**Issue by Ho3ein-maker** [bepass-org/oblivion-desktop#420]
### Feature description | توضیحات ویژگی

با سلام و عرض ادب ، اول اینکه خیلی از سازندگان این برنامه تشکر میکنم ، خیلی عالی و کار آمد با پینگ عالی و بسیاری از ویژگی های دیگه . برای من خیلی خوب عمل میکنه و تمام سایت هایی که فیلتر و تحریم هستن باز میشن به جز سایت faceit ، خیلی عجیبه برام و نمیدونم مشکل از کجاست ؟! چون تمامی سایت ها باز میشن به غیر از سرور های بازی faceit ، تقاضا دارم که این مشکل رو برطرف کنید با سپاس. اینترنت آسیاتک هم استفاده می کنم.

**Comment by ircfspace** [comment]
سلام
دامنه faceit.com/en با متد گول (آیپی آلمان) برام باز میشه؛ اما در کل احتمال داره خود FaceIt امکان دسترسی برخی‌از بخش‌هاشو از طریق وارپ محدود کرده باشه
سرویس‌های بین‌المللی دیگری هم هستن که این‌محدودیت رو اعمال کردن و متاسفانه کاریش نمیشه کرد
