### ISSUE TITLE
استراتژی را فراموش کردیم

### ISSUE THREAD

**Issue by Kamyar2** [bepass-org/oblivion-desktop#422]
### Feature description | توضیحات ویژگی

![Screenshot_20-7-2024_32253_github](https://github.com/user-attachments/assets/1d6a1321-43fa-4722-b1f0-54ecdabcc000)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
برنامه Oblivion Desktop یک GUI برای Warp-plus هست و عمده مواردی‌که بهشون اشاره دارین باید [اینجا](https://github.com/bepass-org/warp-plus/issues) مطرح بشن

برقرار باشید
