### ISSUE TITLE
عدم اجرای برنامه نه به طور ستاپ و نه پرتابل

### ISSUE THREAD

**Issue by TSh1985** [bepass-org/oblivion-desktop#425]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

برنامه oblivion از بعد از دریافت آخرین نسخه در هفته گذشته (یکشنبه ۲۵ تیر) برای من اساساً باز نمی‌شود. من نسخه پرتابل را داشتم که کار می کرد و مشکلی نداشت. روز یکشنبه متصل نمی‌شد و متوجه پیغام آپدیت شدم. نسخه جدید پرتابل را دانلود و اجرا کردم و دیدم اجرا نمی‌شود. وقتی روی آیکون مربوطه اینتر می‌زنی شروع می‌کند به extract کردن فایل‌ها ولی بعد از اتمام آن هیچ اتفاقی نمی‌افتد. 
نسخه ستاپ را هم دانلود و نصب کردم. نصب شد ولی آیکون اجرای آن را هم که اینتر می‌زنم هیچ اتفاقی نمی‌افتد. 

### Relevant log output | لاگ برنامه

```shell
برنامه اجرا نمی‌شود که بخواهم لاگ آن را قرار دهم
```

**Comment by ircfspace** [comment]
سلام
متاسفانه مشخص نیست درخصوص چه سیستم‌عاملی صحبت میکنین، اما پیشنهاد میکنم از نسخه قدیمی‌تر که براتون شرایط پایداری داشت استفاده کرده و منتظر بروزرسانی بعدی برنامه بمونین

**Comment by TSh1985** [comment]
سلام. سیستم عامل من ویندوز است؛ ویندوز ۱۰.
نسخه قدیمی‌تر را پاک کردم و دسترسی ندارم.

**Comment by ircfspace** [comment]
آخرین آپدیت رو دریافت کرده و تست کنین:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.43.1-beta
