### ISSUE TITLE
خطای احراز هویت در کلودفلر.

### ISSUE THREAD

**Issue by ahb1364** [bepass-org/oblivion-desktop#429]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

دکمه اتصال را می زنم این پیغام را می دهد:خطای احراز هویت در کلودفلر؛ دوباره تلاش کنید.

در نسخه اول این مشکل وجود نداشت اما از آپدیت بعدی این پیغام را می دهد و مجبورا از نسخه اولیه درحال استفاده هستم. و البته من از نسخه پرتابل استفاده میکنم.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

i do nothing. 

### Relevant log output | لاگ برنامه

```shell
i dont know.
```

**Comment by ircfspace** [comment]
سلام
این توضیحات رو مطالعه کنید: https://shorturl.at/H3Ygl
اگر مشکلتون حل نشد، از نسخه قبلی استفاده کرده یا منتظر بروزرسانی‌های آتی باشین
