### ISSUE TITLE
Problem connecting by Psiphon!

### ISSUE THREAD

**Issue by Amirinventor2010** [bepass-org/oblivion-desktop#43]
### Feature description

Hello, good time! Thank you for all your hard work. Then I wanted to tell you an error from the desktop program; This program of yours has a problem connecting to **"Psiphon"**, but it connects to **"Gool"**.thanks again!

**Comment by ircfspace** [comment]
Thank you,
We are working to address the Psiphon issue and it will be properly resolved in the next update.
