### ISSUE TITLE
Can't add or edit profiles after v0.43.1 #403

### ISSUE THREAD

**Issue by Mishasama** [bepass-org/oblivion-desktop#430]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![image](https://github.com/user-attachments/assets/db80b9b4-fa64-460c-8baa-e10e6b8e5be9)
The text box is currently inaccessible. When the mouse hovers over it, a disabled icon (🚫) appears, indicating that it cannot be interacted with.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Open profile in settings
2. See error.

### Relevant log output | لاگ برنامه

```shell
No log about this issue. #403 
```
#403

**Comment by ircfspace** [comment]
Hi,
The save/edit button is disabled when you haven't entered a title or a properly structured endpoint. According to the screenshot you sent, the form is empty, so the button is naturally disabled. Do you have any issue other than this? If so, please send a video of the issue so we can better understand the problem.

**Comment by Mishasama** [comment]
![Disabled](https://github.com/user-attachments/assets/69fd3619-440d-4262-b025-0ea4c0a90d55)

**Comment by ircfspace** [comment]
The limit set for adding personal profiles is 7.

However, there were two issues that have now been resolved and will be available in the next update:

1. An error message indicating the limit was not displayed to the user when attempting to add an eighth profile.
2. Editing was not possible when the maximum number of profiles had been reached.
