### ISSUE TITLE
محو شدن گزینه ها

### ISSUE THREAD

**Issue by ali-ghanati** [bepass-org/oblivion-desktop#433]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![Screenshot_20240723_075736](https://github.com/user-attachments/assets/98984cde-53d5-43ab-8a9b-531c47441fd0)

سلام و خسته نباشید وقتی تو برنامه میرم تو قسمت تنظیمات اسکنر و روی اندپوینت که کلیک میکنم صفحه به این شکل درمیاد و دیگه برنامه کلا غیر قابل استفاده میشه
من روی پارچ لینوکس هستم و نسخه tar.xz رو دانلود کردم و این مشکل تو 2 آپدیت آخر اتفاق میوفته

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1.خروج و تست مجدد
2.پاک کردن کامل برنامه و دانلود مجدد 

### Relevant log output | لاگ برنامه

```shell
time=2024-07-23T07:59:59.546+03:30 level=ERROR msg="ping error" subsystem=sc<USERNAME>nner subsystem=sc<USERNAME>nner/engine <USERNAME>ddr=162.159.193.217 error="error sending r<USERNAME>ndom p<USERNAME>cket: write udp 192.168.51.93:36390->162.159.193.217:903: write: connection refused"

time=2024-07-23T07:59:59.547+03:30 level=ERROR msg="ping error" subsystem=sc<USERNAME>nner subsystem=sc<USERNAME>nner/engine <USERNAME>ddr=2606:4700:d0:0:c2dd:9bf1:1f23:5743 error="di<USERNAME>l udp [2606:4700:d0:0:c2dd:9bf1:1f23:5743]:3581: connect: network is unre<USERNAME>ch<USERNAME>ble"

time=2024-07-23T08:00:01.530+03:30 level=INFO msg="successfully lo<USERNAME>ded w<USERNAME>rp identity" subsystem=w<USERNAME>rp/<USERNAME>ccount

time=2024-07-23T08:00:01.529+03:30 level=INFO msg="sc<USERNAME>n results" endpoints="[{AddrPort:188.114.99.109:1018 RTT:110.870055ms Cre<USERNAME>tedAt:2024-07-23 08:00:01.508049303 +0330 +0330 m=+3.981987853} {AddrPort:162.159.192.91:1014 RTT:148.856884ms Cre<USERNAME>tedAt:2024-07-23 07:59:59.478586511 +0330 +0330 m=+1.952525068}]"
time=2024-07-23T08:00:01.529+03:30 level=INFO msg="using w<USERNAME>rp endpoints" endpoints="[188.114.99.109:1018 162.159.192.91:1014]"
time=2024-07-23T08:00:01.529+03:30 level=INFO msg="running in w<USERNAME>rp-in-w<USERNAME>rp (gool) mode"
```

**Comment by SepehrHasanabadi** [comment]
در ابتدا زمانی که کاربر وارد تنظیمات اسکنر شود صفحه مربوطه به درستی نمایش داده میشود ولی در صورتی که بر روی پروفایل در قسمت پایین صفحه کلیک شود  و بر روی بروزرسانی کلیک شود این اتفاق خواهد افتاد و دیگر صفحه اندپوینت مشکل پیدا میکند. 
در ضمن مقادیر مربوط به پروفایل نیز قابل اضافه شدن نمیباشند و درصورت کلیک مجدد پس از اضافه کردن همواره ورودی های عنوان و اندپوینت خالی نمایش داده میشود.

<img width="392" alt="Screen Shot 2024-07-23 at 9 24 04 AM" src="https://github.com/user-attachments/assets/a2996dc1-7a85-409e-833a-ed6520c8fa97">

**Comment by ircfspace** [comment]
دو مورد :

۱) مشخص کنید دقیقا از چه ورژنی استفاده میکنید؟
۲) یکبار تنظیمات برنامه رو ریست کرده و مجددا امتحان کنید

**Comment by ircfspace** [comment]
تکمیلی:
 یه‌تغییر کوچک اعمال کردم که فکر میکنم مشکل رو حل کرده باشه؛ لطفن منتظر بروزرسانی جدید بمونین و بعد مجدد تست بگیرین
