### ISSUE TITLE
DNS & IP Clean & Port Scanner

### ISSUE THREAD

**Issue by mrdiabloo** [bepass-org/oblivion-desktop#437]
### Feature description | توضیحات ویژگی

با درود لطفا اگر ممکنه موارد زیر در رابطه با DNS به اپ اضافه شود. **این فقط یه پیشنهاده و آلردی از شما برای زحماتتون متشکر هستیم**
1. انتخاب خودکار DNS توسط اپ
2. انتخاب حالت کاستوم DNS توسط کاربر
3. اضافه کردن DNS بصورت دستی
4. جستجوی IP تمیز براساس هر اپراتور و انتخاب آن بصورت خودکار و دستی
5. استفاده از لیست IPهای تمیز که در گیت درج شدند  - به صورت دستی و خودکار و قابلیت ذخیره آن و مشخص باشد برای چه اپراتوری ذخیره شده است.

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از پیشنهاد شما،
اپ oblivionDesktop یک GUI برای warp-plus هست و برای موارد مرتبط با DNS لازمه [اینجا](https://github.com/bepass-org/warp-plus/issues) ایشو ایجاد کنید
در رابطه با IP تمیز هم فعلن سازوکاری برای تفکیک بر اساس اپراتور وجود نداره، اما در آینده اگر شرایطش پیش بیاد حتمن انجام میدیم
