### ISSUE TITLE
مسدود شدن برنامه در اپراتور همراه اول

### ISSUE THREAD

**Issue by abs110110** [bepass-org/oblivion-desktop#440]
### Feature description | توضیحات ویژگی

با سلام همراه اول پورت برنامرو بسته لطفا تووی آپدیت جدید پورت جدید بزارید

**Comment by neonramzy** [comment]
روی شاتل هم دیگه کار نمیکنه. upd کلا مسدود شده

**Comment by abs110110** [comment]
لطفا یه تغییراتی تووی کانفیگش بدین ممنون

**Comment by ehsan-adibkia** [comment]
مرسی از برنامه عالیتون لطفا این مشکل رو رفع کنید

**Comment by ircfspace** [comment]
سلام
منتظر بروزرسانی بعدی warp-plus بمونین، تا این‌مشکل برطرف شه

توضیحات مرتبط: https://shorturl.at/H3Ygl
