### ISSUE TITLE
مسدود شدن برنامه در اپراتور همراه اول

### ISSUE THREAD

**Issue by abs110110** [bepass-org/oblivion-desktop#444]
### Feature description | توضیحات ویژگی

 پورت 8086 روی همراه اول deny شده گانفیگو لطفا عوض کنید تووی آپدیت جدید روی همه app ها
ممنون

**Comment by abs110110** [comment]
تیکیتو close نکنید لطفا ببنینم رووی کدوم اپراتورا مشکل هست

**Comment by AMirviki** [comment]
خب چه پورتی پیشنهاد میدی برای همراه اول؟

**Comment by abs110110** [comment]
ازاد پیدا نکردم فعلا

**Comment by abs110110** [comment]
بی ناموسا همرو reject کردن

**Comment by ircfspace** [comment]
توضیحات زیر رو مطالعه کنید :
https://shorturl.at/H3Ygl

یا برای سرعت‌بخشیدن به پیگیری اینجا ایشو بزنین:
https://github.com/bepass-org/warp-plus/issues
