### ISSUE TITLE
ارور میده وقتی میزنم روش باز نمیشه

### ISSUE THREAD

**Issue by kati-hal** [bepass-org/oblivion-desktop#447]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی نصبش کردم تموم شد باز نشد ارور داد

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1
![Untitled77](https://github.com/user-attachments/assets/4574700d-76c9-42b5-87da-ddd766ac583c)

### Relevant log output | لاگ برنامه

```shell
سسسسس
```

**Comment by kati-hal** [comment]
میشه بگید مشکل چیه؟

**Comment by ircfspace** [comment]
سلام
روی ویندوزهای 7 و 8 پشتیبانی نمیشه
