### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by Sarborj** [bepass-org/oblivion-desktop#45]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

روی ویندوز 8.1 برنامه رو کامل نصب کردم ولی برام اجرا نمیشه و این ارور نمایش داده میشه:
Entry Point Not Found
![2024-05-05_154042](https://github.com/bepass-org/oblivion-desktop/assets/168829311/4326e35c-79e1-4e3c-b237-7dc25cf1014e)

### Minimal Reproducible Example (MRE)

کلیک روی آیکن برنامه کلیک می‌کنم و این پیغام میاد.
ران ادیمنستور رو هم تست کردم، بازم باز نشد.

### Version

0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by Sadeghkb** [comment]
مال منم همینجوری میشه

**Comment by Sadeghkb** [comment]
![Screenshot (5)](https://github.com/bepass-org/oblivion-desktop/assets/141251162/5263af59-9458-4b4c-b4ce-4c7a8dd2c115)

**Comment by ircfspace** [comment]
ویندوز 32 بیتی یا 64 بیتی؟

**Comment by Sarborj** [comment]
> ویندوز 32 بیتی یا 64 بیتی؟

64 بیتی

**Comment by kiomarzsss** [comment]
@Sarborj @Sadeghkb 
متاسفانه در حال حاضر برای ویندوز فقط از ویندوز های ۱۰ و ۱۱ (۶۴بیتی) پشتیبانی میکنیم.
پشتیبانی از ویندوز های قدیمی تر در آینده هم دور از انتظاره با توجه به اینکه در کنار خود مایکروسافت، پلتفرمی که روش برنامه توسعه داده شده(electron) هم پشتیبانی از ویندوز های قدیمی تر رو رها کرده:

https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93
