### ISSUE TITLE
the procedure entry point discard virtual memory

### ISSUE THREAD

**Issue by arash1290** [bepass-org/oblivion-desktop#450]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

  the procedure entry point discard virtual memory could not be located in the dy namic link library kernel32.dll

### Relevant log output | لاگ برنامه

```shell
when i run obivilion desktop i got this error   

 the procedure entry point discard virtual memory could not be located in the dy namic link library kernel32.dll
```

**Comment by ircfspace** [comment]
سلام

مشخص کنین از چه سیستم عاملی و کدوم ورژن از برنامه استفاده میکنین

**Comment by ircfspace** [comment]
مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/76#issuecomment-2252535770
