### ISSUE TITLE
سرعت متصل شدن

### ISSUE THREAD

**Issue by adasdasfdvsd** [bepass-org/oblivion-desktop#451]
### Feature description | توضیحات ویژگی

سلام
سرعت باز شدن برنامه و سرعت متصل شدن کند هست! احساس میکنم درخواست هایی برای دریافت سرور جدید و... میشه, اگر این موضوع قابلیت تنظیم داشته باشه خیلی خوبه.
یعنی تنظیم کنیم سرور ها در چند روز یک بار اپدیت بشن یا این عمل یک دکمه خاصی داشته باشه. 
ممنون

**Comment by ircfspace** [comment]
سلام
مساله سرعت مربوط میشه به محدودیت‌هایی که سرویس‌دهنده اینترنتتون روی وارپ اعمال کرده
البته تعویض اندپوینت میتونین یکی‌از راه‌حل‌ها برای رفع مشکل باشه

مطالعه کنید: https://shorturl.at/H3Ygl

**Comment by adasdasfdvsd** [comment]
من تمام اند پوین ها رو تست کردم با سرعت 5 مگابیت بر ثانیه برای متصل شدن حدودا 15 ثانیه طول میکیشه 
سرعت باز شدن برنامه 7 ثانیه هست که اصلا نیاز نیست در اسپلش این همه زمان بمونه همون ثانیه اول باید بیاد بالا ! چرا باید این همه زمان توی اسپلش باشیم ؟

**Comment by ircfspace** [comment]
این‌برنامه فاقد هرگونه تبلیغات یا پلن درآمدی هست و تنها به منظور گرامیداشت یاد افرادی که در اسپلش‌اسکرین تصویرشون دیده میشه، چندین‌ثانیه برای اجرای اولیه زمان میگیره.  درصورتی‌که تمایل ندارین همون چندثانیه آغازین رو شاهد باشین، به‌نظر باید از سایر برنامه‌های مشابه استفاده کنین.

**Comment by adasdasfdvsd** [comment]
> این‌برنامه فاقد هرگونه تبلیغات یا پلن درآمدی هست و تنها به منظور گرامیداشت یاد افرادی که در اسپلش‌اسکرین تصویرشون دیده میشه، چندین‌ثانیه برای اجرای اولیه زمان میگیره. درصورتی‌که تمایل ندارین همون چندثانیه آغازین رو شاهد باشین، به‌نظر باید از سایر برنامه‌های مشابه استفاده کنین.

چندثانیه آغازین باید بر اساس منطقی باشه اینکه در روز یک بار 7 ثانیه واستیم نه اینکه هر موقع باز میکنیم 7 ثانیه واستیم بقیه برنامه ها مشابه را برسی کنید مثلا Gmail گوگل چک کنید. چند بار ببندید باز کنید ببینید چند بار اسپلشو میبینید !

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
I suggest adding a countdown timer inside the spinner, as shown in the attached screenshot, to let users know how much time is left until the splash screen ends. What do you think? If you agree, I can implement this in a PR.
<img width="269" alt="splash" src="https://github.com/user-attachments/assets/dd0843e8-8405-4f2b-ae1f-2e5f2d7d353c">

**Comment by ircfspace** [comment]
@ShadowZagrosDev 
Thank you, but no; adding a timer to the splash screen might not result in a great user experience. Also, the issue mentioned is different. It's recommended to disable the forced app closure option in the settings, so the splash screen doesn't appear every time the app is launched.
