### ISSUE TITLE
نمی تواند تحریم های store وxbox را بشکاند

### ISSUE THREAD

**Issue by XGAMMERIR** [bepass-org/oblivion-desktop#454]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی من اومدم حالت گول را فعال کردم با این حال که برای شکاندن تحریم store و xbox هست نتوانست کاری کنه
لطفا اگه می توانی این مشکل را حل کن چون سید ما کلا یه تابستان داریم الان هم سریع دوس دارم گیم پس گرفتم بازی هاش را بازی کنم ولی وی پی ان مثل وی پی ان تو خوب نیست دمت گرم خدا خیرت بده عشقی بوس بوس پسرما !!!

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. وصلش کردم روی حالت گول
2. استور بالا نیومد

### Relevant log output | لاگ برنامه

```shell
این را نمی دانم
```

**Comment by ircfspace** [comment]
سلام
برخی‌از سرویس‌دهنده‌ها امکان اتصال از طریق وارپ رو بستن و نمیشه کاریش کرد
با اینحال از متد سایفون برای اتصال کمک بگیرید
