### ISSUE TITLE
مصرف بیش از حد باتری در سرفیس و لپ تاپ

### ISSUE THREAD

**Issue by majix127** [bepass-org/oblivion-desktop#455]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود بر شما-تو ورژن 51 مصرف باتری به شدت بالا رفته و دستگاه شدیدن داغ میکنه
دم شما گرم که انقد زحمت میکشین

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

battry usage issue

### Relevant log output | لاگ برنامه

```shell
لاگ عادی هست.فقط مصرف باتری بالا هست
```

**Comment by ircfspace** [comment]
سلام
آیا امکان بررسی اینکه مصرف باتری به خاطر GUI هست یا CLI دارید؟

**Comment by majix127** [comment]
درود بر شما
وقتی برنامه باز هست مصرف عادیه،و مشکلی نیس،ولی به محض برقراری اتصال و  نشون
دادن ای پی مصرف بالا میره،جوری ک cpu usage بالا میره
در ضمن یه مشکلی هم تازه متوجه شدم،مصرف ایننرنت یمقدار بیشتر شده،نزدیک ۳۰
درصد بیشتر شده
تانل برنامه کی اضافه میشه؟
دمتون گرم،هیچوقت فراموشتون نمیکنیم

**Comment by ircfspace** [comment]
طبق توضیحتون، به‌نظر میرسه موضوعی که بهش اشاره دارین مربوط به CLI یا همون Warp-plus باشه
فکر میکنیم باید منتظر بروزرسانی بسته هسته باشین

ویژگی TUN هم هنوز آماده نشده، اما @kiomarzsss داره روش کار میکنه

**Comment by majix127** [comment]
بله cliهست
هر روز چک میکنم و منتظر آپدیت
فعلا شیفت میکنم رو ورژن قبل

**Comment by ircfspace** [comment]
روی ورژن قبل این مشکل رو نداشتین؟
دقیقن کدوم نسخه رو استفاده میکنین و ورژن قبل منظورتون دقیقن کدوم نسخه هست؟

آخرین نسخه‌ای که منتشر کردیم اینه:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.51.0-beta

**Comment by majix127** [comment]
ورژن قبلی اگر اشتباه نکنم ۰.۴۷ بود
قبلی این مشکلو نداشتم،مصرف باتری اوکی بود،مصرف اینترنت هم عادی،ولی ورژن
۰.۵۱ هم مصرف باتری و نت بالا رفته،حتی رو پی سی خونه هم همین مشکل هست،موقع
استفاده دمای سیستم بالاتر میره و مصرف نت غیر عادیه
در حال حاضر ورژن ۵۱ استفاده میکنم
ولی فردا برای تست دقیقتر ورژن ۴۷ رو نصب میکنم،
در ضمن ورژن ۰.۵۱ رو کامل پاک کردم و دوباره نصب کردم ولی هنوز مشکل پابر جاست

**Comment by ircfspace** [comment]
در بخش تنظیمات، به تنظیمات شبکه رجوع کرده و گزینه بررسی IP رو خاموش کنین؛ ببینین مصرف باتری تغییری میکنه؟

**Comment by majix127** [comment]
روی نت همراه اول فقط ایپی وی۶ کتر میکنه،نمیشه کاری کرد هر دو ایپی وی۴ و۶
کار‌کنن؟یه مدت اوکی بود
مرسی ک جواب میدین

**Comment by majix127** [comment]
فردا صبح تست میکنم و نتیجه رو میگم،ممنون

**Comment by majix127** [comment]
توی ورژن ۰.۴۷ این مشکل وجود نداره-مصرف باتری و نت بالا نیست و عادی هست

**Comment by ircfspace** [comment]
مشکل توسط @ShadowZagrosDev برطرف شده 
در آپدیت بعدی از برنامه میتونین گزینه **مصرف منابع** رو خاموش کرده و مجدد بررسیش کنین

**Comment by majix127** [comment]
ممنون،چیزی ک من متوجه شدم با فایروال ویندوز درگیری داشت
