### ISSUE TITLE
نمایش مدت زمان اتصال

### ISSUE THREAD

**Issue by omidmousavi** [bepass-org/oblivion-desktop#456]
### Feature description | توضیحات ویژگی

اگه موافق باشین میتونم کار برنامه نویسی و پول ریکوئستش رو انجام بدم...

![image](https://github.com/user-attachments/assets/3c9e8eef-6cd2-4be2-9998-e3d6f617ff13)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از پیشنهاد شما،
بله، ایده بدی نیست؛ فقط لطفا در تولتیپ مربوط به totalUsage قرار بگیره
