### ISSUE TITLE
نسخه دسکتاپ اوبویلیون با اینترنت دانلود منینجر هیچی نمیشه دانلود کرد از گوگل کروم 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#46]
### Feature description

سلام نسخه ویندوز obvilion دسکتاپ ای پی تمیز میدی دستی کار نمی کنه روی ایرانسل و همراه اول ومخابرات وشاتل   دوم سایفون مشکل داره وصل میشه هیچی باز نمی کنه سوم با اینترنت دانلود منینجر هیچی دانلود نمیشه کرد از سایت فیلتر شده

**Comment by inmemeoryof** [comment]
سلام، من که رو ویندوز نصب ندارمش بخوام بگم ولی میدونم idm تنظیمات پروکسی خودشو داره و تابع سیستم نیست، اینو تو تنظیماتش چک کن و پروکسی اپ رو اونجا اد بده

**Comment by seramo** [comment]
تنظیمات پروکسی idm رو روی سیستم پروکسی تنظیم کنید
![2024-05-05_22-24](https://github.com/bepass-org/oblivion-desktop/assets/23317510/f931f12b-6c89-413f-96d8-dfcc16efdd12)

**Comment by ircfspace** [comment]
ضمن تشکر از @seramo
نحوه پروکسی‌کردن سیستم رو در آپدیت‌های بعدی بهبود میدیم
