### ISSUE TITLE
عدم تنظیم صحیح سیستم پروکسی

### ISSUE THREAD

**Issue by Alizad00A** [bepass-org/oblivion-desktop#463]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با متصل شدن نرم افزار پروکسی سیستم به آدرس 0.0.0.0:8086 تنظیم می‌شود که در این حالت نرم افزارها و مرورگرها امکان دسترسی به اینترنت را ندارند.
با تنظیم دستی پروکسی از تنظیمات ویندوز به آدرس 127.0.0.1:8086 مشکل رفع می‌شود.

### Relevant log output | لاگ برنامه

```shell
[2024-08-06] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 0.0.0.0:8086 --gool --endpoint xxx --dns 1.1.1.1

time=2024-08-06 level=INFO msg="serving proxy" address=0.0.0.0:8086
```

**Comment by ircfspace** [comment]
سلام
از چه نسخه‌ای از برنامه استفاده میکنین؟
در تنظیمات شبکه، اگر گزینه اتصال از LAN رو روشن کردین، خاموشش کنین

**Comment by Alizad00A** [comment]
سلام درود
آخرین نسخه 0.58.3
بله با خاموش کردن اتصال از LAN مشکل حل شد.
