### ISSUE TITLE
عدم اتصال به فیبر نوری

### ISSUE THREAD

**Issue by ahmadipass** [bepass-org/oblivion-desktop#464]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام مشکلی که چند وقته به وجو اومده عدم اتصال به فیبر نوری هستش با بقیه نت ها راحت اتصال برقرار میشه ولی رویی فیبر اتصال برقرار نمیشه. ممنون میشم بررسی کنین.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

انجام تست روی ویندوز و اندروید با نت فیبر نوری مخابرات

### Relevant log output | لاگ برنامه

```shell
روی کانکتینگ میمونه
```

**Comment by ircfspace** [comment]
سلام
منتظر بروزرسانی بعدی warp-plus بمونین
