### ISSUE TITLE
روی مک ام وان کار نمی کند

### ISSUE THREAD

**Issue by arf79** [bepass-org/oblivion-desktop#466]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![Downloads](https://github.com/user-attachments/assets/7511f3c3-ca06-44d0-9e38-12ddcc1da85d)

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

installation

### Relevant log output | لاگ برنامه

```shell
nc
```

**Comment by ShadowZagrosDev** [comment]
@arf79  https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223

**Comment by ShadowZagrosDev** [comment]
@arf79 

Enter the commands from [this comment](https://github.com/bepass-org/oblivion-desktop/issues/206#issuecomment-2131312223) into your terminal.
