### ISSUE TITLE
It keeps showing "Oblivion Desktop is damaged and cannot be opened" on Mac ARM64

### ISSUE THREAD

**Issue by aliahmari** [bepass-org/oblivion-desktop#468]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

I have faced with this error that shows the app is damaged.
![Screenshot 2024-08-08 at 1 24 11 AM](https://github.com/user-attachments/assets/76047708-e0a7-44bf-9a07-ae47d1ccac45)
I've tried zip version of it but nothing changed.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Downloaded Oblivion Desktop for mac (ARM)
2. Unzipped it
3. Opened it
4. You will see this message: Oblivion Desktop is damaged and cannot be opened

### Relevant log output | لاگ برنامه

```shell
there is no log
```

**Comment by ircfspace** [comment]
سلام
تاپیک مشابه رو مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/206
