### ISSUE TITLE
Dont run on windows 11

### ISSUE THREAD

**Issue by hamidreza2000m** [bepass-org/oblivion-desktop#47]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

application runs but after click on connect button it did nothing and said متصل نیستید!

### Minimal Reproducible Example (MRE)

1.run
2.click on button connect
3. ...

### Version

0.2.44-beta

### Platform/OS

Windows

### Relevant log output

```shell
time=2024-05-05T19:09:58.563+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-05T19:09:58.569+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-05T19:09:58.577+03:30 level=ERROR msg="mkdir ./stuff: Access is denied."

time=2024-05-05T19:09:58.576+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hamidreza2000m** [comment]
if run program as admin , it runs ok

**Comment by ircfspace** [comment]
we will fix that in new update

**Comment by Majidzam1101** [comment]
> we will fix that in new update

چرا گول فقط المان سرور داره چرا فنلاند یا کشور دیگر ندارد ؟

**Comment by ircfspace** [comment]
برای آیپی سایر کشورها باید از گزینه سایفون (در آخرین نسخه) استفاده کنین

**Comment by Majidzam1101** [comment]
> برای آیپی سایر کشورها باید از گزینه سایفون (در آخرین نسخه) استفاده کنین

سلام خطای هویت سنجی نگفتی اشکالش از چیه این اخطار میده  نسخه  0.2.52

 لاینسس از جنترال گرفتم ورد کردم این خطا را  میزنه 
![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/5e999a13-a30d-4079-9660-7ec2b3e62ae6)
