### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by Miladdogecoin** [bepass-org/oblivion-desktop#471]
### Feature description | توضیحات ویژگی

سلام ممنون از زحماتی که میکشید- اگه امکان داره برای وارپ برنامه امکان انتخاب ای پی کشورهارو بذارید - مثلا بعضی ها ای پی ثابت نیاز دارن - روی یه کشور مشخص مثل مثلا المان - اگه امکان داره امکان انتخاب کشور روی حالت وارپ هم بذارید - فقط جوری باشه که حتما با انتخاب کشور ای پی هم همون باشه - با تشکر از زحماتتون

**Comment by ircfspace** [comment]
سلام

امکان انتخاب لوکیشن و تغییر IP به کشور خاص از طریق **متد سایفون** میسر هست
در رابطه با سایر متدها متاسفانه چنین امکانی وجود نداره

**Comment by Miladdogecoin** [comment]
خب - یعنی نمیتونید بذارید؟؟ نمیشه کلا؟

**Comment by ircfspace** [comment]
خیر، چنین امکانی در سرویس وارپ کلودفلر وجود نداره

**Comment by Miladdogecoin** [comment]
ممنونم
