### ISSUE TITLE
زیاد شدن علکی سرعت آپلود بعد از وصل شدن

### ISSUE THREAD

**Issue by esmail-mkh** [bepass-org/oblivion-desktop#474]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سرعت آپلود اینترنتم بعد از وصل شدن بیهوده زیاد میشه و کم هم نمیشه دوستان کسی می دونه چطور میشه این مشکل رو حل کرد؟

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by ircfspace** [comment]
این‌مورد رو باید در [warp-plus](https://github.com/bepass-org/warp-plus) مطرح کنین
