### ISSUE TITLE
وصل نشدن ورژن 1.1

### ISSUE THREAD

**Issue by Abolfazl2687** [bepass-org/oblivion-desktop#479]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

بعد از اپدیت به ورژن 1.1 وصل نمیشه به محض اینکه دکمه اتصال فعال میکنی خودش رو غیرفعال میکنه

### Relevant log output | لاگ برنامه

```shell
system proxy turned off
```

**Comment by ircfspace** [comment]
یکبار تنظیمات برنامه رو ریست کنین

همچنین امکان استفاده از نسخه‌های قدیمی همچنان میسر هست:
https://github.com/bepass-org/oblivion-desktop/releases
