### ISSUE TITLE
Hello, Is there any way to connect in windows 8.1 ?

### ISSUE THREAD

**Issue by Sam-EY** [bepass-org/oblivion-desktop#482]
### Feature description | توضیحات ویژگی

Hello, Is there any way to connect in windows 8.1 ?  Thank You

سلام.
آیا راهی برای اتصال در ویندوز 8.1 وجود دارد؟
سپاسگزارم

**Comment by ircfspace** [comment]
سلام
متاسفانه درحال‌حاضر خیر
