### ISSUE TITLE
تونل پس کی اضافه میشه؟

### ISSUE THREAD

**Issue by mrgamerrg** [bepass-org/oblivion-desktop#492]
### Feature description | توضیحات ویژگی

خیلی وقته منتظره قابلیت تونل هستم ولی ورژن 1 هم اومده ولی قابلیت اضافه نشده

**Comment by ircfspace** [comment]
ویژگی TUN در ورژن ۲ در دسترس قرار میگیره
دو نفر از مشارکت‌کنندگان دارن روی این‌موضوع کار میکنن

**Comment by mrgamerrg** [comment]
ممنون بخاطره زحماتتون
