### ISSUE TITLE
Program path and binary name

### ISSUE THREAD

**Issue by someonemax** [bepass-org/oblivion-desktop#496]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Can you please not play with the program path and binary name on every patch?!
This breaks our scripts. :)

You went from 
"C:\Program Files\Oblivion Desktop\OblivionDesktop.exe" 
To 
"C:\Program Files\Oblivion Desktop\OblivionDesktop\OblivionDesktop.exe"
And then to:
"C:\Program Files\Oblivion Desktop\OblivionDesktop\oblivion-desktop\oblivion-desktop.exe"

In a matter of 3 patches. 

Please just choose a path and binary name and stick with it! :pray:

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

NA

### Relevant log output | لاگ برنامه

```shell
NA
```

**Comment by ircfspace** [comment]
It's not possible :)
You’re probably aware that this issue doesn't exist in the stable version, and the concern you're mentioning is related to pre-release versions. Naturally, when we change the name, we're not just playing around; we're trying to address user issues on Linux.

Once the issue reported in #467 is resolved, there won't be any further changes.

Anyway, thanks for your feedback!
