### ISSUE TITLE
برنامه نسخه بیلد شده  در سیستم عامل ابونتو باز نمی شود

### ISSUE THREAD

**Issue by MahyarGdz** [bepass-org/oblivion-desktop#497]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

برنامه در سیستم عامل ابونتو باز نمی شود و مشکل دارد و هیچ لاگی نیز برای دیباگ وجود ندارد

### Relevant log output | لاگ برنامه

```shell
there is no log
```

**Comment by samavatmilad** [comment]
اگر از فایل .deb استفاده کردید پس از نصب به این محل برید:
/usr/share/applications
با یک editor در حالت root فایل oblivion-desktop.desktop را باز کنید و قسمت Exec که الان به این شکل است:
Exec="/opt/Oblivion Desktop/oblivion-desktop" %U
به این شکل عوض کنید:
Exec="/opt/Oblivion Desktop/oblivion-desktop" --no-sandbox %U
حالا با استفاده از این دستور اگر از gnome استفاده می‌کنید آن را ریستارت کنید:
sudo systemctl restart gdm
حالا اگر باز کنید درست کار می‌کند.

**Comment by MahyarGdz** [comment]
thanks its work now
