### ISSUE TITLE
پینگ دریافتی

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/oblivion-desktop#5]
### Feature description

با سلام و تشکر بابت زحمتتاتون
سوال فنی وارپ وصل میشیم پینگ المان میده راهی هست پینگ بحرین یا امارات متحده عربی بده؟!!
برای گیم و پینگ میپرسم

**Comment by ircfspace** [comment]
سلام
به‌طور پیشفرض گزینه «گول» فعال هست. باید از تنظیمات گول رو غیرفعال کرده و سایفون رو فعال کنین. اونجا میتونین لوکیشن موردنظرتون رو انتخاب کنین

**Comment by WeebMan1** [comment]
ممنون بابت پاسخ ، ولی منظورم چیز دیگه ای هست
وقتی از warp خالی هم استفاده کنیم و ای پی ایران بگیریم، پایین ترین پینگ ما از المان هست مثلا حدود 120ms
امکانش هست پایین ترین پینگ ما برای بحرین یا دبی باشه ک پینگشون در حد 40 تا 50 هست؟ (منظورم این نیست ای پی اون کشور ها رو بگیریم)

**Comment by ircfspace** [comment]
این‌مورد رو باید اینجا ایشو کنین :

https://github.com/bepass-org/warp-plus/issues

**Comment by WeebMan1** [comment]
تشکر

**Comment by Majidzam1101** [comment]
> این‌مورد رو باید اینجا ایشو کنین :
> 
> https://github.com/bepass-org/warp-plus/issues
سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه




![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/7ec39b10-5845-409e-8ff5-b5d9c31850a4)
![Screenshot (7)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/0816c786-a253-41f1-994c-e11d087feffd)
