### ISSUE TITLE
باگ نمایش ندادن میزان مصرف اینترنت و ارسال و دریافت دیتا

### ISSUE THREAD

**Issue by majix127** [bepass-org/oblivion-desktop#501]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود بر شما
ورژن 1.6.13 و 1.6.15 توی ویندوز 11 نسخع 24h2 بعد از اتصال ،میزان مصرف دیتا و سند و ریسیو نمایش داده نمیشه-هر دو نسخه رو پاک کردم و دوباره نصب کردم-ولی بازم مشکل حل نشد
دمتون گرم و سرتون سلامت
![Screenshot 2024-08-24 064250](https://github.com/user-attachments/assets/c24c7aea-7317-4813-816b-f33cc0589957)

### Relevant log output | لاگ برنامه

```shell
[2024-08-24 06:57:09.458] [info]  past logs was deleted for new connection.
[2024-08-24 06:57:09.464] [info]  ------------------------MetaData------------------------
[2024-08-24 06:57:09.466] [info]  running on: win32 10.0.26100 x64
[2024-08-24 06:57:09.467] [info]  at od: 1.6.13
[2024-08-24 06:57:09.467] [info]  at wp: v1.2.4
[2024-08-24 06:57:09.469] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe
[2024-08-24 06:57:09.470] [info]  method: gool
[2024-08-24 06:57:09.471] [info]  proxyMode: true
[2024-08-24 06:57:09.472] [info]  routingRules: Default
[2024-08-24 06:57:09.473] [info]  endpoint: custom
[2024-08-24 06:57:09.474] [info]  asn: MKH
[2024-08-24 06:57:09.475] [info]  license: false
[2024-08-24 06:57:09.476] [info]  exe: C:\Users\<USERNAME>\AppData\Local\Programs\OblivionDesktop\oblivion-desktop\oblivion-desktop.exe
[2024-08-24 06:57:09.497] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-08-24 06:57:09.499] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-08-24 06:57:09.500] [info]  ------------------------MetaData------------------------
[2024-08-24 06:57:09.503] [info]  starting wp process...
[2024-08-24 06:57:09.504] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8086 --gool --endpoint 162.159.195.147:3476 --dns 94.140.14.14
[2024-08-24 06:57:10.142] [info]  trying to set system proxy...
[2024-08-24 06:57:10.620] [info]  system proxy has been set.
time=2024-08-24T06:57:11.217+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.147:3476 162.159.195.147:3476]"
time=2024-08-24T06:57:11.218+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-08-24T06:57:11.219+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-24T06:57:18.932+03:30 level=INFO msg="connection test successful"

time=2024-08-24T06:57:18.936+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-24T06:57:20.827+03:30 level=INFO msg="connection test successful"

time=2024-08-24T06:57:20.827+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086
```

**Comment by ircfspace** [comment]
سلام
احساس میکنم آنتی‌ویروس این‌مشکل رو رقم زده باشه
طبق [این‌توضیحات](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) پیش‌برید

**Comment by majix127** [comment]
درود بر شما
مواردی ک گفتین انجام دادم ولی متاسفانه مشکل پابرجاست فعلا
ب هر حال دمتون گرم

**Comment by ircfspace** [comment]
متاسفانه به طور دقیق نمیدونم مشکل از چی هست، اما اگر راه‌حلی براش پیدا شد حتمن لحاظ میکنیم
تا قبل از اون از تنظیمات غیرفعالش کنین، که مصرف CPU بی‌دلیل بالا نره

**Comment by majix127** [comment]
اوکی
ورژن ۱.۱ هم سریع تر هست هم پایدار تر،هم این مشکل نیس
زنده باشین
ورژن اندروید اپدیتی نمیدین؟یسری مشکلات  داره

**Comment by ShadowZagrosDev** [comment]
@majix127 @ircfspace 
https://media.tenor.com/dmUPx0eFh4AAAAAC/fuck-microsoft.gif
ممنون از گزارش و منشن
طبق توضیحات، در نسخه‌های ۱.۱۶.۱۵ و ۱.۱۶.۱۳ به این مشکل برخوردید که توی این نسخه‌ها تغییری در اون بخش ایجاد نشده. امکان داره نسخه ۱.۶.۶ رو هم تست کنید؟
گفتید که در نسخه ۱.۱ چنین مشکلی نیست. این نسخه رو الان نصب دارید و مشکلی نداره؟

**Comment by majix127** [comment]
درود بر شما
نسخه 1.6.6 پایداری خوبی نداشت و مصرف سخت افزار زیادی داشت-cpu usage بالا و
مصرف نت بالایی داشت-توی نسخه 1.6.13 و 1.6.15 مشخل مصرف نت و سخت افزار
نداشتم-ولی نمایش میزان مصرف و سرعت انتقال کار نمیکنه-توی نسخه 1.1 شدیدا
پایداره و مصرف نت و سخت افزار نزدیک 1 درصده ک فوق العادست-سرعت نت هم تو
نسخه 1.1 هم عالیه-
در ضمن این نسخه هارو هم تو لپ تاپ تست کردم هم پی سی -دقیقا تو هر دو تا
کامپیوتر همین شرایط بود و نسخه 1.1 بهترین بود-در ضمن هردو ویندوز 11 بودن
ورژن 24h2

**Comment by ShadowZagrosDev** [comment]
@majix127 
ممنون از توضیحات. مشکل نمایش اطلاعات سرعت و مصرف داده رفع و مصرف منابع در این رابطه بهینه شده. و در نسخه بعدی اعمال میشه. لطفا بعد از انتشار، تست و اگر مشکلی بود بازم گزارش بدید.

**Comment by majix127** [comment]
سپاس فراوان
نسخه اندروید اپدیتی ندارین؟یه مقدار نا پایدار هست؟

**Comment by ircfspace** [comment]
@majix127 
تقریبن آماده‌س و بعد از باگ‌فیکس، در روزهای آینده در دسترس قرار میدن

**Comment by majix127** [comment]
دمتون گرم

**Comment by ircfspace** [comment]
بروزرسانی جدید به‌صورت نسخه پیش‌ازانتشار در دسترس قرار گرفت
https://github.com/bepass-org/oblivion-desktop/releases/tag/v1.6.22
@majix127 

---
* با تشکر از @ShadowZagrosDev برای رفع مشکل.

**Comment by majix127** [comment]
درود بر شما عزیزان
یسری باگ هست از جمله کندی سرعت.و یه باگ دیگه اینه  بعد از وارد کردن
اندپوینت دستی وقتی میخوای

**Comment by majix127** [comment]
رود بر شما عزیزان
فکر کنم یه ایمیل ناقص ارسال شد -متاسفانه دستم خورد و ناقص شد
یه باگ مشکل سرعت اینترنت هست -و باگ دیگه اینه که توی پروفایل اندپوینت وارد
میکنیم ،قسمت اندپوینت دیپه وارد نمیشه و فریز میشه-رکورد گرفتم و ارسال میکنم
ببینین-
و یه مشکل دیگه اینه دیفندر ویندوز تو این نسخه اخر هم خود فایل و هم بعد نصب
به عنوان ویروس میشناسه و بلاک میکنه
دمتون گرم

**Comment by majix127** [comment]
اسکرین رکورد باگ

**Comment by ircfspace** [comment]
درخصوص آنتی‌ویروس [اینجا رو](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) مطالعه کنید

درخصوص اندپوینت‌های ذخیره شده [اینجا رو ](https://github.com/bepass-org/oblivion-desktop/issues/473#issuecomment-2276824763) مطالعه کنید یا تنظیمات برنامه رو بازیابی کنین

درخصوص کندی سرعت اتصال هم باید [اینجا](https://github.com/bepass-org/warp-plus/issues) ایشو بزنین
