### ISSUE TITLE
مشکل نمایش پینگ و سرعت در نسخه ی جدید 

### ISSUE THREAD

**Issue by alicarnage** [bepass-org/oblivion-desktop#502]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با وجود وصل بودن تایم اوت نمایش داده می شود و پینگ و سرعت مشخص نیست 
![Screenshot 2024-08-25 010437](https://github.com/user-attachments/assets/540134e0-c6c7-4351-b2c9-db999de57ff2)

### Relevant log output | لاگ برنامه

```shell
time=2024-08-25T00:55:55.393+03:30 level=INFO msg="serving proxy"
```

**Comment by ircfspace** [comment]
سلام
تاپیک مشابه: https://github.com/bepass-org/oblivion-desktop/issues/501#issuecomment-2308514058
