### ISSUE TITLE
باز نشدن در ویندوز یازده

### ISSUE THREAD

**Issue by efithatkid** [bepass-org/oblivion-desktop#504]
### Attention | توجه

- [x] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام. داستان ازین قراره که وقتی لپ تاپو روشن میکنم و برای اولین بار برنامه رو باز میکنم همچی اوکیه. ولی وقتی میبندم و دوباره باز میکنم باز نمیشه. یعنی رسما هیچ اتفاقی نمی‌افته. حذف و نصب هم کردم ولی درست نشد

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. بستن برنامه
2. باز نشدن برنامه برای دومین بار

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by ircfspace** [comment]
سلام
مشخص نیست از چه نسخه‌ای استفاده میکنین
لاگ برنامه رو ارسال کرده و ترجیحن یک ویدئو از فرایند برام ارسال کنین
