### ISSUE TITLE
استفاده از Tauri

### ISSUE THREAD

**Issue by Silitonix** [bepass-org/oblivion-desktop#509]
### Feature description | توضیحات ویژگی

سلام و درود ! دوستان عزیز لطفا از الکترون و nwjs برای ساخت پورت دیسکتاپ استفاده نکنید ! برای استفاده میتونید از Tauri استفاده کنید باندل سایز خیلی کمتری داره و ایمن تره!

https://tauri.app/

یا میتونید از HTA هم استفاده کنید ولی خب خوب نیست

**Comment by ircfspace** [comment]
سلام
تشکر از پیشنهاد، البته کمی دیر شده :‌)

پ.ن: در ماه‌های آینده oblivion به‌صورت مالتی‌پلتفرم، به‌طور کامل روی فلاتر جلو میره.

**Comment by Silitonix** [comment]
خیلی عالی ! فلاتر هم گزینه خیلی خوبیه ولی برای اینکه راحت تر باشه نخواین کل کد رو تغییر بدید گفتم ! عالی موفق باشید.
