### ISSUE TITLE
اشتراک گذاری از طریق پروتکل socks 

### ISSUE THREAD

**Issue by itskazemk** [bepass-org/oblivion-desktop#51]
### Feature description

سلام خسته نباشید واقعا، ممنون میشم در صورت امکان قابلیتی مانند v2rayn اضافه کنید تا بشه روی socks تنظیم کرد که دیگه نیازی به خاموش روشن کردن vpn نباشه و داخل برنامه ای مانند SwitchyOmega بشه وصل شد بهش. ❤️

**Comment by itskazemk** [comment]
تازه دیدم از قبل همچون درخواستی شده.

**Comment by ircfspace** [comment]
سلام
تشکر از شما
در بروزرسانی‌های بعدی اضافه میکنیم
