### ISSUE TITLE
نسخه ios 

### ISSUE THREAD

**Issue by developerjava1366** [bepass-org/oblivion-desktop#513]
### Feature description | توضیحات ویژگی

ممنون و خسته نباشید بابت پروژه خوبتون. نسخه ios ولی دیگه خیلی طول کشید ممنون میشیم بفکر اونم باشید

**Comment by amirhosseinamini145** [comment]
دقیقا درسته،ضمن تشکر از تلاش بی مزد و منت که این تیم عالی با وجود همه مشکلات میکشن واقعا تو زمینه استارت پروژه ios این نرم افزار تاخیر وجود داره البته با تاکید اینکه بابد قبول کنیم اینکار بسیار مشکل و زمانبر هست این مورد رو گفتم،درسته که جمعیت کاربر ios تو کشور ما از اندروید کمتره ولی به هر حال جمعیت چند میلیونی این سیستم عامل واقعا نیاز مبرم و میشه گفت فوری به این نرم افزار دارن چون محدودیتهای شرکت اپل باعث شده تو این زمینه نیاز به کمک بیشتری داشته باشن

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،
این ریپازیتوری مربوط به نسخه دسکتاپ هست؛ در رابطه با موبایل باید [اینجا](https://github.com/bepass-org/oblivion/issues) ایشو بزنید
