### ISSUE TITLE
"oblivion-desktop.app" is damaged and can't be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by momalekiii** [bepass-org/oblivion-desktop#514]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

After download version 1.6.15 macOs arm64, deleted previous version and installed the new one, but it says its damaged and cannot be opened.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

after installation process, just double click on the icon

### Relevant log output | لاگ برنامه

```shell
-
```

**Comment by momalekiii** [comment]
![Uploading Screenshot 1403-06-07 at 00.23.04.png…]()

**Comment by ircfspace** [comment]
سلام
ایشوی مشابه رو [مشاهده کنید](https://github.com/bepass-org/oblivion-desktop/issues/206)
