### ISSUE TITLE
missing metadata package

### ISSUE THREAD

**Issue by ali-pourhadi** [bepass-org/oblivion-desktop#515]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

error :  
error: missing package metadata in oblivion-desktop-linux-x64 (1).tar.xz
error: 'oblivion-desktop-linux-x64 (1).tar.xz': invalid or corrupted package

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

installation

### Relevant log output | لاگ برنامه

```shell
bug during installation (no log)
```

**Comment by ircfspace** [comment]
از چه ورژنی استفاده میکنین؟
بسته رو مجددا دریافت کنین

**Comment by ali-pourhadi** [comment]
> از چه ورژنی استفاده میکنین؟ بسته رو مجددا دریافت کنین

دوباره هم ریختم ولی بازم همون ارور رو میده ورژن هم 1.6.15 عه .. رو لینوکس مانجارو

**Comment by ircfspace** [comment]
آخرین نسخه 1.6.22 هست:
https://github.com/bepass-org/oblivion-desktop/releases

**Comment by ali-pourhadi** [comment]
فرقی نداره بازم همون ارور قبلی رو میده متاسفانه

**Comment by ircfspace** [comment]
ایشو رو باز کردم و لیبل Linux زدم، تا شاید سایرین بتونن مساله رو بررسی و راهنماییتون کنن

**Comment by kiomarzsss** [comment]
بعد از اجرای چه دستوری چنین اروری گرفتین؟

**Comment by NIMANITRO** [comment]
i use ''' sudo pacman -U ''' and show this error

**Comment by kiomarzsss** [comment]
oblivion desktop does not have an official package for pacman/arch. you can use it on arch by simply extracting tar.gz file and running oblivion-desktop binary dirctly.
