### ISSUE TITLE
windows bluescreen while using oblivion

### ISSUE THREAD

**Issue by COD-sg** [bepass-org/oblivion-desktop#518]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Each time I use oblivion desktop on my windows 11 , I get bluescreen after some time.

### Relevant log output | لاگ برنامه

```shell
on bluescreen it shows error with tiltle: DPC Watchdog violation
```

**Comment by ircfspace** [comment]
Hello,
Which version are you using? 
https://github.com/bepass-org/oblivion-desktop/releases

**Comment by COD-sg** [comment]
1.6.15

**Comment by S3CRE-7** [comment]
well DPC is a driver issue most likely caused by RAM or GPU, but the other reason could be sth with the app and the anti virus, which anti-virus are you using?

**Comment by mayanima2016** [comment]
سلام در ویندوز 10 نسخه دسکتاپ هم ورژن بتا و هم نسخه پایین وقتی میخوام اسکنر فعال کنم صفحه سیاه میشه و امکان استفاده نمیده کلا قفل میشه و باید از تسکبار خروج بزنیم ممنون میشم اگر راهی برای این مشکل هست توضیح بدید.

**Comment by ircfspace** [comment]
> 
سلام در ویندوز 10 نسخه دسکتاپ هم ورژن بتا و هم نسخه پایین وقتی میخوام اسکنر فعال کنم صفحه سیاه میشه و امکان استفاده نمیده کلا قفل میشه و باید از تسکبار خروج بزنیم ممنون میشم اگر راهی برای این مشکل هست توضیح بدید.


برای این موضوع یک ایشوی جدید ایجاد کرده و لاگ برنامه رو قرار بدین، تا اگر خطایی وجود داره دیده بشه و ورژنی که استفاده کردین قابل رویت باشه
