### ISSUE TITLE
خطا The warp-plus file is not located alongside the application package!

### ISSUE THREAD

**Issue by holms2012** [bepass-org/oblivion-desktop#519]
### Feature description | توضیحات ویژگی

درود و سپاس
رو دسکتاپ این خطارو میده

The warp-plus file is not located alongside the application package!

**Comment by ircfspace** [comment]
سلام
مجددا برنامه رو دریافت نموده و نصب کنید

توضیحات تکمیلي: https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3
