### ISSUE TITLE
عدم اتصال در ویندوز 

### ISSUE THREAD

**Issue by Samaneh2022** [bepass-org/oblivion-desktop#52]
### Feature description

اداره ما شبکه داره و با اکانت وصل میشیم، اینجا اصلا تو ویندوز وصل نمیشه

**Comment by reza-ashoori** [comment]
برنامه رو موقع اجرا روی حالت administrator

**Comment by ircfspace** [comment]
در نسخه بعدی مشکل مذکور حل میشه

**Comment by Samaneh2022** [comment]
سلام، با administrator هم درست نشد
