### ISSUE TITLE
حذف تبلیغات یوتیوب

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#525]
### Feature description | توضیحات ویژگی

درود بر شما...
میخواستم بدونم برای تیم عزیز oblivion امکانش هست که تبلیغات youtube  بواسطه این فیلترشکن حذف بشه یا به حداقل برسه؟
مثل یک سری از نرم افزار های vpn دیگر؟؟؟

**Comment by ircfspace** [comment]
سلام
احتمالن با مراجعه به بخش تنظیمات » تنظیمات شبکه » DNS بتونین نتیجه مناسب رو بدست بیارین

**Comment by ShadowZagrosDev** [comment]
سلام. خیر. از طریق DNS نمیشه تبلیغات یوتیوب رو مسدود کرد. چون تبلیغات و محتوای اصلی از یک جا پخش میشن. حذف تبلیغات در سطح DNS از طریق مسدود کردن دامین های تبلیغات انجام میگیره. حالا اگر شما بخوای دامین یوتیوب رو برای تبلیغات مسدود کنی، محتوای اصلی هم مسدود میشن در نتیجه.

**Comment by behzadchtp** [comment]
> سلام. خیر. از طریق DNS نمیشه تبلیغات یوتیوب رو مسدود کرد. چون تبلیغات و محتوای اصلی از یک جا پخش میشن. حذف تبلیغات در سطح DNS از طریق مسدود کردن دامین های تبلیغات انجام میگیره. حالا اگر شما بخوای دامین یوتیوب رو برای تبلیغات مسدود کنی، محتوای اصلی هم مسدود میشن در نتیجه.

پس چطوری میشه که بعضی از این اپ های vpn رو که کانکت میکنیم یوتیوب تبلیغی پخش نمیکنه؟؟؟
