### ISSUE TITLE
Connectivity Ports

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#526]
### Feature description | توضیحات ویژگی

در ابتدا پوزش میخوام که این تاپیک رو اینجا میذارم چون نمیدونستم پرسشم رو در کدوم قسمت باید بذارم...
پرسشم اینه که oblivion برای نسخه اندروید destination port هایی که تو لاگ خود برنامه میندازه هر بار ثابت هست؟؟ 
چون من میخوام تو فایروال destination port هاییکه تو لاگ میندازه رو به عنوان rule  تراست بذارم که فایروال اجازه عبور این پورت ها رو بده...

**Comment by ircfspace** [comment]
سلام
این‌سوال رو باید [اینجا](https://github.com/bepass-org/oblivion/issues) مطرح کنین، تا پاسخ مناسب دریافت کنین
