### ISSUE TITLE
مشکل ویروس trojan

### ISSUE THREAD

**Issue by masood40** [bepass-org/oblivion-desktop#528]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در زمان نصب و استفاده انتی ویروس eset  به صورت تروجان میشناسه و ارور میده و حذف میشه
لاگ هم اارسال شد
![Uploading Screenshot 2024-09-05 162709.jpg…]()

### Relevant log output | لاگ برنامه

```shell
﻿Time;Scanner;Object type;Object;Detection;Action;User;Information;Hash;First seen here
15/06/1403 04:26:13 ب.ظ;Real-time file system protection;file;C:\Program Files\oblivion-desktop\resources\assets\bin\warp-plus.exe;a variant of WinGo/TrojanDropper.Agent_AGen.I trojan;cleaned by deleting;WEB3\websama;Event occurred on a new file created by the application: C:\Users\websama\Downloads\oblivion-desktop-win-x64_3.exe (87BDC6D653F71BB7EBDB1B04E19AB6882E44C296).;36BD0F138BB89562069C4CFC213E0ACCFD51EE12;18/05/1403 07:17:47 ب.ظ
```

**Comment by ircfspace** [comment]
سلام
در رابطه با فالس‌پازتیو [اینجا](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) توضیح دادیم
