### ISSUE TITLE
پکیج لینوکس

### ISSUE THREAD

**Issue by azi1233** [bepass-org/oblivion-desktop#53]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام.
لینک دانلود پکیچ لینوکس، هم deb و  هم rpm و هم tar کار نمیکنه.

### Minimal Reproducible Example (MRE)

1. Go to oblivion-desktop GitHub.
2. Linux download links are broke.

### Version

v0.2.44-beta

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

تا چندروز آینده نسخه مک و لینوکس منتشر میشن

**Comment by Majidzam1101** [comment]
> سلام
> 
> تا چندروز آینده نسخه مک و لینوکس منتشر میشن
سلام قابلیت اشتراک گزاری وی پی ان  از دستگاه کامپیوتر به دستگاه دیگر ندارد
