### ISSUE TITLE
ارور بسته نشدن

### ISSUE THREAD

**Issue by kianaabd** [bepass-org/oblivion-desktop#530]
### Feature description | توضیحات ویژگی

![Screenshot 2024-09-06 214734](https://github.com/user-attachments/assets/77bb5424-64a0-4652-96c6-5de1d18fc750)
امروز نصب کردم اولش کار کرد برنامه رو بستم وقتی امدم دئباره استفاده کنم باز نشد هرکاری کردم حذفش کردم امدم نصبش کنم این ارور رو داد.

**Comment by ircfspace** [comment]
آیکون برنامه رو کنار ساعت پیدا کرده و بعد از کلیک‌راست کردن روی اون، خروج بزنید

**Comment by kianaabd** [comment]
برنامه اوکی شد نصب شد برام ولی نمیتونم واردش شم یه بار کار کرد بعدش از کار افتاد چیکار کنم درست میشه؟

**Comment by ircfspace** [comment]
یه ویدئو از پروسه‌ای که بهش اشاره دارید گرفته و اینجا ارسال کنین
