### ISSUE TITLE
خطا در اتصال در پی سی

### ISSUE THREAD

**Issue by hani9349** [bepass-org/oblivion-desktop#531]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام برای من تو ی پی سی ارور : فایل warp-plus در کنار بسته نصب نشده است میاد من فایل warp-plus هم دانلود کردم توی پوشه یردم ولی باز این ارور رو داد لطفا راهنمایی کنید ممنون

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by ircfspace** [comment]
سلام
مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/500#issuecomment-2306919887

**Comment by hani9349** [comment]
.

**Comment by hani9349** [comment]
اها ممنون
