### ISSUE TITLE
ارور موقع نصب در دسکتاپ

### ISSUE THREAD

**Issue by soodi592** [bepass-org/oblivion-desktop#536]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی که نسخه جدید برنامه رو دانلود و نصب کردم، windows defender ارور PUA:win32/Vigua.A می دهد لطفا رفع کنید.

### Relevant log output | لاگ برنامه

```shell
برنامه نصب نشد
```

**Comment by ircfspace** [comment]
سلام
[مطالعه کنید](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3)
