### ISSUE TITLE
لوکیشن آرژانتین

### ISSUE THREAD

**Issue by arashshrf** [bepass-org/oblivion-desktop#539]
### Feature description | توضیحات ویژگی

با سلام و خسته نباشید
ممنون از شما و تیم برای این اپ عالی
فقط ممکنه لوکیشن آرژانتین هم اضافه بشه
ممنون

**Comment by ircfspace** [comment]
سلام
لوکیشن‌ها، لوکیشن‌های پشتیبانی‌شده در سایفون هستند، و متاسفانه امکان اضافه‌کردن لوکیشن جدید تا زمانی‌که توسط سایفون پشتیبانی نشه وجود نداره
