### ISSUE TITLE
عدم اتصال با لایسنس وارپ پلاس

### ISSUE THREAD

**Issue by Miladeos** [bepass-org/oblivion-desktop#54]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
برنامه در حالت پیشفرض متصل میشه ولی وقتی لایسنس وارپ پلاس وارد میکنم متصل نمیشه و هیچ اروری نمیده. با تعداد زیادی لایسنس که روی خود اپ وارپ کار میکنن تست کردم ولی با هیچکدوم متصل نشد.
ویندوز 11- 64بیتی

### Minimal Reproducible Example (MRE)

1. Proxy settings
2. License

### Version

0.2.44-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از گزارش شما،

1. برای خطاها یه سری توست درنظر گرفته شد، تا وقتی خطایی رخ میده بهتر بشه علتشو مطلع شد؛ این مورد توی آپدیت بعدی در دسترس قرار میگیره
2. مشکل ست شدن لایسنس، یه مشکل از سمت هسته warp-plus هست که به توسعه‌دهندگانش گزارش شد. اونور حل شه، اینورم اوکی میشه
