### ISSUE TITLE
مشکل اجرا شدن نسخه DMG ARM64

### ISSUE THREAD

**Issue by sorousheta** [bepass-org/oblivion-desktop#543]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام وقت بخیر
دیوایس من m2 هست ولی با نسخه arm مشکل داشت و اجرا نشد!
ولی نسخه x65 بدرستی عمل کرد ولی خیلی کند در روند اجرا.
نسخه مناسب برای پردازنده های اپل سلیکون کدامین نسخه هست؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

۱

### Relevant log output | لاگ برنامه

```shell
۱
```

**Comment by MohsenFazaeli** [comment]
نسخه m3 pro هم میگه فایل دمیج شده و بازش نمیکنه هر دو فایل ARM رو چندبار دانلود کردم. بنظر یه مشکلی هست

**Comment by kiomarzsss** [comment]
سلام لطفا این لینک رو چک کنید:

https://github.com/bepass-org/oblivion-desktop/issues/206
و اگر مشکل حل نشد لطفا چک کنید که روی پکیج zip هم مشکل پابرجاست؟

**Comment by MohsenFazaeli** [comment]
برای من کار کرد اول باید نصب کنیم بعد که میگه میخوام پاک کنم پاک نکنیم اینکارو کنیم.

**Comment by ircfspace** [comment]
توضیحات مرتبط: https://github.com/bepass-org/oblivion-desktop/wiki/%D8%B1%D9%81%D8%B9-%D8%AE%D8%B7%D8%A7%DB%8C-%E2%80%9COblivion-Desktop%E2%80%9D-is-damaged-and-can%E2%80%99t-be-opened
