### ISSUE TITLE
نسخه tun اوبویلیون چه زمانی منتشر می شود ؟

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#544]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

نسخه tun اوبویلیون چه زمانی منتشر می شود ؟

### Relevant log output | لاگ برنامه

```shell
نسخه tun اوبویلیون چه زمانی منتشر می شود ؟
```

**Comment by ircfspace** [comment]
زمان دقیقش مشخص نیست

توضیحات رو مطالعه کنید: https://github.com/bepass-org/oblivion-desktop/issues/532
