### ISSUE TITLE
IRAN IP LOCATION

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#545]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

دوسه روزه وقتی oblivion کانکت میشه با لوکیشن ایران کانکت میشه. خوب یوتیوب و تلگرام و اینستاگرام و.... رو باز میکنه ولی سایت هایی که ایران رو تحریم کردن رو باز نمیکنه مثل chatgpt , Intel , vmware و....
قبلا با لوکیشن آلمان همه چیو باز میکرد. ولی لوکیشن ایران سایت هاییکه ایران رو تحریم کردم رو باز نمیکنه.
چکار کنم که oblivion با لوکیشن ایران کانکت نشه؟؟؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

باز کردن وب سایت هاییکه ایران رو تحریم کردم مثل intel و chatgpt و vmware و نمایش پیغام ip منطقه ما اجازه دسترسی به وب سایت را ندارد.

### Relevant log output | لاگ برنامه

```shell
no log
```

**Comment by Dariush-ss** [comment]
اگر حالت warp تنها وصل بشین ایرانه، ولی اگر با gool متصل شدین و ایران بود، مشکله dns برنامه است، روی گوگل، ایران میشه. روی کلود، آلمان میشه.

**Comment by Azare77** [comment]
> اگر حالت warp تنها وصل بشین ایرانه، ولی اگر با gool متصل شدین و ایران بود، مشکله dns برنامه است، روی گوگل، ایران میشه. روی کلود، آلمان میشه.

جدیدا با حالت گول با هر DNS لوکیشن رو ایران میده

**Comment by ircfspace** [comment]
سلام

این‌مشکل به‌نظر میرسه یه اختلال از سمت کلودفلر باشه
چون با DNS پیشفرض هم دیروز چندین‌مرتبه همین‌مشکل رو روی متد گول داشتم، اما با تغییر اندپوینت برطرف شد

**Comment by amirrezaDev1378** [comment]
راهی برای جلوگیری از این مسئله هست ؟ شما از چه اند پوینتی استفاده کردید ؟
@ircfspace

**Comment by ircfspace** [comment]
به نسخه 1.10.3 یا نسخه‌های جدیدتر بروزرسانی کنین:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v1.10.3

**Comment by amirrezaDev1378** [comment]
روی آخرین نسخه هستم.

با حالت گول و Cloudflare امتحان میکنم بعضی وقت ها بهم آیپی ایران میده.

@ircfspace

**Comment by amirrezaDev1378** [comment]
نه این کار رو نمیکنه، یک ایشو جدید ساختم براش.

https://github.com/bepass-org/oblivion-desktop/issues/578

@ircfspace
