### ISSUE TITLE
خطای احراز هویت میزنه و روی حالت گول پرچم و ای پی ان میزنه 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#547]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

خطای احراز هویت میزنه و روی حالت گول پرچم و ای پی ان میزنه 

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

![Screenshot (236)](https://github.com/user-attachments/assets/3f5f3dc4-51a3-4ff6-b4cc-55b2e9e872cd)
![Screenshot (237)](https://github.com/user-attachments/assets/d74de2fa-a3a9-4b65-ac82-cb68b1666531)
![Screenshot (236)](https://github.com/user-attachments/assets/c672fa33-1284-4d65-ad46-55b35a4d47ea)
![Screenshot (238)](https://github.com/user-attachments/assets/529a4bae-3a64-4d7b-9fde-c09af6873507)

### Relevant log output | لاگ برنامه

```shell
خطای احراز هویت میزنه و روی حالت گول پرچم و ای پی ان میزنه
```

**Comment by ircfspace** [comment]
از ایجاد ایشوی تکراری خودداری کنید:‌ https://github.com/bepass-org/oblivion-desktop/issues/545#issuecomment-2365305917
