### ISSUE TITLE
FR: تنظیمات لایسنس وارپ پلاس

### ISSUE THREAD

**Issue by mohammad35322** [bepass-org/oblivion-desktop#55]
### Feature description

در قسمت لایسنس وارپ پلاس بعد از وارد کردن کلید و تایید کردن کلید یک پیغام به معنی درست و معتبر بودن کلید و همچنین موفقیت آمیز بودن تبدیل به وارپ پلاس نشان داده شود تا کاربران تجربه ی استفاده بهتر و راحت تری داشته باشن

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از پیشنهاد شما،
این‌برنامه یک رابط کاربری برای Warp-Plus بوده و اونم چنین امکانی در هسته‌ش تعریف نشده

به نظر بهتر باشه ایشوی مشابهی در آدرس زیر ایجاد کنین:
[warp-plus](https://github.com/bepass-org/warp-plus)
