### ISSUE TITLE
عدم شناسایی IP لوکال

### ISSUE THREAD

**Issue by majid1605** [bepass-org/oblivion-desktop#551]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی سیستم خاموش روشن میشه مخصوصا برق یهو قطع میشه و نرم افزار رو اجرا می کنم. اگر IP لوکال نسبت به قبل تغییر کرده باشه دیگه نمی تونه کانکت بشه .و دوباره مجبور میشم سیستم رو ریست کنم چند بار تا درست کار کنه.

### Relevant log output | لاگ برنامه

```shell

time=2024-09-24T08:44:40.227-06:00 level=INFO msg="connection test successful"

time=2024-09-24T08:44:40.227-06:00 level=ERROR msg="listen tcp 192.168.1.3:9560: bind: The requested address is not valid in its context."

[2024-09-24 08:44:40.232] [info] wp process exited.
[2024-09-24 08:44:40.234] [info] trying to disable system proxy...
[2024-09-24 08:44:40.324] [info] system proxy has been disabled on your system.



```
در صورتیکه  ای پی لوکال سیستم 
192.168.1.4

**Comment by ircfspace** [comment]
سلام
اگر گزینه اتصال از LAN رو در تنظیمات شبکه روشن کردین، خاموش کنین
