### ISSUE TITLE
فایل warp-plus در کنار بسته برنامه وجود ندارد!

### ISSUE THREAD

**Issue by omidmazloum** [bepass-org/oblivion-desktop#554]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وقتی دکمه اتصال رو میزنم چنین خطایی میده

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1- اجرای نرم افزار
2- فشردن دکمه اتصال

### Relevant log output | لاگ برنامه

```shell
فایل warp-plus در کنار بسته برنامه وجود ندارد
```

**Comment by ircfspace** [comment]
سلام
[این توضیحات](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) رو مطالعه کنید
