### ISSUE TITLE
نمی توان در opensuse tumb 84 نصب کرد 

### ISSUE THREAD

**Issue by Ali-qaz** [bepass-org/oblivion-desktop#562]
### Attention | توجه

- [x] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

تمام مراهل را یاست طی می کند اما خبری از برنامه نیست 
![نماگرفت از 2024-09-29 14-59-12](https://github.com/user-attachments/assets/55a03b14-c1ad-488a-97fa-de8b06959d35)
![نماگرفت از 2024-09-29 15-00-35](https://github.com/user-attachments/assets/d9c51b1f-cd45-404d-8d6c-bffc1948684a)
ایا اوپن سوسه از ابلیوین پشتیبانی می کند ؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

هیچ

### Relevant log output | لاگ برنامه

```shell
نصب نشده بوده
```

**Comment by kiomarzsss** [comment]
سلام از کدوم پکیج استفاده کردید؟ (rpm, deb, tar.xz)

**Comment by Borderliner** [comment]
برای من:

```
╰─❯ sudo zypper in ./oblivion-desktop-linux-x86_64.rpm 
[sudo] password for root: 
Refreshing service 'NVIDIA'.
Refreshing service 'openSUSE'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: nothing provides 'libuuid' needed by the to be installed oblivion-desktop-1.10.3-1.x86_64
 Solution 1: do not install oblivion-desktop-1.10.3-1.x86_64
 Solution 2: break oblivion-desktop-1.10.3-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

**Comment by Ali-qaz** [comment]
هنوز هم نصب نمی شه لاگ کنسول
![image](https://github.com/user-attachments/assets/e4478676-1077-40a9-96b7-dd5c6012ad42)
dhcppc2:/home/ali/بارگیری‌ها # zypper in ./vpn1.rpm
Refreshing service 'NVIDIA'.
Refreshing service 'openSUSE'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: nothing provides 'libuuid' needed by the to be installed oblivion-desktop-1.14.0-1.x86_64
 Solution 1: do not install oblivion-desktop-1.14.0-1.x86_64
 Solution 2: break oblivion-desktop-1.14.0-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2

Resolving dependencies...
Resolving package dependencies...

The following NEW package is going to be installed:
  oblivion-desktop

1 new package to install.

Package download size:    75.4 MiB

Package install size change:
              |     272.6 MiB  required by packages that will be installed
   272.6 MiB  |  -      0 B    released by packages that will be removed

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: oblivion-desktop-1.14.0-1.x86_64 (Plain RPM files cache)                                                                      (1/1),  75.4 MiB    
vpn1.rpm:
    Package header is not signed!

oblivion-desktop-1.14.0-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i

Checking for file conflicts: ...........................................................................................................................[done]
error: unpacking of archive failed on file /usr/share/icons/hicolor/512x512/apps/oblivion-desktop.png;670c0f51: cpio: link failed - No data available
error: oblivion-desktop-1.14.0-1.x86_64: install failed
(1/1) Installing: oblivion-desktop-1.14.0-1.x86_64 ....................................................................................................[error]
Installation of oblivion-desktop-1.14.0-1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: Command exited with status 1.
Abort, retry, ignore? [a/r/i] (a): i
