### ISSUE TITLE
chaotic-aur

### ISSUE THREAD

**Issue by Pakrohk** [bepass-org/oblivion-desktop#563]
### Feature description | توضیحات ویژگی

https://github.com/chaotic-aur/packages/issues/3253

Hello, I kindly request your assistance in helping the chaotic-aur team to more easily add the warp-plus oblivion-desktop software to their repositories. Your support in this process would be greatly appreciated.

**Comment by Technetium1** [comment]
To be clear, the problem is that Electron is not current. 27 (as specified on AUR) is end of life https://endoflife.date/electron and 26 is even more behind https://github.com/bepass-org/oblivion-desktop/blob/c501d7c3e29813f1f989784058ff97cc85c905a7/package.json#L96

**Comment by xiota** [comment]
Even if Electron version updated, program cannot be included in binary repo because license states, "You are prohibited from... distributing the software..."

**Comment by ircfspace** [comment]
Hello,
Currently, all our focus is on the TUN feature, which introduces significant changes to the code. 
However, after that, we can allocate time to update Electron.

Regarding the license, if the goal is to provide people with access to free internet and no changes are made to the name or details of the program, we can adjust the license to some extent.

I'll keep this issue open so we can address it when the time is right.

**Comment by ircfspace** [comment]
Hi,
- The system tunneling feature has been made available.  
- The Electron core has been updated to the latest version.  
- A minor change has been applied to the program's license.

**Comment by Pakrohk** [comment]
I think the license in aur is still problematic because if you try to install the package, you will unfortunately encounter a license error.

**Comment by xiota** [comment]
@Pakrohk Can you provide more info... What program produces it?  What is the wording of the message?

**Comment by Pakrohk** [comment]
> @Pakrohk Can you provide more info... What program produces it? What is the wording of the message?

``` Aur (1)                   Old Version  New Version    Make Only
aur/oblivion-desktop-bin               2.0.6-1        No

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: oblivion-desktop-bin 2.0.6-1 (Sun 15 Dec 2024 06:02:08 AM +0330)
==> Retrieving sources...
  -> Downloading LICENSE.md...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1734  100  1734    0     0   2154      0 --:--:-- --:--:-- --:--:--  2156
  -> Downloading oblivion-desktop-2.0.6-amd64.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 97.6M  100 97.6M    0     0   237k      0  0:07:01  0:07:01 --:--:--  241k
==> Validating source files with sha256sums...
    LICENSE.md ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'oblivion-desktop-bin-2.0.6-1': 
error: packages failed to build: oblivion-desktop-bin-2.0.6-1
 ```

**Comment by xiota** [comment]
@Pakrohk You probably have an old `LICENSE.md`.  Try again after clearing cache or with fresh copy of the package.  If that doesn't work, AUR maintainer may need to update the package.
