### ISSUE TITLE
Feature Request: Improved VPN Mode Support in NetworkManager

### ISSUE THREAD

**Issue by Pakrohk** [bepass-org/oblivion-desktop#564]
## Description
As a user of this open-source project, I would like to request enhancing NetworkManager's VPN mode support to provide a better and more standardized experience across GNU/Linux distributions, particularly for SOCKS and HTTPS connections.

## Relevant Documentation and Projects
I've found the following documentation and projects that might be helpful for the development team:
- [Red Hat Enterprise Linux 8: NetworkManager Connection Profiles in Keyfile Format](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/assembly_networkmanager-connection-profiles-in-keyfile-format_configuring-and-managing-networking)
- [Arch Linux Wiki: NetworkManager](https://wiki.archlinux.org/title/NetworkManager)
- [shadowsocks-nm](https://github.com/cakturk/shadowsocks-nm): A project that integrates Shadowsocks with NetworkManager, which could serve as a reference for SOCKS integration.

## Suggested Improvements
Based on my understanding as a user, I believe improving support for NetworkManager could lead to a more robust and standardized VPN mode for GNU/Linux distributions. Specifically:
1. Better integration of SOCKS and HTTPS connections into NetworkManager VPN profiles.
2. A standardized approach for converting SOCKS and HTTPS connections to NetworkManager VPN profiles, similar to what shadowsocks-nm does for Shadowsocks.

## Potential Benefits
- Enhanced VPN functionality across different Linux distributions
- More consistent user experience, especially for SOCKS and HTTPS VPN connections
- Improved adherence to networking standards
- Easier management of various types of VPN connections through NetworkManager

## Additional Notes
As a user of this software, I think this improvement could significantly enhance the VPN experience in the Linux ecosystem, particularly for those using SOCKS or HTTPS-based VPNs. The shadowsocks-nm project could serve as a valuable reference for how to integrate these types of connections with NetworkManager.

I understand that I'm not a developer of this project, but I hope this suggestion and the provided documentation and project references can be useful for the development team.

I'm open to any questions or clarifications if needed. Thank you for considering this feature request.

**Comment by ircfspace** [comment]
Hello,
Thank you for your suggestion.
We are currently working on the TUN feature using the Sing-box core, which enables system-wide tunneling. This feature will be introduced in version 2 of the program, and we’ve provided some details about it here: https://github.com/bepass-org/oblivion-desktop/issues/532

**Comment by Pakrohk** [comment]
> Hello, Thank you for your suggestion. We are currently working on the TUN feature using the Sing-box core, which enables system-wide tunneling. This feature will be introduced in version 2 of the program, and we’ve provided some details about it here: #532

Is this feature (using sing-box core) as standard as having an interface to NetworkManager? Modifying a network manager interface for your software will be much easier and more efficient than using sing-box core, especially if your software is not a V2ray service or similar.

**Comment by ircfspace** [comment]
The best option for tunneling the system at the moment (considering support for multiple operating systems) is using Sing-box. 
This process is also nearing its final stages.
