### ISSUE TITLE
امکان استفاده از آی پی ایران

### ISSUE THREAD

**Issue by hamedrashnoo** [bepass-org/oblivion-desktop#567]
### Feature description | توضیحات ویژگی

باسلام
امکانش هست بشه از ای پی های ایران وارپ هم استفاده کرد؟ یعنی به جای آی پی مثلا فرانسه به ایران متصل بشه. اینطوری بخش زیادی از مشکلات خارج نشینان حل میشه و کمک میکنه به ارتباط خانواده ها در صورت قطعی و ملی بودن اینترنت یا حتی مشکلات روزانه وصل شدنشون به سایت های داخلی.
تشکر

**Comment by ircfspace** [comment]
> ### Feature description | توضیحات ویژگی
> باسلام امکانش هست بشه از ای پی های ایران وارپ هم استفاده کرد؟ یعنی به جای آی پی مثلا فرانسه به ایران متصل بشه. اینطوری بخش زیادی از مشکلات خارج نشینان حل میشه و کمک میکنه به ارتباط خانواده ها در صورت قطعی و ملی بودن اینترنت یا حتی مشکلات روزانه وصل شدنشون به سایت های داخلی. تشکر

سلام. درحال حاضر چنین امکانی وجود نداره
اما میتونین [اینجا](https://github.com/bepass-org/warp-plus/issues) از توسعه‌دهندگان warp-plus درخواست کنین، تا امکان‌سنجی کنن

**Comment by ircfspace** [comment]
> من الان بعد اپدیت جدید در اتصال خودم مشکل دارم اگر میشه یا کاری کنید این قابیلت به ایران وصل شد قطع بشه بره ی جا دیگه به صورت دکمه Ture یا False کنید

اینکه روی حالت گول، آیپی ایران دریافت کنین یه باگه و بزودی حل میشه
اگر میخواین به طور مستقیم آیپی ایران بگیرین لازمه سوییچ کنین روی متد وارپ

**Comment by Mohammadrezaio** [comment]
سلام میخواستم بدونم چطوری ایپی های هر کشوری رو ک خواستیم بهش بدیم از طریق همون ایپی وارد بشه مثلا من سرورم المانه از طریق وارپ میخوام ایپی ترکیه بندازم وقتی وارد شم با ایپی ترکیه باشه

**Comment by ircfspace** [comment]
> سلام میخواستم بدونم چطوری ایپی های هر کشوری رو ک خواستیم بهش بدیم از طریق همون ایپی وارد بشه مثلا من سرورم المانه از طریق وارپ میخوام ایپی ترکیه بندازم وقتی وارد شم با ایپی ترکیه باشه

برای تغییر لوکیشن باید از متد سایفون در تنظیمات برنامه استفاده کنین
البته باید کشور موردنظرتون در لیست کشورهای پشتیبانی‌شده وجود داشته باشه
