### ISSUE TITLE
نسخه پرتابل - ويندوز 7

### ISSUE THREAD

**Issue by amir385276** [bepass-org/oblivion-desktop#57]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با عرض سلام و ادب
متاسفانه مثل ساير برنامه هاي قند شكن اين نسخه پرتابل هم با مشكل فايل سيستمي kernel32.dll بر روي ويندوز 7 نسخه 64 بيتي مواجه شده.
اين نسخه از ويندوز كاملا آپديت شده هست و لايسنس داره
لطفا بررسي بفرمائيد.
![Clip_8](https://github.com/bepass-org/oblivion-desktop/assets/43181048/130750a6-6424-486b-a8f6-ec7d334b3727)

### Minimal Reproducible Example (MRE)

وقتي برنامه لود نشه نميشه مشكلي رو گزارش كرد.

### Version

0.2.44

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
در ایشوی مشابهی پاسخ داده شد:
https://github.com/bepass-org/oblivion-desktop/issues/11#issuecomment-2094928540
