### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by Tariux** [bepass-org/oblivion-desktop#573]
### Feature description | توضیحات ویژگی

think its a good idea,

**Comment by ircfspace** [comment]
Thank you for your suggestion.
 What features do you have in mind for this potential extension?

**Comment by mmm-eskandari** [comment]
hi @Tariux 
If you prefer not to tunnel your entire system, you can easily use the "**Proxy Switcher and Manager**" extension, available for Chrome, Edge, and Firefox.
First, go to the Oblivion Desktop network settings and set the configuration to "None."
Next, open the extension and In the "Manual Proxy" tab, simply set the port to 8086 and you're ready to go!

**Comment by Tariux** [comment]
Hi @mmm-eskandari , you are right
There are many ways that can be used instead
But I do not recommend this extension idea for this reason
From a software perspective, an extension is much more installable and more efficient on some systems and sometimes more acceptable to users.
