### ISSUE TITLE
تلاش برای اتصال مجدد، زمانی که در متد گول به آی پی ایران وصل شده (بدون پراکسی سیستم)

### ISSUE THREAD

**Issue by amirrezaDev1378** [bepass-org/oblivion-desktop#578]
### Feature description | توضیحات ویژگی

در حال حاضر ویژگی ای داریم که در متد گول، اگر به آیپی ایران وصل شده بودیم اتصال قطع شده و مجددا برای اتصال تلاش می شود، اما این فیچر فقط درحالت system proxy کار میکنه و اگر ما نخوایم که کل سیستم رو پراکسی کنیم (proxy mode = none) این فیچر کار نمیکنه.

**Comment by ircfspace** [comment]
عملن در حالت proxy = none شما دارید از warp-plus به صورت مستقیم استفاده میکنید
بنابراین باید برای رفع این‌مشکل منتظر بروزرسانی بعدی هسته باشین؛ یا برای سرعت‌بخشیدن به پیگیری **[اینجا](https://github.com/bepass-org/warp-plus/issues)** ایشو بسازین
