### ISSUE TITLE
باز هم مشکل قبلی openSUSE حل نشد

### ISSUE THREAD

**Issue by Ali-qaz** [bepass-org/oblivion-desktop#579]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

هنوز نصب نمی شود خروجی کامند را داخل لاگ برنامه قرار مدهم
![نماگرفت از 2024-10-13 21-55-00](https://github.com/user-attachments/assets/83abeb88-d7cf-437e-b202-a20debeed7d9)

### Relevant log output | لاگ برنامه

```shell
dhcppc2:/home/ali/بارگیری‌ها # zypper in ./vpn1.rpm
Refreshing service 'NVIDIA'.
Refreshing service 'openSUSE'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: nothing provides 'libuuid' needed by the to be installed oblivion-desktop-1.14.0-1.x86_64
 Solution 1: do not install oblivion-desktop-1.14.0-1.x86_64
 Solution 2: break oblivion-desktop-1.14.0-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2

Resolving dependencies...
Resolving package dependencies...

The following NEW package is going to be installed:
  oblivion-desktop

1 new package to install.

Package download size:    75.4 MiB

Package install size change:
              |     272.6 MiB  required by packages that will be installed
   272.6 MiB  |  -      0 B    released by packages that will be removed

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: oblivion-desktop-1.14.0-1.x86_64 (Plain RPM files cache)                                                                      (1/1),  75.4 MiB    
vpn1.rpm:
    Package header is not signed!

oblivion-desktop-1.14.0-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i

Checking for file conflicts: ...........................................................................................................................[done]
error: unpacking of archive failed on file /usr/share/icons/hicolor/512x512/apps/oblivion-desktop.png;670c0f51: cpio: link failed - No data available
error: oblivion-desktop-1.14.0-1.x86_64: install failed
(1/1) Installing: oblivion-desktop-1.14.0-1.x86_64 ....................................................................................................[error]
Installation of oblivion-desktop-1.14.0-1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: Command exited with status 1.
Abort, retry, ignore? [a/r/i] (a): i
```

**Comment by Ali-qaz** [comment]
ممنون بابت کامندی دادید اما کارنمی کند که نمی کند

**Comment by kiomarzsss** [comment]
چرا از tar.xz استفاده نمکنین؟

**Comment by Borderliner** [comment]
@Ali-qaz 
به نظر میاد مشکل از دانلودتون باشه که خراب شده.
اول:
`sudo rm -f /usr/share/icons/hicolor/512x512/apps/oblivion-desktop.png`
بعد:

`sudo zypper in ./oblivion-desktop-1.14.0-1.x86_64.rpm`
بعدشم که بریک و ایگنور کنید. روی آخرین نسخه از OpenSuse Tumbleweed تست کردم نصب شد. مطمئن شید که فایل رو درست دانلود میکنید. ترجیجن با wget یا curl یا aria2 دانلودش کنید نه با مرورگر.

**Comment by Ali-qaz** [comment]
نه هنوز کار نمی کنه 
![نماگرفت از 2024-10-14 22-33-47](https://github.com/user-attachments/assets/4b906d83-bb19-4a0d-b4bb-8d637be4244c)

**Comment by Ali-qaz** [comment]
دوباره با ولی این بار با wget دانلود کردم هنوز هم ارور  های قبلی  رو میده

**Comment by Borderliner** [comment]
@Ali-qaz 
فایل رو هرجا که میخواید اکسترکت کنید و فایل
oblivion-desktop
رو اجرا کنید. بعدش خودتون باید دستی برنامه رو به منوی خودتون اضافه کنید. میتونید از برنامه ای به اسم
menulibre
استفاده کنید، یا اگه دسکتاپتون کی‌دی‌ای هست، روی منوی پایین سمت چپ کلیک راست کنید و گزینه 
Edit Applications
رو بزنید و خودتون آیتم بسازید براش.

**Comment by Ali-qaz** [comment]
سلام خیلی ممنون برنامه بالا میاد اما وصل نمیشه راستی از گنوم استفاده می کنم

**Comment by ircfspace** [comment]
در رابطه با مشکل اتصال با اندپوینت‌های سفارشی امتحان کنین

توضیحات بیشتر: [اینجا](https://github.com/bepass-org/oblivion-desktop/wiki)
