### ISSUE TITLE
مشکل سرعت تروخدا کمکم کنین

### ISSUE THREAD

**Issue by Bifckr** [bepass-org/oblivion-desktop#58]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

ادمین عزیز من همراه داشتم با این اپ چه ویندوز چه اندروید سرعت افتضاحی داره برام برا رفیقم ولی اوکین 
در این قسمت نگاه کنین یک ساب معمولی چه سرعتی داره
![Screenshot_۲۰۲۴-۰۵-۰۷-۰۱-۰۴-۴۱-۹۱۱_com mi android globallauncher](https://github.com/bepass-org/oblivion-desktop/assets/117599163/a42b8d5b-ac62-4d31-b88a-a4af3a8a5b6a)

حالا در این قسمت سرعت وارپ چه با خود این اپ چه با ترمینال و ترموکس یکیه چیکار باید انجام بدم امروز رفتم ایرانسل گرفتم باز همینه 

![Screenshot_۲۰۲۴-۰۵-۰۶-۱۸-۰۲-۱۴-۳۵۸_org zwanoo android speedtest](https://github.com/bepass-org/oblivion-desktop/assets/117599163/10872b92-fa11-4dfe-a7c2-07e9c782ba71)

### Minimal Reproducible Example (MRE)

نمی‌دونم 

### Version

همین اخریه

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Bifckr** [comment]
اون تصویر اول ۶۰ مگابیت هست

**Comment by paulvek** [comment]
> ### Search first
> * [x]  I searched and no similar issues were found
> 
> ### What Happened?
> ادمین عزیز من همراه داشتم با این اپ چه ویندوز چه اندروید سرعت افتضاحی داره برام برا رفیقم ولی اوکین در این قسمت نگاه کنین یک ساب معمولی چه سرعتی داره ![Screenshot_۲۰۲۴-۰۵-۰۷-۰۱-۰۴-۴۱-۹۱۱_com mi android globallauncher](https://private-user-images.githubusercontent.com/117599163/328329086-a42b8d5b-ac62-4d31-b88a-a4af3a8a5b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjcxNDksIm5iZiI6MTcxNTA2Njg0OSwicGF0aCI6Ii8xMTc1OTkxNjMvMzI4MzI5MDg2LWE0MmI4ZDViLWFjNjItNGQzMS1iODhhLWE0YWYzYThhNWI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwNzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWIxNDA0ZGNkNjAxZTgwMzYyNWIxY2UwMDA2YzdjNDY1NDUyN2MzZDcxYTVjYzYxYTJhNzRlYzc4YzI0YjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qbqiM2JB3-MKW5PaK4vREM6QZfn15BSUU7MmE0i5d34)
> 
> حالا در این قسمت سرعت وارپ چه با خود این اپ چه با ترمینال و ترموکس یکیه چیکار باید انجام بدم امروز رفتم ایرانسل گرفتم باز همینه
> 
> ![Screenshot_۲۰۲۴-۰۵-۰۶-۱۸-۰۲-۱۴-۳۵۸_org zwanoo android speedtest](https://private-user-images.githubusercontent.com/117599163/328329304-10872b92-fa11-4dfe-a7c2-07e9c782ba71.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjcxNDksIm5iZiI6MTcxNTA2Njg0OSwicGF0aCI6Ii8xMTc1OTkxNjMvMzI4MzI5MzA0LTEwODcyYjkyLWZhMTEtNGRmZS1hN2MyLTA3ZTljNzgyYmE3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwNzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFiMmFjOGI4MWUyODlkOTNmZWM2OGM1NmYyODFjZDkzOGIxN2EwM2EzYWE5YTEwZmMxN2QyMzUyZTk0NzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fsDTCwekZc1X8ZLtV5IB4XWgCwYIgoDErNOMTnV-vrk)
> 
> ### Minimal Reproducible Example (MRE)
> نمی‌دونم
> 
> ### Expected Behavior
> _No response_
> 
> ### Version
> همین اخریه
> 
> ### Platform/OS
> Windows
> 
> ### Additional Context
> _No response_
> 
> ### Application Config Options
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [ ]  I'm willing to submit a PR (Thank you!)

چرا از hiddify استفاده میکنید؟ شما باید از این oblivion desktop به تنهایی استفاده کنید به خاطر همین به مشکل برخوردید معمولا وقتی از دو وی پی ان یا پروکسی و چند اپ ضد تحریم و فیلتر و... با هم استفاده کنید همین مشکلات وجود داره. مثلا وقتی به وی پی ان وصل هستید پروکسی تلگرام دیگه درست کار نیمکنه یا از پروکسی تلگرام به تنهایی باید استفاده کنید یا خاموش کنید و از وی پی ان استفاده کنید و...

**Comment by Bifckr** [comment]
نه من از هیدیفای یک ساب رو تست زدم که سرعت اون رو ببینید بعد رفتم خاموش کردم ابلیویون رو روشن کردم که سرعت اون رو ببینین مقایسه کنین

**Comment by Bifckr** [comment]
![IMG_۲۰۲۴۰۵۰۷_۱۱۳۹۰۰](https://github.com/bepass-org/oblivion-desktop/assets/117599163/777cf0e7-527d-4515-b8d4-1722392480e6)
جالبه نتمو رو به ویندوز وصل کردم همچین سرعتی رو میده ولی رو خود گوشیم که بخام استفاده کنم همین سرعت افتضاحی که بالاتر دادم رو میده 
جالبه با ترموکس هم میزنم همینطوره

**Comment by aminpple** [comment]
cmd رو باز کن 
اینو بزن
 netsh winsock reset

 لپ تاپتو ریست کن

شاید احتمالا مشکلت حل شه

**Comment by ircfspace** [comment]
سلام

موضوع کندی ممکنه به موارد زیر مرتبط باشه :
1. اختلال منطقه ای 
2. اختلال سراسری
3. تنظیمات دیوایس یا تنظیمات برنامه
4. 
توجه داشته باشین که oblivion desktop یک واسط کاربری برای warp-plus هست و مسائلی مثل کندی اینترنت در ایشوها قابل پیگیری نیستند
