### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by CapitanArdeshir** [bepass-org/oblivion-desktop#581]
### Feature description | توضیحات ویژگی

سلام و وقت بخیر
آیا امکانش هست برای ویندوز 7 هم اضافه کنید یا حداقل بفرمایید کدامین ورژن روی ویندوز 7 کار میکنه که اونو دانلود کنم
سپاس

**Comment by ircfspace** [comment]
سلام
متاسفانه از ویندوز 7 و 8 (به دلیل عدم پشتیبانی از سمت مایکروسافت) ساپورت نمیشه
برای این سیستم عامل باید از برنامه‌های دیگه نظیر v2rayN-Pro استفاده کنین
