### ISSUE TITLE
Blacklist is ignored without additional reconnect

### ISSUE THREAD

**Issue by tollfree** [bepass-org/oblivion-desktop#587]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

**Issue**: On macOS, after establishing a connection, blacklisted IPs and domains are still routed through the proxy server despite being set to bypass.

**Details**:
- The blacklist entries from the Oblivion app are correctly transferred to the **Bypass proxy settings for these hosts & domains** field in the network's proxy settings.
- The SOCKS proxy is enabled, and the app log (attached below) shows no errors.
- However, macOS does not enforce the bypass rules until a network reconnection is triggered. This can be done by toggling the **Exclude simple hostnames** option or toggling the entire Wi-Fi connection, without making any changes to the Oblivion app.

**Environment**:
- macOS 15.0.1
- oblivion-desktop 1.10.3

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Go to Oblivion Desktop > Settings > Network > Blacklist.
2. Create some entries (either IP addresses or domains) that are blocked in your country, to ensure they remain blocked.
3. Reconnect the Oblivion app if it was previously connected.
4. Ensure your blacklist entries appear in your network's proxy settings. Do not change anything there!
5. Check the blacklisted resources in the Safari browser. They will be unblocked.
6. Now, go to System Settings > Wi-Fi > your current network (Details...) > Proxies, and toggle, for instance, **Exclude simple hostnames**. Save the network settings by clicking OK.
7. Repeat step 5. You will see that the website is now unavailable.

### Relevant log output | لاگ برنامه

```shell
[2024-10-18 18:03:15.090] [info]  past logs was deleted for new connection.
[2024-10-18 18:03:15.093] [info]  ------------------------MetaData------------------------
[2024-10-18 18:03:15.093] [info]  running on: darwin 24.0.0 arm64
[2024-10-18 18:03:15.093] [info]  at od: 1.10.3
[2024-10-18 18:03:15.093] [info]  at wp: v1.2.4
[2024-10-18 18:03:15.094] [info]  ls assets/bin: LICENSE,README.md,warp-plus
[2024-10-18 18:03:15.094] [info]  <USERNAME>thod: warp
[2024-10-18 18:03:15.094] [info]  proxyMode: true
[2024-10-18 18:03:15.095] [info]  routingRules: Customized
[2024-10-18 18:03:15.095] [info]  endpoint: custom
[2024-10-18 18:03:15.095] [info]  asn: UNK
[2024-10-18 18:03:15.095] [info]  license: false
[2024-10-18 18:03:15.095] [info]  exe: /Applications/oblivion-desktop.app/Contents/MacOS/oblivion-desktop
[2024-10-18 18:03:15.095] [info]  userData: /Users/<USERNAME>/Library/Application Support/oblivion-desktop
[2024-10-18 18:03:15.096] [info]  logs: /Users/<USERNAME>/Library/Logs/oblivion-desktop
[2024-10-18 18:03:15.096] [info]  ------------------------MetaData------------------------
[2024-10-18 18:03:15.096] [info]  starting wp process...
[2024-10-18 18:03:15.096] [info]  /Users/<USERNAME>/Library/Application Support/oblivion-desktop/warp-plus --bind 127.0.0.1:48086 --endpoint 162.159.192.8:4500 --reserved 0,0,0
[2024-10-18 18:03:15.099] [info]  trying to set system proxy...
[2024-10-18 18:03:15.137] [info]  networksetup -listallnetworkservices: An asterisk (*) denotes that a network service is disabled.
USB 10/100 LAN
Thunderbolt Bridge
Wi-Fi
iPhone USB

[2024-10-18 18:03:15.137] [info]  using hardwarePort: [
  'USB 10/100 LAN',
  'Thunderbolt Bridge',
  'Wi-Fi',
  'iPhone USB'
]
[2024-10-18 18:03:15.137] [info]  using hardwarePort: USB 10/100 LAN
[2024-10-18 18:03:15.138] [info]  using hardwarePort: Thunderbolt Bridge
[2024-10-18 18:03:15.139] [info]  using hardwarePort: Wi-Fi
[2024-10-18 18:03:15.140] [info]  using hardwarePort: iPhone USB
ti<USERNAME>=2024-10-18T18:03:15.144+03:00 level=INFO msg="using warp endpoints" endpoints="[162.159.192.8:4500 162.159.192.8:4500]"  
ti<USERNAME>=2024-10-18T18:03:15.145+03:00 level=INFO msg="running in normal warp mode"
ti<USERNAME>=2024-10-18T18:03:15.148+03:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

[2024-10-18 18:03:15.576] [info]  System proxy has been set for Wi-Fi.
[2024-10-18 18:03:15.724] [info]  System proxy has been set for Thunderbolt Bridge.
[2024-10-18 18:03:15.766] [info]  System proxy has been set for iPhone USB.
[2024-10-18 18:03:15.847] [info]  System proxy has been set for USB 10/100 LAN.
ti<USERNAME>=2024-10-18T18:03:38.698+03:00 level=INFO msg="connection test successful"

ti<USERNAME>=2024-10-18T18:03:38.698+03:00 level=INFO msg="serving proxy" address=127.0.0.1:48086
```

**Comment by ircfspace** [comment]
Hi, 
Is it possible for you to look into this issue?

@gdariushahmadi
@ShadowZagrosDev

**Comment by gdariushahmadi** [comment]
I think this mistake arises from the use of the term 'blacklist.' In fact, what is done with the blacklist is that it does not go through the proxy, and in similar programs, the term 'whitelist' is used for naming.

**Comment by gdariushahmadi** [comment]
I haven't tested this feature until now, but for example, I just added the domain ping.eu. I had no issues in Chrome and Opera, but interestingly, in Safari, all traffic is routed through the proxy, and I encountered this problem.
<img width="399" alt="Screenshot 2024-10-18 at 3 33 17 PM" src="https://github.com/user-attachments/assets/3d581be4-873a-455a-a16f-ced7aa8ae8f9">
<img width="470" alt="Screenshot 2024-10-18 at 3 33 42 PM" src="https://github.com/user-attachments/assets/977b3748-41ac-4c8c-a714-1e40f4215e6e">

**Comment by tollfree** [comment]
ОК, thanks in advance 

I hope the removal of `<local>` was initiated within the custom client build, rather than directly in the Wi-Fi proxy settings, as **any** network settings change seems to resolve the issue.

By the way, I tested `ping.eu` using Firefox v131.0.3 with system proxy settings andChrome Beta 131.0, and both browsers exhibit the same behavior as Safari.

**Comment by tollfree** [comment]
@gdariushahmadi,
And one more quick question: since macOS allows specifying IPs with a netmask, like 172.16.0.0/12, why not use a shorter local IP range default record?

**Comment by gdariushahmadi** [comment]
> @gdariushahmadi, And one more quick question: since macOS allows specifying IPs with a netmask, like 172.16.0.0/12, why not use a shorter local IP range default record?

We have a general list by default for local IP addresses in all operating systems. It would be a good suggestion if netmask support is included in the Windows and Linux versions.

**Comment by gdariushahmadi** [comment]
> ОК, thanks in advance
> 
> I hope the removal of `<local>` was initiated within the custom client build, rather than directly in the Wi-Fi proxy settings, as **any** network settings change seems to resolve the issue.
> 
> By the way, I tested `ping.eu` using Firefox v131.0.3 with system proxy settings andChrome Beta 131.0, and both browsers exhibit the same behavior as Safari.

Could you send a picture of the Exclude simple hostnames settings in the Wi-Fi settings?

**Comment by tollfree** [comment]
Sure
<details>
<summary>Proxies</summary>
<img width="653" alt="Screenshot 2024-10-19 at 04 17 16" src="https://github.com/user-attachments/assets/6e2db914-b8ac-4e8d-b96e-f0eab0f928db">

**Comment by gdariushahmadi** [comment]
> Sure
> 
> Proxies
> <img alt="Screenshot 2024-10-19 at 04 17 16" width="653" src="https://private-user-images.githubusercontent.com/5585001/378040357-6e2db914-b8ac-4e8d-b96e-f0eab0f928db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MTg0MDMsIm5iZiI6MTcyOTQxODEwMywicGF0aCI6Ii81NTg1MDAxLzM3ODA0MDM1Ny02ZTJkYjkxNC1iOGFjLTRlOGQtYjk2ZS1mMGVhYjBmOTI4ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMDk1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDViNjRjYWMyYTc2Y2VmMDUwYzI2YmQ2ZDI5YjY3NDY2ZjIyZDgxYWFiY2EzYjlkNzMzYzcwM2FhMDg3NjU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ow0ZfYm2SWfi2KQ25Nle9WRXp9LhEpx-0SllnCCtQ9U">

As far as I’ve understood so far, in order for the bypass list settings to be applied in Safari, unlike other browsers, just as you mentioned with the 'Exclude simple hostnames' option or toggling the entire Wi-Fi connection, I haven't found a command yet to enable this option to apply the change.

**Comment by tollfree** [comment]
All browsers using system proxy settings are affected in my case. I initially encountered this bug in Chrome.

Please review the settings of your Chromium-based browser and test it again. You might have some extensions that are taking control of the browser's proxy settings.

Currently, I’m using the following workaround:

I have a `.command` file on my desktop that contains the following script:
```
#!/bin/bash

networksetup -setproxybypassdomains "Wi-Fi" *.local 169.254/16 fe80::/64 fc00::/7 192.168/16 172.16/12 10/8  *.wikipedia.org *.ping.eu
```
and I execute this file after every startup of the oblivion-desktop connection.

This command immediately replaces the blocklist received from the client with the entries from this file, making the updated list effective across the entire system right away. As a result, there's no need to reconnect the client every time to refresh the blacklist.

This approach is more convenient than digging into System Settings each time. Therefore, I don't use the app's blacklist at all and simply manage the bypass list by editing my` .command` file.

**Comment by gdariushahmadi** [comment]
> I have a `.command` file on my desktop that contains the following script:
> 
> ```
> #!/bin/bash
> 
> networksetup -setproxybypassdomains "Wi-Fi" *.local 169.254/16 fe80::/64 fc00::/7 192.168/16 172.16/12 10/8  *.wikipedia.org *.ping.eu
> ```
> 
In OBLIVION, the command runs like this, but at least in what I tested on my MacBook, it does not work in Safari if **Exclude simple hostnames** is toggled off before, and to make it work, this option needs to be enabled manually. By the way, in your experience, does it still work without this option being turned on?

**Comment by tollfree** [comment]
The **Exclude simple hostnames** option has no effect on this issue for me. This bug persists regardless of the state of **Exclude simple hostnames**.

Additionally, changes to the blacklist (it would be better to rename this to "Split Tunnel") can be "activated" by altering the NetBIOS name, toggling Auto Proxy Discovery, etc.

I mentioned **Exclude simple hostnames** as a quick way to nudge the connection.


What about a command, my current assumption is that [here](https://github.com/bepass-org/oblivion-desktop/blob/c501d7c3e29813f1f989784058ff97cc85c905a7/src/main/lib/proxy.ts#L413)

`networksetup -setsocksfirewallproxystate "Wi-Fi" on `

executes _before_

`networksetup -setproxybypassdomains "Wi-Fi" domain1,domain2`,

so maybe the SOCKS proxy starts with the default bypass list, and newly added blacklist items do not impact the current connection.

**Comment by ircfspace** [comment]
Hi,
Test the changes (especially in tunnel mode), and let us know if there are still any issues.

https://github.com/bepass-org/oblivion-desktop/releases
