### ISSUE TITLE
Warp-Plus یافت نشد

### ISSUE THREAD

**Issue by omidmazloum** [bepass-org/oblivion-desktop#595]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

موقع اجرا مینویسه warp-plus در کنار بسته وجود ندارد

### Relevant log output | لاگ برنامه

```shell
موقع اجرا مینویسه warp-plus در کنار بسته وجود ندارد
```

**Comment by kordeviant** [comment]
این مال انتی ویروس شما است که بلاک کرده وارپ رو 
باید از تنظیمات انتی ویروس به وارپ پلاس اجازه بدین. مثل اینکه PUA:Win32/Vigua.A  هست و این به معنی ویروس یا بدافزار نیست ولی چون برای دورزدن یک سرویس کامرشیال طراحی شده انتی ویروس ویندوز تشخیص میده که احتمالا شما نخواین استفاده کنید. potetianlly unwanted app

**Comment by ircfspace** [comment]
توضیحات مرتبط: [Wiki](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3)
