### ISSUE TITLE
مشکل استفاده از claude sonet https://www.anthropic.com/

### ISSUE THREAD

**Issue by kordeviant** [bepass-org/oblivion-desktop#596]
### Feature description | توضیحات ویژگی

سایت https://www.anthropic.com/ و هوش مصنوعی claude کانکشن رو از ایران تشخیص میده و اجازه استفاده نمیده
App unavailable
Unfortunately, Claude is only available in certain regions right now. Please contact support if you believe you are receiving this message in error.

مطمئنم دوستان حرفی تر راهی برای دور زدن این پروتکشن از طریق همین وارپ دارند که بتونن به اشتراک بگذارند.
با تشکر از همه عزیزانی که زحمت اینکار رو کشیدند

**Comment by ircfspace** [comment]
از متد گول یا سایفون استفاده کنین
اگر جواب نمیده همچنان، احتمالن با وارپ نمیتونین این‌محدودیت رو دور بزنین
