### ISSUE TITLE
api برنامه

### ISSUE THREAD

**Issue by KarimQaderi** [bepass-org/oblivion-desktop#598]
### Feature description | توضیحات ویژگی

سلام

ایا امکانش هست برای برنامه api گذاشته بشه oblivion قطع وصل کرد
یه سیستم خانگی داریم که می خوایم از راه دور oblivion با api قطع و وصل کنیم

**Comment by ircfspace** [comment]
سلام
ضمن پوزش، متاسفانه امکان انجام این‌ویژگی میسر نیست
