### ISSUE TITLE
App opening several times

### ISSUE THREAD

**Issue by usseff-T** [bepass-org/oblivion-desktop#60]
### What Happened?

Unfortunately, it can open the program several times in Windows 10 64-bit. But with the possibility of only one app connects.

### Expected Behavior

If it can open the program like other VPNs only once.

### Version

0.2.44-beta

### Platform/OS

Windows

### Additional Context

![Screenshot 2024-05-07 090504](https://github.com/bepass-org/oblivion-desktop/assets/72567498/b2e39a2b-3d0e-4414-8b74-7cb417936e68)

**Comment by ircfspace** [comment]
Thank you for your report,
There is an issue being addressed for this matter.

https://github.com/orgs/bepass-org/projects/4/views/1?pane=issue&itemId=61844248
