### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by pejman102000** [bepass-org/oblivion-desktop#602]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در موقع نصب پیغامی بر روی صفحه مشاهده می شود  و اجازه نصب را نمیدهد 
![oblivion](https://github.com/user-attachments/assets/8b91b4c0-d5cc-451f-950d-50a13dac7a3c)
که اسکرین شات  آن را ارسال می کنم

### Relevant log output | لاگ برنامه

```shell
پیدا نکردم
```

**Comment by ircfspace** [comment]
سلام
برای نصب باید از ویندوز ۱۰ یا ۱۱ استفاده کنید
