### ISSUE TITLE
system-wide proxy stays enabled on Windows after shutdown or restart

### ISSUE THREAD

**Issue by amrezaee** [bepass-org/oblivion-desktop#603]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Oblivion sets a proxy on Windows, but when you restart or shut down Windows while Oblivion is still connected, it does not unset the proxy, and you have to do it manually.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

connect to oblivion.  
shutdown or restart Windows.  
the system-wide proxy stays enabled, and you must manually disable it in Windows settings or connect and reconnect to oblivion.

### Relevant log output | لاگ برنامه

```shell
no logs
```

**Comment by amrezaee** [comment]
> Which version are you using?

v1.10.3 on Windows 11

**Comment by ircfspace** [comment]
Thank you for your report.  
We will try to address this issue in the next update.
