### ISSUE TITLE
1030 بار باید امتحان کنیم تا وصل شه

### ISSUE THREAD

**Issue by hreza137575** [bepass-org/oblivion-desktop#605]
### Feature description | توضیحات ویژگی

قابلیت بررسی خودکار اندپوینت و ست کردن خودکار اندپوینت بهش اضافه بشه عالیه

**Comment by ircfspace** [comment]
سلام
اگر از اندپوینت پیشفرض استفاده کنین، اسکنر داخلی برنامه فعال میشه
اگر اتصال هم به درستی صورت بگیره، میتونین از گزینه «اندپوینت اخیر» استفاده کنین تا فرایند اتصال تسریع بشه
