### ISSUE TITLE
The warp-plus file is not located alongside theapplication package!

### ISSUE THREAD

**Issue by yangjiandu2** [bepass-org/oblivion-desktop#606]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

The warp-plus file is not located alongside theapplication package!

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

The warp-plus file is not located alongside theapplication package!

### Relevant log output | لاگ برنامه

```shell
I dont no
```

**Comment by ircfspace** [comment]
Read [this article](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3). 
However, this issue will be largely resolved in the next version of the application.
