### ISSUE TITLE
سایفون کار نمیکنه

### ISSUE THREAD

**Issue by johhny1898** [bepass-org/oblivion-desktop#61]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و خسته نباشین
زمانی که میخوایم از سایفون استفاده کنیم کار نمیکنه و دستور ساکس و اچ تی تی پی کار نمیکنه تو پراکسی سیستم
باید دستی وارد کرد تا وصل بشه
راه حل:
تو قسمت پراکسی سیستم /قسمت ادرس socks=127.0.0.1 باید وارد بشه تا وصل بشه و کل سیستم تانل میشه
با تغیر کشور باید مراحلو از اول برین

### Minimal Reproducible Example (MRE)

ddv

### Expected Behavior

vdv

### Version

v.2.44 beta

### Platform/OS

Windows

### Additional Context

vfbfb

### Application Config Options

```shell
bfd
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

این مورد در آپدیت جدید برطرف شده
امروز یا فردا منتشرش میکنیم
