### ISSUE TITLE
The software on Android TV Not working

### ISSUE THREAD

**Issue by kamalifaez** [bepass-org/oblivion-desktop#613]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

The software on Android TV stops and crashes when switching to another software.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

The software on Android TV stops and crashes when switching to another software.

### Relevant log output | لاگ برنامه

```shell
I don't have
```

**Comment by ircfspace** [comment]
Hello,  
The desktop version is available for Windows, iOS, and Linux.  
Regarding the Android version, you need to open an issue [here](https://github.com/bepass-org/oblivion/issues).
