### ISSUE TITLE
لطفا شکل ایکون اتصال را تغییر بدید 

### ISSUE THREAD

**Issue by aminpple** [bepass-org/oblivion-desktop#62]
### Feature description

لطفا شکل ایکون اتصال را تغییر بدید چون خیلی ها ب جای کلیک روی ایکون اونو ب سمت راست میکشند ک خب کار نمیکنه!
برنامه عالی و سریع تنها مشکلش تانل نشدن کل ویندوزه
وگرنه تمام سایت هایی مثل اینتل و گیم لوپ را راحت باز میکنه ک با هر vpn نمیشه حتی hiddify هم نتونست ولی این میتونه

بعضی وقتها هم وصل میشه ولی سایتی رو باز نمیکنه ک با ی ریستارت ساده ویندوز مشکل حل میشه و راحت وصل میشه
ممنونم از همتون

**Comment by usseff-T** [comment]
کل ویندوز تانل میشه مشکلی نداره.

**Comment by aminpple** [comment]
اگه تانل میشه چرا واتساپ دسکتاپ تانل نمیشه؟
تلگرام ولی مشکلی نداره

**Comment by ircfspace** [comment]
سلام

1. امکان Swipe برای دکمه اتصال اضافه شد و در آپدیت بعدی در دسترس قرار میگیره
2. موضوعاتی مثل TUN و Routing Rules در نسخه‌های بعدی اضافه میشن
3. مشکل سایفون در آپدیت بعدی برطرف میشه

**Comment by Majidzam1101** [comment]
> سلام
> 
> 1. امکان Swipe برای دکمه اتصال اضافه شد و در آپدیت بعدی در دسترس قرار میگیره
> 2. موضوعاتی مثل TUN و Routing Rules در نسخه‌های بعدی اضافه میشن
> 3. مشکل سایفون در آپدیت بعدی برطرف میشه

خطای هویت سنجی دیگه چیه نگفتی پشتیبانی برنامه ؟
![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/33202fa5-ea3c-42c0-8d0e-db8f1a4bbc67)
![Screenshot (17)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/d207bc3a-17d2-4384-abe8-f538e36ce859)
