### ISSUE TITLE
مشکل باز شدن دوباره برنامه

### ISSUE THREAD

**Issue by yaser-front-dev** [bepass-org/oblivion-desktop#627]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

زمانی که روی ضربدر برای بسته شدن برنامه کلیک میکنم دیگه هرچی رو برنامه میزنم برنامه باز نمیشه و مجبور به خاموش و روشن کردن دوباره سیستم برای استفاده دوباره از برنامه میشوم

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

زمانی که روی ضربدر برای بسته شدن برنامه کلیک میکنم دیگه هرچی رو برنامه میزنم برنامه باز نمیشه و مجبور به خاموش و روشن کردن دوباره سیستم برای استفاده دوباره از برنامه میشوم

### Relevant log output | لاگ برنامه

```shell
زمانی که روی ضربدر برای بسته شدن برنامه کلیک میکنم دیگه هرچی رو برنامه میزنم برنامه باز نمیشه و مجبور به خاموش و روشن کردن دوباره سیستم برای استفاده دوباره از برنامه میشوم
```

**Comment by ircfspace** [comment]
سلام
برای ارسال گزارش لازمه لاگ برنامه رو ارسال کنین
چطور متوجه بشیم روی چه سیستم عامل و چه نسخه ای هستین؟

ترجیحا یک دور تنظیمات برنامه رو بازگردانی کرده و روی سیستم عامل‌های غیر از ویندوز، گزینه بستن اجباری رو روشن کرده و مجدد تست بگیرین

همینطور با آخرین نسخه تست انجام بدین:
https://github.com/bepass-org/oblivion-desktop/releases
