### ISSUE TITLE
مشکل با دیفندر ویندوز11

### ISSUE THREAD

**Issue by majidi-mehdi** [bepass-org/oblivion-desktop#631]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام دوستان
تو ورژن جدید هر بار که اجرا میکنم دیفندر ویندوز گیر میده،
داخل تنظیمات دیفندر Exclud کردم مسیر فولدر رو، و حتی فایل exe رو،
ولی باز اون پیغام هر دفعه میادش

### Relevant log output | لاگ برنامه

```shell
Microsoft Defender Problem.
```

**Comment by ircfspace** [comment]
[این مورد](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) و [این مورد](https://github.com/bepass-org/oblivion-desktop/issues/495) رو مشاهده کنید
