### ISSUE TITLE
مشکل نصب در لینوکس 

### ISSUE THREAD

**Issue by apmcraft1387** [bepass-org/oblivion-desktop#635]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

تمام مراحل رو برای نصب  میرم ولی در اخرا دوتا ارور میده :

### Relevant log output | لاگ برنامه

```shell
Couldn't find any package by glob 'oblivion-desktop-linux-arm64.deb' و
E: Unable to locate package oblivion-desktop-linux-arm64.deb
```

**Comment by Pakrohk** [comment]
متاسفنه بسته موجود توی aur هم مشکل داره و باید بش رسیدگی بشه شاید پکیج بیلد خراب باشه و مشکل مشابه دوستمون نباشه.

**Comment by mr-shady** [comment]
روی ubuntu هم نصب میشه ولی اجرا نمیشه

**Comment by Coderx7** [comment]
Use the appimage version and it'll work flawlessly!
just remember to also install libfuse2 if I recall correctly.
