### ISSUE TITLE
video playback on youtube pauses at exactly 1 minute mark when using oblivion-desktop

### ISSUE THREAD

**Issue by Coderx7** [bepass-org/oblivion-desktop#638]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

since a few days ago, I've suddenly noticed whenever I try to use oblivion-desktop, YouTube videos stop at exactly 1 minute mark and seemingly wont load afterwards.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Here's a screencast demonstrating the issue: https://streamable.com/lel7ao?src=player-page-share 

### Relevant log output | لاگ برنامه

```shell
[2024-12-13 12:24:57.816] [info]  past logs was deleted for new connection.
[2024-12-13 12:24:57.819] [info]  ------------------------MetaData------------------------
[2024-12-13 12:24:57.819] [info]  running on: linux 6.8.0-50-generic x64
[2024-12-13 12:24:57.820] [info]  at od: 1.14.0
[2024-12-13 12:24:57.820] [info]  at wp: v1.2.4
[2024-12-13 12:24:57.820] [info]  ls assets/bin: LICENSE,README.md,warp-plus
[2024-12-13 12:24:57.820] [info]  method: warp
[2024-12-13 12:24:57.820] [info]  proxyMode: false
[2024-12-13 12:24:57.820] [info]  routingRules: Default
[2024-12-13 12:24:57.820] [info]  endpoint: default
[2024-12-13 12:24:57.820] [info]  asn: MTN
[2024-12-13 12:24:57.820] [info]  license: false
[2024-12-13 12:24:57.820] [info]  exe: /home/<USERNAME>/i-oblivion-desktop-linux-x64/oblivion-desktop
[2024-12-13 12:24:57.820] [info]  userData: /home/<USERNAME>/.config/oblivion-desktop
[2024-12-13 12:24:57.821] [info]  logs: /home/<USERNAME>/.config/oblivion-desktop/logs
[2024-12-13 12:24:57.821] [info]  ------------------------MetaData------------------------
[2024-12-13 12:24:57.821] [info]  starting wp process...
[2024-12-13 12:24:57.821] [info]  /home/<USERNAME>/.config/oblivion-desktop/warp-plus --bind 127.0.0.1:8086 --gool --scan
time=2024-12-13T12:24:57.827+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-12-13T12:24:57.828+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account
time=2024-12-13T12:24:57.829+03:30 level=ERROR msg="ping error" subsystem=scanner addr=2606:4700:d0:0:ff33:bf47:af03:559d error="dial udp [2606:4700:d0:0:ff33:bf47:af03:559d]:946: connect: network is unreachable"

time=2024-12-13T12:24:59.301+03:30 level=ERROR msg="ping error" subsystem=scanner addr=2606:4700:d1:0:708d:318:1e0a:89ed error="dial udp [2606:4700:d1:0:708d:318:1e0a:89ed]:1180: connect: network is unreachable"

time=2024-12-13T12:25:01.829+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.187:1070 162.159.192.127:8742]"
time=2024-12-13T12:25:01.829+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-12-13T12:25:01.830+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-12-13T12:25:06.725+03:30 level=INFO msg="connection test successful"

time=2024-12-13T12:25:06.726+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-12-13T12:25:08.416+03:30 level=INFO msg="connection test successful"

time=2024-12-13T12:25:08.417+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-12-13T12:48:49.958+03:30 level=ERROR msg=EOF

time=2024-12-13T12:49:00.643+03:30 level=ERROR msg=EOF

time=2024-12-13T12:49:01.525+03:30 level=ERROR msg=EOF

time=2024-12-13T12:49:14.089+03:30 level=ERROR msg=EOF
time=2024-12-13T12:49:14.089+03:30 level=ERROR msg=EOF
time=2024-12-13T12:49:14.089+03:30 level=ERROR msg=EOF
time=2024-12-13T12:49:14.089+03:30 level=ERROR msg=EOF

time=2024-12-13T12:51:07.079+03:30 level=ERROR msg=EOF
```

**Comment by Coderx7** [comment]
yup this happened to me after updating, reverting back didnt help either!

**Comment by itsthepatrick** [comment]
did you have [this ](https://github.com/bepass-org/oblivion-desktop/issues/639)problem too?

**Comment by Coderx7** [comment]
> did you have [this ](https://github.com/bepass-org/oblivion-desktop/issues/639)problem too?
IPV6 doesn't work for me either!

**Comment by ircfspace** [comment]
hi,
In the second version of the application, changes were made regarding the TUN connection method, while no modifications were applied on the Warp-Plus side.  
To ensure everything is working as expected, please install the [previous version of the application](https://github.com/bepass-org/oblivion-desktop/releases/tag/v1.14.0) and test the setup with IPv6. The issue might stem from somewhere else outside of the application.

سلام
در نسخه دوم از برنامه تغییرات در رابطه با متد اتصال tun اعمال شده و سمت warp-plus تغییری نداشتیم
برای اطمینان، لطفا یکبار [نسخه قدیمی](https://github.com/bepass-org/oblivion-desktop/releases/tag/v1.14.0) از برنامه رو نصب کرده و شرایط رو روی IPv6 بررسی کنین
ممکن مشکل از جای دیگری غیر از برنامه باشه

**Comment by ircfspace** [comment]
Hello,  
Please test the Gool method once using custom endpoints (not the default ones).  
It's possible that the endpoint set in the application through the scanner might not be efficient.

**Comment by EpicMoe** [comment]
This problem is related to the Iran IP (when we use wrap), YouTube will not show the video for more than 1 minute. Even using dedicated V2rays links and connection , this problem still exists. You can test it, but if the Endpoint IP is other than Iran, this problem will be solved.

using chrome as a browser can help or for Youtube specially you can use FreeTube Application

**Comment by Coderx7** [comment]
> Hello, Please test the Gool method once using custom endpoints (not the default ones). It's possible that the endpoint set in the application through the scanner might not be efficient.

Thanks but I'm already using the older version but the problem still persists! 

> This problem is related to the Iran IP (when we use wrap), YouTube will not show the video for more than 1 minute. Even using dedicated V2rays links and connection , this problem still exists. You can test it, but if the Endpoint IP is other than Iran, this problem will be solved.
> 
> also using chrome as a browser can help or for Youtube specially you can use "FreeTube" Application.

Thanks a lot, I tried again and the issue is gone! I believe you are 100% correct.

on a side note, would it not be better to show the IP/country in the desktop version just like the android version, this could solve a whole lot of issues like this.

**Comment by itsthepatrick** [comment]
> This problem is related to the Iran IP (when we use wrap), YouTube will not show the video for more than 1 minute. Even using dedicated V2rays links and connection , this problem still exists. You can test it, but if the Endpoint IP is other than Iran, this problem will be solved.
> 
> also using chrome as a browser can help or for Youtube specially you can use "FreeTube" Application.

it's not,i was connected to germany

**Comment by itsthepatrick** [comment]
> on a side note, would it not be better to show the IP/country in the desktop version just like the android version, this could solve a whole lot of issues like this.
it does that rn,unless yours has a bug or something

**Comment by behzadchtp** [comment]
من این مشکلی که دوست عزیزمون مطرح کردم با oblivion desktop ندارم ولی نسخه فیلترشکن WARP Client همون فیلترشکن 1.1.1.1 "نسخه ویندوز" دقیقا همچین مشکلی باهاش دارم که بعد از پخش 1 دقیقه از ویدیو تو یوتیوب دیگه متوقف میشه و ادامه پخش ویدیو رو نمیره.

**Comment by Coderx7** [comment]
It seems the issue is not related to Iran's IP address as previously suggested or maybe it is and somehow somewhere something leaks an IP address related to Iran(could it be the way warpOnwarp functions? like the first IP is from Iran and thats why Youtube acts up like this?) 
myipaddress.com reports the final IP address belongs to Ghana! but Youtube's 1 min limit is activated as well, which shouldnt be the case!
see the screencast below: https://streamable.com/81fcpz

if this is indeed caused by Iran's IP address, then specifically choosing to use locations other than Iran should solve the issue, is that possible in Oblivion or WarpOnWarp?

**Comment by EbiDesa** [comment]
> من این مشکلی که دوست عزیزمون مطرح کردم با oblivion desktop ندارم ولی نسخه فیلترشکن WARP Client همون فیلترشکن 1.1.1.1 "نسخه ویندوز" دقیقا همچین مشکلی باهاش دارم که بعد از پخش 1 دقیقه از ویدیو تو یوتیوب دیگه متوقف میشه و ادامه پخش ویدیو رو نمیره.

بله ظاهرا یوتیوب شناسایی میکنه و برای منم چند روزه همین وضعه. فعلا برای تماشای ویدئوها، زیر ویدئو روی **"همرسانی"** کلیک میکنم و بعد **<>جاسازی** رو میزنم

**Comment by behzadchtp** [comment]
> > من این مشکلی که دوست عزیزمون مطرح کردم با oblivion desktop ندارم ولی نسخه فیلترشکن WARP Client همون فیلترشکن 1.1.1.1 "نسخه ویندوز" دقیقا همچین مشکلی باهاش دارم که بعد از پخش 1 دقیقه از ویدیو تو یوتیوب دیگه متوقف میشه و ادامه پخش ویدیو رو نمیره.
> 
> بله ظاهرا یوتیوب شناسایی میکنه و برای منم چند روزه همین وضعه. فعلا برای تماشای ویدئوها، زیر ویدئو روی **"همرسانی"** کلیک میکنم و بعد **<>جاسازی** رو میزنم

دوست عزیز میشه یکبار دیگه بگین...همرسانی و جاسازی رو متوجه نمیشم.

**Comment by EbiDesa** [comment]
> > > من این مشکلی که دوست عزیزمون مطرح کردم با oblivion desktop ندارم ولی نسخه فیلترشکن WARP Client همون فیلترشکن 1.1.1.1 "نسخه ویندوز" دقیقا همچین مشکلی باهاش دارم که بعد از پخش 1 دقیقه از ویدیو تو یوتیوب دیگه متوقف میشه و ادامه پخش ویدیو رو نمیره.
> > 
> > 
> > بله ظاهرا یوتیوب شناسایی میکنه و برای منم چند روزه همین وضعه. فعلا برای تماشای ویدئوها، زیر ویدئو روی **"همرسانی"** کلیک میکنم و بعد **<>جاسازی** رو میزنم
> 
> دوست عزیز میشه یکبار دیگه بگین...همرسانی و جاسازی رو متوجه نمیشم.

برای من فارسیه و این کلمات رو نوشته. همون گزینه share و وقتی پنجرش باز شود، گزینه اولی <>

**Comment by behzadchtp** [comment]
> > > > من این مشکلی که دوست عزیزمون مطرح کردم با oblivion desktop ندارم ولی نسخه فیلترشکن WARP Client همون فیلترشکن 1.1.1.1 "نسخه ویندوز" دقیقا همچین مشکلی باهاش دارم که بعد از پخش 1 دقیقه از ویدیو تو یوتیوب دیگه متوقف میشه و ادامه پخش ویدیو رو نمیره.
> > > 
> > > 
> > > بله ظاهرا یوتیوب شناسایی میکنه و برای منم چند روزه همین وضعه. فعلا برای تماشای ویدئوها، زیر ویدئو روی **"همرسانی"** کلیک میکنم و بعد **<>جاسازی** رو میزنم
> > 
> > 
> > دوست عزیز میشه یکبار دیگه بگین...همرسانی و جاسازی رو متوجه نمیشم.
> 
> برای من فارسیه و این کلمات رو نوشته. همون گزینه share و وقتی پنجرش باز شد، گزینه اولی <>

دمت گرم داداش. جواب داد. با اجازت روشی که گفتی رو توی نت به اشتراک بذارم برای کسانیکه همین مشکل رو دارند.

**Comment by itsthepatrick** [comment]
دوستان منم همین مشکل رو داشتم،اگه با tunnel میرید،مطمئن شید که firewall تون هیچ چیز مربوط به oblivion رو بلاک نمیکنه
بعد مطمئن شید که ادبلاکر روی یوتیوب غیر فعاله
اگه باز هم اوکی نشد،با هر کدوم از اسکنر هایی که تو ircf.space لیستشون هست(برای من اونایی که تحت وب نبودن بهتر کار کردن) خودتون اندپوینت پیدا کنید،و از اون استفاده کنید
