### ISSUE TITLE
Adding the ability to connect with a network connection instead of a proxy

### ISSUE THREAD

**Issue by Amohasan23** [bepass-org/oblivion-desktop#64]
### Feature description

درود بر شما توسعه دهندگان بزرگوار
لطفا قابلیت کانکشن  را برای این ابزار محیا کنید تا کل ترافیک سیستم را از طریق یک کانکشن شبکه عبور دهد نه از طریق پروکسی در تنظیمات
سپاس فراوان و خسته نباشید

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،

درحال کار روی این‌موضوع برای نسخه‌های بعدی هستیم
