### ISSUE TITLE
اجازه بدید برنامه را تغییر اندازه بدهیم

### ISSUE THREAD

**Issue by xmha97** [bepass-org/oblivion-desktop#644]
### Feature description | توضیحات ویژگی

سلام، لطفا اجازه دهید برنامه را تغییر اندازه دهیم
من از یک تبلت ویندوزی استفاده می‌کنم و این برای من خوش‌آیندتر است

![image](https://github.com/user-attachments/assets/3906b5e3-1152-4043-8ad1-8eb655e26e00)
حتی اگر یوآی برنامه مناسب گوشی باشد باز هم خوبه که بشه ری‌سایزش کنیم

**Comment by ircfspace** [comment]
سلام
این‌امکان فراهم شد و در آپدیت بعدی از برنامه در دسترس قرار میگیره

**Comment by xmha97** [comment]
درود، اپلیکیشن رو آپدیت کردم
 ماگزیمایز میشه اما همچنان نمی‌تونم ری‌سایز کنم

https://github.com/user-attachments/assets/4fee221a-c560-451e-80b9-c103ca00f125

**Comment by ircfspace** [comment]
در این‌نسخه امکان تغییر اندازه به تمام صفحه فراهم شده
در نسخه‌های بعدی امکان کاستومایز بیشتری رو فراهم میکنیم

**Comment by xmha97** [comment]
ممنون
