### ISSUE TITLE
blacklist upgrade

### ISSUE THREAD

**Issue by itsthepatrick** [bepass-org/oblivion-desktop#649]
### Feature description | توضیحات ویژگی

greetings!
first of all, thanks for everything you guys did, you guys had the goal to provide uncensored internet to everybody, and you did it really well!

The idea:
- adding support of .txt to blacklist
- creating a web scraper for [this site](https://eservices.ito.gov.ir/Page/IPList),(which has a big list of Iranian registered sites without .ir, which makes connection to them way easier)
- making a GitHub repo (or .io) to update the file through it

_for some reason, I couldn't create the scraper (some problems with the table loading and next button), but I am not an expert, and I think you guys could do it_

PS: _the site has a download button which is broken_ nvm it worked after 1 month of trying

**Comment by ircfspace** [comment]
Hello,  
Thank you for your feedback.  

In the **tun** feature, which utilizes **sing-box**, we have used the blacklist from the **[Chocolate4U/Iran-sing-box-rules](https://github.com/Chocolate4U/Iran-sing-box-rules)** repository, as it is the most comprehensive and reliable source. If there are updates to the list or new items to be added individually or in groups, you should submit a PR to that repository, as it is compatible with sing-box.

**Comment by itsthepatrick** [comment]
> Hello, Thank you for your feedback.
> 
> In the **tun** feature, which utilizes **sing-box**, we have used the blacklist from the **[Chocolate4U/Iran-sing-box-rules](https://github.com/Chocolate4U/Iran-sing-box-rules)** repository, as it is the most comprehensive and reliable source. If there are updates to the list or new items to be added individually or in groups, you should submit a PR to that repository, as it is compatible with sing-box.

thanks!is there any way to have a link like that for system proxy?

**Comment by ircfspace** [comment]
We are currently working on stabilizing the TUN feature in the app. After that, we might connect the system proxy to SingBox, so it can potentially benefit from its routing rules.
