### ISSUE TITLE
غیر فعال نشدن آیکن "پیکربندی شبکه"

### ISSUE THREAD

**Issue by Paaayman** [bepass-org/oblivion-desktop#65]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

https://github.com/bepass-org/oblivion-desktop/assets/125666427/5c7954d1-63b6-4b43-aa23-a07e6c711516

### Minimal Reproducible Example (MRE)

1-طبق فیلم ارائه شده گزینه "پیکر بندی شبکه" غیر فعال نمیشود
2-با غیر فعال کردن پیکر بندی شبکه گزینه "نمایش آی پی غیر فعال میشود"

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

1. مورد اول برطرف شد و در آپدیت بعدی در دسترس قرار میگیره
2. این‌مورد مشکل نیست؛ وقتی پروکسی سیستم تعریف نشه، IP پروکسی رو دریافت نمیکنین و آیپی اصلیتون رو می‌بینین. بنابراین لازمه درحالت پیکربندی خاموش، اینم خاموش‌شه
