### ISSUE TITLE
فایل warp plus در کنار بسته قرار ندارد

### ISSUE THREAD

**Issue by homa2006** [bepass-org/oblivion-desktop#651]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![image](https://github.com/user-attachments/assets/7022aff6-aa32-4163-9605-57f9ffa4145f)
فایل warp plus در کنار بسته قرار ندارد ! لطفا کمک کنید اینو حلش کنم، نسخه قبل از اخرین نسخه رو هم نصب کردم اینو نشون داد 

### Relevant log output | لاگ برنامه

```shell
نفهمیدم
```

**Comment by ircfspace** [comment]
سلام
[این توضیحات](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3) رو مطالعه کنید
