### ISSUE TITLE
Split Tunneling for Oblivion-Desktop

### ISSUE THREAD

**Issue by trentcalvert** [bepass-org/oblivion-desktop#656]
### Feature description | توضیحات ویژگی

If the implementation described in [this issue](https://github.com/orgs/bepass-org/projects/4/views/1?pane=issue&itemId=90962635) already covers split tunneling functionality, please disregard this request. Otherwise, adding the ability to selectively route specific applications or websites through the VPN while maintaining direct access for others would be a valuable enhancement.

**Comment by ircfspace** [comment]
Hello,  
Thank you for your feedback.  
This feature is available as part of the blacklist settings.
