### ISSUE TITLE
bypass Iran IPs and Domains

### ISSUE THREAD

**Issue by miitzi** [bepass-org/oblivion-desktop#66]
### Feature description

اگر بشه آی پی ها و دامنه های ایرانی bypass بشه که نیاز به خاموش روشن کردن سرویس نباشه خیلی بهتر میشه.

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
همونطور که گفته شد ویژگی Routing Rules در آپدیت‌های بعدی اضافه میشه

**Comment by miitzi** [comment]
سلام ارادت
اطلاعی نداشتم
متشکرم

**Comment by miladhatami1393** [comment]
Good luck
