### ISSUE TITLE
اجرا نشدن نسخه جدید در ubuntu

### ISSUE THREAD

**Issue by Tebjox** [bepass-org/oblivion-desktop#664]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در آخرین نسخه stable یعنی v2.1.2 و نسخه بتا v2.3.6 نرم افزار به هیچ وجه اجرا نمی شود.
برای بدست آوردن ارور، سعی کردم از طریق ترمینال اون رو اجرا کنم که همچین اروری رو دریافت کردم:
Ubuntu version:  24.04.1 LTS

![Screenshot from 2024-12-18 14-27-37](https://github.com/user-attachments/assets/bd929274-a182-42f7-b907-ee458aea27aa)

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Download latest (.deb) version.
2. Run

### Relevant log output | لاگ برنامه

```shell
null
```

**Comment by Hosein-Rahnama** [comment]
> با استفاده از راه حل [drata/drata-agent#20 (comment)](https://github.com/drata/drata-agent/issues/20#issuecomment-2094848078) مشکل حل شد. دستور زیر رو اجرا کردم
> 
> ```
> sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> ```

طبق [صحبت‌هایی](https://github.com/drata/drata-agent/issues/20#issuecomment-2173474122) که یکی از توسعه‌دهنده‌های drata زیر همون پست کرده، ظاهرا غیر فعال کردن AppArmor برای Kernel کار خوبی نیست. باید از آپشن `--no-sandbos' برای `drata` استفاده کنی که [اینجا](https://github.com/drata/drata-agent/issues/20#issuecomment-2181136642) توضیح داده شده. طبق این [پست](https://github.com/drata/drata-agent/issues/20#issuecomment-2339248189)، مشکل هم ظاهرا باگ خود `drata` نیست و یک عدم سازگاری ubuntu نسخه‌ی 24.04 با این نرم‌افزاره.

**Comment by Hosein-Rahnama** [comment]
> با استفاده از راه حل [drata/drata-agent#20 (comment)](https://github.com/drata/drata-agent/issues/20#issuecomment-2094848078) مشکل حل شد. دستور زیر رو اجرا کردم
> 
> ```
> sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> ```

According to [comments](https://github.com/drata/drata-agent/issues/20#issuecomment-2173474122) of drata's developers, it is not a good practice to deactivate AppArmor and we should use `--no-sandbox` option.

**Comment by Tebjox** [comment]
> > با استفاده از راه حل [drata/drata-agent#20 (comment)](https://github.com/drata/drata-agent/issues/20#issuecomment-2094848078) مشکل حل شد. دستور زیر رو اجرا کردم
> > ```
> > sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> > ```
> 
> According to [comments](https://github.com/drata/drata-agent/issues/20#issuecomment-2173474122) of drata's developers, it is not a good practice to deactivate AppArmor.

با این حساب مجبوریم هر دفعه نرم افزار رو از طریق ترمینال با فلگ
`--no-sandbox`
اجرا کنیم.

یعنی دستور نهایی میشه این:
`oblivion-desktop --no-sandbox`

**Comment by Hosein-Rahnama** [comment]
> > > با استفاده از راه حل [drata/drata-agent#20 (comment)](https://github.com/drata/drata-agent/issues/20#issuecomment-2094848078) مشکل حل شد. دستور زیر رو اجرا کردم
> > > ```
> > > sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> > > ```
> > 
> > 
> > According to [comments](https://github.com/drata/drata-agent/issues/20#issuecomment-2173474122) of drata's developers, it is not a good practice to deactivate AppArmor.
> 
> با این حساب مجبوریم هر دفعه نرم افزار رو از طریق ترمینال با فلگ
> 
> ```
> --no-sandbox
> ```
> 
> اجرا کنیم.
> 
> یعنی دستور نهایی میشه این:
> 
> ```
> oblivion-desktop --no-sandbox
> ```

توی همون کامنت اشاره شده راه‌حل بهتر تا زمانی که مشکل اوبنتو با `drata` حل بشه استفاده از فلگی که گفتی برای خود `drata` عه.
‍‍‍`drata-agent --no-sandbox `
گفته که این مشکل از نسخه‌ی ۲۳ اوبنتو شروع شده و به ۲۴ هم سرایت کرده. احتمالا `obilibion-desktop` هم ازین نرم‌افزار استفاده می‌کنه و برای همین به همچین مشکلی می‌خوره ولی در حال حاضر فکر نمی‌کنم `oblivion-desktop` همچین فلگی داشته باشه. در حال حاضر من خودم از نسخه‌ی قدیمی‌ترش ‍‍`v1.6.151` که این مشکل رو نداره استفاده می‌کنم. می‌شه هم مستقیم از خود `warp-plus` بدون واسط گرافیکی استفاده کنیم تا بالاخره این مشکل حل بشه.

**Comment by Tebjox** [comment]
> > > > با استفاده از راه حل [drata/drata-agent#20 (comment)](https://github.com/drata/drata-agent/issues/20#issuecomment-2094848078) مشکل حل شد. دستور زیر رو اجرا کردم
> > > > ```
> > > > sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> > > > ```
> > > 
> > > 
> > > According to [comments](https://github.com/drata/drata-agent/issues/20#issuecomment-2173474122) of drata's developers, it is not a good practice to deactivate AppArmor.
> > 
> > 
> > با این حساب مجبوریم هر دفعه نرم افزار رو از طریق ترمینال با فلگ
> > ```
> > --no-sandbox
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > اجرا کنیم.
> > یعنی دستور نهایی میشه این:
> > ```
> > oblivion-desktop --no-sandbox
> > ```
> 
> توی همون کامنت اشاره شده راه‌حل بهتر تا زمانی که مشکل اوبنتو با `drata` حل بشه استفاده از فلگی که گفتی برای خود `drata` عه. ‍‍‍`drata-agent --no-sandbox ` گفته که این مشکل از نسخه‌ی ۲۳ اوبنتو شروع شده و به ۲۴ هم سرایت کرده. احتمالا `oblivion-desktop` هم ازین نرم‌افزار استفاده می‌کنه و برای همین به همچین مشکلی می‌خوره ولی در حال حاضر فکر نمی‌کنم `oblivion-desktop` همچین فلگی داشته باشه. در حال حاضر من خودم از نسخه‌ی قدیمی‌ترش ‍‍`v1.6.15` که این مشکل رو نداره استفاده می‌کنم. می‌شه هم مستقیم از خود `warp-plus` بدون واسط گرافیکی استفاده کنیم تا بالاخره این مشکل حل بشه.

ساپورت میکنه و بطور موقت مشکل حل شده. (تو کامنت بالاتر روش رو آپدیت کردم).
با تشکر از راهنمایی شما.

**Comment by Saeid008** [comment]
سلام. @ircfspace 
میشه مثل warp-cli طراحی کنید که گرافیکی نباشه؟ به با ترمینال اوبنتو راحت بشه باهاش کار کرد.

**Comment by ircfspace** [comment]
از [warp-plus](https://github.com/bepass-org/warp-plus) استفاده کنید
@Saeid008

**Comment by hmrad** [comment]
سلام منم تا اینجای مسیر اومدم ولی الان که با نو سندباکس رانش میکنم همچین اروری میده
Cannot find target for triple amdgcn-- Unable to find target for this triple (no targets are registered)
[22109:0406/225040.200429:ERROR:gpu_process_host.cc(982)] GPU process exited unexpectedly: exit_code=139
[22109:0406/225040.200476:FATAL:gpu_data_manager_impl_private.cc(423)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
هرچی تگ های گرافیک هم برمیدارم همینه ... نظری دارین ؟

**Comment by ircfspace** [comment]
خودم چنین مشکلی برخورد نکردم، اما این راهنمایی رو chatGPT داد
@hmrad 

برای رفع این مشکل، می‌توانید این مراحل را دنبال کنید:

1. به‌روزرسانی درایورهای گرافیکی: از آخرین نسخه درایورهای GPU خود استفاده کنید.

2. غیرفعال کردن استفاده از GPU در Electron: می‌توانید با تنظیم متغیر محیطی ELECTRON_ENABLE_HARDWARE_ACCELERATION به false، استفاده از شتاب‌دهی سخت‌افزاری را غیرفعال کنید تا به طور موقت مشکل را حل کنید. برای این کار می‌توانید قبل از اجرای اپلیکیشن دستور زیر را وارد کنید:

`export ELECTRON_ENABLE_HARDWARE_ACCELERATION=false`

3. بررسی سازگاری سیستم: اگر از کارت گرافیک AMD استفاده می‌کنید، بررسی کنید که آیا همه ابزارهای مربوط به AMD در سیستم شما نصب شده‌اند یا نه.

این خطا به احتمال زیاد به دلیل مشکلات در پردازش GPU یا شتاب‌دهی سخت‌افزاری است.

----
اگر طبق این راهنما پیش رفتین،
https://github.com/bepass-org/oblivion-desktop/wiki/The-error-FATAL:setuid_sandbox_host

این دستور رو هم تست بگیرین:
`ELECTRON_ENABLE_HARDWARE_ACCELERATION=false ./oblivion-desktop --no-sandbox`
