### ISSUE TITLE
تنظیم پراکسی فقط برای استفاده برنامه های انتخاب شده

### ISSUE THREAD

**Issue by hassanshahi** [bepass-org/oblivion-desktop#667]
### Feature description | توضیحات ویژگی

لطفا در نسخه دسکتاپ قابلیتی قرار دهید که فقط برنامه های خاص از ترافیک عبور کنند
یا اینکه با تنظیم یک پورت بتوان از آن در برنامه خاص مثل فایرفاکس استفاده کرد و سایر برنامه ها از ترافیک عبور نکنند

سپاس

**Comment by ircfspace** [comment]
سلام
دو فیچر به شرح زیر وجود داره:
- امکان اضافه کردن برنامه‌های موردنظر به لیست سیاه، برای جلوگیری از عبور از وارپ (مرتبط با حالت اتصال تانل)
- امکان استفاده از حالت اتصال None، که بشه فقط پروکسی رو در برنامه‌هایی نظیر فایرفاکس و ... استفاده کرد

**Comment by hassanshahi** [comment]
درود

این دو فیچر را دیده بودم اما به درستی کار نمی کرد:

فیچر اول که مربوط به لیست سیاه می باشد تنها برای عدم عبور دامین کار می کند هیچ مقاله ای برای تنظیم این لیست پیدا نکردم
فیچر دوم الان متوجه شدم که بایستی تیک LAN برداشته شود وگرنه کار نمی کند

من نسخه اندروید هم مدتی هست استفاده می کنم و این نسخه دسکتاپ که هر دو بینظیر هستند

سپاس بیکران

**Comment by ircfspace** [comment]
در رابطه با مورد اول، توی نسخه ۲.۵ یه‌سری الگو برای لیست سیاه وجود داره که اگر روی دکمه نمونه کلیک کنین، نمونه‌ی اضافه‌کردن برنامه هم داخلش هست.
