### ISSUE TITLE
نسخه 2.5.0 ویندوز 11 أمار به درستی نمایش داده نمیشه

### ISSUE THREAD

**Issue by nonbarbari** [bepass-org/oblivion-desktop#668]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

![image](https://github.com/user-attachments/assets/02ed8a14-3ab1-4f4f-9547-59ebc1ae7373)

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

از تانل استفاده کردم و وارپ

### Relevant log output | لاگ برنامه

```shell
.
```

**Comment by ShadowZagrosDev** [comment]
چه آمار عجیبی. همیشه همینطور نشون داده میشه؟ منظورم این با دیسکانکت کردن و کانکت مجدد یا ریستارت برنامه هم همینطوره؟
اگه آره، لطفا این کارها رو در حالی که کانکت هستید با برنامه و نمایش آمار فعاله، انجام بدید تا ما بتونیم بهتر بررسی کنیم.
این دستورات روی توی پاورشل وارد کنید و از هر کدوم یک اسکرین‌شات مجزا بگیرید.

```bash
Get-NetAdapter -Name *
```
```bash
Get-NetAdapter -Name * -IncludeHidden
```
   
   و در نهایت این دستور رو بزنید:
```bash
typeperf "Network Interface(*)\Bytes Received/sec" typeperf "Network Interface(*)\Bytes Sent/sec"
```
بذارید یه کم کار کنه و آمار رو بده. حالا در حالی که Oblivion-Desktop هم مشخص باشه، اسکرین‌شات بگیرید.

هر سه این اسکرین‌شات‌ها رو همینجا بفرستید. توصیه ما اینه اطلاعات شخصی مثل IP در برنامه و یوزرنیم و MacAddress های موجود در پاورشل(نتیجه دو دستور اول) رو ماسک کنید.

**Comment by nonbarbari** [comment]
![1](https://github.com/user-attachments/assets/33ea2b16-4d49-4a42-b466-26db2d20b1c9)
![22](https://github.com/user-attachments/assets/dc5ad6cd-15ec-4227-8ecd-dd52fb99c9d9)

**Comment by ircfspace** [comment]
درصورت امکان لاگ برنامه رو هم قرار بدین
@nonbarbari

**Comment by ShadowZagrosDev** [comment]
اسکرین‌شات دستور اول رو نفرستادید!
بنظر میرسه نتیجه اون Ethernet و Wi-Fi باشه. درسته؟
اگه آره، به مسیر زیر(چون لاگ نفرستادید، تصور میکنم ویندوز در درایو C نصب شده باشه) برید:
```bash
C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
```
در اونجا باید فایل اجرایی zag-netStats.exe موجود باشه. یه کنسول پاورشل در اون مسیر باز کنید و این دستورات رو جداگانه اجرا کنید:
```bash
./zag-netStats.exe -i Ethernet
```
```bash
./zag-netStats.exe -i Wi-Fi
```
هر کدام از دستورات، آمار اون اینترفیس رو باید نمایش بده. آیا اون آمار درست هستن یا شبیه به آمار برنامه؟
نتیجه هر دستور رو برای ما بفرستید.

**Comment by nonbarbari** [comment]
> اسکرین‌شات دستور اول رو نفرستادید! بنظر میرسه نتیجه اون Ethernet و Wi-Fi باشه. درسته؟ اگه آره، به مسیر زیر(چون لاگ نفرستادید، تصور میکنم ویندوز در درایو C نصب شده باشه) برید:
> 
 (رو به روی آداپتور های هیدن ستاره هست)
نت روی آداپتور Ethernet فعاله

> ```shell
> C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
> ```
> 
> در اونجا باید فایل اجرایی zag-netStats.exe موجود باشه. یه کنسول پاورشل در اون مسیر باز کنید و این دستورات رو جداگانه اجرا کنید:
> 
> ```shell
> ./zag-netStats.exe -i Ethernet
> ```

```

| INTERFACE |  SENT SPEED   |  RECV SPEED  | TOTAL SENT  | TOTAL RECV | TOTAL USAGE |
+-----------+---------------+--------------+-------------+------------+-------------+
| Ethernet  | 11112.00 GB/s | 6664.00 GB/s | 11112.00 GB | 6664.00 GB | 17776.00 GB |
+-----------+---------------+--------------+-------------+------------+-------------+
+-----------+------------+-------------+-------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED  | TOTAL SENT  | TOTAL RECV | TOTAL USAGE |
+-----------+------------+-------------+-------------+------------+-------------+
| Ethernet  | 0.00 B/s   | 984.00 GB/s | 11112.00 GB | 7648.00 GB | 18760.00 GB |
+-----------+------------+-------------+-------------+------------+-------------+
+-----------+--------------+--------------+-------------+------------+-------------+
| INTERFACE |  SENT SPEED  |  RECV SPEED  | TOTAL SENT  | TOTAL RECV | TOTAL USAGE |
+-----------+--------------+--------------+-------------+------------+-------------+
| Ethernet  | 2424.00 GB/s | 2232.00 GB/s | 13536.00 GB | 9880.00 GB | 23416.00 GB 
```


> 
> ```shell
> ./zag-netStats.exe -i Wi-Fi
> ```
> 



```

| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Wi-Fi     | 0.00 B/s   | 0.00 B/s   | 0.00 B     | 0.00 B     | 0.00 B      |
+-----------+------------+------------+------------+------------+-------------+
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Wi-Fi     | 0.00 B/s   | 0.00 B/s   | 0.00 B     | 0.00 B     | 0.00 B      |
+-----------+------------+------------+------------+------------+-------------+
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Wi-Fi     | 0.00 B/s   | 0.00 B/s   | 0.00 B     | 0.00 B     | 0.00 B      |
+-----------+------------+------------+------------+------------+-------------+
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Wi-Fi     | 0.00 B/s   | 0.00 B/s   | 0.00 B     | 0.00 B     | 0.00 B      |
+-----------+------------+------------+------------+------------+-------------+

```
> هر کدام از دستورات، آمار اون اینترفیس رو باید نمایش بده. آیا اون آمار درست هستن یا شبیه به آمار برنامه؟ نتیجه هر دستور رو برای ما بفرستید.

**Comment by ShadowZagrosDev** [comment]
ممنونم از گزارش نتیجه. ابزار نیاز به بازبینی و رفع باگ احتمالی داره. لطفا روزانه همین ایشو رو چک کنید تا هروقت فیکس شده همینجا اطلاع بدم تا نسخه جدید رو تست کنید.

**Comment by ShadowZagrosDev** [comment]
ممنون میشم یه تست دیگه برای ما انجام بدین:
```bash
./zag-netStats.exe -i Ethernet -p 6
```

**Comment by nonbarbari** [comment]
>zag-netStats.exe -i Ethernet -p 6
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
| INTERFACE |     SENT SPEED     |    RECV SPEED     |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
| Ethernet  | 272840.000000 GB/s | 42176.000000 GB/s | 272840.000000 GB | 42176.000000 GB | 315016.000000 GB |
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 7720.000000 GB/s | 7024.000000 GB/s | 280560.000000 GB | 49200.000000 GB | 329760.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+-----------------+-----------------+------------------+-----------------+------------------+
| INTERFACE |   SENT SPEED    |   RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+-----------------+-----------------+------------------+-----------------+------------------+
| Ethernet  | 872.000000 GB/s | 824.000000 GB/s | 281432.000000 GB | 50024.000000 GB | 331456.000000 GB |
+-----------+-----------------+-----------------+------------------+-----------------+------------------+
+-----------+--------------+-----------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |   RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+-----------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 240.000000 GB/s | 281432.000000 GB | 50264.000000 GB | 331696.000000 GB |
+-----------+--------------+-----------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 1784.000000 GB/s | 1728.000000 GB/s | 283216.000000 GB | 51992.000000 GB | 335208.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+--------------+-----------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |   RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+-----------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 240.000000 GB/s | 283216.000000 GB | 52232.000000 GB | 335448.000000 GB |
+-----------+--------------+-----------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 2424.000000 GB/s | 1584.000000 GB/s | 285640.000000 GB | 53816.000000 GB | 339456.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+-------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED     |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+-------------------+------------------+-----------------+------------------+
| Ethernet  | 8400.000000 GB/s | 10680.000000 GB/s | 294040.000000 GB | 64496.000000 GB | 358536.000000 GB |
+-----------+------------------+-------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 7848.000000 GB/s | 7512.000000 GB/s | 301888.000000 GB | 72008.000000 GB | 373896.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 2552.000000 GB/s | 2712.000000 GB/s | 304440.000000 GB | 74720.000000 GB | 379160.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+--------------+--------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |  RECV SPEED  |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+--------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 0.000000 B/s | 304440.000000 GB | 74720.000000 GB | 379160.000000 GB |
+-----------+--------------+--------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 7208.000000 GB/s | 6936.000000 GB/s | 311648.000000 GB | 81656.000000 GB | 393304.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 4168.000000 GB/s | 4876.000000 GB/s | 315816.000000 GB | 86532.000000 GB | 402348.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 4848.000000 GB/s | 3960.000000 GB/s | 320664.000000 GB | 90492.000000 GB | 411156.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 4168.000000 GB/s | 4072.000000 GB/s | 324832.000000 GB | 94564.000000 GB | 419396.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 1616.000000 GB/s | 2472.000000 GB/s | 326448.000000 GB | 97036.000000 GB | 423484.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+------------------+
| Ethernet  | 9008.000000 GB/s | 4036.000000 GB/s | 335456.000000 GB | 101072.000000 GB | 436528.000000 GB |
+-----------+------------------+------------------+------------------+------------------+------------------+
+-----------+------------------+------------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+------------------+
| Ethernet  | 3648.000000 GB/s | 5564.000000 GB/s | 339104.000000 GB | 106636.000000 GB | 445740.000000 GB |
+-----------+------------------+------------------+------------------+------------------+------------------+
+-----------+------------------+------------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+------------------+
| Ethernet  | 1120.000000 GB/s | 1992.000000 GB/s | 340224.000000 GB | 108628.000000 GB | 448852.000000 GB |
+-----------+------------------+------------------+------------------+------------------+------------------+
+-----------+--------------+-----------------+------------------+------------------+------------------+
| INTERFACE |  SENT SPEED  |   RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+-----------------+------------------+------------------+------------------+
| Ethernet  | 0.000000 B/s | 240.000000 GB/s | 340224.000000 GB | 108868.000000 GB | 449092.000000 GB |
+-----------+--------------+-----------------+------------------+------------------+------------------+
+-----------+--------------+--------------+------------------+------------------+------------------+
| INTERFACE |  SENT SPEED  |  RECV SPEED  |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+--------------+------------------+------------------+------------------+
| Ethernet  | 0.000000 B/s | 0.000000 B/s | 340224.000000 GB | 108868.000000 GB | 449092.000000 GB |
+-----------+--------------+--------------+------------------+------------------+------------------+
+-----------+--------------+-----------------+------------------+------------------+------------------+
| INTERFACE |  SENT SPEED  |   RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+-----------------+------------------+------------------+------------------+
| Ethernet  | 0.000000 B/s | 240.000000 GB/s | 340224.000000 GB | 109108.000000 GB | 449332.000000 GB |
+-----------+--------------+-----------------+------------------+------------------+------------------+
+-----------+------------------+--------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED    |  RECV SPEED  |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+--------------+------------------+------------------+------------------+
| Ethernet  | 4496.000000 GB/s | 0.000000 B/s | 344720.000000 GB | 109108.000000 GB | 453828.000000 GB |
+-----------+------------------+--------------+------------------+------------------+------------------+
+-----------+------------------+------------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+------------------+
| Ethernet  | 8444.000000 GB/s | 1964.000000 GB/s | 353164.000000 GB | 111072.000000 GB | 464236.000000 GB |
+-----------+------------------+------------------+------------------+------------------+------------------+
+-----------+-------------------+--------------------+------------------+------------------+------------------+
| INTERFACE |    SENT SPEED     |     RECV SPEED     |    TOTAL SENT    |    TOTAL RECV    |   TOTAL USAGE    |
+-----------+-------------------+--------------------+------------------+------------------+------------------+
| Ethernet  | 63948.000000 GB/s | 390252.000000 GB/s | 417112.000000 GB | 501324.000000 GB | 918436.000000 GB |
+-----------+-------------------+--------------------+------------------+------------------+------------------+
+-----------+-------------------+--------------------+------------------+------------------+-------------------+
| INTERFACE |    SENT SPEED     |     RECV SPEED     |    TOTAL SENT    |    TOTAL RECV    |    TOTAL USAGE    |
+-----------+-------------------+--------------------+------------------+------------------+-------------------+
| Ethernet  | 17676.000000 GB/s | 129792.000000 GB/s | 434788.000000 GB | 631116.000000 GB | 1065904.000000 GB |
+-----------+-------------------+--------------------+------------------+------------------+-------------------+
+-----------+--------------+--------------+------------------+------------------+-------------------+
| INTERFACE |  SENT SPEED  |  RECV SPEED  |    TOTAL SENT    |    TOTAL RECV    |    TOTAL USAGE    |
+-----------+--------------+--------------+------------------+------------------+-------------------+
| Ethernet  | 0.000000 B/s | 0.000000 B/s | 434788.000000 GB | 631116.000000 GB | 1065904.000000 GB |
+-----------+--------------+--------------+------------------+------------------+-------------------+
+-----------+------------------+------------------+------------------+------------------+-------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |    TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+-------------------+
| Ethernet  | 2424.000000 GB/s | 2568.000000 GB/s | 437212.000000 GB | 633684.000000 GB | 1070896.000000 GB |
+-----------+------------------+------------------+------------------+------------------+-------------------+
+-----------+------------------+------------------+------------------+------------------+-------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |    TOTAL USAGE    |
+-----------+------------------+------------------+------------------+------------------+-------------------+
| Ethernet  | 2772.000000 GB/s | 2328.000000 GB/s | 439984.000000 GB | 636012.000000 GB | 1075996.000000 GB |
+-----------+------------------+------------------+------------------+------------------+-------------------+
+-----------+-------------------+------------------+------------------+------------------+-------------------+
| INTERFACE |    SENT SPEED     |    RECV SPEED    |    TOTAL SENT    |    TOTAL RECV    |    TOTAL USAGE    |
+-----------+-------------------+------------------+------------------+------------------+-------------------+
| Ethernet  | 57824.000000 GB/s | 1064.000000 GB/s | 497808.000000 GB | 637076.000000 GB | 1134884.000000 GB |
+-----------+-------------------+------------------+------------------+------------------+-------------------+

**Comment by nonbarbari** [comment]
>zag-netStats.exe -i Ethernet -p 6
+-----------+-----------------+------------------+---------------+----------------+----------------+
| INTERFACE |   SENT SPEED    |    RECV SPEED    |  TOTAL SENT   |   TOTAL RECV   |  TOTAL USAGE   |
+-----------+-----------------+------------------+---------------+----------------+----------------+
| Ethernet  | 296.000000 GB/s | 5300.000000 GB/s | 296.000000 GB | 5300.000000 GB | 5596.000000 GB |
+-----------+-----------------+------------------+---------------+----------------+----------------+
+-----------+-----------------+------------------+---------------+----------------+----------------+
| INTERFACE |   SENT SPEED    |    RECV SPEED    |  TOTAL SENT   |   TOTAL RECV   |  TOTAL USAGE   |
+-----------+-----------------+------------------+---------------+----------------+----------------+
| Ethernet  | 344.000000 GB/s | 2972.000000 GB/s | 640.000000 GB | 8272.000000 GB | 8912.000000 GB |
+-----------+-----------------+------------------+---------------+----------------+----------------+
+-----------+--------------+------------------+---------------+-----------------+-----------------+
| INTERFACE |  SENT SPEED  |    RECV SPEED    |  TOTAL SENT   |   TOTAL RECV    |   TOTAL USAGE   |
+-----------+--------------+------------------+---------------+-----------------+-----------------+
| Ethernet  | 0.000000 B/s | 4524.000000 GB/s | 640.000000 GB | 12796.000000 GB | 13436.000000 GB |
+-----------+--------------+------------------+---------------+-----------------+-----------------+
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
| INTERFACE |   SENT SPEED    |    RECV SPEED    |   TOTAL SENT   |   TOTAL RECV    |   TOTAL USAGE   |
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
| Ethernet  | 932.000000 GB/s | 3732.000000 GB/s | 1572.000000 GB | 16528.000000 GB | 18100.000000 GB |
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
| INTERFACE |   SENT SPEED    |    RECV SPEED    |   TOTAL SENT   |   TOTAL RECV    |   TOTAL USAGE   |
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
| Ethernet  | 348.000000 GB/s | 1140.000000 GB/s | 1920.000000 GB | 17668.000000 GB | 19588.000000 GB |
+-----------+-----------------+------------------+----------------+-----------------+-----------------+
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
| INTERFACE |     SENT SPEED     |    RECV SPEED     |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
| Ethernet  | 280140.000000 GB/s | 15260.000000 GB/s | 282060.000000 GB | 32928.000000 GB | 314988.000000 GB |
+-----------+--------------------+-------------------+------------------+-----------------+------------------+
+-----------+--------------+------------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 1140.000000 GB/s | 282060.000000 GB | 34068.000000 GB | 316128.000000 GB |
+-----------+--------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 3020.000000 GB/s | 8172.000000 GB/s | 285080.000000 GB | 42240.000000 GB | 327320.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+------------------+------------------+------------------+-----------------+------------------+
| INTERFACE |    SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+------------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 1052.000000 GB/s | 4020.000000 GB/s | 286132.000000 GB | 46260.000000 GB | 332392.000000 GB |
+-----------+------------------+------------------+------------------+-----------------+------------------+
+-----------+--------------+--------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |  RECV SPEED  |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+--------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 0.000000 B/s | 286132.000000 GB | 46260.000000 GB | 332392.000000 GB |
+-----------+--------------+--------------+------------------+-----------------+------------------+
+-----------+--------------+------------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 2964.000000 GB/s | 286132.000000 GB | 49224.000000 GB | 335356.000000 GB |
+-----------+--------------+------------------+------------------+-----------------+------------------+
+-----------+-----------------+------------------+------------------+-----------------+------------------+
| INTERFACE |   SENT SPEED    |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+-----------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 296.000000 GB/s | 1196.000000 GB/s | 286428.000000 GB | 50420.000000 GB | 336848.000000 GB |
+-----------+-----------------+------------------+------------------+-----------------+------------------+
+-----------+--------------+------------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 1028.000000 GB/s | 286428.000000 GB | 51448.000000 GB | 337876.000000 GB |
+-----------+--------------+------------------+------------------+-----------------+------------------+
+-----------+--------------+------------------+------------------+-----------------+------------------+
| INTERFACE |  SENT SPEED  |    RECV SPEED    |    TOTAL SENT    |   TOTAL RECV    |   TOTAL USAGE    |
+-----------+--------------+------------------+------------------+-----------------+------------------+
| Ethernet  | 0.000000 B/s | 2084.000000 GB/s | 286428.000000 GB | 53532.000000 GB | 339960.000000 GB |
+-----------+--------------+------------------+------------------+-----------------+------------------+

این جا کلا برنامه را بسته بودم

**Comment by ShadowZagrosDev** [comment]
ممنون. عجیبه که ۶ رقم اعشار صفر باشن همگی. یه نسخه جهت تریس ساختم، امکان داره تستش کنید؟ این نسخه کاری به Oblivion نداره و قابل استفاده هم نیست داخلش. فقط جهت اینکه بتونم متوجه شم مشکل دقیقا از کجا نشأت میگیره. با این دستور ازش خروجی بگیرین و لطفا نتیجه رو از شروعش بفرستید چون مقادیر اینیشیال مهمه برای بررسی:
```bash
./zag.exe -i Ethernet
```
[zag.zip](https://github.com/user-attachments/files/18218090/zag.zip)

**Comment by nonbarbari** [comment]
zag.exe -i Ethernet

init: {"name":"Ethernet","bytesSent":17613670,"bytesRecv":241092437,"packetsSent":130999,"packetsRecv":194640,"errin":0,"errout":0,"dropin":87,"dropout":0,"fifoin":0,"fifoout":0}
current: {"name":"Ethernet","bytesSent":17615530,"bytesRecv":241093611,"packetsSent":131013,"packetsRecv":194648,"errin":0,"errout":0,"dropin":87,"dropout":0,"fifoin":0,"fifoout":0}
sent: 1860 - recv: 1174 - tSent: 1860 - tRecv: 1174
formatted => sent: {1.81640625 KB/s} - recv: {1.146484375 KB/s} - tSent: {1.81640625 KB} - tRecv: {1.146484375 KB}
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Ethernet  | 1.82 KB/s  | 1.15 KB/s  | 1.82 KB    | 1.15 KB    | 2.96 KB     |
+-----------+------------+------------+------------+------------+-------------+

current: {"name":"Ethernet","bytesSent":17620267,"bytesRecv":241101569,"packetsSent":131054,"packetsRecv":194692,"errin":0,"errout":0,"dropin":87,"dropout":0,"fifoin":0,"fifoout":0}
sent: 4737 - recv: 7958 - tSent: 6597 - tRecv: 9132
formatted => sent: {4.6259765625 KB/s} - recv: {7.771484375 KB/s} - tSent: {6.4423828125 KB} - tRecv: {8.91796875 KB}
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Ethernet  | 4.63 KB/s  | 7.77 KB/s  | 6.44 KB    | 8.92 KB    | 15.36 KB    |
+-----------+------------+------------+------------+------------+-------------+

current: {"name":"Ethernet","bytesSent":17631359,"bytesRecv":241148160,"packetsSent":131131,"packetsRecv":194776,"errin":0,"errout":0,"dropin":87,"dropout":0,"fifoin":0,"fifoout":0}
sent: 11092 - recv: 46591 - tSent: 17689 - tRecv: 55723
formatted => sent: {10.83203125 KB/s} - recv: {45.4990234375 KB/s} - tSent: {17.2744140625 KB} - tRecv: {54.4169921875 KB}
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Ethernet  | 10.83 KB/s | 45.50 KB/s | 17.27 KB   | 54.42 KB   | 71.69 KB    |
+-----------+------------+------------+------------+------------+-------------+

current: {"name":"Ethernet","bytesSent":17647417,"bytesRecv":241170453,"packetsSent":131193,"packetsRecv":194839,"errin":0,"errout":0,"dropin":87,"dropout":0,"fifoin":0,"fifoout":0}
sent: 16058 - recv: 22293 - tSent: 33747 - tRecv: 78016
formatted => sent: {15.681640625 KB/s} - recv: {21.7705078125 KB/s} - tSent: {32.9560546875 KB} - tRecv: {76.1875 KB}
+-----------+------------+------------+------------+------------+-------------+
| INTERFACE | SENT SPEED | RECV SPEED | TOTAL SENT | TOTAL RECV | TOTAL USAGE |
+-----------+------------+------------+------------+------------+-------------+
| Ethernet  | 15.68 KB/s | 21.77 KB/s | 32.96 KB   | 76.19 KB   | 109.14 KB   |
+-----------+------------+------------+------------+------------+-------------+

**Comment by ShadowZagrosDev** [comment]
خب مثل اینکه مشکل رفع شده. درسته؟

**Comment by ShadowZagrosDev** [comment]
این نسخه رو بگیرید:
https://github.com/ShadowZagrosDev/Zag-NetStats/releases/tag/v1.0.1
 و فایل اجرایی داخلش رو جایگزین قبلی در این مسیر کنید.
C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
همچنین در مسیر نصب برنامه هم این کار رو بکنید.
و توی برنامه بررسی کنید. اگر اوکیه همه چیز،‌ به ما اطلاع بدید تا نسخه جدید رو در ریلیز بعدی Oblivion قرار بدیم.

**Comment by nonbarbari** [comment]
اوکی شد.
