### ISSUE TITLE
اضافه شدن تست سرعت 

### ISSUE THREAD

**Issue by Paaayman** [bepass-org/oblivion-desktop#67]
### Feature description

با درود خدمت عزیزان 
لطفا یک ویژگی برای تست سرعت هم به برنامه اضافه کنید 
ممنون از زمانی که صرف درسترسی مردم به اینترنت آزاد میکنید
ارادت فراوان

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
براش تسک ایجاد شد و درصورت امکان در نسخه‌های بعدی اضافه میکنیم

**Comment by ircfspace** [comment]
به صورت یک ابزارک به برنامه اضافه شد و در نسخه بعدی در دسترس قرار میگیره

![image](https://github.com/bepass-org/oblivion-desktop/assets/128790947/1abbaf89-774e-4937-be41-d6fdf9db3322)

**Comment by Majidzam1101** [comment]
> سلام
> 
> ضمن تشکر از بازخورد شما، براش تسک ایجاد شد و درصورت امکان در نسخه‌های بعدی اضافه میکنیم
خطای هویت سنجی دیگه چیه نگفتی پشتیبانی برنامه ؟

**Comment by ircfspace** [comment]
> با سپاس بیشتر منظورم مثل عکس پیوست بود نمیدونم از لحاظ فنی امکانش هست یا خیر 
سعی میکنیم در آپدیتهای بعدی لحاظ کنیم
