### ISSUE TITLE
Decouple configuration settings from the connections

### ISSUE THREAD

**Issue by Coderx7** [bepass-org/oblivion-desktop#670]
### Feature description | توضیحات ویژگی

Hello, 
Currently any changes to the configuration settings/proxy settings causes the application to reconnect. 
This is not a reasonable/expected behavior as they have different functions and one is not related to the function of the other. 
A user should be able to easily switch between different proxy settings without establishing a new connection as its the norm in virtually all similar applications. However this is not the case here and I therefore would like to suggest to decouple the two unrelated functions.

**Comment by ircfspace** [comment]
Hello,  
Thank you for your feedback.  
As you are aware, the Oblivion Desktop application is a GUI for Warp-Plus, and the CLI does not currently support the feature you mentioned. However, the Warp-Plus development team is working on releasing a parallel version of the CLI that will address many such needs.
