### ISSUE TITLE
Please add http/https proxy support

### ISSUE THREAD

**Issue by Navid079** [bepass-org/oblivion-desktop#672]
### Feature description | توضیحات ویژگی

Please let the user choose between http[s]/socks5 proxy server protocols or maybe enable multipe protocols at the same time.

**Comment by ircfspace** [comment]
Hello,  
Thank you for your feedback.  
The Oblivion Desktop software is a GUI for Warp Plus.  
The mentioned issue should be raised as an issue **[here](https://github.com/bepass-org/warp-plus/issues)**.
