### ISSUE TITLE
Recent releases do not work on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Hosein-Rahnama** [bepass-org/oblivion-desktop#677]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

I am on Ubuntu 24.04. All of the releases after v1.6.15 crash or does not start. However, v1.6.15 works just fine on this OS.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

I just used `apt` to install the the corresponding `.deb` file. Then, I ran the installed program.

### Relevant log output | لاگ برنامه

```shell
I cannot provide any log since the program crash at the very beginning.
```

**Comment by ircfspace** [comment]
Hello,  
Please search for similar issues, and if you don't find a solution, let us know in this issue.

https://github.com/bepass-org/oblivion-desktop/issues?q=Ubuntu
