### ISSUE TITLE
Is it possible to use Oblivion on Ubuntu server without GUI?

### ISSUE THREAD

**Issue by jajoul** [bepass-org/oblivion-desktop#678]
### Feature description | توضیحات ویژگی

من میخوام روی سرورم تونل بشه. امکانش هست؟

**Comment by ircfspace** [comment]
برای استفاده بدون GUI باید از [warp-plus](https://github.com/bepass-org/warp-plus) استفاده کنید

**Comment by jajoul** [comment]
ممنون
