### ISSUE TITLE
tun مشکل 

### ISSUE THREAD

**Issue by ahmadlancer** [bepass-org/oblivion-desktop#680]
### Feature description | توضیحات ویژگی

دمتونگرم با این برنامه عالی ک ساختین
من فقط یه مشکل دارم ک وقتی رو حالت tun وصل میشم توی بازی صدا ندارم (پابجی استیم) ینی کلا با tun ک پینگ روی 1 نشون میده همین مشکل رو دارم حالا چه این برنامه باشه چه v2rayn
امکانش هست یه کانکشنی مثل خوده وارپ اصلی هم به برنامه اضافه کنین ک پینگ واقعی رو نشون بده با دستور پینگ چون وارپ اصلی اصلا مشکل صدا ندارم ولی به یه سرورهایی با پینگ بالا وصل میشه ک نمیتونم سرورشو عوض کنم ولی اوبلیون پینگ عالی میده داخل گیم :((
همه مدای استک هم تست زدم چه gvisior چه سیستم چه mixed
سیپیو هم تا کانکت میزنم 50 درصد رو درگیر میکنه عجیب نیست ؟

**Comment by ircfspace** [comment]
سلام
در رابطه با موضوع صدا، احتمالا محدودیتی هست که برای WarpInWarp اعمال کردن؛ با این وجود با DNSهای مختلف تست بگیرید
در رابطه با مصرف CPU هم سعی میکنیم توی آپدیتهای بعدی بهبود بدیم

**Comment by ahmadlancer** [comment]
نه فقط با warp in warp نیست با حالت وارپ خالی هم تست زدم سایفون هم تست زدم
روی مد tun این مشکل هست این کارت شبکش انگار مشکلشه

**Comment by ircfspace** [comment]
توی تنظیمات گزینه LAN روشنه یا خاموش؟

**Comment by ahmadlancer** [comment]
لن غیر فعاله کلا
روی حالت tun
وقتی روی پروکسی هست میشه خاموشو روشن کرد

**Comment by ircfspace** [comment]
منتظر نسخه جدید بمونین و شرایط رو یه‌دور روی اون نسخه هم تست بگیرین

**Comment by ahmadlancer** [comment]
با برنامه warp این مشکل نیست ولی خب به یه سرورهایی وصل میشه ک پینگ خیلی
بالا میره جدیدا با اینترنت مخابرات
بهشون ایمیل هم زدم برای تغییر colocation center
اما گفتن این مربوط به روتینگ ای اس پی هست با هر نتی اتومات تغییر میکنه
راهی هست بشه دستی دور زد محدودیت نسخه اصلی وارپ رو
چون کارت شبکه اوبلیون بر اساس sing box توسعه داده شده و مشکل صدای بازی هم
بخاطر همین هست 🥲

**Comment by ahmadlancer** [comment]
دمتگرم مشکل استفاده از سیپیو و صدا داخل بازی با نسخه جدید حل شد فقط من تیک تحلیل بسته هارو برداشتم مشکا صدای تو بازی حل شد سیپیو هم دیگه درگیر نمیشه با  اتصال وی پی ان 
ماچ به کللت
