### ISSUE TITLE
ست کردن پورت 8086 روی کارت شبکه دلخواه

### ISSUE THREAD

**Issue by behzadchtp** [bepass-org/oblivion-desktop#684]
### Feature description | توضیحات ویژگی

برنامه oblivion تنظیم اتصال از LAN رو روی کارت شبکه یا همون اینترفیسی که خودش بخواهد خودکار ست میکند.
به عنوان مثال روی سیستم خودم سه تا کارت شبکه دارم. اینترفیس وایرلس و دوتا هم اترنت. ولی میخوام که پورت 8086 روی اینترفیس اترنت ست بشه نه روی اینترفیس وایرلس. ..چون وقتی دستور netstat رو اجرا میکنم میبینم که روی اینترفیس وایرلس داره پورت 8086 رو lesten میکنه.
اگر امکانش هست در آپدیت های بعدی امکان کاستوم کردم اتصال از LAN با اینترفیسی که کاربر مد نظرشه هم اضافه شود.

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از گزارش شما،
این مورد رو در آپدیت‌های آینده برطرف میکنیم
