### ISSUE TITLE
عدم اتصال به توییتر و ....

### ISSUE THREAD

**Issue by hosseinkazemi7400** [bepass-org/oblivion-desktop#69]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام   خدمت سازندگان محترم برنامه ، در نسخه جدید برنامه متصل می شود  ولی فقط  یوتیوب را باز می کند . تلگرام و توییتر  و سایت های دیگر را باز نمی کند پروکسی سیستم را هم دستی تنظیم کردم  socks=127.0.0.1  ممنون از شما

### Minimal Reproducible Example (MRE)

time=2024-05-08T11:17:57.167+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T11:17:57.170+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T11:17:59.898+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-08T11:17:59.898+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T11:17:59.900+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T11:18:01.128+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-08T11:18:04.140+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.96.111:2371 RTT:180.5895ms CreatedAt:2024-05-08 11:18:04.0392719 +0330 +0330 m=+6.881199501} {AddrPort:162.159.195.71:1843 RTT:184.9182ms CreatedAt:2024-05-08 11:18:03.2682221 +0330 +0330 m=+6.110149701}]"

time=2024-05-08T11:18:04.141+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.96.111:2371 162.159.195.71:1843]"
time=2024-05-08T11:18:04.141+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-08T11:18:06.797+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-08T11:18:06.806+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-08T11:18:09.553+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.163 error="read udp 192.168.1.103:52152->162.159.193.163:2408: i/o timeout"

time=2024-05-08T11:19:19.336+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=t.kite.com:443

time=2024-05-08T11:19:49.693+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=login.live.com:443

time=2024-05-08T11:20:04.955+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=clientservices.googleapis.com:443

time=2024-05-08T11:20:30.696+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=safebrowsing.googleapis.com:443

time=2024-05-08T11:21:03.798+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=update.googleapis.com:443

time=2024-05-08T11:23:27.064+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=rc.kite.com:443

time=2024-05-08T11:23:28.873+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=safebrowsing.google.com:443

time=2024-05-08T11:26:39.416+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=clients3.google.com:80

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

1. از مرورگر کروم استفاده کنید
2. چک کنید اکستنشن مربوط به پروکسی روی مرورگرتون نصب نباشه

**Comment by hosseinkazemi7400** [comment]
سلام  از مرورگر کروم استفاده می کنم  اکستنشن روی مرورگر نصب نیست . از بین سایت ها فقط یوتویب متصل میشه

**Comment by ircfspace** [comment]
از تنظیمات برنامه یکبار بر روی بازگردانی تغییرات بزنین، ببینین مشکل حل میشه؟

**Comment by hosseinkazemi7400** [comment]
سلام   مشکل از مرورگر کروم هست . باقی مرورگر ها سایت ها را باز می کند .  ممنون از برنامه بسیار خوبتان

**Comment by ircfspace** [comment]
اگر فقط کروم هست، یه اکستنشن VPN/PROXY روش فعاله که باید حذفش کنین

**Comment by hosseinkazemi7400** [comment]
مهندس جان همین چند تا اکستنشن روی کروم نصب هست 
![489](https://github.com/bepass-org/oblivion-desktop/assets/110343254/3d8b0ff5-eace-4a4f-909e-17cb6b3e80b9)

**Comment by johhny1898** [comment]
با سلام
مشکل از دی انس داخلی سایفونه که باز نمیکنه یوتیوب و توییتر ولی تلگرامو باز میکنه
چند پیشنهاد 
برای باز کردن این سایتها بهتره سایفون رو با وارپ و وارپ پلاس یا وارپ این وارپ ترکیب کنین تا این مشکل رفع بشه (یعنی بشه تو برنامه وارپ و سایفونو با هم انتخاب کرد که سایفون از طریق وارپ تانل بشه)مثل این https://t.me/v2raycollectorgroup/1/272963

اضافه کردن split tunnel
اضافه کردن پرکسی چین به برنامه

اضافه کردن کانفیگهای دلخواه کاربر به برنامه مثل warp or Warp in warp
موفق باشید

**Comment by johhny1898** [comment]
با سلام

مشکل باز نکردن توییتر و یوتیوب بر میگرده به عدم اتصال  به dns در socks
جند پیشنهاد
اضافه کردن split tunnel
اضافه کردن پراکسی چین
اضافه کردن کانفیگهای دلخواه کاربر به برنامه(وارپ/وارپ پلاس/وارپ این وارپ)
ترکیب سایفون با وارپ 
با تشکر
