### ISSUE TITLE
شناسایی فایل های exe به عنوان ویروس

### ISSUE THREAD

**Issue by mardanafa** [bepass-org/oblivion-desktop#690]
### Attention | توجه

- [ ] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام
من نسخه ۶۴ بیت پورتابل رو دانلود و unzip کردم
وقتی میخواستم برنامه رو اجرا کنم آنتی ویروس سیمنتک برنامه و فایل های exe اصلی رو به عنوان ویروس شناسایی کرد و حذف شدن

### Relevant log output | لاگ برنامه

```shell
-
```

**Comment by ircfspace** [comment]
سلام
قبلا در این رابطه توضیحاتی ارائه شده
[اینجارو مطالعه کنید](https://github.com/bepass-org/oblivion-desktop/wiki/False-Antivirus-Warning-%7C-%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87-%D8%A2%D9%86%D8%AA%DB%8C-%D9%88%DB%8C%D8%B1%D9%88%D8%B3)
