### ISSUE TITLE
MacOS version doesn't exists

### ISSUE THREAD

**Issue by Ariiima** [bepass-org/oblivion-desktop#7]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

Is the download link broken or it's not developed yet?

### Minimal Reproducible Example (MRE)

download link doesn't work

### Version

v0

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
the builds for Mac & Linux will be added in the next few days

**Comment by Majidzam1101** [comment]
> the builds for Mac & Linux will be added in the next few days

ببخشید کانال زیر بر علیه برنامه شما مطلب نوشته که برنامه شما ناامن است ایا حقیقت داره 
https://t.me/PewezaVPN
