### ISSUE TITLE
هویت سنجی در کلود فلر با خطا مواجه شد

### ISSUE THREAD

**Issue by Jahboulan** [bepass-org/oblivion-desktop#70]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و تشکر از همه بابت زحمت هایی که میکشن 
تا آزاد باشیم و زیر دست ظلم ملا نریم
وقتی تلاش میکنم که وصل بشم توی همون مرحله اول پیام میاد که 
هویت سنجی در کلود فلر با خطا مواجه شد
و فرقی هم نمیکنه توی حالت وارپ یا گول یا سایفون باشه 
کاری نمیکنه و متصل نمیشه

### Minimal Reproducible Example (MRE)

you can find the massege on the main page of the vpn

### Version

v0.2.52. beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

چندمرتبه روی اتصال بزنین ببینین مشکل برطرف میشه؟

**Comment by Jahboulan** [comment]
نه چندین بار هم امتحان کردم متصل نمیشه متاسفانه

**Comment by ircfspace** [comment]
روی اتصال بزنین؛ لاگ برنامه رو برداشته و اینجا ارسال کنین

**Comment by Jahboulan** [comment]
time=2024-05-08T12:39:56.145+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T12:39:56.149+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T12:39:57.663+03:30 level=INFO msg="updating account license key" subsystem=warp/account

time=2024-05-08T12:39:58.838+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-08T12:39:58.838+03:30 level=ERROR msg="activation error, status 400 {\"result\":null,\"success\":false,\"errors\":[{\"code\":1056,\"message\":\"Too many connected devices.\"}],\"messages\":[]}\n"

**Comment by Jahboulan** [comment]
بله یه لایسنس از بات وارپ ست کردم

**Comment by ircfspace** [comment]
توضیحاتی که در نسخه جدید نوشته شد رو مطالعه نکردین؟

**- در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه**

برای استفاده از برنامه فعلن لایسنس رو غیرفعال کنین

**Comment by ircfspace** [comment]
خطای Too many connected devices یعنی سقف استفاده از لایسنس پر شده

ضمن اینکه :
- در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه

**Comment by Jahboulan** [comment]
ممنونم از توضیحات شما 
یعنی من اگر لایسنس رو پاک کنم مشکل باید حل بشه
