### ISSUE TITLE
نسخه جدید افتضاحه  اصلا وصل نمیشه 

### ISSUE THREAD

**Issue by Majidzam1101** [bepass-org/oblivion-desktop#72]
### Feature description

سلام دوست عزیز نسخه جدید 0.2.52 واقعا گند زدید به برنامه حتی حالت گول وصل نمیشه نه سایفون افتضاحه خطای اعبترسنجی میزنه روی حالت گول روی دریافت اطلاعات می ماند گند زدید به برنامه نسخه 0.252 افتضاحه امروز منتشر کرد مشکل تونل کردن کل سیستم همچنان دارد نه واتساپ باز می کنه نه دانلود منینجر سایفون وصل نمیشه گول هم وصل نمیشه دریافت اطلاعات می ماند ! واقعا برای سازنده برنامه متاسفم
![Screenshot (20)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/229defe6-13e8-4a3d-94f1-3ecebe678e44)
![Screenshot (17)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/39c001c9-9bde-4bd7-8a67-0f4f11e5fc0f)

![Screenshot (15)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/9bf70072-2b99-4b3e-9497-184087206665)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از ابراز تاسف شما،
**میتونید از سایر برنامه‌های VPN استفاده کنید**

**Comment by Majidzam1101** [comment]
> سلام
> 
> ضمن تشکر از ابراز تاسف شما، **میتونید از سایر برنامه‌های VPN استفاده کنید**
لاینسس استفاده کردیم ولی خطای هویت سنجی میزنه در نسخه قبلی این مشکل نداشت

![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/24114a64-65c4-42af-ad91-47c84b82fffe)

![Screenshot (17)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/3655a3bc-0546-4822-a3a4-0e3263c64243)
