### ISSUE TITLE
error in connection 

### ISSUE THREAD

**Issue by Jahboulan** [bepass-org/oblivion-desktop#74]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

بعد از حذف لایسنس همچنان هم کل سیستم من تونل نمیشه و یوتیوب رو هم نمیتونم باز کنم 
لاگ رو هم در بخش نمونه میزارم

### Minimal Reproducible Example (MRE)

time=2024-05-08T13:04:36.434+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T13:04:36.437+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T13:04:38.091+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-08T13:04:38.091+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/secondary error="CreateFile stuff\\secondary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T13:04:38.094+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T13:04:40.105+03:30 level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account

time=2024-05-08T13:04:42.123+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d1:0:36ca:3c64:ffbb:90c5 error="dial udp [2606:4700:d1:0:36ca:3c64:ffbb:90c5]:2506: connect: A socket operation was attempted to an unreachable network."

time=2024-05-08T13:04:42.807+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:884:a184:4629:9dc9 error="dial udp [2606:4700:d0:0:884:a184:4629:9dc9]:3581: connect: A socket operation was attempted to an unreachable network."

time=2024-05-08T13:04:43.108+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:162.159.192.235:946 RTT:203.3856ms CreatedAt:2024-05-08 13:04:42.8065858 +0330 +0330 m=+6.385608001} {AddrPort:188.114.96.141:3854 RTT:210.406ms CreatedAt:2024-05-08 13:04:42.1215067 +0330 +0330 m=+5.700528901}]"
time=2024-05-08T13:04:43.108+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.192.235:946 188.114.96.141:3854]"
time=2024-05-08T13:04:43.108+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-08T13:04:45.720+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-05-08T13:04:45.726+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=cloudflare.com:443

time=2024-05-08T13:05:11.071+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=iup.360safe.com:80

time=2024-05-08T13:05:14.131+03:30 level=INFO msg="handling connection" gool=inner subsystem=vtun protocol=tcp destination=s.cloud.360safe.com:80

### Version

v0.2.52. beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
دکمه اتصال روشن میشه یا کلن اتصال صورت نمیگیره؟

**Comment by Jahboulan** [comment]
اتصال صورت میگیره و پرچم المان هم در حالت گول نمایش داده میشه ولی هیچ اکسسی وجود نداره و ارور پر.کسی روی بروزر میاد

**Comment by ircfspace** [comment]
1. توی تنظیمات برنامه گزینه پیکربندی شبکه روشنه یا خاموش؟

2. روی بروزر اکستنشن VPN یا امثالهم نصب نیست؟

**Comment by Jahboulan** [comment]
تیک تنظیمات پیکر بندی شبکه روشنه 
و بعد از پاک کردن اکستنشن وی پی ان بروزر مشکل حل شد 
سپاس بیکران از شما
به امید نابودی ظلم

**Comment by Jahboulan** [comment]
اما همچنان هم فقط بروزر به تلگرام دسترسی داره و خود اپلیکیشن دسکتاب تلگرام روی لپ تاب باز نمیشه

**Comment by Paaayman** [comment]
> اما همچنان هم فقط بروزر به تلگرام دسترسی داره و خود اپلیکیشن دسکتاب تلگرام روی لپ تاب باز نمیشه

برای این کار یه ساکس 5 ایجاد کد با پورت 8086 اون هم وصل میشه

**Comment by Jahboulan** [comment]
انجام دادم ولی همش در حال کانته و متصل نمیشه متاسفانه

**Comment by ircfspace** [comment]
اگر اشتباه نکنم در مورد اکستنشن مرورگر ازتون توی ایشوی قبلی پرسیده بودم، که گفتین نصب نیست

در رابطه با تلگرام هم روی گزینه Use System Proxy تنظیمش کنین

**Comment by Jahboulan** [comment]
ممنونم از همراهی شما
احتمالا متن رو درست متوجه نشدم و اگر جواب درستی ندادم پوزش میخوام

**Comment by ircfspace** [comment]
> ممنونم از همراهی شما احتمالا متن رو درست متوجه نشدم و اگر جواب درستی ندادم پوزش میخوام

مشکل برطرف شد؟

**Comment by Jahboulan** [comment]
اگر جواب درستی ندادم پس متوجه متن نشدم پوزش مخوایم و از راهنمایی و همراهی شما نهایت تشکر رو دارم

**Comment by ircfspace** [comment]
نسخه جدید منتشر شد :
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.5-beta

اگر مشکلی در رابطه با اتصال هست، روی این نسخه بررسی کنین

**Comment by iranintrnetisfucked** [comment]
سلام من تو linux xfce نصبش کردم و هیچ یک از تنظیماتش رو دستکاری نکردم ولی به موقع تلاش برای اتصال ارور میده اتصال به کلود فلر به طور غیر منتظره قطع شد تو ویندوز هم این ارور رو میداد ولی با غیر فعال کردن دیفندر ویندوز این مشکل حل میشد ولی اینجا نمیدونم چجوری باید این کار رو بکنم لطفا راهنمایی کنین

**Comment by ircfspace** [comment]
برای این مساله باید یک ایشو جدید زده و لاگ برنامه رو ارسال کنین
