### ISSUE TITLE
هویت سنجی در کلودفلر با خطا مواجه شد

### ISSUE THREAD

**Issue by amirhosseinamini145** [bepass-org/oblivion-desktop#75]
### Feature description

سلام و تشکر از نرم افزار بسیار خوبتون، در هنگام استفاده از اینترنت مخابرات با ارور هویت سنجی در کلود فلر با خطا مواجه شد روبرو میشم و دیگه وصل نمیشه ولی در دو سه نوع اینترنت مثل ماهان نت و تی دی ال تی ای ایرانسل دیگه این مشکل نیست و وصل میشه لایسنس وارپ بصورت فری هست چند بار امتحان میکنم همون ارور هست با سه حالت وارپ و وارپ این وارپ و سایفون همین مشکل هست

**Comment by amirhosseinamini145** [comment]
اخرین ورژن 0.2.52 رو نصب دارم

**Comment by amirhosseinamini145** [comment]
time=2024-05-08T13:54:29.566+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T13:54:29.567+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T13:54:34.573+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-08T13:54:34.573+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": dial tcp 141.101.113.82:443: i/o timeout"

**Comment by ircfspace** [comment]
سلام

از لایسنس استفاده میکنین؟

**Comment by ehsanna11111** [comment]
برای من هم در حالت وارپ روی نت مخابرات بدون لایسنس برنامه وصل میشه ولی در دوحالت دیگه گول و سایفون خطای هویت سنجی کلودفلر میده
time=2024-05-08T16:37:34.281+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-05-08T16:37:34.282+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path=./stuff/primary error="CreateFile stuff\\primary\\wgcf-identity.json: The system cannot find the path specified."

time=2024-05-08T16:37:34.283+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-08T16:37:49.505+03:30 level=ERROR msg="couldn't load primary warp identity" subsystem=warp/account
time=2024-05-08T16:37:49.505+03:30 level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a3596/reg\": EOF"

**Comment by ehsanna11111** [comment]
اینبار روی حالت سایفون کشور رو از آلمان به چک و امریکا تغییر دادم و برنامه کانکت شد ولی سایتهای فیلتر شده مثل یوتیوب و توییتر رو باز نمیکنه ولی صفحه گوگل رو باز کرد

**Comment by ircfspace** [comment]
یه دور تنظیمات برنامه رو ریست کرده و مجدد تست بگیرین

**Comment by Majidzam1101** [comment]
مشکل تونل کردن کل سیستم ویندوز توی این نسخه پابرجاست

**Comment by ehsanna11111** [comment]
> یه دور تنظیمات برنامه رو ریست کرده و مجدد تست بگیرین

برنامه رو ریست کردم روی حالت گول مشکل حل شد و کانکت میشه و فیلترینگ رو هم رد میکنه ولی همچنان رو حالت سایفون اگه کشور المان باشه خطای هویت سنجی میده و کانکت نمیشه و روی کشور دیگه ایی مثل هلند کانکت میشه ، ای پی رو هم عوض میکنه ولی سایت های فیلتر شده رو باز نمیکنه... من از نسخه پورتابل استفاده میکنم

**Comment by amirhosseinamini145** [comment]
لایسنسم فری هست توی توضیحات اول خدمتتون فرستادم روی المان و امریکا در حالت سایفون هم وصل نشد روی کشورهای دیگه هم وصل نشد ریست هم از داخل نرم افزار کردم ولی باز هم وقل نشد

**Comment by Majidzam1101** [comment]
> یه دور تنظیمات برنامه رو ریست کرده و مجدد تست بگیرین
سلام سازدنده محترم لطفا جواب بده ایا لاینسس از ربات تلگرام  می گیریم لازمه یا خیر این خطای هویت سنجی جواب ندادی علتش چیه ؟

![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/083ce002-30b9-430d-9158-6ab8f481747b)

**Comment by Majidzam1101** [comment]
> سلام
> 
> از لایسنس استفاده میکنین؟

لاینسس استفاده کردیم ولی خطای هویت سنجی میزنه در  نسخه قبلی این مشکل نداشت

**Comment by ircfspace** [comment]
> لاینسس استفاده کردیم ولی خطای هویت سنجی میزنه در نسخه قبلی این مشکل نداشت

به جای اینکه با اسپم‌کردن برای یک موضوع ده‌ها ایشوی تکراری ایجاد کنین، کافی بود توضیحات نسخه جدید رو مطالعه کنین :

**- در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه**

**Comment by ehsanna11111** [comment]
> کسی تغییر پورت یا تغییر تنظیمات دیگه ای انجام نداده که تست بشه؟

من پورت رو هم تغییر دادم ولی مشکل حالت سایفون حل نشد و با وجودی که آی پی تغییر میکنه ولی فقط سایتهای بدون فیلتر باز میشه

**Comment by amirhosseinamini145** [comment]
تشکر از ادمین عزیز من کاملا مطالعه کردم و تمام موضوعات رو اول بررسی کردم حتی خط اینترنت رو هم جابجا کردم لایسنس هم وارد نکردم با جابجایی خط اینترنت مخابرات با چند ای اس پی دیگه مشکل حل میشه فقط مخابرات ای ارور رو داره توضیحات دیگه هم چون تکراری میشه تو کامنتها خدمتتون فرستادم

**Comment by ircfspace** [comment]
> تشکر از ادمین عزیز من کاملا مطالعه کردم و تمام موضوعات رو اول بررسی کردم حتی خط اینترنت رو هم جابجا کردم لایسنس هم وارد نکردم با جابجایی خط اینترنت مخابرات با چند ای اس پی دیگه مشکل حل میشه فقط مخابرات ای ارور رو داره توضیحات دیگه هم چون تکراری میشه تو کامنتها خدمتتون فرستادم

خودم روی مخابرات درحال استفاده هستم و مشکل از سرویس‌دهنده اینترنت نیست

پیشنهاد میکنم با دقت اکستنشن‌های کروم رو بررسی کنین؛ احتمالن یه اکستنشن Proxy روش فعاله که باید حذف کنین

**Comment by Majidzam1101** [comment]
> تشکر از ادمین عزیز من کاملا مطالعه کردم و تمام موضوعات رو اول بررسی کردم حتی خط اینترنت رو هم جابجا کردم لایسنس هم وارد نکردم با جابجایی خط اینترنت مخابرات با چند ای اس پی دیگه مشکل حل میشه فقط مخابرات ای ارور رو داره توضیحات دیگه هم چون تکراری میشه تو کامنتها خدمتتون فرستادم

مشکل تونل کردن کل سیستم نسخه جدید هم  پابرجاست واتساپ باز نمی کنه ماکروسافت استور 

![Screenshot (24)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/2dc38791-93d9-4373-9152-82b8322a238e)

**Comment by amirhosseinamini145** [comment]
ممنون از دانش فنی بسیار بالا و خوب ادمین محترم که راهنمایی کردن و‌درست هم بود تمام مشکلات از اکستنشهای داخل کروم یا ستینگ مودم یا میکروتیک یا خود دیوایس که ست شده هست و خود نرم افزار با هیچ مشکلی در رابطه با اینرنت مخابرات مواجه نیست من اکثرا کامنتها رو که خوندم بعد بررسی کردم دیدم اگه کانفیگها همه درست و روتین باشه اصلا مشکلی پیش نمیاد خواهش میکنم دوستانی که اینموارد رو گفتن حتما یک بررسی بکنن یکجا یا دی ان اس یا وی پی ان یا اکستنشن یا هر موردی دیگه ای رو که در نظرشون الان نیست دارن که بعد اگه درستش کنن دیگه نرم افزار مشکل نداره نه در بحث سایتها نه ای اس پی خاص

**Comment by Majidzam1101** [comment]
> ممنون از دانش فنی بسیار بالا و خوب ادمین محترم که راهنمایی کردن و‌درست هم بود تمام مشکلات از اکستنشهای داخل کروم یا ستینگ مودم یا میکروتیک یا خود دیوایس که ست شده هست و خود نرم افزار با هیچ مشکلی در رابطه با اینرنت مخابرات مواجه نیست من اکثرا کامنتها رو که خوندم بعد بررسی کردم دیدم اگه کانفیگها همه درست و روتین باشه اصلا مشکلی پیش نمیاد خواهش میکنم دوستانی که اینموارد رو گفتن حتما یک بررسی بکنن یکجا یا دی ان اس یا وی پی ان یا اکستنشن یا هر موردی دیگه ای رو که در نظرشون الان نیست دارن که بعد اگه درستش کنن دیگه نرم افزار مشکل نداره نه در بحث سایتها نه ای اس پی خاص

سلام شما خطای  ارور زیر  هویت اعتبارسنجی داشتید با وارد کردن لاینسس ؟
![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/84ba33ce-07be-42d2-8311-a1b16e7e422d)

**Comment by amirhosseinamini145** [comment]
روی ورژن قبلی بله داشتم که بعد متوجه تنظیکات خاص روی میکروتیکم شدم که با تغییرات درست شد

**Comment by FARHADAMIRIR1382** [comment]
سلام خسته نباشید نسخه جدید رو ولی با مشکل خطای اهراز هویت در کلود فلر مواجه شدم تمام کار هایی که دیگران کامنت کرده بودن 
 هم خوندم انجام دادم اما درست نشدش و اینکه من اصلا لایسنسی نخواستم بزنم توی حالت عادی این ارور میده میشه لطفا کمک کنین و راهنمایی کنید

**Comment by ircfspace** [comment]
> سلام خسته نباشید نسخه جدید رو ولی با مشکل خطای اهراز هویت در کلود فلر مواجه شدم تمام کار هایی که دیگران کامنت کرده بودن هم خوندم انجام دادم اما درست نشدش و اینکه من اصلا لایسنسی نخواستم بزنم توی حالت عادی این ارور میده میشه لطفا کمک کنین و راهنمایی کنید

یکبار تنظیمات برنامه رو ریست کنین و بعد با اندپوینت‌های سفارشی تست بگیرین
اگر مشکل حل نشد لاگ برنامه رو ارسال کنین

**Comment by FARHADAMIRIR1382** [comment]
سلام وقت بخیر درست نشد بازم
[2025-05-06 00:40:58.765] [info]  Deleted past logs for new connection.
[2025-05-06 00:41:00.164] [info]
 ------------------------MetaData------------------------
[2025-05-06 00:41:00.164] [info]  running on: Microsoft Windows 10 Pro
(10.0.19045) ia32 19045
[2025-05-06 00:41:00.165] [info]  at od: v2.78.1
[2025-05-06 00:41:00.165] [info]  at wp: v1.2.5
[2025-05-06 00:41:00.165] [info]  at hp: v1.2.2
[2025-05-06 00:41:00.165] [info]  ls assets/bin:
LICENSE,oblivion-helper,proxy-reset.exe,README.md,vbs,warp-plus.exe,zag-netStats.exe
[2025-05-06 00:41:00.165] [info]  method: warp
[2025-05-06 00:41:00.165] [info]  proxyMode: system
[2025-05-06 00:41:00.165] [info]  routingRules: Default
[2025-05-06 00:41:00.166] [info]  endpoint: custom
[2025-05-06 00:41:00.166] [info]  ipType: v6
[2025-05-06 00:41:00.166] [info]  tunAddrType: v64
[2025-05-06 00:41:00.166] [info]  dataUsage: false
[2025-05-06 00:41:00.166] [info]  asn: UNK
[2025-05-06 00:41:00.166] [info]  reserved: true
[2025-05-06 00:41:00.166] [info]  geo Ip: none, Site: none, Block: false,
NSFW: false
[2025-05-06 00:41:00.166] [info]  testUrl:
https://connectivity.cloudflareclient.com/cdn-cgi/trace
[2025-05-06 00:41:00.167] [info]  dns: 1.1.1.1
[2025-05-06 00:41:00.167] [info]  exe:
C:\Users\<USERNAME>\AppData\Local\Programs\oblivion-desktop\oblivion-desktop.exe
[2025-05-06 00:41:00.167] [info]  userData:
C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2025-05-06 00:41:00.167] [info]  logs:
C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2025-05-06 00:41:00.167] [info]
 ------------------------MetaData------------------------
[2025-05-06 00:41:00.168] [info]  trying to set system proxy...
[2025-05-06 00:41:00.279] [info]  system proxy has been set.
[2025-05-06 00:41:00.281] [info]  Starting WarpPlus process...
[2025-05-06 00:41:00.281] [info]
 C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind
0.0.0.0:8086 --endpoint [2606:4700:d0::64e0:11a6:edec:c744]:987
[2025-05-06 00:41:00.410] [info]  trying to disable system proxy...
[2025-05-06 00:41:00.504] [info]  system proxy has been disabled on your
system.
[2025-05-06 00:41:00.507] [info]  WarpPlus process exited.
time=2025-05-06T00:41:00.315+03:30 level=INFO msg="using warp endpoints"
endpoints="[[2606:4700:d0::64e0:11a6:edec:c744]:987
[2606:4700:d0::64e0:11a6:edec:c744]:987]"
time=2025-05-06T00:41:00.316+03:30 level=INFO msg="running in normal warp
mode"
time=2025-05-06T00:41:00.316+03:30 level=INFO msg="failed to load identity"
subsystem=warp/account
path=C:\Users\<USERNAME>\AppData\Local\cache/warp-plus/primary
error="CreateFile
C:\Users\<USERNAME>\AppData\Local\cache\warp-plus\primary\wgcf-identity.json:
The system cannot find the file specified."
time=2025-05-06T00:41:00.316+03:30 level=INFO msg="creating new identity"
subsystem=warp/account
time=2025-05-06T00:41:00.391+03:30 level=ERROR msg="couldn't load primary
warp identity"
time=2025-05-06T00:41:00.391+03:30 level=ERROR msg="Post \"
https://api.cloudflareclient.com/v0a4005/reg\": uTlsConn.Handshake() error:
read tcp 192.168.1.10:52771->141.101.113.114:443: wsarecv: An existing
connection was forcibly closed by the remote host."

**Comment by ircfspace** [comment]
سلام
مشاهده کنین: 

https://github.com/bepass-org/oblivion-desktop/wiki/Fixing-proxy-connection-issues-on-certain-networks
