### ISSUE TITLE
Windows 7 and 8 Or Entry Point Not Found

### ISSUE THREAD

**Issue by ipp2610** [bepass-org/oblivion-desktop#76]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

عدم اجرای برنامه بر روی پلتفرم های ویندوز 7 و 8.1 
پس از نصب یا استفاده از نسخه پرتابل با ارور زیر مواجه می شویم . (پس از به روز رسانی ++C و اصلاح فایل های sfc هم چنان با خطا مواجه می شویم.)
no Entry Point found
![Error](https://github.com/bepass-org/oblivion-desktop/assets/50997010/c2bf5a49-38a5-4ff8-b6c4-4063e052039c)

### Minimal Reproducible Example (MRE)

No Entry Point found

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

برنامه با Electron نوشته شده و اونم از ویندوزهای ۷ و ۸ ساپورت نمیکنه؛ مثل خود مایکروسافت.
اگر به نسخه استیبل برسیم شاید یه فورک مجزا از برنامه ساختیم و با الکترون قدیمی بیلد گرفتیم.

**Comment by Sepidar2023** [comment]
منم با ویندوز 8.1 همین ارور برام میاد

**Comment by akh791** [comment]
عدم احراز هویت در کلودفلر نسخه 0.4.5 در ویندوز 10

**Comment by kiomarzsss** [comment]
there will be a release(fork probably) for older version of windows when oblivion desktop gets to stable version(v1).

**Comment by mrjaycodes** [comment]
باسلام، این نسخه من حتی ویندوز 7 رو هم ساپروت میکنه، فقط کافیه که شما یک چند تا کار ساده رو انجام بدید تا این ورژن هم براتون کار کنه.

**Comment by mrjaycodes** [comment]
نسخه آقای RxRLl.dll رو از گیت هاب من دانلود کنید!

**Comment by ipp2610** [comment]
> باسلام، این نسخه من حتی ویندوز 7 رو هم ساپروت میکنه، فقط کافیه که شما یک چند تا کار ساده رو انجام بدید تا این ورژن هم براتون کار کنه.

سلام. ممنونم بدون مشکل اجراء شد .

**Comment by amiralishoja** [comment]
سلام من هم همین ارور رو دریافت میکنم وحتی نسخه ای که دوست عزیزمون برای ویندوز 7 قرار دادند کار نمیکنه نصب میشه ولی به سرور کانکت نمیشه ممنون میشم هر چه سریع تر راه حلی برای این موضوع پیدا کنید

**Comment by 09306677806** [comment]
bc1qgleh9jhkv2yr6upmzmjmuxefjdpepynw0sr858

**Comment by mrjaycodes** [comment]
**سلام، شما باید برای اجرا برنامه فایلی به نام vcruntime.dll و vcruntime_1.dll رو دانلود کنید و در پوشه های SysWOW64 و System32 بریزید. همچنین برای نسخه من باید فایل درایور که مخصوص ویندوز 10 بیلد شده رو ویندوز 7 patch کنید، بدین صورت که این برنامه رو دانلود میکنید و طبق آموزشی که در گیت هاب این بنده خدا هست رو پیش میرید تا به نتیجه برسید.
https://github.com/vxiiduu/VxKex
(نکته بسیار مهم: این برنامه مال ما دو نفر نیست و کاملا جداست، متاسفاته این برنامه تو آنتی ویروس، تروجان شناسایی میشه و شما باید موقتا انتی ویروس رو غیر فعال کنید و نکته دوم اینکه این patch و این روش روی نسخه ما کار میکنه و روی نسخه دیگه oblivion اطلاعاتی داده نمیشود)
خوشحال میشیم اگر بعضی ها این پاسخ رو پاک نکنند😡**

> سلام من هم همین ارور رو دریافت میکنم وحتی نسخه ای که دوست عزیزمون برای ویندوز 7 قرار دادند کار نمیکنه نصب میشه ولی به سرور کانکت نمیشه ممنون میشم هر چه سریع تر راه حلی برای این موضوع پیدا کنید

**### همچنین به تمامی کسانی که ویندوز 7 استفاده میکنن، لینک این پیام رو ارسال کنید، یا حتی درصورت پاک شدن، اسکرین شات این کامنت رو داشته باشید**.

**Comment by mrjaycodes** [comment]
> ### Search first
> * [ ]  I searched and no similar issues were found
> 
> ### What Happened?
> عدم اجرای برنامه بر روی پلتفرم های ویندوز 7 و 8.1 پس از نصب یا استفاده از نسخه پرتابل با ارور زیر مواجه می شویم . (پس از به روز رسانی ++C و اصلاح فایل های sfc هم چنان با خطا مواجه می شویم.) no Entry Point found ![Error](https://private-user-images.githubusercontent.com/50997010/328857764-c2bf5a49-38a5-4ff8-b6c4-4063e052039c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzE0NTgsIm5iZiI6MTcxNjczMTE1OCwicGF0aCI6Ii81MDk5NzAxMC8zMjg4NTc3NjQtYzJiZjVhNDktMzhhNS00ZmY4LWI2YzQtNDA2M2UwNTIwMzljLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNjQyOWQyOGEwNTBhMTQ2YTc0MjE4Njk4MmQ5YjUyY2RlMDI4M2ExNDljYzgwODM3NmNmYWIyNzMyYzQ1NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i1Yc9lR33c73NBGcOAyAVHZddYPmlKvf_5dahMcd5bE)
> 
> ### Minimal Reproducible Example (MRE)
> No Entry Point found
> 
> ### Expected Behavior
> _No response_
> 
> ### Version
> 0.2.52-beta
> 
> ### Platform/OS
> Windows
> 
> ### Additional Context
> _No response_
> 
> ### Application Config Options
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [x]  I'm willing to submit a PR (Thank you!)

مطلبی که گذاشتم رو مطالعه بفرمایید👆

**Comment by ircfspace** [comment]
طبق بررسی‌هایی که داشتیم امکان اجرای Warp-Plus به‌طور قطع بر روی Windows7 وجود نداره؛ بنابراین پیگیری از سمت ما هم بی‌نتیجه‌س. البته در رابطه با ویندوز 8 بررسی انجام میدیم و درصورتی‌که هسته ازش پشتیبانی بکنه، پشتیبانی میکنیمش.
