### ISSUE TITLE
TUN 

### ISSUE THREAD

**Issue by hamsjj** [bepass-org/oblivion-desktop#78]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

ویندوز 11 استفاده میکنم خیلی خوبه کانکت میشه ولی ویندوز رو کامل از پروکسی رد نمیکنه کانکت میشم گوگل کار میکنه ولی مثلا spotify ویا گیم ها مثل pubg از اینترنت مستقیم استفاده مینکه نه از VPN از تو تسک منیجر نگاه کردم میتونین خودتونم تست کنین گفتم بگم شاید کمکی بشه و بتونین درستش کنین خیلی ممنون.
![Screenshot 2024-05-08 194112](https://github.com/bepass-org/oblivion-desktop/assets/169260575/1882dd04-e29d-43b0-a6a3-ac65bfe13ee4)

### Minimal Reproducible Example (MRE)

![Screenshot 2024-05-08 194112](https://github.com/bepass-org/oblivion-desktop/assets/169260575/a5eb6a9c-d0ea-4873-9f61-3ca2386a736c)

### Version

v0.2.52

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
همونطور که پیش‌تر گفته شد درحال کار روی TUN برای پروکسی‌کردن کل سیستم هستیم

این‌مورد در آپدیت‌های آینده در دسترس قرار میگیره

**Comment by Majidzam1101** [comment]
> سلام
> 
> ضمن تشکر از بازخورد شما، همونطور که پیش‌تر گفته شد درحال کار روی TUN برای پروکسی‌کردن کل سیستم هستیم
> 
> این‌مورد در آپدیت‌های آینده در دسترس قرار میگیره


سلام  خطای زیر از چیه ؟

![Screenshot (23)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/e6bb8f3b-5830-49d8-9c99-070d075fa2f4)

**Comment by Majidzam1101** [comment]
> سلام
> 
> ضمن تشکر از بازخورد شما، همونطور که پیش‌تر گفته شد درحال کار روی TUN برای پروکسی‌کردن کل سیستم هستیم
> 
> این‌مورد در آپدیت‌های آینده در دسترس قرار میگیره

سلام خواهشمندم در اپدیت بعدی tunقرار بدید حداقل ازمایشی جهت تست کردن توسط کابران

**Comment by behzadchtp** [comment]
اگه حالت tun اضافه بشه راحت میشه میکروتیک رو کانکت کرد به virtual network adapter برنامه و برای شبکه داخلی هم اینترنت oblivion رو شیر کرد.

**Comment by ircfspace** [comment]
تا آماده‌شدن TUN میتونین از این ترفند استفاده کنین :

https://shorturl.at/Dmzsz
