### ISSUE TITLE
تنظیم نکردن خودکار پروکسی

### ISSUE THREAD

**Issue by fakhamatia** [bepass-org/oblivion-desktop#8]
### Feature description

درود
لطفا پس از اتصال پروکسی، خودکار داخل سیستم عامل تنظیم نشه و براش تنظیمات بذارید.

**Comment by Jahboulan** [comment]
It seems fine and it doesn't have any problem when you want to install it but somehow it's not functional and I cannot use it to 
 enter YouTube or telegram app

**Comment by ircfspace** [comment]
> ### Feature description
> درود لطفا پس از اتصال پروکسی، خودکار داخل سیستم عامل تنظیم نشه و براش تنظیمات بذارید.

توی آپدیت بعدی Warp-Plus توسط @markpash قراره TUN اضافه‌شه. 
ما هم متعاقب اون، تنظیمات پروکسی‌رو بهبود میدیم

**Comment by ircfspace** [comment]
> It seems fine and it doesn't have any problem when you want to install it but somehow it's not functional and I cannot use it to enter YouTube or telegram app

لطفا برای موضوع غیرمرتبط با عنوان ایشو، ایشوی جدیدی ایجاد کنین
مطمئن‌باشین بی‌پاسخ نمیذاریم

**Comment by Majidzam1101** [comment]
> > ### Feature description
> > درود لطفا پس از اتصال پروکسی، خودکار داخل سیستم عامل تنظیم نشه و براش تنظیمات بذارید.
> 
> توی آپدیت بعدی Warp-Plus توسط @markpash قراره TUN اضافه‌شه. ما هم متعاقب اون، تنظیمات پروکسی‌رو بهبود میدیم

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه دومین مشکل اتصال به سایفون است هیچ سایتی باز نمی کنه


![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/acaa095b-1e32-4fa0-8227-0db55fbe36ab)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/7fbd7b57-d642-4229-b847-012a4e17ee08)
![Screenshot (7)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/ccfe79ca-6564-4f87-927f-cccc7e790fb0)

**Comment by amirrezaDev1378** [comment]
this would be awesome!
