### ISSUE TITLE
عدم اتصال گیم با برنامه شما

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/oblivion-desktop#83]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با سلام و تشکر بابت زحمت هاتون
مشکل اینه رو حالت گول که ای پیم المان بود چک کردم گیم نتونست وصل بشه! تو این مورد من گیم Tekken 8 رو تست کردم که از سرور های گوگل کلود استفاده میکنه و گوگل کلود هم مارو تحریم کرده و  این بازی لوکال ای پی هم بررسی میکنه و برای همین با dns امکان دور زدنش نیست و خواستم با برنامه شما تست کنم که نتونست وصل بشه به سرور در صورت امکان فیکس کنین تشکر
 نسخه PC / 0.2.52 

### Minimal Reproducible Example (MRE)

...........

### Version

 0.2.52 

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by javad490** [comment]
درسته، منم هم با حالت گول و هم سایفون روی ویندوز نتونستم به گیم آنلاین وصل بشم ! 
با وجود اینکه با تانل از طریق TUN و کانفیگ nekobox کل ویندوز تانل شده بود و پینگ حدود 500 بود اما به سرور بازی آنلاین وصل نمیشه! در حالی که با vpn و کانفیگهای دیگه حتی با پینگ بالاتر هم به بازی آنلاین وصل میشه
با تشکر از زحمات شما امیدوارم در ورژن بعدی این مشکل برطرف بشه

**Comment by kiomarzsss** [comment]
با درود. این مشکل جز حوزه اختیارات
oblivion desktop
نیست و شاید بهتر باشه داخل:
https://github.com/bepass-org/warp-plus
مطرح کنید
