### ISSUE TITLE
گزینه اتصال LAN کار نمیکنه!

### ISSUE THREAD

**Issue by rezvani002** [bepass-org/oblivion-desktop#85]
### Feature description

گزینه را فعال کردم برنامه را بستم دوباره باز کردم ولی کل نتروک روی پروکسی نمیره!

**Comment by ircfspace** [comment]
در این‌رابطه @HrBDev فکر کنم بتونن راهنمایی کنن

**Comment by ircfspace** [comment]
یه آپدیت در رابطه با LAN داشتیم؛ بررسی کنین:
https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.4.7-beta

**Comment by kiomarzsss** [comment]
please continue discussion about this issue here: https://github.com/bepass-org/oblivion-desktop/issues/142
