### ISSUE TITLE
پروکسی کردن (تونل کردن) کل سیستم عامل و نه فقط مرورگر

### ISSUE THREAD

**Issue by yazbod** [bepass-org/oblivion-desktop#89]
### Feature description

سلام. خیلی ممنون از زحماتتون برای این برنامه فوق العاده.
یک مشکل خیلی اصلی و یا اینکه یک ویژگی خیلی مهمی که این برنامه نداره اینه که کل اینترنت سیستم عامل رو از vpn عبور نمیده و فقط مرورگر از vpn عبور داده میشه. اگه امکانش هست در آپدیت های آینده این مشکل رو رفع کنید و طوری باشه که کل سیستم عامل از vpn استفاده کنه و نه فقط مرورگر. باز هم خیلی ممنون از توسعه دهنده های عزیز.

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
لطفا مطالعه کنین : https://github.com/bepass-org/oblivion-desktop/issues/78#issuecomment-2100538581
