### ISSUE TITLE
Minimize to system tray on close

### ISSUE THREAD

**Issue by fakhamatia** [bepass-org/oblivion-desktop#9]
### Feature description

بعد از بستن برنامه Minimize بشه نه کامل بسته

**Comment by ircfspace** [comment]
سلام

برای مینیمایز در systemTray یه گزینه در تنظیمات برنامه وجود داره
باید اونو فعال کنین

**Comment by fakhamatia** [comment]
> سلام
> 
> برای مینیمایز در systemTray یه گزینه در تنظیمات برنامه وجود داره باید اونو فعال کنین

گزینه `مخفی سازی` ؟ فرقی در عملکرد نداره انگار
منظورم اینه بعد از اتصال وقتی X رو میزنم بره بقل ساعت. در حالت عادی باید Minimize کنم و توی taskbar می مونه.

**Comment by ircfspace** [comment]
خب چرا برای فرستادن کنار ساعت مینیمایز نمی‌کنین؟‌ :‌)

**Comment by fakhamatia** [comment]
> خب چرا برای فرستادن کنار ساعت مینیمایز نمی‌کنین؟‌ :‌)

اوکی شد. من گیج بازی دراوردم.

**Comment by Majidzam1101** [comment]
> خب چرا برای فرستادن کنار ساعت مینیمایز نمی‌کنین؟‌ :‌)

سلام بزرگترین مشکل obvilion desktop اینه که کل سیستم فقط پروکسی سیستم می کنه حالت vpn تانل نداره کل سیستم کامپیوتر تونل وضد فیلتر کنه در نتیجه برخی برنامه ها سیستم ویندوز کار نمی کنند مثل واتساپ از فروشگاه ماکروسافت استور دانلود ونصب شده اند یا دانلود منیجر برای دانلود فایل بر خلاف هیدو فای نکست و nekoray حالت پروکسی سیستم داره و هم حالت turen vpn mode کل سیستم تونل می کنه




![Screenshot (8)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/8390f571-0186-4c76-bc12-f8aa1d031bef)
![Screenshot (6)](https://github.com/bepass-org/oblivion-desktop/assets/167671244/1d677d97-b084-487f-9cca-5871abd06092)

**Comment by Majidzam1101** [comment]
> خب چرا برای فرستادن کنار ساعت مینیمایز نمی‌کنین؟‌ :‌)

مشکل دوم برنامه سایفون کار نمی کنه
