### ISSUE TITLE
open on startup

### ISSUE THREAD

**Issue by siaahatgar** [bepass-org/oblivion-desktop#92]
### Feature description

سلام و درود
اول از همه دم‌همگی گرم و خسته نباشید
1. اگه امکان اینکه با راه‌اندازی ویندوز اجرا بشه قرار بدید عالیه
2. 2. همچنین وقتی x رو می‌زنیم کنار ساعت ویندوز (notification area) قرار بگیره خیلی بهتر میشه

**Comment by yazbod** [comment]
سلام. برای مورد دوم از منوی نرم افزار به "تنظمیات برنامه" برید و گزینه "مخفی سازی" رو فعال کنید.

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،

1. برای این مورد تسک ایجاد میکنیم تا در نسخه های بعدی اضافه بشه
2. در تنظیمات برنامه اگر گزینه system tray رو روشن کنین، با minimze کردن به کنار ساعت میره
