### ISSUE TITLE
Connecting and disconnecting

### ISSUE THREAD

**Issue by Daredevil74** [bepass-org/oblivion-desktop#93]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

برنامه هرازگاهی قطع و وصل میشه
لایسنس ها رو هم چک میکنه میگه سقف استفاده از لایسنس پر شده در صورتی که اینطور نیست. به ناچار رو حالت free استفاده میکنم ازش
با حالت تونل نکردن سیستم اوکیم چون اینطوری مجبور نیستم برای دانلود با idm اتصال رو قط کنم و نیاز هم باشه idm رو میذارم رو حالت پروکسی
لطفا در ورژن های بعدی پروکسی مود رو حذف نکنید.
این مشکل قطع و وصل شدن تو پروژه warp-plus که در این برنامه هم ازش استفاده شده هم هس و اذیت میکنه
در کل خدا قوت و ممنون از همه زحمات شما و مهندس قبادی نازنین.

### Minimal Reproducible Example (MRE)

wt

### Version

v0.2.52

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام
ضمن تشکر از بازخورد شما،

در توضیحات آخرین آپدیت ذکر شده:
**در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه**
