### ISSUE TITLE
حالت tun رو اضافه کنید

### ISSUE THREAD

**Issue by Amohasan23** [bepass-org/oblivion-desktop#94]
### Feature description

فقط حالت tun رو اضافه کنید
همچنین فیلتر کردن دامنه ها در نسخه اندروید و ویندوز
خسته نباشید سپاس از زحماتتون عزیزان

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
درحال کار روی هر دو مورد هستیم

 https://github.com/bepass-org/oblivion-desktop#quick-overview
