### ISSUE TITLE
غیرفعال نشدن پیکربندی شبکه

### ISSUE THREAD

**Issue by MedicoAssassino** [bepass-org/oblivion-desktop#95]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

علی رغم غیرفعال کردن پیکربندی شبکه در تنظیمات روی ویندوز 11 باز هم پروکسی ویندوز را تغییر میدهد.

### Minimal Reproducible Example (MRE)

1.کلیک روی دکمه هبمرگری
2. تنظیمات برنامه
3.گزینه پیکربندی شبکه

### Version

0.2.52-beta

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
این‌باگ برطرف شده و در آپدیت بعدی در دسترس قرار میگیره
