### ISSUE TITLE
عدم امکان اضافه کردن لایسنس

### ISSUE THREAD

**Issue by javad490** [bepass-org/oblivion-desktop#96]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با تشکر از برنامه خوب شما، پس از اضافه کردن لایسنس وقتی اتصال را میزنیم پیام "مشکل در هویت سنجی میده" و وصل نمیشه اما بدون لایسنس و در حالت free وصل میشه

### Minimal Reproducible Example (MRE)

بخش تنظیمات و اضافه کردن لایسنس

### Version

0.2.52

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
همونطور که پیش‌تر گفته شد **در رابطه با استفاده از لایسنس مشکلی از سمت warp-plus وجود داره که توسط توسعه‌دهندگانش درحال بررسیه**
