### ISSUE TITLE
App Closing functionality has a bug

### ISSUE THREAD

**Issue by Tebjox** [bepass-org/oblivion-desktop#99]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

زمانی که روی دکمه Close در Title bar نرم افزار کلیک می شود. نرم افزار به طور کامل بسته می شود و در قسمت Taskbar corner ویندوز باقی نمی ماند که به کار خود ادامه دهد.

### Minimal Reproducible Example (MRE)

1. Click on the close button ("X" button on the Title Bar) 

### Version

0.2.52-beta

### Platform/OS

Windows 11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Tebjox** [comment]
الان با خوندن issue ها متوجه شدم که با دکمه Minimize این عملکرد به درستی صورت میگیره. 
ولی خب اگر مثل سایر نرم افزار ها این عملکرد روی دکمه Close صورت می گرفت بهتر بود.
(بحث تجربه کاربری و اینجور چیزاست) 🙏
با تشکر

**Comment by ircfspace** [comment]
سلام

ضمن تشکر از بازخورد شما،
سعی میکنیم در آپدیت های بعدی بهبود بدیم
